// ## 
// ## WEM4 6 Scripting
// ## Version XMas 2008 (6.5)
// ## 
// ## Script gefahrgut
// ## 
// ## Release 12.12.2008
// ## 
// ## created by WitchDoctor










// Sammelt alle Scripts, die mit der Bearbeitung von Gefahgut zu tun haben
//
// folgende Gefahrgueter kommen zum Einsatz
//
//	33   : leicht brennbare Flüssigkeit -> Kraftstofftransport
//	X423 : Gefahrenziffer für Natrium -> kein Wasser! , bildet brennbare Gase
//	20   : Gas -> Einsatz im Gefahrenbereich nur mit PA
//	411  : explosiver Feststoff -> Munitionstransport !
//	86   : ätzende/giftige Substanz -> Einsatz nur mit CSA
//      70   : radioaktive Substanz, Gefahrenklasse II -> CSA
//	235  : brennbares Gas, Gefahr heftiger chem. Reaktion -> Acetylengas-Flaschen

int DummyGroup = 20;

object kemlerzahl : CommandScript
{

	kemlerzahl()
	{
		SetValidTargets(ACTOR_VEHICLE);
		SetIcon("Kemmlerzahl");
		SetCursor("Kemmlerzahl");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle v(Target);
		return v.HasCommand("gefahrgut");
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		char *info="                                                                                                                                                                                                                           ";
		char *code="        ";
		Vehicle v(Target);
		int ggv=v.GetUserData();
		if (ggv>10)
			ggv=ggv-10;
		snprintf(code,8,"ID_GGV_%u",ggv);
		Game::ShowHelpTextWindow(code);
	}
};

object mm_an_bord : CommandScript
{
	mm_an_bord()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object gz_an_bord : CommandScript
{
	gz_an_bord()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object mir_fehlt_gz : CommandScript
{
	mir_fehlt_gz()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object dichtkissen_an_bord : CommandScript
{
	dichtkissen_an_bord()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object mir_fehlt_dichtkissen : CommandScript
{
	mir_fehlt_dichtkissen()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object mir_fehlt_mm : CommandScript
{
	mir_fehlt_mm()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object gefahrgut : CommandScript
{
	gefahrgut()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}
};

object setggv : CommandScript
{
	setggv()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);
		v.PushActionWait(ACTION_NEWLIST,1.0);
		v.ClearFlag(OF_USABLE);
		int ggv;

		if (childID == 0)
			ggv=Math::rand()%6+1;
		else
			ggv=childID;

		switch (ggv)
		{
			case 2:
			case 4:
			case 6:
				v.ChangePrototype("mod:Prototypes/Vehicles/Winterberg/twinkletruck01.e4p");
				break;
			case 8:
				Spannung=true;
				break;
			default:
				v.ChangePrototype("mod:Prototypes/Vehicles/Winterberg/tanktruck01.e4p");
				break;
		}
		
		v.SetUserData(ggv);
		v.AssignCommand("gefahrgut");
		v.SetChildEnabled("33",false);
		v.SetChildEnabled("201",false);
		v.SetChildEnabled("202",false);
		v.SetChildEnabled("203",false);
		v.SetChildEnabled("861",false);
		v.SetChildEnabled("862",false);
		v.SetChildEnabled("863",false);
		v.SetChildEnabled("oil1",false);
		v.SetChildEnabled("oil2",false);
		v.SetChildEnabled("oil3",false);
		// v.SetChildEnabled("",false);
		switch (ggv)			// Szenario entsprechend dem Gefahrgut vorbereiten
		{
			case 1 :		// leicht brennbare Flüssigkeit
				// setze Energieabstrahlung durch Brand
				// aktiviere Zuendquellenpruefung
				// Fluessigkeitsaustritt einschalten
				break;
			case 2 : 		// Alkalitransport
				// setze Explosionsenergie
				// setze Energieabstrahlung durch Brand
				// aktiviere Pruefung auf Wasserbeaufschlagung
				break;
			case 3 :		// Austreten von Gas
				// setze Contaminationrange
				// setze Gesundheitsschaden durch Gasinhalation
				// aktiviere Leck-Countdown
				// Gaswolke einschalten
				break;
			case 4 :		// Munitionstransport
				v.AssignCommand("kmrd_target");		// Use durch KMRD zulassen
				v.SetFlag(OF_USABLE);
				// aktiviere Funkenreisserpruefung	
				// aktiviere Erschuetterungs/Kollisionsprüfung
				// setze Explosionsenergie
				// aktiviere Entschaerfungsprüfung
				break;
			case 5 :		// Ätzende giftige Substanz
				// setze Contaminationradius
				// setze Gesundheitsschaden durch Substanz
				// aktiviere Leck-Countdown
				// Flüssigkeitsaustritt einschalten
				break;
			case 6 : 		// Radioaktive Substanz
				// setze Contaminationradius
				// setze Gesundheitsschaden durch Substanz
				break;
			case 8:
				Spannung=true;
				break;
		}
		if (Math::rand()%100 < 75)	// Tritt schon Gefahrgut aus ?
		{
			v.PushActionExecuteCommand(ACTION_APPEND,"ggv_leck",&v,ggv,false);
		}
		v.PushActionExecuteCommand(ACTION_APPEND,"ggv_wirken",&v,0,false);
	}
};

object ggv_leck : CommandScript
{

	ggv_leck()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (childID==8)
			return;

		Vehicle v(Caller);
		v.Damage(v.GetMaxEnergy()/100*(Math::rand()%50+40));
		v.SetFlag(OF_USABLE);
		int ggv=v.GetUserData();
		switch (ggv)
		{
			case 1:
				System::Error("GGV 33");
				v.SetChildEnabled("33",true);
				break;
			case 3:
				System::Error("GGV 20");
				v.SetChildEnabled("201",true);
				v.SetChildEnabled("202",true);
				v.SetChildEnabled("203",true);
				break;
			case 5:
				System::Error("GGV 86");
				v.SetChildEnabled("861",true);
				v.SetChildEnabled("862",true);
				v.SetChildEnabled("863",true);
				break;
		}
	}
};

object ggv_check : CommandScript
{
	ggv_check()
	{
		SetGroupID(DummyGroup);
		SetPriority(700);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	// Prüft auf reaktionsauslösende Massnahmen am GGV-Transport
	// die entsprechenden Scripts übermitteln per ChildID im Aufruf die grade durchgeführte Aktion
	// folgende Codes werden z.Zt verarbeitet
	// 1 : Beaufschlagen mit Wasser
	// 2 : Einsatz der Rettungsschere
	// 3 : ASF Aufladen / Heben mit Kran
	// 4 : Reparatur, z.B. Entschärfen durch KMD, Leck abdichten
	// 8 : Bahnerdung/Streckenabschaltung
	// 99: Zuendquelle im Gefahrenbereich

	void PushActions(GameObject *Caller, Actor *Target, int cid)
	{
		Vehicle v(Caller);
		GameObject o(Caller);
		GameObject p(Target);

		if (cid==3)
			o.SetFlag(OF_TRANSPORTABLE);

		if (o.HasNamePrefix("emma") && cid==3)
			o.SetFlag(OF_CUTABLE);

		if (!v.HasCommand("gefahrgut"))
			return;

		int ggv=v.GetUserData();
		bool leck=v.IsFlagSet(OF_USABLE) || ggv==8 || ggv==18;
		bool recall=false;
		int ix;
		System::Log ("ggvCheck");
		System::Log (Target->GetName());

		if ((p.GetNumActions() > 1) && (cid != 99))
		{
			Caller->PushActionExecuteCommand(ACTION_APPEND,"ggv_check",Target,cid,false);	
		} else
		switch (cid)
		{
			case 1:
				System::Log("Wasserbeaufschlagung");
				if (leck)
				switch (ggv)
				{
					case 1 :
						v.SetUserData(ggv+10);
						break;
					case 2 :	
						v.SetSmoking(true);
						v.SetSmokeLevelDuration(5.0f);
						v.PushActionWait(ACTION_NEWLIST,5.0f);
						v.PushActionExecuteCommand(ACTION_APPEND,"ggv_explode",Target,0,false);
						break;
					case 3 :
					case 5 :
					case 6 :
						v.SetUserData(ggv+10);
						v.SetChildEnabled("203",false);
						v.SetChildEnabled("863",false);
						// verändere Contamination Range bei Niederschlagen des Gases mit Wasser;
						break;
					case 8:
					case 18:
						System::Log("Spannungsunfall");
						p.PushActionExecuteCommand(ACTION_NEWLIST,"Hochspannung",Caller,ggv,false);
						break;
				}
				else
					recall=true;
				break;
			case 2:
			case 3:
			case 99:
				switch (ggv)
				{
					case 1:
						if ((Math::rand()%10)<5) 
						{
							v.SetFireObjectBurning("Zuendung");
							v.SetSmoking(true);
							v.SetSmokeLevelDuration(10.0f);
						} else {
							v.SetFireObjectBurning("Zuendung");
							v.PushActionWait(ACTION_NEWLIST,3.0f);
							v.PushActionExecuteCommand(ACTION_APPEND,"ggv_explode",Target,0,false);
						}
						break;
					case 4:
						v.PushActionWait(ACTION_NEWLIST,1.0);
						v.PushActionExecuteCommand(ACTION_APPEND,"ggv_explode",Target,0,false);
						break;					
					case 8:
					case 18:
						if (cid!=99)
							p.PushActionExecuteCommand(ACTION_NEWLIST,"Hochspannung",Caller,ggv,false);
						break;
				}
				break;
			case 4:
				System::Log("ggv_check : abdichten");
				switch (ggv)
				{
					case 1 :
						v.SetFireObjectBurning("Zuendung");
						v.SetSmoking(true);
						v.SetSmokeLevelDuration(1.0f);
						break;
					case 11:
					case 13:
					case 15:
					case 16:
					case 3 :
					case 5 :
					case 6 :
						if (p.IsCurrentAction("EActionRepair"))
						{
							System::Log("Abdichten in progress");
							Caller->PushActionExecuteCommand(ACTION_APPEND,"ggv_check",Target,cid,false);
						} else {
							System::Log("Fahrzeug vollstaendig dicht");
							// Leck ist dicht, kein Gefahrgut tritt mehr aus
							v.PushActionWait(ACTION_NEWLIST,1.0);
							Mission::PlayHint("WIB_GGV_DICHT");
							v.SetChildEnabled("33",false);
							v.SetChildEnabled("201",false);
							v.SetChildEnabled("202",false);
							v.SetChildEnabled("203",false);
							v.SetChildEnabled("861",false);
							v.SetChildEnabled("862",false);
							v.SetChildEnabled("863",false);
						}
						break;
					case 4 :
						if (p.IsCurrentAction("EActionRepair"))
						{
							Caller->PushActionExecuteCommand(ACTION_APPEND,"ggv_check",Target,cid,false);
						} else {
							v.SetUserData(0);
							v.PushActionWait(ACTION_NEWLIST,1.0);
							Mission::PlayHint("WIB_GGV_DEMIN");
						}
						break;
					case 8:
					case 18:
						p.PushActionExecuteCommand(ACTION_NEWLIST,"Hochspannung",Caller,ggv,false);
						break;
				}
				break;
			case 8:
				if (!Spannung)
				{
					if (ggv==8)
					{
						GameObjectList ol(Caller->GetName());
						for (ix=0;ix<ol.GetNumObjects();ix++)
							ol.GetObject(ix)->SetUserData(18);
					}	
					Mission::PlayHint("WIB_GGV_STROMLOS");
				} 
				break;
			case 18:
				if (!Spannung)
				{
					System::Log("gg_check : Strecke stromlos");
					Mission::PlayHint("WIB_GGV_ERDE");
					if (ggv==18)
					{
						GameObjectList ol(Caller->GetName());
						for (ix=0;ix<ol.GetNumObjects();ix++)
						{
							ol.GetObject(ix)->PushActionWait(ACTION_NEWLIST,0.1f);
							ol.GetObject(ix)->RemoveCommand("gefahrgut");
							ol.GetObject(ix)->SetUserData(0);
						}
					}	
				} else 
					p.PushActionExecuteCommand(ACTION_NEWLIST,"Hochspannung",Caller,18,false);
				break;
		}
	}
};

object ggv_wirken : CommandScript
{
	ggv_wirken()
	{
		SetGroupID(DummyGroup);
		SetPriority(700);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	// Prüft zyklisch auf Objekte im Gefahrenbereich
	// je nach Objekt und Gefahrgut wird dann das Objekt geschaedigt oder das
	// Gefahrgut reagiert

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Caller);
		int ggv;

		if (!v.HasCommand("gefahrgut"))
			return;
		if (childID==81)
			ggv=81;
		else
			ggv=v.GetUserData();

		if ((v.GetEnergy() > 0.95*v.GetMaxEnergy()) && (ggv!=8) && (ggv!=18))
		{
			return;		// kein Gefahrgutaustritt -> keine Wirkung;
		}
		float radius;
		switch (ggv)
		{
			case 1:
				radius=300;
				break;
			case 11:
				radius=60;
				break;
			case 2:
				radius=0;
				break;
			case 3:
				radius=500;
				break;
			case 13:
				radius=50;
				break;
			case 4:
				radius=0;
				break;
			case 5:
				radius=600;
				break;
			case 15:
				radius=150;
				break;
			case 6:
				radius=1000;
				break;
			case 16:
				radius=1600;
				break;
			case 8:
				radius=10;
				break;
			case 81:
				radius=700;
				break;
		}
		int actrange;
		actrange=1*radius;
		GameObjectList ol=Caller->GetObjectsInRange(actrange, ACTOR_PERSON | ACTOR_VEHICLE);
		GameObject obj;
		Vehicle ov;
		Person op;
		PersonType pt;
		for (int i=0; i<ol.GetNumObjects(); i++)
		{
			obj=ol.GetObject(i);
			switch (ggv)
			{
				case 1:
				case 11:
					switch (obj.GetType())
					{
						case ACTOR_VEHICLE:
							Vehicle ov(&obj);
							if (!ov.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER)) 
								switch (ov.GetUserData())
								{
									case 102:
									case 104:
										v.PushActionExecuteCommand(ACTION_INSERT,"ggv_check",&v,99,false);			
								}
							else
								if (ov.IsCurrentAction("EActionMove") || ov.IsCurrentAction("EActionMoveToPoint"))
									v.PushActionExecuteCommand(ACTION_INSERT,"ggv_check",&v,99,false);			
							break;
						case ACTOR_PERSON:
							Person op(&obj);
							pt=op.GetPersonType();
							if (op.IsCurrentAction("EActionUseEquipment"))
							{
								v.PushActionExecuteCommand(ACTION_INSERT,"ggv_check",&v,99,false);
							}			
							if ((pt != PT_FIREFIGHTER_ABC) && (pt != PT_FIREFIGHTER_MASK))
								op.Hurt(INJUREREASON_CONTAM_CHEM,50);
							if ((pt == PT_FIREFIGHTER_ABC) && (op.GetUserData() == 107))
								op.PushActionExecuteCommand(ACTION_NEWLIST,"ggv_messung",Caller,0,false);
							break;
					}
					break;
				case 2:
					break;
				case 3:
				case 13:
					switch (obj.GetType())
					{
						case ACTOR_VEHICLE:
							break;
						case ACTOR_PERSON:
							Person op(&obj);
							pt=op.GetPersonType();		
							if ((pt != PT_FIREFIGHTER_ABC) && (pt != PT_FIREFIGHTER_MASK))
								op.Hurt(INJUREREASON_CONTAM_CHEM,100);
							if ((pt == PT_FIREFIGHTER_ABC) && (op.GetUserData() == 107))
								op.PushActionExecuteCommand(ACTION_NEWLIST,"ggv_messung",Caller,0,false);
							break;
					}
					break;
				case 4:
					break;
				case 5:
				case 15:
					switch (obj.GetType())
					{
						case ACTOR_VEHICLE:
							Vehicle ov(&obj);
							ov.Damage(ov.GetEnergy()*0.02);
							ov.SetSmokeLevelDuration(30);
							break;
						case ACTOR_PERSON:
							Person op(&obj);
							pt=op.GetPersonType();		
							if (pt != PT_FIREFIGHTER_ABC)
								op.Hurt(INJUREREASON_CONTAM_CHEM,150);
							op.Contaminate(CONTAMINATION_CHEMICAL);
							if ((pt == PT_FIREFIGHTER_ABC) && (op.GetUserData() == 107))
								op.PushActionExecuteCommand(ACTION_NEWLIST,"ggv_messung",Caller,0,false);
							break;
					}
					break;
				case 6:
				case 16:
					switch (obj.GetType())
					{
						case ACTOR_VEHICLE:
							break;
						case ACTOR_PERSON:
							Person op(&obj);
							pt=op.GetPersonType();
							Vector tpos=Caller->GetPosition();
							Vector ppos=obj.GetPosition();
							op.Hurt(INJUREREASON_CONTAM_ATOM,10);
							if ((pt == PT_FIREFIGHTER_ABC) && (op.GetUserData() == 106))
								op.PushActionExecuteCommand(ACTION_NEWLIST,"ggv_messung",Caller,0,false);
							if (ggv == 16) 
								op.Contaminate(CONTAMINATION_ATOMIC);
							break;
					}
					break;
				case 8:
					System::Log("GGV wirken : Spannung");
					Caller->PushActionExecuteCommand(ACTION_INSERT,"ggv_wirken",Caller,81,false);
					switch (obj.GetType())
					{
						case ACTOR_VEHICLE:
							break;
						case ACTOR_PERSON:
							obj.PushActionExecuteCommand(ACTION_NEWLIST,"Hochspannung",Caller,8,false);
							break;
					}
					break;
				case 81:
					System::Log("GGV wirken : Spannung 81");
					if (obj.IsCurrentAction("EActionExtinguish") || obj.IsCurrentAction("EActionCool"))
						obj.PushActionExecuteCommand(ACTION_NEWLIST,"Hochspannung",Caller,8,false);
					break;
			}
		}
		if (ggv!=81)
		{
			Caller->PushActionWait(ACTION_APPEND,1.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"ggv_wirken",Caller,0,false);
		}
	}
};

object ggv_explode : CommandScript
{
	ggv_explode()
	{
		SetGroupID(DummyGroup);
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Caller);
		v.Explode();
	}
};

object ggv_messung : CommandScript	// GGV-Detektor
{
	ggv_messung()
	{
		SetPriority(500);
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		// Liste aller Objekte im Radius -> wenn Leckage und GGV passend zum Detektor, dann Ton an sonst Ton aus
		Vehicle ov(Target);
		Vector CarPos=Caller->GetPosition();
		if (Caller->GetUserData() == 107)
			Audio::PlaySample3D("mod:Audio/FX/228_einzel.wav", CarPos, false);
		else
			Audio::PlaySample3D("mod:Audio/FX/ggz.wav", CarPos, false);
	}
};

bool Spannung;

object Hochspannung : CommandScript
{
	Hochspannung()
	{
		SetPriority(500);
	}

	void PushActions(GameObject *Caller, Actor *Target, int voltage)
	{
		bool hint=false;
		GameObject flash=Game::CreateObject("mod:Prototypes/Objects/Particles/lightning02.e4p","eschock");
		if (Caller->GetType()==ACTOR_PERSON)
		{
			Person p(Caller);
			hint=!p.IsInjured();
			if (hint)
			{
				flash.SetPosition(Caller);
				flash.PushActionWait(ACTION_NEWLIST,2.0);
				flash.PushActionDeleteOwner(ACTION_APPEND);
			}
		}
		switch (Caller->GetType())
		{
			case ACTOR_VEHICLE:
				Vehicle v(Caller);
				switch (voltage)
				{
					case 8:
						Caller->Explode();
						break;
					case 18:
						v.SetSmoking(true);
						break;
				}
				hint=true;
				break;
			case ACTOR_PERSON:
				switch (voltage)
				{
					case 8:
						if (hint)
							p.Hurt(INJUREREASON_ENERGY,1600);
						else p.Hurt(INJUREREASON_ENERGY,100);
						break;
					case 18:
						if (hint)
							p.Hurt(INJUREREASON_ENERGY,1000);
						break;
				}
				break;
		}
		if (hint)
			Mission::PlayHint("WIB_GGV_SCHLAG");
	}
};

object Bahnerdung : CommandScript
{
	Bahnerdung()
	{
		SetValidTargets(ACTOR_VEHICLE);
		SetIcon("erdung");
		SetCursor("erdung");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);
		return v.HasCommand("gefahrgut") && ((Target->GetUserData()==18) || (Target->GetUserData()==8));
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Mission::PlayHint("WIB_GGVERDE_GO");
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"gf_erdung",Target,0,false);
	}
};

object Abschalten : CommandScript
{
	Abschalten()
	{
		SetIcon("erdung");
		SetCursor("erdung");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);
		return v.HasCommand("gefahrgut") && Target->GetUserData()==8;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (childID==0)
		{
			Mission::PlayHint("WIB_GGVAUS_GO");
			Caller->PushActionWait (ACTION_NEWLIST,Math::rand()%3+2);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"Abschalten",Target,1,false);
		} else {
			Vehicle v(Target);
			v.PushActionExecuteCommand(ACTION_APPEND,"ggv_check",Caller,8,false);
			Spannung=false;
		}
	}
};
