// ## 
// ## Winterberger 4 Scripting
// ## Version 6.0
// ## 
// ## Script fz_winterberg
// ## 
// ## Release 07.07.2008
// ## 
// ## created by WitchDoctor








// ABSCHNITT : Fz erstellen 
//
// Winterberger für Em4 by WitchDoc
// Fahrzeuge erstellen und besetzen
// 
// Rotation function by bass-ti
//
//  Revision:
//  02.07.2006 : Alle Fz bekommen eindeutige synth. Kennung nach einheitlichem System
//		 Die Zuordnung zum Parkplatz-VOB geschieht über Indextabelle

		const char * kennung[1];
		const int MAX_FZ = 100;
		int rtw_c=0;
		int nef_c=0;
		int hubi_c=0;
		
		GameObjectList sirs;
		bool KatSZustand=false;


object kaufen : CommandScript
{
	bool ersatz;

	kaufen()
	{
		ersatz=false;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		ersatz=true;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle vec;
		int MaxPass, maxTrans;
		char *Act[];
		Actor fz;
		int i,wache;
		GameObject *ofz;
		GameObjectList lfz;
		ActorList fzl;
		int q=childID;
		Vector Wache;
		float rot[9];
		float childRot[9];
		bool bedarfsfz = false;
		bool nachbarfz = false;
		bool td_fz=false;
		bool kripo=false;
		bool kompakt=false;
		bool isith=false;
		bool fuehrung=false;
		int dir = 0;
		const char *parken[2];
		int speed,trans,pass,rw;
		int alarmcode;
		int fzcodierung=0;

		if (q == 99999)
		{
			Vehicle vec(Target);
			vec.Hide();
			kennung[0]=vec.GetName();
			q=fzlocal::fzid(&vec);
			wache=fzlocal::fzort(&vec);
			ersatz=true;
			parken[1]="neuwagen";
			if (wache>50)
				nachbarfz=true;	
			else if (wache>0)
				bedarfsfz=true;	
			if (fzlocal::inplace(&vec))
			{
				parken[1]=fzlocal::kennung(q);
				ersatz=false;
			}
		} else {
			if (q>99999)
			{
				alarmcode=q/100000;
				q=q-(100000*alarmcode);
			}
			if (q>10000)
			{
				i=q/10000;
				q=q-(10000*i);
				switch (i)
				{
					case 1 :
						nachbarfz=true;
						break;
					case 2 :
						bedarfsfz=true;
						break;
					// ob Ersatzbeschaffung, wird durch CheckTarget geklärt
				}
			}

			wache=q/100;
			q=q-(100*wache);
			if (wache>50)
				dir=wache-50;
			else
				dir=wache;
			if (dir==0)
				parken[1]= fzlocal::kennung(q); // Fz direkt am Standort erzeugen
			else
				parken[1]= fzlocal::stellplatz(dir); // Fz direkt am Standort erzeugen

			kennung[0]="KFZSOKN00000TSC";
			char * format[]="%s0000000000000";
			int x=snprintf(kennung[0],13,format,fzlocal::kennung(q));
	
		} // Ende Neufahrzeug Kennung	


		int radius;
		int a,b,c;
		Game::GetTime(a,b,c);
		kennung[0][7]=char(32+wache);  // 7. Stelle codiert die Wache
		kennung[0][8]=char(32+a);    // 8. -4. Stelle eindeutige Objektkennung
		kennung[0][9]=char(32+b);	
		kennung[0][10]=char(32+c);
		kennung[0][11]=char(32+q);    // 5. Stelle codiert Fz-Typ
		kennung[0][12]=fzcode[q][4]; // die 12.Stelle codiert bei RTW/NEF/Hubi den Platz im Tableau
		kennung[0][13]=fzcode[q][0]; // 13.stelle codiert fz-alarmgeschwindigkeit
		kennung[0][14]=fzcode[q][5]; // Sonderfunktionen-Code
		switch (int(fzcode[q][5]))
		{
			case 67 :
				fuehrung=true;
				break;
			case 73 :
				isith=true;
				fzcodierung=fzcodierung | FZ_ITH;
				break;
			case 75:
				kripo=true;
				fzcodierung=fzcodierung | FZ_KRIPO;
				break;
		}

		fzl=Game::GetActors(parken[1]); // Fz am gewuenschten Stellplatz erzeugen
		if(fzl.GetNumActors() > 0)
			fz = *fzl.GetActor(0);
		else {
			System::Error("Ungueltiger Stellplatz");
			return;
		}


		//Wo soll das Fahrzeug parken?
		Wache=fz.GetPosition();
		if (bedarfsfz || (q==62))
			radius=100;
		else
			if (ersatz)
				radius=300;
			else 
				radius=0;
	
		// Logischer Block Fahrzeug erzeugen
		if (ersatz)
		{
			vec.PushActionDeleteOwner(ACTION_NEWLIST);
			if (bedarfsfz)
				return; // Verry verry evil, Kein Fz erzeugen, Schrott iss ja weg
		}


		speed=int(fzcode[q][0])-64;
		if (speed>26)
		{
			speed=speed-32;
			fuehrung=true;
		}

		if (deluxe)
			speed=speed*1.2;

		pass=int(fzcode[q][1])-48;
		trans=int(fzcode[q][2])-48;
		rw=int(fzcode[q][3])-48;
		//Erzeuge das Fahrzeug
		if (rand()%10>4 && (q==56 || q==59 || q==60))
			vec = Game::CreateVehicle(proto[76],kennung[0]);
		else
			vec = Game::CreateVehicle(proto[q],kennung[0]);

		if (Game::IsMultiplayer())
		{
			if (vec.IsFirefighter())
				vec.SetPlayerMP(1);
			else if (vec.IsPolice() || vec.IsThw())
				vec.SetPlayerMP(2);
			else if (vec.IsAmbulance())
				vec.SetPlayerMP(0);
		}

		vec.SetSpeed(speed*1.0);
		//Platz schaffen
		vec.SetMaxPassengers(pass);
		vec.SetMaxTransports(trans);
		//Lichter aus
		vec.EnableBlueLights(false);
		vec.EnableBreakLights(false);
		vec.EnableSpecialLights(false);
		//Drehen
		vec.GetRotation(rot[0], rot[1], rot[2], rot[3], rot[4], rot[5], rot[6], rot[7], rot[8]);
		Math::EulerToMatrix(rw*90.0f, 0.f, 0.f, childRot);
		Math::MultiplyMatrices(childRot, rot);
		vec.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
		//Position setzen
		Game::FindFreePosition(&vec,Wache,radius);
		vec.SetPosition(Wache);
		
		vec.ClearFlags();
		fzlocal::fz_beladen(&vec);
		// Flags setzen
		vec.SetFlags(OF_RECOVERABLE | OF_TRANSPORTABLE | OF_SHOOTABLE | OF_COOLABLE|OF_HAS_FIRE_EXTINGUISHER);
		if (vec.IsFirefighter())
		{
			vec.SetFlag(OF_HAS_FIREAXE);
			vec.SetFlag(OF_HAS_SHEARS);
			vec.SetFlag(OF_HAS_HOSE);
			vec.SetFlag(OF_HAS_CHAINSAW);
		};

		//Personen erzeugen ?
		int pn=pass;
		int px,ps;
		vec.PushActionWait(ACTION_NEWLIST,0.1f);
		switch (vec.GetVehicleType())
		{
			case VT_AMBULANCE_RTW:
				if (ersatz)
					vec.PushActionExecuteCommand(ACTION_INSERT,"init_fza",&vec,0,false);
				if (q==17)
				{
					vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,10,false);
					fzcodierung=fzcodierung | FZ_BSW;
				} else
					fzcodierung=fzcodierung | FZ_RTW;
				if (q==37)
					vec.SetFlag(OF_CARRYABLE_BY_BULLDOZER);
				break;
			case VT_AMBULANCE_RHF:
				vec.SetFlag(OF_CARRYABLE_BY_BULLDOZER);
				fzcodierung=fzcodierung | FZ_SEG;
				break;
			case VT_AMBULANCE_NEF:
				if (ersatz)
					vec.PushActionExecuteCommand(ACTION_INSERT,"init_nef",&vec,0,false);
				vec.SetFlag(OF_USABLE_WITH_MEGAPHONE);
				fzcodierung=fzcodierung | FZ_NA;
				break;
			case VT_AMBULANCE_RHC:
				if (ersatz)
					vec.PushActionExecuteCommand(ACTION_INSERT,"init_rth",&vec,0,false);
				vec.SetFlag(OF_USABLE_WITH_MEGAPHONE);
				fzcodierung=fzcodierung | FZ_NA | FZ_RTW | FZ_HUBI;
				break;
			case VT_POLICE_PHC:
				fzcodierung=fzcodierung | FZ_HUBI | FZ_POL;
				break;
			case VT_POLICE_STW:
				fzcodierung=fzcodierung | FZ_POL;
				break;
			case VT_POLICE_MTW:
				if (q!=70)
					vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,32,false);
				vec.SetFlag(OF_HAS_FLASHGRENADE | OF_HAS_ROADBLOCK);
				fzcodierung=fzcodierung | FZ_POL | FZ_MTW;
				break;
			case VT_FIREFIGHTERS_DLK:
				vec.SetFlag(OF_HAS_JUMPPAD);
				
			case VT_FIREFIGHTERS_RW:
			case VT_FIREFIGHTERS_TLF:
			case VT_FIREFIGHTERS_GTF:
				vec.AssignCommand("gf_pa");
				vec.AssignCommand("gf_csa");
			case VT_FIREFIGHTERS_DEKONP:
				break;
			case VT_FIREFIGHTERS_FMB:
				GameObjectList ll("fmb01");
				vec.PushActionExecuteCommand(ACTION_APPEND,"gohome_winterberg",&vec,0,true);
				break;
			case VT_FIREFIGHTERS_ASF:
				vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,6,false);
				break;
			case VT_POLICE_GETAWAY:
				break;
			case VT_THW_FGRI_EKW:
				switch (q)
				{
					case 33:
						vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,7,false);
						break;
					case 34:
						vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,16,false);
						vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,17,false);
						break;
					default:
						vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,5,false);
						break;
				}
				break;
		}
	
		if (!vec.HasCommand("FlyTo") && (vec.GetVehicleType() != VT_FIREFIGHTERS_FMB))
			vec.SetSpeed(civspeed);

		if (vec.GetVehicleType() != VT_FIREFIGHTERS_FMB)
		{
			vec.AssignCommand("AutoUmleiten");	
			vec.AssignCommand("notruf_pol");	
			vec.AssignCommand("Status6");
		}

		if (vec.HasChild("NA"))
			vec.SetChildEnabled("NA",false);
		if (vec.HasChild("POL"))
			vec.SetChildEnabled("POL",false);

		if (fuehrung)
			vec.AssignCommand("fuehrung");

		if (isith)
			vec.AssignCommand("isith");

		vec.SetFlag(OF_HAS_ROADBLOCK);

		if (!vec.HasCommand("aufsitzen"))
			vec.AssignCommand("aufsitzen");
	
		vec.AssignCommand("WT_SoSi");

		if (bedarfsfz)
		{
			vec.AssignCommand("bedarfs_fz");
			vec.AssignCommand("ich_bin_nicht_frei");
			vec.Hide();
			vec.PushActionExecuteCommand(ACTION_APPEND,"alarmiere_Winterberg",Target,alarmcode,false);
		} else if (nachbarfz)
			vec.AssignCommand("hidden");

		if (ersatz)
		{
			vec.SetFlag(OF_PULLABLE);
			vec.PushActionExecuteCommand(ACTION_APPEND,"CreateNewPerson",&vec,70,false);
			Mission::PlayHint("WIB_ERSATZ");
			vec.PushActionExecuteCommand(ACTION_APPEND,"gohome_winterberg",&vec,0815,false); // Ersatzfz zum Standort schicken
		} else 	if (nachbarfz)
				vec.PushActionShowHide(ACTION_APPEND,true);

		ersatz=false;  // Marker für Ersatzfahrzeug wieder zuruecksetzen für nächsten Aufruf
	}
};

// ABSCHNITT: RUFE Fz 
// 
// basiert auf rufe_stw.script für Em3 by manuelt
//
// Revision
// 17.6.2006 : Auswahl über VehicleList, gesteuert über childID, default -> Streife/MTW
//		childID = 100 -> nur MTW -> 110 Wasserwerfer -> 181 MTW Demo
//		childID = 101 -> PolFahrzeug -> 111 Z-Pol für Löschzug -> 180 EL Demo
//		childID	= 120 -> KriPO
//		childID = 130 -> FluchtFz
//		childID = 150 -> SEK Kombi -> 151 SEK MTW
//		childID = 200 -> Pol.Hubschrauber
//		childID = 300 -> ASF	-> 350 Kran
//		childID = 400 -> TecJeep -> 450 DB-Notfallmanager -> 475 Kampfmittelraeumer -> 480 Wasserwerk
//		childID = 500 -> GW-Mess -> 515 GW-AS im Loeschzug -> 535 takt GW-Mess im Chemie-Zug  
//		childID	= 536 -> Dekon-P im Chemie-Zug
//		childID = 501 -> Löschfahrzeug
//		childID	= 502 -> Wasserretter
//		childID	= 503 -> techn. Rettung -> 513 Takt. RW für Ruestzug -> 533 Takt. RW für Chemiezug
//		childID = 504 -> Hubretter
//		childID = 505 -> Chemieschutzfahrzeug -> 
//		childID = 506 -> GTLF
//		childID = 507 -> GTLF
//		childID = 510 -> takt. Löschfahrzeug für Zug (510 und 511 bilden die gemeinsame Basis fur 501 kleiner Löscheinsatz)
//		childID = 520 -> takt. Löschfahrzeug für Ruestzug -> A-Trupp rüstet sich nicht mit PA aus
//		childID	= 530 -> takt. Löschfahrzeug für Chemiezug
//		childID	= 511 -> takt. TLF für Zug -> 531 = takt.TLF für Chemiezug
//		childID = 512 -> takt. Hubretter für Zug
//		childID = 550 -> Einsatzleitung -> 553 EL Ruestzug  -> 555 EL Chemiezug -> 559 -> Fernmeldedienst
// 		childID = 600 -> Bestattungsdienst
//		childID = 601 -> Notarztbesetztes Rettungsmittel -> 611 = ZNEF
//		childID = 602 -> RTW -> 612 = ZRTW -> 622 = NAW im Rendezvous, RTW aber kein KTW
//		childID = 610 -> explizit RTH -> 618 ITH sekundär
//		childID = 620 -> LNA
//		childID = 650 -> SEG	-> 651 = SEG Arzt  -> 652 = SEG Truck -> 653 = NB-RTW -> 654 = NB-NEF -> 655 = 7 NB-NAW
//		childID	= 660 -> DLRG Insel -> 666 Schockraumteam
//		childID = 692 -> KompaktNAW
//		childID = 199 -> POL Notruf -> alle freien Fz werden gerufen
//
// 20.6.2006 : Erzeugt einen externen Bestatter  
//		alarmierter Streifenwagen kann Verdächtigen direkt verfolgen		
//
// 24.6.2006 : einzelne Feuerwehrfahrzeuge sowie RTD werden auch von diesem Script alarmiert
//
// 02.7.2006 : Fahrzeuge werden anhand ByteCode identifiziert. Die ich_bin_funkruf-Kommandos sind entbehrlich
//		alle genau einmal einsetzbaren Fz stehen hidden auf der Map -> einfachere Nachrücklisten

// Basis: Garagenausfahrt by Big Bob

// Ruft ein freies Winterberger Fahrzeug oder alarmiert externe Fahrzeuge

// Die Verwendung in anderen Mods ist gestattet, solange dieser
// Kommentar erhalten bleibt

int auftrag=0;

int ndmask=131072;
int stmask=ndmask*2;
int nfmask=stmask*2;
int noflags=ndmask-1;

object rufe_winterberg : CommandScript	
{

	// 1. schritt der Alarmierung :Fz Disponieren

	bool kriterien_erfuellt; //Ist dieser STW gerade frei?
	float abstand, minimum; // Abstand und kürzester Abstand zwischen STW und Ziel...

	rufe_winterberg()
	{
		SetPriority(400);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vector FzPos;
		Vector MinFz;
		Vector Abstand;
		Vehicle v;
		Vehicle stw;
		int dir=0;
		char * hint[];
		int randact;	
		Vector TargetPos;
		int pt;
		int wblevel=0;
		int quad;
		Vector Mitte;
		int rtw=0;
		int h,m,s;
		int quad;
		float dist, mindist;

		TargetPos=Game::GetCommandPos();
		bool dummy=false;
		bool nachforderung=false;
		bool zugende=false;
		int basewert;
		int sw;
		bool kompakt=false;
		int aufruf=childID;

		bool neudispo=childID & ndmask;
		bool storno=childID & stmask;
		bool normale_fahrt= childID & nfmask;

		childID=childID & noflags;

		System::Log("Rufe Winterberg %u %u %u %u ",childID,int(neudispo),int(storno),int(normale_fahrt));

		GameObject tob(Target);

		if (Target->GetType() == ACTOR_FLOOR)
		{
			Vehicle p = Game::CreateVehicle("mod:Prototypes/Vehicles/Winterberg/pylone.e4p", "alarmdummy");
			p.Hide();
			Game::FindFreePosition(&p,TargetPos);
			p.SetPosition(TargetPos);
			Target=&p;
			p.AssignCommand("alarm_dummy");
			if (Game::IsMultiplayer())
				p.SetPlayerMP(Caller->GetPlayerMP());
		} else 
			tob.SetPlayerMP(Caller->GetPlayerMP());

		if (neudispo || storno)
			Caller->PushActionExecuteCommand(ACTION_INSERT,"storno",Caller,0,false);

		if (childID>999)
		{
			rtw=childID/1000;
			childID=childID-1000*rtw;
		}


		switch (rtw)
		{
			case 99:
				basewert=10; // Kreisalarm, wenn kein passendes Fz in der Ortswehr naechste Wehr alarmieren
				break;
			default:
				basewert=-1; // ortsbezogene Alarmierung
				break;
		}

		bool nachruecken=false;

		switch (childID) 
		{
			// Sonderfunktionen zur Alarmierungssteuerung
			case 2:
			case 3:
				Caller->PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",Caller,100+childID,false);
				return;
				break;
			// FzAuswahl
			case 100 :
				VehicleList l0(VT_POLICE_MTW,VT_POLICE_MTW);
				dir=(Math::rand()%8+1)*100+20010;
				break;
			case 110 :
				VehicleList l0(VT_POLICE_WAW,VT_POLICE_WAW);
				dir=(Math::rand()%8+1)*100+20010;
				break;
			case 182 :
				VehicleList l0;
				dir=20668;
				break;
			case 180 :
				VehicleList l0;
				dir=20671;
				break;
			case 181 :
				VehicleList l0;
				dir=20672;
				break;
			case 200 :
				VehicleList l0(VT_POLICE_PHC,VT_POLICE_PHC);
				if (l0.GetNumVehicles() < 4)
					dir=(Math::rand()%8+1)*100+20018;
				break;
			case 300:
				VehicleList l0(VT_FIREFIGHTERS_ASF,VT_FIREFIGHTERS_ASF);
				if (l0.GetNumVehicles() < 7)
					dir=(Math::rand()%8+1)*100+20011;
				break;
			case 350:			
				VehicleList l0(VT_THW_FGRR_BKF, VT_THW_FGRR_BKF);
				if (l0.GetNumVehicles() < 1)
					dir=20916;
				break;
			case 400:
				VehicleList l0(VT_THW_FGRI_EKW, VT_THW_FGRI_EKW);
				if (l0.GetNumVehicles() < 7)
					dir=(Math::rand()%8+1)*100+20013;
				break;
			case 475:
				VehicleList l0(VT_THW_FGRI_EKW, VT_THW_FGRI_EKW);	
				dir=(Math::rand()%8+1)*100+20034;
				break;
			case 480:
				VehicleList l0(VT_THW_FGRI_EKW, VT_THW_FGRI_EKW);	
				dir=(Math::rand()%8+1)*100+20057;
				break;
			case 450:
				VehicleList l0(VT_THW_FGRI_EKW, VT_THW_FGRI_EKW);	
				dir=(Math::rand()%8+1)*100+20033;
				break;
			case 666:
				VehicleList l0(VT_THW_FGRI_EKW, VT_THW_FGRI_EKW);	
				dir=(Math::rand()%8+1)*100+20075;
				break;
			case 500:
			case 535:
			case 515:
				VehicleList l0(VT_FIREFIGHTERS_RW,VT_FIREFIGHTERS_RW);
				break;
			case 536:
				VehicleList l0(VT_FIREFIGHTERS_DEKONP,VT_FIREFIGHTERS_DEKONP);
				dir=(Math::rand()%8+1)*100+20041;
				break;
			case 506:
			case 501:
				VehicleList l0(VT_FIREFIGHTERS_TLF,VT_FIREFIGHTERS_GTF);
				break;
			case 502:
				VehicleList l0(VT_FIREFIGHTERS_DLK,VT_FIREFIGHTERS_GTF);
				break;
			case 533:
			case 513:
			case 507:
			case 503:
			case 560:
				VehicleList l0(VT_FIREFIGHTERS_RW,VT_FIREFIGHTERS_GTF);
				break;
			case 504:
			case 512:
				VehicleList l0(VT_FIREFIGHTERS_DLK,VT_FIREFIGHTERS_DLK);
				break;
			case 505:
				VehicleList l0(VT_FIREFIGHTERS_DLK,VT_FIREFIGHTERS_GTF);
				break;
			case 510:
			case 520:
			case 530:
				nachruecken=true;
			case 580:
				VehicleList l0(VT_FIREFIGHTERS_TLF,VT_FIREFIGHTERS_GTF);
				break;
			case 511:
			case 531:
				nachruecken=true;
			case 581:
				VehicleList l0(VT_FIREFIGHTERS_TLF,VT_FIREFIGHTERS_GTF);
				break;
			case 550:
			case 553:
			case 555:
			case 559:
				VehicleList l0(VT_FIREFIGHTERS_RW,VT_FIREFIGHTERS_RW);
				break;
			case 598:
				nachruecken=true;
			case 599:
				VehicleList l0(VT_FIREFIGHTERS_TLF,VT_FIREFIGHTERS_GTF);
				break;
			case 600:
				VehicleList l0(VT_AMBULANCE_RTW,VT_AMBULANCE_RTW);
				dir=20717;
				break;
			case 650:
				VehicleList l0(VT_AMBULANCE_RTW,VT_AMBULANCE_RTW);
				dir=25435;
				break;
			case 651:
				VehicleList l0(VT_AMBULANCE_RTW,VT_AMBULANCE_RTW);
				dir=25436;
				break;
			case 652:
				VehicleList l0(VT_AMBULANCE_RHF,VT_AMBULANCE_RHF);
				dir=25437;
				break;
			case 655:
				kompakt=true;
			case 653:
				VehicleList l0(VT_AMBULANCE_RTW,VT_AMBULANCE_RTW);
				dir=(Math::rand()%8+1)*100+20063;
				break;
			case 654:
				VehicleList l0(VT_AMBULANCE_NEF,VT_AMBULANCE_NEF);
				dir=(Math::rand()%8+1)*100+20064;
				break;
			case 601:
			case 611:
				VehicleList l0(VT_AMBULANCE_NEF,VT_AMBULANCE_RHC);
				VehicleList cl(Caller->GetName());
				if (Target->GetType() == ACTOR_PERSON)
					if (cl.GetNumVehicles()>0)
						nachforderung=(cl.GetVehicle(0)->GetVehicleType() == VT_AMBULANCE_RTW);
				break;
			case 692:
				kompakt=true;
			case 622:
			case 612:
			case 602:
				VehicleList l0(VT_AMBULANCE_RTW,VT_AMBULANCE_RTW);
				VehicleList cl(Caller->GetName());
				if (Target->GetType() == ACTOR_PERSON)
					if (cl.GetNumVehicles()>0)
						nachforderung=(cl.GetVehicle(0)->GetVehicleType() == VT_AMBULANCE_RTW);
				break;
			case 618:
				dir=(Math::rand()%8+1)*100+20073+rand()%2;
			case 610:
				VehicleList l0(VT_AMBULANCE_RHC,VT_AMBULANCE_RHC);
				break;		
			case 620:
				VehicleList l0(VT_AMBULANCE_NEF,VT_AMBULANCE_NEF);
				break;		
			case 660:
				VehicleList l0(VT_FIREFIGHTERS_FMB,VT_FIREFIGHTERS_FMB);
				break;
			case 101:
			case 111:
				VehicleList l0(VT_POLICE_STW,VT_POLICE_STW);
				dir=(Math::rand()%8+1)*100+20008;
				break;
			case 150:
				VehicleList l0(VT_POLICE_STW,VT_POLICE_STW);
				dir=20169;
				break;
			case 151:
				VehicleList l0(VT_POLICE_MTW,VT_POLICE_MTW);
				dir=20170;
				break;
			case 120:
				VehicleList l0(VT_POLICE_STW,VT_POLICE_STW);
				break;
			case 130:
				VehicleList l0(VT_POLICE_GETAWAY,VT_POLICE_GETAWAY);
				dir=(Math::rand()%8+1)*100+20061;
				break;
			case 199:
				VehicleList l0(VT_POLICE_MTW,VT_POLICE_STW);
				break;
		}

		int max=l0.GetNumVehicles();
		float wert=101;
		int maxspeed;
		float folge=100;
		int fzid, fzort;
		int fzstart;
		int choose=Math::rand()%3;
		int mdir=dir;
		int lt,hasna, hasra, needra, needna,panz;
		Person doc;
		float multi;
	
		int h,m,s;
		Game::GetTime(h,m,s);
		bool nacht=((h>18) || (h<7));
		bool flugwetter=((Weather::GetFogIntensity()<0.5) && (Weather::GetStormIntensity()<0.5) && (Weather::GetRainIntensity()<0.5) && (Weather::GetSnowIntensity()<0.7));

		for(int i=0; i<max; i++)
		{
			//Aktuelles Objekt
			v = l0.GetVehicle(i);
			fzid=fzlocal::fzid(&v); // Fz-Typ laut AutosKaufen
			fzort=fzlocal::fzort(&v);
			lt=0;
			multi=1.0;

			if (storno)
			{
				if (fzid == rtw)
				{
					v.PushActionExecuteCommand(ACTION_NEWLIST,"aufsitzen",&v,0,false);
					return;
				}
			}
		
			switch (fzid)
			{
				case 34:
					if (childID==475)
						dir=0;
					break;
				case 32:
				case 35:
				case 36:
				case 37:
					break;
				case 7:
				case 8:
				case 9:
				case 59:
				case 60:
					lt=2;
					break;
				case 10:
					lt=4;
					break;
				case 41:
					break;
				case 69:
					if (childID==150)
						dir=0;
					break;
				case 75:
					if (childID==666)
						dir=0;
					break;
				case 70:
					lt=4;
					if (childID==151)
						dir=0;
					break;
				case 73:
				case 74:
					if (childID==618)
						dir=0;
					break;
				default:
					dir=mdir;
					break;
			} 

			bool einsatzbereit=(!v.HasCommand("ich_bin_nicht_frei")&& !v.HasCommand("wird_alarmiert") && !v.IsDestroyed() && !v.HasCommand("alarm_dummy") && !storno && v.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER));
			//Nur ohne Transport möglich...
			kriterien_erfuellt=(v.GetNumTransported() <= lt) && !v.IsCarryingAnything() && !v.HasVehicleUploaded();
			hasna=0;
			hasra=0;
			needra=0;
			needna=0;

			switch (v.GetVehicleType())
			{
				case VT_AMBULANCE_NEF:
					needra=1;
					break;
				case VT_AMBULANCE_RHC:
				case VT_AMBULANCE_RTW:
					needra=2;
					break;
			} 
			if ((einsatzbereit || neudispo) && kriterien_erfuellt)
			{
				switch (childID)
				{
					case 666:
						if (fzid == 75)
							wert=1;
						else
							wert=-1;
						break;
					case 620:
						if (fzid == 32)
							wert=1;
						else
							wert=-1;
						break;
					case 650:
						if (fzid == 35)
							wert=1;
						else
							wert=-1;
						break;
					case 651:
						if (fzid == 36)
							wert=1;
						else 
							wert=-1;
						break;
					case 652:
						if (fzid == 37)
							wert=1;
						else
							wert=-1;
						break;
					case 655:
						kompakt=true;
					case 653:
						if (fzid == 63)
							wert=1;
						else 
							wert=-1;
						break;
					case 654:
						if (fzid == 64)
							wert=1;
						else 
							wert=-1;
						break;
					case 601:
					case 611:
					case 610:
						kriterien_erfuellt = false;
						//Ist mind. ein NA an Bord?
						if (v.IsFlagSet(OF_PULLABLE))
						{
							PersonList na(v.GetName());
							panz=na.GetNumPersons();
							for(int j=0; j<panz; j++)
							{
								doc=na.GetPerson(j);
								if (doc.GetEnteredCarID() == v.GetID() || doc.GetEnteredCarID()==-1)
									if (doc.IsDoctor())
										hasna++;
									else 	if (doc.IsParamedicTeam())
											hasra+=2;
										else hasra++; 
							}
						};
						kriterien_erfuellt=((hasna==1 && hasra>=needra) || !v.IsFlagSet(OF_PULLABLE)) && (v.GetNumTransported()==0);
						if (kriterien_erfuellt)
						{
							wblevel=1;
							if (rtw == 0) // automat. NAW-Alarmierung
								switch (v.GetVehicleType())
								{
									case VT_AMBULANCE_NEF:
										switch (fzid)
										{
											case 1:
												wert=1;
												break;
											case 26: 
												wert=2;
												break;
											case 21:
												wert=4;
												break;
											case 65:
												wert=3;
												break;
											case 32:
												wert=11;
												break;
										}
										break;
									case VT_AMBULANCE_RTW:
										wert=10; // Kompakt-NAW gefunden, lieber NEF oder RTH
										break;
									case VT_AMBULANCE_RHC:
										// RTH merken, aber lieber NEF suchen
										if (childID == 610)
										{
											wert=1;
											i=max; // wenn nur RTH gesucht, dann Suche beenden
										} else if (flugwetter && !nacht)
												wert=9;
											else 
												wert=-1;
										break;
								} 
							else if (fzid == rtw)
									wert=1;
								else 
									wert=-1;
						}
						break;
					case 692:	// Kompakt-NAW
						needna=0;
					case 602:	// RTW
					case 612:
					case 622:
						kriterien_erfuellt = false;
						if (v.IsFlagSet(OF_PULLABLE))
						{
							PersonList ra(v.GetName());
							panz=ra.GetNumPersons();
							for(int j=0; j<panz; j++)
							{
								doc=ra.GetPerson(j);
								if (doc.GetEnteredCarID() == v.GetID() || doc.GetEnteredCarID()==-1)
									if (doc.IsDoctor())
										hasna++;
									else 	if (doc.IsParamedicTeam())
											hasra+=2;
										else hasra++; 
							}
						};
						kriterien_erfuellt=((hasra>=needra && hasna>=needna) || !v.IsFlagSet(OF_PULLABLE)) && (v.GetNumTransported()==0);
						if (kriterien_erfuellt)
						{	
							if (fzid == rtw)
							{
								wert=1;
								i=max;
								kompakt=(hasna>0 || !v.IsFlagSet(OF_PULLABLE)) && kompakt;
							}
							else
								wert=-1;
						} else 
							wert=-1;
						break;
					case 300:
						if (!v.HasVehicleUploaded())
						{
							stw=v;
							i=max;
							wert=1;
						} else 
							wert=-1;
						break;
					case 600:
						if (fzid == 17)
						{
							wert=1;
							i=max;
							
						}	
						else
							wert=-1;
						break;
					case 350:
						wert=1;
						i=max;
						break;
					case 450:
						if (fzid == 33)
						{
							wert=1;
							i=max;
							
						}
						else
							wert=-1;
						break;
					case 475:
						if (fzid == 34)
						{
							wert=1;
							i=max;
							
						}
						else
							wert=-1;
						break;
					case 480:
						if (fzid == 57)
						{
							wert=1;
							i=max;
						}
						else
							wert=-1;
						break;
					case 660:
						if (fzid == 58)
						{
							wert=1;
							i=max;
						}
						else
							wert=-1;
						break;
					case 560:
						if (fzid==62)
						{
							wert=1;
							i=max;
						} else
							wert=-1;
						break;
					case 506:
						switch (fzid)
						{
							case 50:
								wert=1;
								break;
							case 20:
								wert=2;
								break;
							default:
								wert=-1;
						}
						break;
					case 507:
						wert=-1;
						if (fzid == 39)
							wert=1;
						break;
					case 598:
					case 599:
						wert=-1;
						wblevel=0;
						if (v.IsFirefighter() &&  (fzort == rtw) && (fzid!=62))
							switch (v.GetVehicleType())
							{
								case VT_FIREFIGHTERS_TLF:
									wert=2;
									break;
								case VT_FIREFIGHTERS_GTF:
									wert=1;
									break;
							}
						break;
					case 501:
						wert=-1;
						wblevel=5;
						if (v.IsFirefighter() &&  (fzort==rtw))
							wert=1;
						else 
							wert=basewert;
						break;
					case 502:
						wert=-1;
						wblevel=5;
						if (v.IsFirefighter())
						{
							if (fzlocal::has_equip(&v,2) && (v.GetVehicleType()!=VT_FIREFIGHTERS_FMB))
							{
								if (stw.IsValid())
								{
									if (v.GetSpeed() > stw.GetSpeed()) // Suche das schnellste Fahrzeug
										stw=v;					
								} else {
									stw=v;
								}
								wert=1;
							}
						} else wert=-1;
						break;
					case 503:
					case 513:
					case 533:
						wert=-1;
						wblevel=2;
						if (v.IsFirefighter())
						{
							if (fzlocal::has_equip(&v,5)) 
							{
								wert=5;
								if (v.GetVehicleType()==VT_FIREFIGHTERS_RW)
								{
									if ((fzort == rtw)&&(rtw>0))
										wert=1;
									else
										wert=3;
								} else if (fzort == rtw)
										wert=4;
							}
						}
						break;
					case 505:
						wert=-1;
						if (fzlocal::has_equip(&v,1))
						{
							stw=v;
							i=max;
						}
						break;
					case 511:
					case 531:
					case 581:
						wert=-1;
						if (v.IsFirefighter())
						{
							if ((fzort == rtw || rtw == 99) && fzid!=62)
								switch (v.GetVehicleType())
								{
									case VT_FIREFIGHTERS_TLF:
										if ((v.GetNumPassengers()+v.GetFreePassengers())>3)
											wert=2+basewert;
										else 
											wert=5+basewert;
										break;
									case VT_FIREFIGHTERS_GTF:
											wert=3+basewert;
										break;
									default:
										wert=-1;
										break;
								}
						}
						break;
					case 500:
					case 535:
					case 515:
						wert=-1;
						if (fzid == 15)
							wert=1;
						break;
					case 536:
						wert=-1;
						if (fzid == 41)
							wert=1;
						break;
					case 510:
					case 520:
					case 530:
					case 580:
						wert=-1;
						if (v.IsFirefighter())
						{
							if ((fzort == rtw || rtw == 99) && fzid!=62)
								switch (v.GetVehicleType())
								{
									case VT_FIREFIGHTERS_GTF:
										if ((v.GetNumPassengers()+v.GetFreePassengers()) >5)
											wert=2+basewert;
										else
											wert=4+basewert;
										break;
									case VT_FIREFIGHTERS_TLF:
										if ((v.GetNumPassengers()+v.GetFreePassengers())>3)
											wert=3+basewert;
										else 
											wert=5+basewert;
										break;
									default:
										wert=-1;
										break;
								}
						}
						break;
					case 512:
					case 504:
						wert=-1;
						if (v.IsFirefighter())
						{
							wert=5;
							if ((fzort == rtw)&&((rtw>0)||(childID == 512)))
									wert=1;
							else
								switch (fzort)
								{
									case 0:
										wert=1;
										break;
									default:
										wert=3;
										break;
								}										
						}
						break;
					case 550:
					case 553:
					case 555:
						wert=-1;
						if (v.HasCommand("fuehrung") && fzid!=62)
						{
							if (fzort == rtw)
								wert=1;
							else 
								wert=basewert;
						}
						break;
					case 559:
						if (fzid==62)
							wert=1;
						else 
							wert=-1;
						break;
					case 400:
						if (fzid == 13)
						{
							wert=1;
							i=max;
						}
						else
							wert=-1;
						break;
					case 200:
						wert=1;	
						i=max;
						break;
					case 110:
					case 182:
						wert=1;	
						i=max;
						break;
					case 100:
					case 199:
						if (fzid!=70)
							if (v.IsFlagSet(OF_PULLABLE))
								wert=1;
							else
								wert=2;
						else
							wert=-1;
						break;
					case 111:
						if (fzid>10)
							multi=5.0;
						else
							multi=1.0;
					case 101:
						dist=fzlocal::Distanz(v,Target)*multi;
						if (!v.IsFlagSet(OF_PULLABLE))
							dist=dist*3.5;
						if (fzid!=69)
							if ((dist < mindist) || (folge == 100))
							{
								mindist=dist;
								stw=v;
								folge=1;
								wert=0;
							}
						break;
					case 120:
						wert=-1;
						if (fzid>10)
							if (!v.IsFlagSet(OF_PULLABLE))
								wert=2;
							else 
								wert=1;
						break;
					case 150:
						if (fzid == 69)
							wert=1;
						else
							wert=-1;
						break;
					case 151:
						if (fzid == 70)
							wert=1;
						else
							wert=-1;
						break;
					case 130:
						wert=1;
						i=max;
						break;
					case 180:
						if (fzid==71)
						{
							wert=1;
							i=max;
						} else
							wert=-1;
						break;
					case 181:
						if (fzid==72)
						{
							wert=1;
							i=max;
						} else
							wert=-1;
						break;
					case 618:
						if (fzid==73 || fzid==74)
						{
							wert=1;
							i=max;
						} else
							wert=-1;
						break;
					default:
						char * buf="                                                       ";
						snprintf(buf,40,"Ungueltige Fz Anforderung %u",childID);
						Mission::PlayHint(buf);
						break;
				}
				if (wert>0)
				{
					if (v.IsCurrentAction("EActionFindPath") || (!v.IsHidden() && v.HasCommand("hidden")))
						wert=wblevel+wert/100;
					if (v.GetVehicleType()==VT_AMBULANCE_RHC)
					{
						if (!flugwetter || nacht)
						{
							if (childID == 610)
							{
								// Audio::PlaySample("mod:Audio/fx/kein_hubi.wav");
								Mission::PlayHint("kein_hubi");
							}
							wert=-1;
						}
					}	
				}
				if ((wert<folge) && (wert>-1))
				{
					folge=wert;
					stw=v;
				}				
			}
		}

	  	//Ab hier gehts nur mit einem weiter...

	  	if (!stw.IsValid() || folge==100)
	  	{
			if (dir>0) 
			{
				dir=dir+childID*100000;
				Caller->PushActionExecuteCommand(ACTION_INSERT,"kaufen",Target,dir,false);
			} else {
				System::Log("Kein Fz gefunden zu Code %u %u",rtw,aufruf);
				if (nachruecken && rtw!=99)
					Caller->PushActionExecuteCommand(ACTION_INSERT,"rufe_winterberg",Target,99000+childID,false);
			}
		} else {
			if ((kompakt && stw.IsHidden()) || childID==199 || childID==150)
				stw.SetFlag(OF_USABLE_WITH_MEGAPHONE);
			switch (childID)
			{
				case 599:
					Caller->PushActionExecuteCommand(ACTION_INSERT,"rufe_winterberg",Target,rtw*1000+childID,false);
					break;
				case 199:
					Caller->PushActionExecuteCommand(ACTION_INSERT,"rufe_winterberg",Target,199,false);
					break;
				case 692:
					if (!stw.IsFlagSet(OF_USABLE_WITH_MEGAPHONE)) 
					{
						Caller->PushActionExecuteCommand(ACTION_INSERT,"rufe_winterberg",Target,601,false);
						childID=622;
					}
					break;
			}
			if (nachforderung)
			{
				stw.SetUserData(Caller->GetID());
				childID=2048+childID;
			}
			if (normale_fahrt)
				childID=childID | nfmask;
			stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmiere_Winterberg",Target,childID,false);
		}
	}
};

object alarmiere_winterberg : CommandScript	
{

	// 2. schritt der Alarmierung : Fz alarmieren

	alarmiere_winterberg()
	{
		SetPriority(400);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle stw(Caller);
		int ptype=0;
		int cid=0;
		bool nachforderung=(childID & 2048)>0;
		bool normale_fahrt=childID & nfmask;
		bool trauma=false;
		bool bereitstellung=childID==910;

		if (bereitstellung)
			Vehicle stw(Target);
		
		childID=childID&2047;

		int fzid=fzlocal::fzid(&stw); // Fz-Typ laut AutosKaufen
		int fzstart=fzlocal::fzort(&stw); // Fz-Standort
		int callobj=stw.GetUserData();

		switch (childID)
		{
			case 620:
				ptype=19221;
				break;
			case 650:
			case 652:
				ptype=19224;
				break;
			case 651:
				ptype=19294;
				break;
			case 655:
				stw.SetFlag(OF_USABLE_WITH_MEGAPHONE); // die sieben Samurai
			case 653:
			case 654:
			case 601:
			case 610:
			case 611:
			case 612:
			case 692:	// Kompakt-NAW
			case 602:	// RTW
			case 622:
				ptype=19222;
				break;
			case 618:
				ptype=22222;
				break;
			case 350:
			case 480:
				ptype=11880;
				break;
			case 660:
				ptype=9578;
				break;
			case 666:
				ptype=84064;
				trauma=true;
				break;
			case 506:
			case 507:
			case 598:
			case 599:
			case 501:
			case 502:
			case 503:
			case 513:
			case 533:
			case 505:
			case 511:
			case 531:
			case 500:
			case 510:
			case 580:
			case 581:
			case 520:
			case 530:
			case 512:
			case 504:
			case 550:
			case 553:
			case 555:
			case 536:
			case 515:
			case 535:
			case 559:
				ptype=112;
				break;
			case 400:
				ptype=11880;
				break;
			case 200:
				ptype=110;
				break;
			case 110:
			case 100:
			case 199:
			case 101:
			case 111:
				if (fzid>10)
					ptype=1101;
				else 
					ptype=110;
				break;
			case 120:
				ptype=1101;
				break;
			case 150:
				stw.AssignCommand("fuehrung");
				ptype=1110;
				break;
			case 151:
				ptype=1111;
				break;
			case 180:
				stw.AssignCommand("fuehrung");
			case 181:
			case 182:
				ptype=115;
				break;
			case 911:
				break;
			case 910:
				ptype=112;
				break;
			default:
				break;
		}

		// Fz in Marsch setzen

		if (!bereitstellung)
		{
			stw.AssignCommand("ich_bin_nicht_frei");
			if (Game::IsMultiplayer())
				stw.SetPlayerMP(Caller->GetPlayerMP());
		}

		stw.AssignCommand("wird_alarmiert");
		GameObject obj(Target);

		System::Log("FZ ALARM %u %u %u %s",childID,fzstart,fzid,stw.GetName());

		if (childID > 600 && childID < 699 && !trauma) 
		{
			auftrag++;
			char * fms="                           ";
			char * format[]="RD-Auftrag Nr. %u";
			int x=snprintf(fms,27,format,auftrag);
			Mission::PlayHint(fms);
			Mission::SetCounter("Animal deaths",auftrag);
			System::Log(fms);
		}
		
			switch (fzid)
			{
				case 69:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,50,false);	
					break;
				case 67:
					if (stw.IsFlagSet(OF_USABLE_WITH_MEGAPHONE))
						stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,49,false);	
					else
						stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,48,false);	
					break;
				case 66:
					if (stw.IsFlagSet(OF_USABLE_WITH_MEGAPHONE))
						stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,47,false);	
					else					
						stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,46,false);	
					break;
				case 65:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,45,false);	
					break;
				case 64:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,44,false);	
					break;
				case 63:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,43,false);	
					break;
				case 62:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,42,false);	
					break;
				case 58:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,41,false);	
					break;
				case 56:
				case 59:
				case 60:
					if (childID==120)
					{
						stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,39,false);	
					} else
						stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,100,false);	
					break;
				case 57:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,40,false);	
					break;
				case 49:
				case 50:
				case 51:
				case 55:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,37,false);	
					break;
				case 54:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,38,false);	
					break;
				case 48:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,36,false);	
					break;
				case 42:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,530,false);
					ptype=113;	
					break;
				case 43:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,531,false);	
					break;
				case 44:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,32,false);	
					break;
				case 45:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,533,false);	
					ptype=113;
					break;
				case 46:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,34,false);	
					break;
				case 47:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,535,false);	
					break;
				case 1:	
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,0,false);	
					break;
				case 26:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,1,false);	
					break;
				case 21:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,2,false);	
					break;
				case 2:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,3,false);	
					break;
				case 14:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,4,false);	
					break;
				case 23:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,5,false);	
					break;
				case 24:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,6,false);	
					break;
				case 27:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,7,false);	
					break;
				case 25:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,8,false);	
					break;
				case 22:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,9,false);	
					break;
				case 12:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,10,false);	
					break;
				case 19 :
				case 30 :
				case 53	:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,11,false);	
					break;
				case 20 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,12,false);	
					break;
				case 28 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,513,false);	
					break;
				case 29 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,514,false);	
					break;
				case 13:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,16,false);	
					break;
				case 16:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,17,false);	
					break;
				case 3:
				case 4:
				case 5:	
				case 6:
				case 40:
				case 15:
				case 39:
					switch (childID)
					{
						case 501:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,18,false);	
							break;
						case 510:
						case 511:
						case 512:
						case 515:
						case 550:
						case 599:
						case 598:
						case 507:
						case 580:
						case 581:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,22,false);	
							break;
						case 911:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,522,false);	
							break;
						case 910:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,22,false);	
							break;
						case 513:
						case 520:
						case 553:
						case 503:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,23,false);	
							break;
						case 504:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,20,false);	
							break;
						case 502:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,21,false);	
							break;
						case 530:
						case 531:
						case 533:
						case 535:
						case 555:
						case 505:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,28,false);	
							break;
						case 500:
							stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,15,false);	
							break;
					}
					break;
				case 38 :
				case 31 :
				case 52	:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,19,false);	
					break;
				case 32 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,24,false);	
					break;
				case 33 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,25,false);	
					break;
				case 34 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,26,false);	
					break;
				case 35 :
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,27,false);	
					break;
				case 73 :
				case 74	:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,51,false);	
					break;
				case 75	:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,52,false);	
					break;
				case 41	:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,54,false);	
					break;
				default:
					stw.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&stw,100,false);	
					break;
			}

			if (trauma)
				stw.PushActionExecuteCommand(ACTION_APPEND,"mannschaft_rufen",Target,ptype,false);
			else
			{
				stw.PushActionExecuteCommand(ACTION_APPEND,"mannschaft_rufen",&stw,ptype,false);
				if (stw.HasCommand("zugfz"))
					stw.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"zugliste_fz_entfernen",&stw,0,false);
				if (!bereitstellung)
				{
					stw.PushActionExecuteCommand(ACTION_APPEND,"zugliste_fz",Target,0,false);
					switch (childID)
					{
						case 501:
						case 510:
						case 511:
						case 580:
						case 581:
						case 599:
						case 598:
							cid=112;
							break;
						case 692:
							if (!stw.IsFlagSet(OF_USABLE_WITH_MEGAPHONE))
							{
								stw.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"rufe_winterberg",Target,601,false); // NEF mitalarmieren
								childID=622;
								cid=19292;
							}
							break;
						case 622:
							cid=19292;
							break;
						case 618:
							ActorList al("landeplatz");
							Target=*al.GetActor(0);
							break;
						case 650:
							cid=650;
							break;
						default:
							cid = 0;
					}
				} else 
					cid=999;

				stw.PushActionExecuteCommand(ACTION_APPEND,"check_ms_vollzaehlig",Target,cid,false);
				
				if (!bereitstellung)
				{
					stw.PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,3,false);
					if (stw.IsHidden() && stw.HasCommand("hidden"))		// Nachbarfz ausserhalb des Stadtgebietes ?
					{
						float anmarsch=fzlocal::verz(&stw);
						stw.PushActionWait(ACTION_APPEND,anmarsch);
					}
			
					Actor ziel;
				
					if (nachforderung)
					{
						ziel=Game::GetActor(callobj);
					} else
						ziel=*Target;
				
					stw.PushActionExecuteCommand(ACTION_APPEND,"fz_raus",&ziel,childID,normale_fahrt);
				}
			}
			
			if (bereitstellung)
				stw.PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,1,false);
			else 
			{	
				stw.PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,4,false);
	
				if (obj.IsValid()) 
				{
					switch (childID) 
					{
						case 692:
						case 610:
						case 601:
						case 654:
							stw.PushActionExecuteCommand(ACTION_APPEND,"CheckHubiDown",Target,1,false);
							if ((((Target->GetType() == ACTOR_PERSON) && !obj.HasCommand("tl")) || (Target->GetType() == ACTOR_OPEN_HOUSE)) && !obj.HasCommand("alarm_dummy") && stw.IsFlagSet(OF_USABLE_WITH_MEGAPHONE))
								stw.PushActionExecuteCommand(ACTION_APPEND,"NEF_examine",Target,0,false); // NA versorgt Pat
							else 
								if (Target->GetType() == ACTOR_VEHICLE)
								{
									if (!obj.HasCommand("ErwarteNA"))
									{
										obj.AssignCommand("ErwarteNA");
										obj.SetUserData(-1);
									}
									stw.PushActionExecuteCommand(ACTION_APPEND,"TransportBegleiten",Target,0,false);
								} else
									stw.PushActionExecuteCommand(ACTION_APPEND,"emptycar",&stw,0,false);
							break;
						case 618:
							stw.PushActionExecuteCommand(ACTION_APPEND,"CheckHubiDown",Target,12,false);
							break;
						case 622:
						case 602:
						case 653:
						case 655:
							if ((((Target->GetType() == ACTOR_PERSON) && !obj.HasCommand("tl")) || (Target->GetType() == ACTOR_OPEN_HOUSE)) && !obj.HasCommand("alarm_dummy"))
								stw.PushActionExecuteCommand(ACTION_APPEND,"RTW_examine",Target,1,false); // RA versorgt Patient
   							 else if (Target->GetType() == ACTOR_VEHICLE)
								stw.PushActionExecuteCommand(ACTION_APPEND,"SEG_an_RTW",Target,0,false); // RTW übernimmt vom SEG-Zelt
							break;
						case 300:
					      		if ((Target->GetType() == ACTOR_VEHICLE) || (Target->GetType() == ACTOR_OBJECT))
								stw.PushActionExecuteCommand(ACTION_APPEND,"LoadUp_Freeplay",Target,0,true); // Fahrzeug aufladen
							break;
						case 620:
							stw.PushActionExecuteCommand(ACTION_APPEND,"emptycar",&stw,0,false);
							break;
						case 101:
						case 111:
							if (Target->GetType() == ACTOR_VEHICLE)
								stw.PushActionExecuteCommand(ACTION_APPEND,"TransportBegleiten",Target,0,false);
							else {
								Person tp(Target);
								if ((Target->GetType() == ACTOR_PERSON) && !tp.HasCommand("tl") && !tp.HasName("anrufer"))
									stw.PushActionExecuteCommand(ACTION_APPEND,"POL_arrest",Target,0,false);
							}
							break;
						case 130:
							break;
					}
					if (childID!=130 && !trauma)
						stw.PushActionRedirect(ACTION_APPEND);
				}
			}
	}
};

object fz_raus : CommandScript
{

	bool normale_fahrt=false;

	fz_raus()
	{
		SetPriority(500);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		normale_fahrt=true;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		GameObject obj(Target);
		int udat=obj.GetUserData();
		int cid=0;
		Vector TargetPos;
		Vehicle stw(Caller);
		char * fz[1];
		bool nachbar=stw.IsHidden();
		int sosi;

		if (nachbar)
			int sosi=0;
		else 
			int sosi=3;
	
		
		if (Target->GetType()==ACTOR_OPEN_HOUSE)
		{
			OpenHouse oh(Target);
			TargetPos=oh.GetEntrancePosition(true,0.0);
		} else if (Target->GetType()==ACTOR_VEHICLE && obj.HasChild("SEGOUT"))
				TargetPos=obj.GetChildPosition("SEGOUT");
			else
				TargetPos=Target->GetPosition();

		Game::FindFreePosition(&stw, TargetPos,250);

		if (stw.HasChild("pumpe"))
			stw.SetChildEnabled("pumpe",true);

		stw.EnableSpecialLights(false);
		stw.EnableBreakLights(false);
   		stw.EnableCommand("WarningLightOn", true);
   	  	stw.RemoveCommand("WarningLightOff");
	  	//FZG ist nicht mehr verfügbar.

		if (!normale_fahrt)
		{
			stw.PushActionExecuteCommand(ACTION_INSERT,"WT_SoSi",&stw,sosi,false); //Einsatzfahrt, erst nur Blaulicht
			stw.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST, "DUMMYDisableSiren", &stw, 2, false); //childID 1: Blaulichter bleiben an...
		}

		switch (childID)
		{
			case 200:
				if (((Target->GetType() == ACTOR_PERSON) || (Target->GetType() == ACTOR_VEHICLE)) && (!obj.HasCommand("alarm_dummy")))
					stw.PushActionHeliFollow(ACTION_INSERTAFTERFIRST,Target);
				stw.PushActionFlyTo(ACTION_INSERTAFTERFIRST, TargetPos,false,-1.0f);
				break;
			default:
				if (stw.HasCommand("FlyTo"))
					stw.PushActionFlyTo(ACTION_INSERTAFTERFIRST,TargetPos,true,135);
				else
					stw.PushActionMove(ACTION_INSERTAFTERFIRST, TargetPos,false);
				break;
		}
		
		if (stw.IsHidden())
			stw.PushActionExecuteCommand(ACTION_INSERT,"nachbar_holen",&stw,0,false);

		if (!nachbar && !normale_fahrt)
		{
			float wait;
			if (stw.IsPolice())
				wait=1.5;
			else if (stw.IsFirefighter())
				wait=4.5;
			else 
				wait=5.0;
			PersonList pass=stw.GetPassengers();
			pass.GetPerson(0)->PushActionWait(ACTION_NEWLIST,wait);
			pass.GetPerson(0)->PushActionExecuteCommand(ACTION_APPEND,"WT_SoSi",&stw,10,false); //Einsatzfahrt
		}
		normale_fahrt=false;
	}
};


object nachbar_holen : CommandScript
{
	nachbar_holen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle stw(Caller);
		int fzort=fzlocal::fzort(&stw); // Fz-Standort
		if (fzort>50)
			fzort=fzort-50;
		GameObjectList ol;
		Game::CollectObstaclesOnVirtualObject(fzlocal::stellplatz(fzort),ol,ACTOR_VEHICLE);
		if (ol.GetNumObjects()>0)
		{
			stw.PushActionWait(ACTION_INSERT,1.0f);
			stw.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"nachbar_holen",Target,ChildID,false);
			System::Error("nachbar holen: ausfahrt blockiert");
		} else {
			ActorList fzl=Game::GetActors(fzlocal::stellplatz(fzort)); // Fz am gewuenschten Stellplatz erzeugen
			if(fzl.GetNumActors() > 0)
				Actor fz = *fzl.GetActor(0);
			else
				System::Error("Ungueltiger Stellplatz");

			Vector nachbarpos=fz.GetPosition();
			Game::FindFreePosition(&stw,nachbarpos,20);
			stw.SetPosition(nachbarpos);
			stw.Show();
		}
	}
};

object ResetSpeed : CommandScript
{
	ResetSpeed()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle stw(Target);
		switch (stw.GetVehicleType())
		{
			case VT_AMBULANCE_RHC:
			case VT_POLICE_PHC:
			case VT_FIREFIGHTERS_FMB:
				break;
			default:
				stw.SetSpeed(civspeed);
				break;
		}
	}
};

// ABSCHNITT : GO HOME
//
//

const char DUMMY_HASWARNINGLIGHTS[] = "DUMMYHasWarningLights";
const char DUMMY_DISABLE[] = "DUMMYDisableSiren";

object gohome_winterberg : CommandScript
{
	Vector Wache;
	Actor fz;

	gohome_winterberg()
	{
		SetCursor("gowache");
		SetIcon("gowache");
		SetValidTargets(ACTOR_VEHICLE);
		SetPriority(85);
	}

	bool CheckPossible(GameObject *Caller)
	{
		Vehicle v(Caller);
		return !v.IsDestroyed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Caller);
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() != Caller->GetID() || Caller->GetType() != ACTOR_VEHICLE || ((v.GetNumPassengers() == 0) && (v.GetFreePassengers()>0)))
			return false;

		//Freeplay oder nicht?
		// changed by Bass-ti -> new em4-codec
		if (Game::IsFreeplay())
			return true;

		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Caller);
		bool nachbarfz=v.HasCommand("hidden");
		bool extern=(!(v.HasCommand("gohome_winterberg")) && !(v.HasCommand("aufsitzen")));
		bool bedarfsfz=v.HasCommand("bedarfs_fz");		
		const char * parken[2];
		int fzid;

		Game::ExecuteCommand("WitchDocAction",Caller);
		bool keine_abfahrt=((v.GetNumPassengers() == 0) && (v.GetFreePassengers() > 0) && (v.GetVehicleType()!=VT_POLICE_GETAWAY)) || (v.HasCommand("ErwarteNA") && v.GetNumTransported()>0);
		
		if (keine_abfahrt)	// Fz nicht ohne sein Personal wegfahren lassen, NEF darf ins KH folgen
			return;

		v.PushActionWait(ACTION_NEWLIST,0.1);
		if (v.HasCommand("DUMMYHasMast"))
			v.PushActionExecuteCommand(ACTION_APPEND,"Funkmast",Caller,0,false);

		if (v.GetVehicleType() == VT_FIREFIGHTERS_GTF)
		{
			PersonList pl(ROLE_SQUAD);
			bool SchlauchDran=false;
			Person fw;
			for (int i=0; (i<pl.GetNumPersons()) && (!SchlauchDran);i++)
			{
				fw=pl.GetPerson(i);
				if (fw.GetFirehoseID()!=0)
					SchlauchDran=v.IsUsingConnector(&fw);
			}
			if (SchlauchDran)
			{
				Mission::PlayHint("WIB_HOSE_CONNECTED");
				v.PushActionWait(ACTION_NEWLIST,1.0);
				return;
			}
		}
	
		v.SetFlag(OF_HAS_FIRE_EXTINGUISHER);

		if (v.HasChild("NA"))
			v.SetChildEnabled("NA",false);
		if (v.HasChild("POL"))
			v.SetChildEnabled("POL",false);

		if (v.HasCommand("zugfz"))
			v.PushActionExecuteCommand(ACTION_APPEND,"zugliste_fz_entfernen",&v,0,false);


		if (v.HasCommand("DUMMYHasWarningLights"))
		{
 			v.EnableBlinker(BLT_NONE);
 			v.RemoveCommand(DUMMY_HASWARNINGLIGHTS);
		}

		v.RemoveCommand("DUMMYHasUmfeld");
		v.EnableSpecialLights(false);

		if (v.GetVehicleType() == VT_THW_FGRR_BKF)
			Caller->PushActionDeinstall(ACTION_INSERT);

		v.PushActionExecuteCommand(ACTION_APPEND,"ActionStopSound",&v);
		v.PushActionExecuteCommand(ACTION_APPEND, "DUMMYEnableLights", Caller, 2, false);
		
		if (extern)
		{
			Mission::PlayHint("Externes Zusatzfahrzeug zurueck zur Basis.");
			Caller->PushActionReturnToBase(ACTION_APPEND);
		} else {
			int dir=fzlocal::fzort(Caller);
			if (dir>50)
				dir=dir-50;
			fzid=fzlocal::fzid(Caller);
			if (dir==0)
				parken[1]= fzlocal::kennung(fzid);
			else			
				parken[1]= fzlocal::stellplatz(dir);
	
			ActorList fzl=Game::GetActors(parken[1]); 
			if(fzl.GetNumActors() > 0)
				Actor fz = *fzl.GetActor(0);
			else
				System::Error("Ungueltiger Fz_Standort");

			//Wo soll das Fahrzeug parken?
			Vector Wache=fz.GetPosition();
			Game::FindFreePosition(&v, Wache);
			Caller->PushActionExecuteCommand(ACTION_APPEND, DUMMY_DISABLE, Caller, 1, false);
			Caller->PushActionLightOn(ACTION_APPEND,false);

			int cid;
			bool rueckfahrwarnung = false;  // erstmal für alle an

			switch(v.GetVehicleType())
			{
				case VT_AMBULANCE_NEF :
				case VT_AMBULANCE_RTW :
				case VT_AMBULANCE_RHC :
					if (v.HasCommand("ich_bin_ein_bsw"))
					{
						Mission::PlayHint("WIB_FRIEDHOF");
						break;
					}

					if (v.GetNumTransported() > 0)
					{
						Caller->PushActionExecuteCommand(ACTION_APPEND,"zum_krankenhaus",Caller,0,false);
						return;
					}
					cid=0;		// nicht absitzen
					
					if (v.GetVehicleType() != VT_AMBULANCE_RTW)
					{
						//Leeres NEF bekommt am KH einen neuen NA...
						PersonList persons = v.GetPassengers();
						bool HasNA=(childID==0815);
						for(int j=0; j<persons.GetNumPersons(); j++)
						{
							HasNA=(HasNA || persons.GetPerson(j)->IsDoctor()); //Ist ein NA an Bord?
						}
						if (!HasNA)
						{
							Caller->PushActionExecuteCommand(ACTION_APPEND, "NEF_zum_KH", Target, 0, false);
							return;
						}
						cid=0;
						break;
					}
					break;
				case VT_POLICE_STW:
				case VT_POLICE_MTW:
					if (childID==19292)
					{
						Caller->PushActionExecuteCommand(ACTION_APPEND, "NEF_zum_KH", Target, 0, false);
						return;
					}
					break;
			}

			bool frei=false;
			bool trans=false;
			bool teamok=(v.GetFreePassengers()==0);
			bool reparieren=(childID==60);
			GameObjectList ol=v.GetCarriedObjects();

			trans=((ol.GetNumObjects() > 0) || (v.GetNumTransported() > 0)) && !reparieren;  // es wird nix transportiert
			teamok=(teamok || ((v.GetVehicleType()==VT_AMBULANCE_RTW) && (v.GetFreePassengers() < 2)) || ((v.GetVehicleType()==VT_POLICE_STW) && (v.GetFreePassengers()<3))); // Mannschaft komplett
			frei=(!trans && ((v.GetEnergy()/v.GetMaxEnergy()) > 0.4) && teamok && !reparieren); // Fz nicht schwer beschaedigt
			

			Caller->PushActionExecuteCommand(ACTION_APPEND,"Geraete_entfernen",Caller,0,false);
			
			if (childID!=110)
			{
				if (reparieren && !v.HasCommand("FlyTo"))
					Caller->PushActionExecuteCommand(ACTION_APPEND,"Fzreparieren",Caller,0,false);
				else if (frei)
					Caller->PushActionExecuteCommand(ACTION_APPEND,"FzFrei",Caller,0,false);
				else if (trans)
					Caller->PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,7,false);
				else 
					Caller->PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,6,false);
			}
				
			rueckfahrwarnung=((fzid == 3) || (fzid == 4));
			Vector Vorfahrt=Vector (0,-200,0);
			Vector Wende=Vector (0,-600,0);	// Standardwende
			int eje=fzlocal::richtung(fzid);

			switch (eje)
			{
				case 0 :
					Vorfahrt=Vector (300,0,0);
					Wende=Vector (600,0,0);
					break;
				case 1:
					Vorfahrt=Vector (0,300,0);
					Wende=Vector (0,500,0);
					break;
				case 2:
					Vorfahrt=Vector (-200,0,0);
					Wende=Vector (-400,0,0);
					break;
				case 3:
					break;
			}
	
			if (Caller->HasCommand("FlyTo"))
				v.PushActionFlyTo(ACTION_APPEND,Wache,(!bedarfsfz && !nachbarfz),135);
				// wenn stammfz, dann am ziel landen
			else {
				Caller->PushActionMove(ACTION_APPEND, Wache + Vorfahrt); // Fahre zum Wendepunkt
				Caller->PushActionExecuteCommand(ACTION_APPEND,"VCmdWarningLights",Caller);
				Caller->PushActionTurnTo(ACTION_APPEND, Wache + Wende); // Wende
				if (rueckfahrwarnung)
					Caller->PushActionExecuteCommand(ACTION_APPEND,"ActionMotorSound",Caller,4,false);
				Caller->PushActionMove(ACTION_APPEND, Wache); // Einparken
				if (rueckfahrwarnung)
					Caller->PushActionExecuteCommand(ACTION_APPEND,"ActionStopSound",Caller);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"VCmdWarningLights",Caller);
			}

			bool indiewache=!v.IsFirefighter() || !KatSZustand;
			
			if (Caller->HasCommand("feierabend"))
				Caller->PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,6,false);
			else
				if (indiewache)
					Caller->PushActionExecuteCommand(ACTION_APPEND,"StatusSenden",Caller,2,false);

			switch(v.GetVehicleType())
			{
				case VT_FIREFIGHTERS_DLK :
				case VT_FIREFIGHTERS_RW :
				case VT_FIREFIGHTERS_TLF :
				case VT_FIREFIGHTERS_LF :
				case VT_FIREFIGHTERS_LPF :
				case VT_FIREFIGHTERS_TFMB :
				case VT_FIREFIGHTERS_GTF :
				case VT_FIREFIGHTERS_DEKONP :
					cid=112;	// Absitzen und Fw betretet
					break;	

				case VT_POLICE_SW :
				case VT_POLICE_STW :
				case VT_POLICE_MTW :
					if ((v.GetVehicleType() == VT_POLICE_MTW) && (v.GetNumTransported() < 4))
						Caller->PushActionExecuteCommand(ACTION_INSERT,"FzFrei",Caller,0,false);
					cid=110;	// Absitzen und PSt betreten			
					break;
				case VT_AMBULANCE_RTW :
					cid=112;
					break;
				case VT_FIREFIGHTERS_ASF:
					if (Caller->IsCarryingAnything())
						Caller->PushActionExecuteCommand(ACTION_APPEND,"ActionFreeplayUnload",Caller,0,false);
					// und dann nicht absitzen
				case VT_AMBULANCE_RHC :
				case VT_AMBULANCE_NEF :
					cid=112;
					break;
				default : 
					cid=0;	// wenn nicht gelistet, dann nicht absitzen
			}

			if (bedarfsfz)
			{
				Caller->PushActionWait(ACTION_APPEND,5.0);
				Caller->PushActionDeleteOwner(ACTION_APPEND);
				
			} else {
				if (nachbarfz)
					Caller->PushActionShowHide(ACTION_APPEND,true);
				if (indiewache)
				{				
					Caller->PushActionExecuteCommand(ACTION_APPEND,"WacheAussteigen",Caller,cid,false);
					Caller->PushActionExecuteCommand(ACTION_APPEND,"FzInspektion",Caller,fzid,false);
				}
			}
			GameObjectList zl;
			zl=Game::GetGameObjectsWithPrefix("ZUG");
			for (int zc=0;zc<zl.GetNumObjects();zc++)
				if (Caller->GetID()==zl.GetObject(zc)->GetUserData())
					Game::RemoveGameObject(zl.GetObject(zc));
		}
	}
};


object WacheAussteigen : CommandScript
{

	WacheAussteigen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		ActorList place;
		bool klinik=false;

		int fzid=fzlocal::fzid(Caller);
		switch (fzid)
		{
			case 3:
				place=Game::GetActors("tor3");
				break;
			case 4:
				place=Game::GetActors("tor2");
				break;
			case 5:
				place=Game::GetActors("tor5");
				break;
			case 6:
				place=Game::GetActors("tor4");
				break;
			case 15:
				place=Game::GetActors("tor5");
				break;
			case 39:
				place=Game::GetActors("tor5");
				break;
			case 40:
				place=Game::GetActors("tor1");
				break;
			case 7:
			case 8:
			case 9:
			case 10:
				place=Game::GetActors("police_entry");
				break;

			case 1:
			case 2:
			case 27:
				place=Game::GetActors("rwache");
				klinik=true;
				break;
			default:
				place=Game::GetActors(Caller->GetName());
				break;
		}

		Actor entry;
		entry=place.GetActor(0);
		Vehicle v(Caller);
		PersonList pl=v.GetPassengers();
		PersonList tl=v.GetTransports();
		Person p,t;
		int tn=tl.GetNumPersons();
		bool nix=false;
		bool boot=false;
		bool IsKompakt=v.GetVehicleType()==VT_AMBULANCE_RTW;

		if (IsKompakt || v.IsPolice())
			v.ClearFlag(OF_USABLE_WITH_MEGAPHONE);

		switch (ChildID)
		{
			case 0:
				break;
			case 9578:
				PersonList pl(Caller->GetName());
				tn=0;
				boot=true;
				Caller->PushActionEmptyBoat(ACTION_APPEND);
				Caller->PushActionDrop(ACTION_APPEND);
			default:
				for (int i=0; i<pl.GetNumPersons(); i++)
				{
					p=pl.GetPerson(i);
					if (boot)
						p.PushActionWait(ACTION_NEWLIST,0.1f);
					 else
						p.PushActionLeaveCar(ACTION_NEWLIST,Caller);
					if (p.HasCommand("tl"))
						p.PushActionExecuteCommand(ACTION_APPEND,"tl_aufsitzen",&p,0,false);
					if (tn>0)
					{
						tn--;
						t=tl.GetPerson(tn);
						if (!t.HasAnimation("bark")) //Gangster oder Hund ?
						{
							t.PushActionLeaveCar(ACTION_NEWLIST, Caller);
							if (!v.IsHidden())	
							{
								nix=t.SetBehaviour(BEHAVIOUR_GANGSTER_CIVILUNARMED);
								t.PushActionWait(ACTION_APPEND, 5.f);
							} else
								t.PushActionDeleteOwner(ACTION_APPEND);
						}
					}
					if (nix)
					{
						p.PushActionMove(ACTION_APPEND, &t, TARGET_FOLLOW);
						p.PushActionArrest(ACTION_APPEND, &t,false);
					}

					if (klinik)
						p.PushActionExecuteCommand(ACTION_APPEND,"InDieAnstalt",&entry,0,true);
	
					else if (!v.IsHidden() && !boot)
						p.PushActionExecuteCommand(ACTION_APPEND,"MoveTo",&entry,112,true);

					if (nix)
						p.PushActionPutInBase(ACTION_APPEND);
					p.PushActionDeleteOwner(ACTION_APPEND);
					nix=false;
				}
				if (v.GetVehicleType() == VT_POLICE_STW)
					p.PushActionExecuteCommand(ACTION_INSERTBEFORELAST,"Patrouille_frei",&v,15,false);
				break;
		}
		v.ClearFlag(OF_PULLABLE);
		v.ClearFlag(OF_FLOTSAM);
		fzlocal::fz_beladen(Caller);
	}
};

object FzFrei : CommandScript
{
	FzFrei()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		char * fzfrei="Einsatzfahrzeug frei auf Funk";
		int fzid=fzlocal::fzid(Caller); 	// Fz-Typ laut AutosKaufen
		bool killed=false;
		if (childID == 0)
		{
			Caller->PushActionExecuteCommand(ACTION_INSERT,"StatusSenden",Caller,1,false);
		}
		PersonList pl(Caller->GetName());
		for (int px=0;px<pl.GetNumPersons();px++)
			if (!pl.GetPerson(px)->HasCommand("tl"))
				pl.GetPerson(px)->SetUserData(0);
		Caller->RemoveCommand("ich_bin_nicht_frei");	
	}
};

Person signalgeber;
GameObject metronom;
int schleife=-1;

const int maxfae=75;
bool zfae[maxfae];
bool zalarm=false;
bool zf=false;
bool zug=false;
float civspeed=6.0;

object alarmgeber : CommandScript
{

	alarmgeber()
	{
		SetPriority(700);
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		signalgeber.PushActionExecuteCommand(ACTION_APPEND,"kanalfrei",Target,childID,false);
	}
};

int rwacheid;

object alarminit : CommandScript
{
	alarminit()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		PersonList al("5tongeber");
		GameObjectList ol(metronam);
		metronom=ol.GetObject(0);
		metronom.ClearFlags();
		signalgeber=al.GetPerson(0);
		zug=false;
		zugstart=false;
		zf=false;
		if (deluxe)
			civspeed=7.5;
		else
			civspeed=6.0;
		schleife=-1;
		signalgeber.PushActionWait(ACTION_NEWLIST,1.0);
		metronom.PushActionExecuteCommand(ACTION_NEWLIST,"CheckWTDInit",&metronom,0,false);
		metronom.PushActionExecuteCommand(ACTION_APPEND,"dienstende",&metronom,3,false);
		for (int i=0;i<maxfae;i++)
			zfae[i]=true;
		VehicleList vl(VT_POLICE_STW,VT_POLICE_STW);
		for (i=0;i<vl.GetNumVehicles();i++)
			vl.GetVehicle(i)->PushActionExecuteCommand(ACTION_NEWLIST,"Fahre_Patrouille",vl.GetVehicle(i),i*20,false);
		ActorList rl("klinik");
		rwacheid=rl.GetActor(0)->GetID();
		return;
	}
};

bool katsalarmierung=false;
bool nobeep=false;
bool kats=false;
bool play_fms=true;
bool sir=false;
bool zugstart;
int zugcode;

object kanalfrei : CommandScript
{	
	int cid;

	kanalfrei()
	{
		SetPriority(700);
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int al=0;
		char * agcode[]="FAE";
		bool sirzvei=false;
		bool probe=false;

		switch (childID)
		{		
			case 402:
				KatSZustand=false;
				nobeep=false;
				break;
			case 401:
				KatSZustand=true;
				katsalarmierung=true;
				nobeep=true;
				break;
			case 301:
				kats=true;
			case 201:
				sir=true;
			case 101:	// Zugalarmsequenz starten
				for (int i=0;i<maxfae;i++)
					zfae[i]=true;
				zalarm=true; 
				zug=true;
				signalgeber.PushActionExecuteCommand(ACTION_INSERT,"set_wartezeit",Target,8,false);
				zugstart=true;
				cid=0;
				System::Log("FZ ALARM ------------- Zugstart");
				break;
			case 102:	// Zugalarmsequenz Ende
			case 103:	// Zugalarmsequenz Ende
				zalarm=false;
				zugstart=false;
				nobeep=false;
				System::Log("Zugsequenz Ende");
				break;
			case 104:
				signalgeber.PushActionExecuteCommand(ACTION_INSERT,"set_wartezeit",Target,12,false);
				break;
			case 108: // Fzabstand Abstand fuer Demo-Zug
				signalgeber.PushActionExecuteCommand(ACTION_INSERT,"set_wartezeit",Target,4,false);
				break;
			case 100:
				if (zalarm)
					cid++;
				signalgeber.PushActionExecuteCommand(ACTION_INSERT,"fz_rueckt_aus",Target,cid,false);
				break;
			default:
				// System::Log("KanalFrei Code %u von %s an %s",childID,Caller->GetName(),Target->GetName());
				bool fz_raus=false;
				Vehicle vec(Target);
				int mem=childID;
				int sircode;
				bool alarmieren=false;

				if (childID>999)
					alarmieren=true;
				else 
				{
					if ((childID > 500) && (childID < 600) || sir)
					{
						al=fzlocal::fzort(Target)-50;
						agcode="SIR";
						if (childID > 500)
							childID=childID-500;
						sirzvei=true;
					} else if ((childID > 899) && (childID < 1000))
						{
							fz_raus=false;
							al=childID-600;
							childID=childID-900;
							probe=true;							
							sirzvei=true;
							agcode="SIR";	
						}
					alarmieren=(!zalarm || (zalarm && zfae[childID])) && !vec.IsFlagSet(OF_PULLABLE);
				}
				if (alarmieren)
					if ((schleife > -1) && Audio::IsPlaying(schleife))
					{
						signalgeber.PushActionExecuteCommand(ACTION_INSERT,"kanalfrei",Target,mem,false);
						signalgeber.PushActionWait(ACTION_INSERT,0.1f);
						return;
					} else {
						if ((childID>999) && !Target->IsValid())
						{}
						else if (childID>1999)
						{
							char * fms="                           ";
							char * format[]="mod:/Audio/fx/fms/%u%u.wav";
							int status=childID-2000;
							if (status>9)
							{
								int fzid=Target->GetUserData()+1000;
								status=status-10;
								if (deluxe)
									fzid=fzid+100;
							}
							else
								int fzid=fzlocal::fzid(Target);
							int x=snprintf(fms,27,format,1000+fzid,status);
							System::Log(fms);
							if (play_fms)
								schleife=Audio::PlaySample(fms);
							signalgeber.PushActionWait(ACTION_INSERT,0.5f);
						} else if (childID>999)
						{
							int status=childID-1000;
							if (status>9)
							{
								int fzid=Target->GetUserData()+1000;
								status=status-10;
								if (deluxe)
									fzid=fzid+100;

								int h,m,s;
								Game::GetTime(h,m,s);

								System::Log(":BMA:%u:%u:%u:%u:%u:%u",
deluxe ? 1 : 0,
Target->GetUserData(),
status,
h, m, s);
							} else {
								int fzid=fzlocal::fzid(Target);
								int h,m,s;

								Game::GetTime(h,m,s);

								System::Log(":FMS:%u:%u:%u:%u:%u",fzid,status,h, m, s);
							
							}
							char * fms="                           ";
							char * format[]="mod:/Audio/fx/fms/%u%u.wav";
							int x=snprintf(fms,27,format,1000+fzid,status);
							if (play_fms)
								schleife=Audio::PlaySample(fms);
							signalgeber.PushActionExecuteCommand(ACTION_INSERT,"kanalfrei",Target,(1000+childID),false);
						} else {
							cid=1;
							if (katsalarmierung)
							{
								cid=1000;
								al=49;	// virtueller Alarm-Fuer-Alle-Ort
								sirzvei=true;
							}

							if (katsalarmierung || !nobeep)
							{
								if (sirzvei || sir)
								{
									if (!probe)
									{
										signalgeber.PushActionExecuteCommand(ACTION_INSERT,"kanalfrei",Target,childID,false);
										sircode=150+al;
									} else
										sircode=al-200;
									char * fms="                           ";
									char * format[]="mod:/Audio/fx/sir%u.wav";
									int x=snprintf(fms,28,format,sircode);
									schleife=Audio::PlaySample(fms);
								} else {
									schleife=Audio::PlaySample(fzlocal::fae(childID));
									zfae[childID]=false;
									Mission::PlayHint(fzlocal::dusa(childID));
									System::Log("Alarmierung wird ausgelöst");
									System::Log(fzlocal::dusa(childID));
								}
							}

							if (katsalarmierung)
							{
								agcode="KTS";
								al=999;
									
							} else if (kats)
							{
								al=103;
								kats=false;
								sir=false;
								agcode="KAT";
							} else if (sir)
							{
								al=102;
								Caller->PushActionExecuteCommand(ACTION_INSERT,"sirene",Caller,0,false);
								sir=false;
								agcode="SIR";
							}
							if (al==0)
								if (vec.IsFirefighter() || vec.IsAmbulance() || vec.GetVehicleType()==VT_THW_FGRR_BKF)
									al=-childID-1;
							if ((al!=0 && !nobeep) || katsalarmierung)
							{
								metronom.PushActionExecuteCommand(ACTION_INSERT,"FMEauf",Target,al,false);
								metronom.PushActionWait(ACTION_INSERT,0.7f);
							}
							if ((!sir && !sirzvei) || nobeep)
								fz_raus=true;
							katsalarmierung=false;
							sir=false;
							kats=false;
							int h,m,s;
							Game::GetTime(h,m,s);
							System::Log(":SIR:%s:%u:%u:%u:%u", agcode, childID, h, m, s);
						}
					}
				else
				{
					if (zalarm)
						cid++;
					fz_raus=true;
				}
				if (fz_raus)
				{
 					signalgeber.PushActionExecuteCommand(ACTION_INSERT,"fz_rueckt_aus",Target,cid,false);
					zugstart=false;
				}
				break;
		}
	}
};


object fz_rueckt_aus : CommandScript
{

	fz_rueckt_aus()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);
		if ((v.IsFirefighter() && v.GetVehicleType()!=VT_FIREFIGHTERS_FMB && (v.GetNumPassengers()+v.GetFreePassengers()) > 3) || v.HasCommand("fuehrung") && childID!=1000)
		{
			v.SetFlag(OF_USABLE_WITH_MEGAPHONE);
		}
		switch (childID)
		{
			case 0:
				v.RemoveCommand("wird_alarmiert");
				break;
			case 100:
				break;
			case 1000:
				childID=1;
			default:
				v.AssignCommand("abwarten");
				v.SetUserData(childID);
				v.RemoveCommand("wird_alarmiert");
				break;
		}
	}
};

bool fme_fix=true; // fester Melderton je Alarmierung

object FMEfix : CommandScript
{
	FMEfix()
	{
		SetIcon("notaus");
		SetCursor("notaus");
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		fme_fix=!fme_fix;
	}
};

object FMEauf : CommandScript
{
	FMEauf()
	{
		SetPriority(1000);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int pieper;
		Vector pos;
		int x;
		bool sirwib=childID==102 || childID==103 || childID==300; 
		bool sirext=childID>0 && !sirwib;
		bool allesirs=childID==999;
		bool nofme=childID>299;
		bool isfme=childID<0;

		if (fme_fix && isfme)
			switch (childID)
			{
				case -44:
				case -45:
					pieper=99;
					break;
				default:
					for (pieper=-childID;pieper>35;pieper=pieper-35);
					break;
			}
			
		else 		
			pieper=Math::rand()%35+1;

		if (allesirs||sirext||sirwib)
			pieper=1;	

		if (!allesirs && !nofme)
		{
			char * fme="                            ";
			char * format[]="mod:/Audio/fx/fme/fme%u.wav";
			x=snprintf(fme,28,format,pieper+100);
			Audio::PlaySample(fme);
		} else System::Log("Kats Alarm kreisweit");

		if (sirwib || allesirs)
		{
			for (int i=0;i<sirs.GetNumObjects();i++)
			{
				pos=sirs.GetObject(i)->GetPosition();
				switch (childID)
				{
					case 102:
					case 300:
					case 999:
						x=Audio::PlaySample3D("mod:/Audio/fx/sir.wav",pos);
						break;
					case 103:
						x=Audio::PlaySample3D("mod:/Audio/fx/kats.wav",pos);
						break;
				}
				Audio::SetVolume(x,15);
			}
		}

		if (allesirs)
		{
			sirext=true;
			childID=1;
		} else if (nofme)
				childID=childID-350;

		for (int ort=childID;sirext;ort++)
		{
			ActorList ol(pkennung[childID]);
			pos=ol.GetActor(0)->GetPosition();
			for (int i=0;i<sirs.GetNumObjects();i++)
			{
				x=Audio::PlaySample3D("mod:/Audio/fx/sir.wav",pos);
				Audio::SetVolume(x,15);
				if (i==0)
					ol.GetActor(0)->SetUserData(x);
			};
			sirext=allesirs && ort<11;
		}	
	}
};

object StatusSenden : CommandScript
{
	StatusSenden()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		char *com="     ";
		char *rd="rd%u";
		char *fw="fw%u";

		switch (childID)
		{
			case 8:
				if (!Caller->IsFlagSet(OF_HAS_FIRE_EXTINGUISHER))
					return;
				break;
			case 2:
				Caller->ClearFlag(OF_PULLABLE);
			case 1:
				Caller->RemoveCommand("ich_bin_nicht_frei");
				Caller->SetFlag(OF_HAS_FIRE_EXTINGUISHER);
				break;
			case 6:
				Caller->AssignCommand("ich_bin_nicht_frei");
				break;
			case 9:
				Caller->ClearFlag(OF_HAS_FIRE_EXTINGUISHER);
				Caller->PushActionShowHide(ACTION_INSERT,true);
				break;
		}
		signalgeber.PushActionExecuteCommand(ACTION_INSERT,"kanalfrei",Caller,(1000+childID),false);
		Vehicle v(Caller);
		if (v.IsAmbulance() && !v.HasCommand("bedarfs_fz"))
		{
			int fzcom=fzlocal::fzid(&v)+100;
			snprintf(com,5,rd,fzcom);
			System::Log("Status Icon Change : %s %u",com,fzcom);
			switch (fzcom)
			{
				case 135:
				case 136:
				case 173:
				case 174:
					break;
				default:
					Caller->PushActionExecuteCommand(ACTION_INSERT,com,Caller,fzcom*10+childID,false);
					break;
			}
		}
	}
};

object fms_umschalten : CommandScript
{
	fms_umschalten()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		play_fms=!play_fms;
	}
};

object GetChainsaw : CommandScript
{
	GetChainsaw()
	{
		SetValidTargets(ACTOR_VEHICLE | ACTOR_OBJECT);
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
		SetRestrictions(RESTRICT_NOTDESTROYED | RESTRICT_NOTBURNING | RESTRICT_HASCHAINSAW);
		SetPossibleCallers(ACTOR_PERSON);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool show=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),6));
		// show=(show && Caller->HasCommand("umkleidemenue"));
		return show;
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),6) && !Caller->HasCommand("fuehrung");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if (!Caller->IsValid() || !Target->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		GameObject obj(Target);
		if ((Caller->GetObjectType()==TYPE_PERSON) && (Caller->GetEquipment()!=EQUIP_CHAINSAW) && obj.IsValid() && obj.IsFlagSet(OF_HAS_CHAINSAW))
		{
			Person p(Caller);
			if(p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
				return false;
			
			return fzlocal::has_equip(Target,6);
		}
		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vector TargetPos = Target->GetTargetPoint(Caller, TARGET_EQUIPMENTDOOR);
		
		Caller->PushActionMove(ACTION_NEWLIST, TargetPos);
		Caller->PushActionTurnTo(ACTION_APPEND, Target);
		if (fzlocal::take_equip(Target,6))
			Caller->PushActionGetEquipment(ACTION_APPEND, Target, EQUIP_CHAINSAW);
	}
};

object GetFirehose : CommandScript
{
	GetFirehose()
	{
		SetIcon("crohr");
		SetCursor("crohr");
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
		SetRestrictions(RESTRICT_NOTDESTROYED | RESTRICT_NOTBURNING | RESTRICT_HASFIREHOSE);
		SetPossibleCallers(ACTOR_PERSON);
		// SetNeedsCarWithFlagSet(OF_HAS_HOSE);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),3) && !Caller->HasCommand("fuehrung");
	}
	
	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool show=(!Caller->IsEquipped());
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
			case PT_FIREFIGHTER_ABC:
				break;
			default:
				return false;
		}
			
		bool avail=false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (v.IsFirefighter())
				avail=fzlocal::has_equip(Target,3);
			else 
				avail=false;
		} else
			if (Caller->GetID() == Target->GetID())
				avail=fzlocal::has_equip(Caller,3);
	
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()!=ACTOR_VEHICLE)
		{
			VehicleList vl(Caller->GetName());
			Vehicle v(vl.GetVehicle(0));
		} else
			Vehicle v(Target);
	
		Vector TargetPos = v.GetTargetPoint(Caller, TARGET_EQUIPMENTDOOR);
		if (fzlocal::take_equip(&v,3))
			Caller->PushActionGetEquipment(ACTION_INSERT, &v, EQUIP_FIREHOSE);
		Caller->PushActionTurnTo(ACTION_INSERT, &v);
		Caller->PushActionMove(ACTION_INSERT, TargetPos);
	}
};

object GetShears : CommandScript
{
	GetShears()
	{
		SetValidTargets(ACTOR_VEHICLE | ACTOR_OBJECT);
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
		SetRestrictions(RESTRICT_NOTDESTROYED | RESTRICT_NOTBURNING | RESTRICT_HASSHEARS);
		SetPossibleCallers(ACTOR_PERSON);
		//SetNeedsCarWithFlagSet(OF_HAS_SHEARS);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),5) && !Caller->HasCommand("fuehrung");
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool show=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),5));
		return show;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if (!Caller->IsValid() || !Target->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		GameObject obj(Target);
		if (Caller->GetObjectType()==TYPE_PERSON && Caller->GetEquipment()!=EQUIP_SHEARS && obj.IsValid() && obj.IsFlagSet(OF_HAS_SHEARS))
		{
			Person p(Caller);
			if(p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
				return false;
			
			return fzlocal::has_equip(Target,5);
		}
		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vector TargetPos = Target->GetTargetPoint(Caller, TARGET_EQUIPMENTDOOR);
		
		if (fzlocal::take_equip(Target,5))
			Caller->PushActionGetEquipment(ACTION_INSERT, Target, EQUIP_SHEARS);
		Caller->PushActionTurnTo(ACTION_INSERT, Target);
		Caller->PushActionMove(ACTION_INSERT, TargetPos);
	}
};

object check_ms_vollzaehlig : CommandScript
{


	check_ms_vollzaehlig()
	{
		SetPriority(300);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void FwDVGruppe (PersonList pl,Vehicle fz,bool brandeinsatz, int zugid)
	{
		int staerke=pl.GetNumPersons();
		int x;
		for (x=0;x<staerke;x++)
		{
			Person p=pl.GetPerson(x);
			p.SetAutoHealDistance(0);
			p.RemoveCommand("ich_bin_nicht_frei");
			switch (x)
			{
				case 0:
					p.ChangePrototype("mod:Prototypes/Persons/Fire Department/grufue_60.e4p");
					p.SetUserData(zugid);
					p.AssignCommand("gf_gefahr");
					p.AssignCommand("eh");
					switch (staerke)
					{
						case 3:
						case 2:
						case 1:
							p.AssignCommand("tf");
							break;
						case 4:
						case 5:
						case 6:
							p.AssignCommand("sf");
							break;
					}
					break;
				case 1:
				case 2:
					if (brandeinsatz)
						if (fzlocal::take_equip(&fz,0))
							p.ChangePrototype("mod:Prototypes/Persons/Fire Department/firefightermask_upgraded2.e4p");
					p.AssignCommand("at");
					break;
				case 3:
					if (p.IsEquipped())
						p.RemoveEquipment();
					p.AssignCommand("ma");
					p.AssignCommand("fuehrung");
					break;
				case 4:
				case 5:
					p.AssignCommand("wt");
					break;
				case 6:
				case 7:
					p.AssignCommand("st");
					break;
				case 8:
					p.AssignCommand("me");
					break;
			}
		}		
	} 

	void TL_definieren (Vehicle v,PersonList pl, Actor *Target, bool sek)
	{
		bool tl_noetig=false;

		if (v.IsFlagSet(OF_USABLE_WITH_MEGAPHONE))
		{
			GameObject o(Target);
			v.ClearFlag(OF_USABLE_WITH_MEGAPHONE);
			if (!o.IsFlagSet(OF_USABLE_WITH_MEGAPHONE))	// TL erforderlich ?
			{
				tl_noetig=true;
				if (!v.IsFlagSet(OF_FLOTSAM))		// Kein TL an Bord ?
				{
					if (v.IsFirefighter())
						Person p=pl.GetPerson(pl.GetNumPersons()-1);
					else
						Person p=pl.GetPerson(0);
					if (p.IsEquipped())
						p.RemoveEquipment();
					if (v.IsFirefighter())
						p.ChangePrototype("mod:Prototypes/Persons/Fire Department/wefue.e4p");
					else if (v.IsPolice())
						p.ChangePrototype("mod:Prototypes/Persons/SEK/profiler_upgrade.e4p");
					else if (v.IsAmbulance())
						p.ChangePrototype("mod:Prototypes/Persons/Ambulance/drk_el.e4p");
					p.AssignCommand("tl");
					p.AssignCommand("fuehrung");
					p.AssignCommand("tl_gefahr");
					if (v.IsFirefighter())
					{
						p.AssignCommand("Evacuate");
						p.AssignCommand("tl_rufe_ith");
					}
					o.SetFlag(OF_USABLE_WITH_MEGAPHONE);
					v.SetFlag(OF_FLOTSAM);
				} else {
					System::Log("Schon TL im Fz");
					o.SetFlag(OF_USABLE_WITH_MEGAPHONE);
				}
			} else System::Log("Kein TL erforderlich");
		}

		if (v.IsFlagSet(OF_FLOTSAM) && !tl_noetig)	// kein EL-Fz aber EL an Bord
		{
			for (int x=0;x<pl.GetNumPersons();x++)
				if (pl.GetPerson(x)->HasCommand("tl"))
				{
					Person ep=pl.GetPerson(x);
					if (v.IsFirefighter())
						ep.ChangePrototype("mod:Prototypes/Persons/Fire Department/firefighternorm_upgrade2.e4p");
					else if (v.IsAmbulance())
						p.ChangePrototype("mod:Prototypes/Persons/Ambulance/drk_helfer.e4p");
					else if (sek)
							ep.ChangePrototype("mod:Prototypes/Persons/SEK/scout_upgraded2.e4p");
						else
							ep.ChangePrototype("mod:Prototypes/Persons/Police/policeman_upgraded2_m.e4p");
					ep.RemoveCommand("tl");
					ep.RemoveCommand("fuehrung");
				}
			v.ClearFlag(OF_FLOTSAM);							
		}

		for (int x=0;x<pl.GetNumPersons();x++)
			if (pl.GetPerson(x)->HasCommand("gf") || pl.GetPerson(x)->HasCommand("tl"))
				pl.GetPerson(x)->SetUserData(Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		// System::Log("Check MS %s",Caller->GetName());
		int lim=0;
		Vehicle v(Caller);
		bool feuerwehr=true;
		bool kats=ChildID==999;
		bool ffw=ChildID==112;
		bool sek=(fzlocal::fzid(Caller)==69 || fzlocal::fzid(Caller)==71);
		bool seg=fzlocal::fzid(Caller)==35 || fzlocal::fzid(Caller)==36 || fzlocal::fzid(Caller)==37;
		bool sekundaer=(fzlocal::fzid(Caller)==73 || fzlocal::fzid(Caller)==74);

		// 1. Schritt : Fz nachbesetzt ? Dann auf Personal warten

		if (v.IsFlagSet(OF_USABLE))
		{
			switch (v.GetVehicleType())
			{
				case VT_AMBULANCE_RTW:
					if (v.IsFlagSet(OF_USABLE_WITH_MEGAPHONE) && !seg)
						lim=0;
					else 
						lim=1;
					break;
				case VT_AMBULANCE_RHC:
					if (fzlocal::fzid(Caller)==73 || fzlocal::fzid(Caller)==74)
						lim=1;
					break;
				case VT_POLICE_GETAWAY:
					lim=9;
					break;
				case VT_POLICE_STW:
					if (sek)
						lim=0;
					else
						lim=2;
					break;
				case VT_FIREFIGHTERS_TLF:
				case VT_FIREFIGHTERS_RW:
				case VT_FIREFIGHTERS_GTF:
					if (ffw)
						if (v.GetNumPassengers()>1)
							lim=9;
						else
							lim=0;
					else
						lim=0;
					break;
				case VT_FIREFIGHTERS_FMB:
					feuerwehr=false;
					break;
			}

			// System::Log("zuviele freie Plaetze ? %u %u",v.GetNumPassengers(),v.GetFreePassengers());
			if (v.GetFreePassengers()>lim)
			{
				Caller->PushActionWait(ACTION_INSERT,1.0f);
				Caller->PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"check_ms_vollzaehlig",Target,ChildID,false);
				return;	// evil aber funktioniert
			}
	

			// 2. Schritt : Fuehrungskraft auf dem Fz einrichten

			PersonList pl=v.GetPassengers();
			
			// System::Log("2 Trupps einrichten : %s %u",v.GetName(),pl.GetNumPersons());

			if (v.IsFirefighter() && feuerwehr)
				FwDVGruppe(pl,v,ChildID==112,Target->GetID());
		} else
			PersonList pl=v.GetPassengers();	// Fz bereits unterwegs, jetzt Besatzung ermitteln

		// 3.Schritt : Polizei oder Feuerwehr ? Einsatzleiter dem fz zugeordnet ?

		if ((v.IsFirefighter() && !kats) || v.IsPolice() || (v.HasCommand("fuehrung") && !kats))
			TL_definieren(v,pl,Target,sek);
		else if (v.GetVehicleType()==VT_AMBULANCE_RTW) 
			{
				// System::Log("Check MS EMCase %s",v.GetName());

			if (v.GetNumPassengers()>1 && !v.IsFlagSet(OF_USABLE_WITH_MEGAPHONE) && !seg)
				pl.GetPerson(0)->SetEquipment(EQUIP_EMERGENCY_CASE);
			}
			
		if (v.IsFlagSet(OF_USABLE_WITH_MEGAPHONE) || ChildID == 19292)
		{
			System::Log("Check MS Notarzt %s %u",v.GetName(),ChildID);
			pl.GetPerson(0)->SetUserData(44);
			pl.GetPerson(1)->SetUserData(44);
			if (pl.GetNumPersons()>2)
				pl.GetPerson(2)->SetUserData(44);
		}

		if (sekundaer)
		{
			// System::Log("Check MS Sekundaer %s",v.GetName());
			for (int i=0;i<pl.GetNumPersons();i++)
				pl.GetPerson(i)->SetFlag(OF_BULLDOZABLE);
		}


		// System::Log("CHECKMS Fz Status %s %u %u %u %u",v.GetName(),int(ffw),int(kats),int(v.IsHidden()),int(v.HasCommand("ich_bin_nicht_frei")));

		if ((ffw||kats) && !v.IsHidden() && v.IsFlagSet(OF_USABLE))
		{
			System::Log("Check MS FFW %s",v.GetName());
			PersonList pl(v.GetName());
			for (int i=0;i<pl.GetNumPersons();i++)
			{
				Person p=pl.GetPerson(i);
				if (p.GetEnteredCarID()!=v.GetID())
					p.PushActionDeleteOwner(ACTION_INSERT);
			}
		}

		v.ClearFlag(OF_USABLE);
			
		if (seg)
			v.PushActionExecuteCommand(ACTION_INSERT,"zugliste_zugid",&v,1,false);

		if (Game::IsMultiplayer())
		{
			for (int mpx=0;mpx<pl.GetNumPersons();mpx++)
				pl.GetPerson(mpx)->SetPlayerMP(v.GetPlayerMP());
		}
		// System::Log("Check MS Ende %s",v.GetName());
			
	}
};

object sir_abwarten : CommandScript
{

	sir_abwarten()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		if (!KatSZustand)
		{
			int fzort=fzlocal::fzort(Target)-50;
			ActorList ol(pkennung[fzort]);
			fzort=ol.GetActor(0)->GetUserData();
			Caller->PushActionExecuteCommand(ACTION_INSERT,"sir_laeuft",Target,fzort,false);
			// Game::ShowHelpTextWindow("2 Sirene abwarten");
		}
	}
};

object sir_laeuft : CommandScript
{

	sir_laeuft()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int sir)
	{
		Vehicle v(Caller);
		if (Audio::IsPlaying(sir) && v.GetFreePassengers()>0)
		{
			// Game::ShowHelpTextWindow("W Sirene laeuft");
			Caller->PushActionExecuteCommand(ACTION_INSERT,"sir_laeuft",Target,sir,false);
			Caller->PushActionWait(ACTION_INSERT,2.0f);
		} else {
			// Game::ShowHelpTextWindow("3 Freiwillige ausruecken");
			if (v.GetNumPassengers()<6)
				v.ClearFlag(OF_USABLE_WITH_MEGAPHONE);
			Caller->PushActionExecuteCommand(ACTION_INSERT,"check_ms_vollzaehlig",Target,112,false);
		}
	}
};



object ChangeToMask: CommandScript
{
	ChangeToMask()
	{
		SetGroupLeader(false);
	}

	bool CheckPossible(GameObject *Caller)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		return p.GetPersonType() != PT_FIREFIGHTER_MASK;
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool show=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,0) && (p.GetPersonType() != PT_FIREFIGHTER_MASK));
		return show;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		bool avail=false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (v.IsFirefighter())
				avail=fzlocal::has_equip(Target,0) && v.IsFlagSet(OF_RECOVERABLE);
			else 
				avail=false;
		} else
			if (Caller->GetID() == Target->GetID())
				avail=fzlocal::has_equip(Caller,0);
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		switch (childID)
		{
			case 1:
				if (fzlocal::take_equip(Caller,0))
				{
			                Caller->PushActionExecuteCommand(ACTION_INSERT, "DummyChange", Caller, 101, false);
					break;
				}
			default:
				if (fzlocal::take_equip(Target,0))
	        		        Caller->PushActionExecuteCommand(ACTION_INSERT, "DummyChange", Target, 101, false);
				break;
		}
	}
};

object ChangeToABC: CommandScript
{
	ChangeToABC()
	{
		SetGroupLeader(false);
	}

	bool CheckPossible(GameObject *Caller)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		return p.GetPersonType() != PT_FIREFIGHTER_ABC;
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool show=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,1) && (p.GetPersonType() != PT_FIREFIGHTER_ABC));
		return show;
	}


	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		bool avail=false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (v.IsFirefighter())
				avail=fzlocal::has_equip(Target,1) && v.IsFlagSet(OF_RECOVERABLE);
			else 
				avail=false;
		} else
			if (Caller->GetID() == Target->GetID())
				avail=fzlocal::has_equip(Caller,1);
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		switch (childID)
		{
			case 1:
				if (fzlocal::take_equip(Caller,1))
				{
			                Caller->PushActionExecuteCommand(ACTION_INSERT, "DummyChange", Caller, 102, false);
					break;
				}
			default:
				if (fzlocal::take_equip(Target,1))
	        		        Caller->PushActionExecuteCommand(ACTION_INSERT, "DummyChange", Target, 102, false);
				break;
		}
	}
};

object ChangeToDiver: CommandScript
{
	ChangeToDiver()
	{
		SetGroupLeader(false);
	}

	bool CheckPossible(GameObject *Caller)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		return p.GetPersonType() != PT_DIVER;
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		// for (int i=0; (i<vl.GetNumVehicles()) && (!vl.GetVehicle(i)->IsFlagSet(OF_HAS_FIRE_EXTINGUISHER)); i++);
		bool show=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),2) && (p.GetPersonType() != PT_DIVER));
		return show;
	}


	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		bool avail=false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (v.IsFirefighter())
				avail=fzlocal::has_equip(Target,2) && v.IsFlagSet(OF_RECOVERABLE);
			else 
				avail=false;
		} else
			if (Caller->GetID() == Target->GetID())
				avail=fzlocal::has_equip(Caller,2);
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (fzlocal::take_equip(Target,2))
	                Caller->PushActionExecuteCommand(ACTION_INSERT, "DummyChange", Target, 103, false);
	}
};

object ChangeToFireFighter: CommandScript
{
	ChangeToFireFighter()
	{
//		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
	}

	bool CheckPossible(GameObject *Caller)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		return p.GetPersonType() != PT_FIREFIGHTER_NORMAL;
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		for (int i=0; (i<vl.GetNumVehicles()) && (!vl.GetVehicle(i)->IsFlagSet(OF_HAS_FIRE_EXTINGUISHER)); i++);
		bool show=(!Caller->IsEquipped() && (p.GetPersonType()!=PT_FIREFIGHTER_NORMAL));
		// show=(show && Caller->HasCommand("geraetemenue"));
		return show;
	}


	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || Caller->IsEquipped())
			return false;
		Person p(Caller);
    		if (p.IsCarryingPerson() || p.IsInDLKBasket())
    			return false;
		bool avail=false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (v.IsFirefighter())
				avail=v.IsFlagSet(OF_RECOVERABLE);
			else 
				avail=false;
		} else
			if (Caller->GetID() == Target->GetID())
				avail=true;
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);
                Caller->PushActionExecuteCommand(ACTION_INSERT, "DummyChange", Target, 4, false);
	}
};
	
object DummyChange: CommandScript
{
	DummyChange()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int enter = 0;

		if (childID<4)
		{
			if (!fzlocal::take_equip(Target,(childID-1)))
				return; 	// unsauber aber praktisch
		}
		else if (childID > 99)
			childID=childID-100;
			

		Caller->SetCommandable(false);
		if (Target->GetType() != ACTOR_VEHICLE)
		{
			VehicleList vl(Caller->GetName());
			Vehicle v(vl.GetVehicle(0));
		} else
			Vehicle v(Target);
           	Caller->PushActionExecuteCommand(ACTION_INSERT,"umziehen",&v,childID,false);
		Caller->PushActionWait(ACTION_INSERT, 3.0f);
         	Caller->PushActionSwitchAnim(ACTION_INSERT,"useobjmid");
		if (childID=41)
		{
			Caller->PushActionTurnTo(ACTION_INSERT, Target);
			Caller->PushActionMove(ACTION_INSERT, Target->GetPosition());
		} else {
			Caller->PushActionTurnTo(ACTION_INSERT, &v);
			Caller->PushActionMove(ACTION_INSERT, &v, TARGET_EQUIPMENTDOOR);
		}
	}
};

int ffw=5;

object umziehen: CommandScript
{
	umziehen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		bool grufue=Caller->HasCommand("gf");
		bool tl=Caller->HasCommand("tl");
		bool at=Caller->HasCommand("at");
		bool wt=Caller->HasCommand("wt");
		bool st=Caller->HasCommand("st");
		bool ma=Caller->HasCommand("ma");
		bool me=Caller->HasCommand("me");
		Person p(Caller);
		int fzid=fzlocal::fzid(Caller);
		switch (childID)
                {
			case 1:
				if (grufue)
	                       		Caller->ChangePrototype("mod:Prototypes/Persons/Fire Department/grufue60_mask.e4p");
				else if (!tl)
        	               		Caller->ChangePrototype("mod:Prototypes/Persons/Fire Department/firefightermask_upgraded2.e4p");
				break;

			case 2:
				if (grufue)
	                       		Caller->ChangePrototype("mod:Prototypes/Persons/Fire Department/grufue60_tesimax.e4p");
				else if (!tl)
		                	Caller->ChangePrototype("mod:Prototypes/Persons/Fire Department/firefighterabc_upgraded2.e4p");
				break;
			case 3:
                     		p=Game::CreatePerson("mod:Prototypes/Persons/Fire Department/diver_upgraded2.e4p",Caller->GetName());
				p.SetPosition(Caller->GetPosition());
				Caller->PushActionDeleteOwner(ACTION_NEWLIST);
				Caller=&p; // This is definitively a very evil workaround
				break;

			case 41:
			case 4:
				if (grufue)
	                       		Caller->ChangePrototype("mod:Prototypes/Persons/Fire Department/grufue_60.e4p");
				else
	                        	Caller->ChangePrototype("mod:Prototypes/Persons/Fire Department/firefighternorm_upgrade2.e4p");
				break;
			case 5:
                       		Caller->ChangePrototype("mod:Prototypes/Persons/Ambulance/leaderrescuedog_upgraded2.e4p");
				break;
			case 6:
                       		Caller->ChangePrototype("mod:Prototypes/Persons/SEK/sharpshooter_upgraded2.e4p");
				break;
			case 7:
				switch (fzid)
				{
					case 12:
						p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr25ra_upgraded2.e4p", Caller->GetName());
						break;
					case 48:
						p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr7ra_upgraded2.e4p", Caller->GetName());
						break;
					default:
                       				p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/paramedic02_upgraded2.e4p",Caller->GetName());
						break;
				}
				p.SetPosition(Caller);
				Caller->Hide();
				Caller->PushActionDeleteOwner(ACTION_NEWLIST);
				switch (Target->GetType())
				{
					case ACTOR_PERSON:
						p.PushActionExecuteCommand(ACTION_NEWLIST,"Lift",Target,0,false);
						break;
					case ACTOR_VEHICLE:
						p.PushActionExecuteCommand(ACTION_NEWLIST,"EnterCar",Target,0,false);
						break;
				}					
				break;
			case 71:
				switch (fzid)
				{
					case 12:
						Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr25ra_upgraded2_single.e4p", Target->GetName());
						break;
					case 48:
						Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr7ra_upgraded2_single.e4p", Target->GetName());
						break;
					default:
						Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/paramedic_upgraded2_single.e4p", Target->GetName());
						break;
				}
				p.SetPosition(Caller);
				Caller->Hide();
				Caller->PushActionExecuteCommand(ACTION_NEWLIST,"CreateNewPerson",Target,9,false);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"aufsitzen",Target,0,false);
				Caller->PushActionDeleteOwner(ACTION_APPEND);
				break;
			default:
				Mission::PlayHint("FKK Modus oder was ? Kein gueltiges Outfit gewaehlt!");
				break;
                }
		if (tl) Caller->AssignCommand("tl");
		if (at) Caller->AssignCommand("at");
		if (wt) Caller->AssignCommand("wt");
		if (st) Caller->AssignCommand("st");
		if (ma) Caller->AssignCommand("ma");
		if (me) Caller->AssignCommand("me");
			
		switch (childID)
                {
			case 1:
				Caller->AssignCommand("GetGZ");
				Caller->AssignCommand("GetMM");
				Caller->AssignCommand("ggv_abdichten");
				Caller->AssignCommand("SetLuefter");
				Caller->RemoveCommand("GetJumppad");
				// Caller->PushActionExecuteCommand(ACTION_INSERT,"pa_check",Caller,0,false);
				break;

			case 2:
				Caller->AssignCommand("PutInCar");
				Caller->AssignCommand("GetGZ");
				Caller->AssignCommand("GetMM");
				Caller->AssignCommand("ggv_abdichten");
				// Caller->PushActionExecuteCommand(ACTION_INSERT,"pa_check",Caller,1,false);
				break;
			case 41:
				Caller->PushActionWait(ACTION_APPEND,ffw*1.0);
				Caller->PushActionMove(ACTION_APPEND,Target,TARGET_PASSENGERDOOR);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"EnterCar",Target,984,true);
				ffw--;
				if (ffw<0)
					ffw=5;
				break;
                }
		Caller->SetCommandable(true);
	}
};

const char IMG[] = "sosi";

const char EACTION_FINDPATH[] = "EActionFindPath";

const char DUMMY_UPDATEPOS[] = "DUMMYUpdatePos";
const char DUMMY_FINDPATH[] = "DUMMYFindPath";

const char CMD_MOVETO[] = "MoveTo";

int DummyGroup = 20;

class WibSoSi : CommandScript
{
	bool SoSiAus(Vehicle Fz, GameObject horn, int sample,bool resetSpeed)
	{
		if (horn.IsValid())
		{
			Audio::StopSample(sample);
			horn.PushActionDeleteOwner(ACTION_NEWLIST);
		}
		Fz.ClearFlag(OF_BULLDOZABLE);
		if (Fz.HasCommand(DUMMY_FINDPATH))
			Fz.RemoveCommand(DUMMY_FINDPATH);
		if (resetSpeed)
			if (Fz.GetVehicleType()!=VT_AMBULANCE_RHC && Fz.GetVehicleType()!=VT_POLICE_PHC)
				Fz.SetSpeed(civspeed);
		return true;
	}

};

object WT_SoSi : CommandScript
{
	WT_SoSi()
	{
		SetIcon(IMG);
		SetCursor(IMG);
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckPossible(GameObject *Caller)
	{
		if (!Caller->IsValid())
			return false;

		if (Caller->GetType() == ACTOR_VEHICLE)
		{
			return true;
		}

		return false;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if (!Target->IsValid() || Target->GetID() != Caller->GetID())
			return false;

		if (!Caller->HasCommand(CMD_MOVETO) || Caller->GetType() != ACTOR_VEHICLE)
			return false;

		return true;
	}

	void SignalAn(Vehicle v,char * hornid, bool einsatzfz, int childID, int fzid)
	{
			GameObjectList ol(hornid);
			if (ol.GetNumObjects() >0)
				for (int hx=ol.GetNumObjects()-1;hx>-1;hx--)
				{
					Audio::StopSample(ol.GetObject(hx)->GetUserData());
					ol.GetObject(hx)->PushActionDeleteOwner(ACTON_NEWLIST);
				}
			if (einsatzfz)
				v.SetSpeed(fzlocal::fzspeed(&v));
			int soundID;
			int zufall = rand()%3;
			v.EnableBlueLights(true);
			if (childID!=3)
			{
				Vector CarPos = v.GetPosition();
				if (fzid > 75)
					System::Error(parken[0]);

				if (StrCompare(fzlocal::Signal(fzid),"NULL") == 0)	// Fz ohne Sosi -> raus hier
					return;
	
				if (StrCompare(fzlocal::Signal(fzid),"MULTI") == 0)	// Fz mit wechselndem Signalhorn
				{
					if ((fzid == 4)	|| (fzid ==47))			// ELW -> separates Hornset
					{
						switch(zufall)
						{
							case 0:
								soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/tlf_land.wav", CarPos, true);
								break;
							case 1:
								soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/tlf_stadt.wav", CarPos, true);
								break;
							case 2:
								soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/tlf_mix.wav", CarPos, true);
								break;
						}
					} else {
						switch(zufall)
						{
							case 0:
								soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/rtk_land.wav", CarPos, true);
								break;
							case 1:
								soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/rtk_stadt.wav", CarPos, true);
								break;
							case 2:
								soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/rtk_mix.wav", CarPos, true);
								break;
						}
					}
				} else	if (!einsatzfz)
						soundID = Audio::PlaySample3D("mod:Audio/FX/Sirens/fluchtfzg.wav", CarPos, true);
					else					
						soundID = Audio::PlaySample3D(fzlocal::Signal(fzid), CarPos, true);
				
				GameObject horn =  Game::CreateObject("mod:Prototypes/Objects/Misc/empty.e4p", hornid);
				horn.Hide();
				horn.SetUserData(soundID);
				horn.PushActionExecuteCommand(ACTION_NEWLIST, "SoSiPos", &v, soundID, false);
				v.SetFlag(OF_BULLDOZABLE);
				v.AssignCommand(DUMMY_FINDPATH);
			}
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{

		const char hornid[] = "               ";
		const char dummymask[]="SoSi%u";
		int fzid=-1;

		bool einsatzfz=childID<100;
		
		if (Caller->GetType()==ACTOR_VEHICLE)
			Vehicle v(Caller);
		else
			Vehicle v(Target);

		// System::Log("WT SOSI : Fz %s Code %u",v.GetName(),childID);

		if (childID==10)
			if (v.IsCurrentAction("EActionFindPath"))
				childID=0;
			else
				return;

		if (einsatzfz)
			fzid=fzlocal::fzid(&v);

		int x=snprintf(hornid,15,dummymask,v.GetID());

		switch (childID)
		{
			case 0:	// Sosi FlipFlop
			case 3: // SoSi an mit Verzoegerung
			case 5:	// SoSi immer AN
				if (!v.IsFlagSet(OF_BULLDOZABLE))
				{
					SignalAn(v,hornid,einsatzfz,childID,fzid);
					break;
				}
				if (childID==5)
					break;
				
			case 1:	// SoSi aus und Blaulicht AUS
			case 2: // SoSi aus und Blaulicht AN
				if (v.IsFlagSet(OF_BULLDOZABLE))
				{
					if (childID == 1)
						v.EnableBlueLights(false);
				
					GameObjectList list = Game::GetGameObjects(hornid);
					GameObject obj;
					int ref;
					if (list.GetNumObjects()>0)
					{
						obj = list.GetObject(0);
						ref = obj.GetUserData();
						obj.SetUserData(0);
					}
					WibSoSi::SoSiAus(v,obj,ref,true);
				}
				break;
		}
	}
};


// 01.1
object SoSiPos : CommandScript
{
	SoSiPos()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

  	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{

		Vehicle v(Target);
		GameObject horn(Caller);
		bool ok;

		if (v.IsDestroyed() || !v.IsValid() || v.IsSmoking() || !v.IsFlagSet(OF_BULLDOZABLE))
			ok=WibSoSi::SoSiAus(*v,*horn,childID,true);
		else {
			Vector CarPos = v.GetPosition();
			Audio::UpdatePos(childID, CarPos, true);
			if (v.IsCurrentAction(EACTION_FINDPATH))
			{
				if (!v.HasCommand(DUMMY_FINDPATH))
					v.AssignCommand(DUMMY_FINDPATH);
			}
			horn.PushActionWait(ACTION_NEWLIST,1.0f);
			horn.PushActionExecuteCommand(ACTION_APPEND, "SoSiPos", Target, childID, false);
			if (v.HasCommand(DUMMY_FINDPATH))
			{
				if (!v.IsCurrentAction(EACTION_FINDPATH) && v.GetNumActions() < 2)
					ok=WibSoSi::SoSiAus(v,horn,childID,true);
			}
		}
	}
};

object DUMMYDisableSiren : CommandScript
{
	DUMMYDisableSiren()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

  	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		const char hornid[] = "               ";
		const char dummymask[]="SoSi%u";
		bool ok;

		if (Caller->GetType()==ACTOR_VEHICLE)
			Vehicle v(Caller);
		else
			Vehicle v(Target);

		if (childID == 1)
		{
			v.EnableBlueLights(false);
		} else
			v.EnableBlueLights(true);

		if (v.IsFlagSet(OF_BULLDOZABLE))
		{
			int x=snprintf(hornid,15,dummymask,v.GetID());
			GameObjectList list = Game::GetGameObjects(hornid);
			GameObject obj;
			int ref;
			if (list.GetNumObjects()>0)
			{
				obj = list.GetObject(0);
				ref = obj.GetUserData();
				obj.SetUserData(0);
			}
			ok=WibSoSi::SoSiAus(v,obj,ref,true);
		}
	}
};

// 01.3
object DUMMYFindPath : CommandScript
{
	DUMMYFindPath()
	{
		SetGroupID(DummyGroup);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return false;
	}

  	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
	}
};

object CreateNewPerson: CommandScript
{

	CreateNewPerson()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle vec(Target);
		int zufall = rand()%2;
		bool anderwache=false;
		bool anderwerkstatt=false;
		bool poscheck=false;
		int alarm=984;
		bool am_fz=false;
		ActorList place;
		int abfahrn=0;
		bool freiwillig=false;
		bool imhaus=false;
		bool trauma=false;
		
		if (childID > 300)
		{
			childID=childID-200;
			alarm=0;
		}

		if (childID > 200)
		{
			childID=childID-200;
			poscheck=true;
		}
	
		if (childID > 100)
		{
			childID=childID-100;
			anderwache=(!vec.IsHidden() && vec.GetVehicleType()!=VT_FIREFIGHTERS_FMB) || trauma;
			if (anderwache)
				System::Error("An der Wache");
			else 
				System::Error("Nachbarfz");
		}

		trauma=childID==86 || childID==87;
		imhaus=trauma;
		anderwache=anderwache || trauma;
		
		int fzid=fzlocal::fzid(&vec);

		switch (childID)
		{
			case 1:
			//EL
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/Einsatzl.e3p", Target->GetName());
			break;
			
			case 50:
				freiwillig=true;
				anderwache=false;
			case 2:
			//FWM
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/firefighternorm_upgrade2.e4p", Target->GetName());
			switch (fzid)
			{
				case 3:
					place=Game::GetActors("tor3");
					break;
				case 4:
					place=Game::GetActors("tor2");
					break;
				case 5:
					place=Game::GetActors("tor5");
					break;
				case 6:
					place=Game::GetActors("tor4");
					break;
				case 15:
					place=Game::GetActors("tor5");
					break;
				case 39:
					place=Game::GetActors("tor5");
					break;
				case 40:
					place=Game::GetActors("tor1");
					break;
				case 62:
					place=Game::GetActors("dlrg");
					break;
			}
			p.AssignCommand("StopPull");
			break;

			case 3:
			//Polizist
			switch(zufall)
			{
				case 0:
				Person p = Game::CreatePerson("mod:Prototypes/Persons/Police/policeman_upgraded2_m.e4p", Target->GetName());
				break;
				case 1:
				Person p = Game::CreatePerson("mod:Prototypes/Persons/Police/policeman_upgraded2_f.e4p", Target->GetName());
				break;
			}
			place=Game::GetActors("police_entry");
			break;

			case 4:
			//Shooter
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Police/bepo.e4p", Target->GetName());
			p.AssignCommand("POL_GetDog");
			p.SetResistance(INJUREREASON_SHOT,25.0);
			p.SetResistance(INJUREREASON_ENERGY,300.0);
			place=Game::GetActors("police_entry");
			break;

			case 5:
			case 26:
			//Siemens Techniker
			Person p = Game::CreatePerson("mod:Prototypes/Persons/TEC/engineer_upgraded2.e4p",  Target->GetName());
			p.SetEquipment(EQUIP_THW_CASE);
			break;

			case 6:
			//ADAC
			Person p = Game::CreatePerson("mod:Prototypes/Persons/TEC/adac.e4p",  Target->GetName());
			p.SetEquipment(EQUIP_THW_CASE);
			break;

			case 7:
			//DB-NFM
			Person p = Game::CreatePerson("mod:Prototypes/Persons/TEC/nfm.e4p",  Target->GetName());
			break;

			case 8:
			case 81:
			//NA
			switch(fzid)
			{
				// Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/doctor_upgraded2_f.e4p", Target->GetName());
				case 12:
					Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr25doc_upgraded2_m.e4p", Target->GetName());
					break;
				case 48:
					Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr7doc_upgraded2_m.e4p", Target->GetName());
					break;
				default:
					Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/doctor_upgraded2_m.e4p", Target->GetName());
					break;
			}

			if (vec.GetVehicleType()!=VT_AMBULANCE_NEF)
				p.SetEquipment(EQUIP_EMERGENCY_CASE);

			p.AssignCommand("rufe_manv");

			if (childID==81)
			{
				place=Game::GetActors("rwache");
				imhaus=true;			
				if (vec.GetVehicleType() == VT_AMBULANCE_RHC)
					p.SetAutoHealDistance(500.0f);
				else
					p.SetAutoHealDistance(0.0f);
			} else
				p.SetAutoHealDistance(0.0f);	// Sekundaerverleger NA darf kein AutoHeal haben, sonst wird der Code unterbrochen
			break;

			case 9:
			case 91:
			//RA
			switch (fzid)
			{
				case 12:
					Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr25ra_upgraded2_single.e4p", Target->GetName());
					break;
				case 48:
					Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr7ra_upgraded2_single.e4p", Target->GetName());
					break;
				default:
					Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/paramedic_upgraded2_single.e4p", Target->GetName());
					break;
			}
			switch (vec.GetVehicleType())
			{
				case VT_AMBULANCE_RTW:
					break;

				case VT_AMBULANCE_NEF:
					p.RemoveCommand("ratransport");
					break;
			
				case VT_AMBULANCE_RHC:
					break;
			}
			if (childID==91)
			{
				place=Game::GetActors("rwache");
				imhaus=true;			
			}
			break;

			case 35:
			case 34:
				switch (fzid)
				{
					case 12:
						Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr25ra_upgraded2.e4p", Caller->GetName());
						break;
					case 48:
						Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/chr7ra_upgraded2.e4p", Caller->GetName());
						break;
					default:
                       				Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/paramedic02_upgraded2.e4p",Caller->GetName());
						break;
				}

			place=Game::GetActors("hospital_entry");
			if (childID==35)
				p.SetFlag(OF_BULLDOZABLE);
			break;

			case 10:
			//Bestatter
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/bestatter.e4p",  Target->GetName());
			break;

			case 11:
			//Sharpshooter
			Person p = Game::CreatePerson("mod:Prototypes/Persons/SEK/sharpshooter_upgraded2.e4p",  Target->GetName());
			p.SetEquipment(EQUIP_RIFLE);
			break;

			case 12:
			//LNA
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/LNA.e4p", Target->GetName());
			p.SetEquipment(EQUIP_EMERGENCY_CASE);
			p.AssignCommand("rufe_seg");
			p.AssignCommand("lna_start_triage");
			p.SetAutoHealDistance(0.0f);
			place=Game::GetActors("hospital_entry");
			break;

			case 13:
			//FWM
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/firefightermask_upgraded2.e4p",  Target->GetName());
			p.AssignCommand("ggv_abdichten");
			p.AssignCommand("SetLuefter");
			p.RemoveCommand("GetGZ");
			p.RemoveCommand("GetMM");
			p.RemoveCommand("GetJumppad");
			break;

			case 14:
			//Diver
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/diver_upgraded2.e4p",  Target->GetName());
			break;

			case 15:
			//ABC
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/firefighterabc_upgraded2.e4p",  Target->GetName());
			p.AssignCommand("ggv_abdichten");
			p.AssignCommand("GetMM");
			p.AssignCommand("GetGZ");
			// p.AssignCommand("geraetemenue");
			break;

			case 16:
			//Kampfmittelraeumer
			Person p = Game::CreatePerson("mod:Prototypes/Persons/TEC/kmrd.e4p",  Target->GetName());
			p.AssignCommand("Repair");
			p.SetEquipment(EQUIP_LAPTOP);
			break;

			case 17:
			//Kampfmittelraeumer
			Person p = Game::CreatePerson("mod:Prototypes/Persons/TEC/kmrd.e4p",  Target->GetName());
			p.SetEquipment(EQUIP_TVCAMERA);
			break;

			case 18:
			//SEG-Sani
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/drk_helfer.e4p",  Target->GetName());
			switch (fzid)
			{
				case 37:		
					p.AssignCommand("SetZelt");
					break;
			}
			break;

			case 19:
			//SEG-Arzt
			switch(zufall)
			{
				case 0:
				Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/doctor_upgraded2_f.e4p", Target->GetName());
				break;
				case 1:
				Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/doctor_upgraded2_m.e4p", Target->GetName());
				break;
			}
			p.SetEquipment(EQUIP_EMERGENCY_CASE);
			p.SetAutoHealDistance(0.0f);
			p.RemoveCommand("lna_start_triage");
			break;

			case 20:	// ORGL SEG
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/drk_el.e4p",  Target->GetName());
			p.AssignCommand("fuehrung");
			p.AssignCommand("tl");
			p.AssignCommand("tl_abmarsch");
			p.AssignCommand("tl_gefahr");
			break;

			case 25:
			// Mechaniker Werkstatt
			Person p = Game::CreatePerson("mod:Prototypes/Persons/TEC/adac.e4p",  "Mechaniker");
			place=Game::GetActors("werkstatt_entry");
			anderwache=true;
			anderwerkstatt=true;
			break;

			case 29:
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/paramedic02_upgraded2.e4p", Caller->GetName());
			am_fz=true;
			Vehicle vec(Caller);
			break;

			case 30:
			// SEK Shooter
			Person p = Game::CreatePerson("mod:Prototypes/Persons/SEK/shooter_upgraded2.e4p", Target->GetName());
			p.SetResistance(INJUREREASON_SHOT,75.0);
			p.SetResistance(INJUREREASON_ENERGY,1000.0);
			place=Game::GetActors("police_entry");
			break;
			
			case 31:
			// SEK Scout
			Person p = Game::CreatePerson("mod:Prototypes/Persons/SEK/scout_upgraded2.e4p", Target->GetName());
			p.SetResistance(INJUREREASON_SHOT,50.0);
			p.SetResistance(INJUREREASON_ENERGY,1000.0);
			place=Game::GetActors("police_entry");
			break;

			case 32:
			// Hund
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/rescuedog.e4p", Target->GetName());
			vec.AddTransport(&p);
			return;
			break;

			case 33:
			//Polizist zivil
			switch(zufall)
			{
				case 0:
				Person p = Game::CreatePerson("mod:Prototypes/Persons/Police/policeman_zivil1.e4p", Target->GetName());
				break;
				case 1:
				Person p = Game::CreatePerson("mod:Prototypes/Persons/Police/policeman_zivil2.e4p", Target->GetName());
				break;
			}
			place=Game::GetActors("police_entry");
			break;

			case 86:
			// SchockraumDoc
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/arzt.e4p",Caller->GetName());
			place=Game::GetActors("rwache");
			p.SetEquipment(EQUIP_EMERGENCY_CASE);
			p.AssignCommand("trauma_ende");
			p.Hide();
			break;

			case 87:
			// SchockraumPflege
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Ambulance/pfleger.e4p",Caller->GetName());
			place=Game::GetActors("rwache");
			p.RemoveCommand("ratransport");
			p.Hide();
			break;

			
			case 70:
			if ((vec.GetNumPassengers()>0) || (vec.GetFreePassengers()==0))
				return;
			// faehrt neue Autos nach hause
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Civil/civilman02_silver.e4p", Target->GetName());
			place=Game::GetActors("police_entry");
			break;

			case 99:
			//Alarmgeber-Objekt
			Person p = Game::CreatePerson("mod:Prototypes/Persons/Fire Department/firefighternorm_upgrade2.e4p", "5tongeber");
			p.SetCommandable(false);
			anderwache=true;
			place=Game::GetActors("platz2");
			p.Hide();
			return;
			break;

			default:
				Mission::PlayHint("Ungueltiger PersonalCode");
				Mission::PlayHint(vec.GetName());
				System::Error("Ungueltiger PersonalCode");
				System::Error(vec.GetName());
				return;
				break;
		}
		
		if (vec.IsFlagSet(OF_USABLE_WITH_MEGAPHONE) || trauma)
			p.SetUserData(44); // unterbindet NA-Nachforderung bei Erstversorgung
		else
			p.SetUserData(0);

		if (!p.HasCommand("heal") && !p.HasCommand("raheal"))
			p.AssignCommand("eh");

		if (Game::IsMultiplayer())
			p.SetPlayerMP(Caller->GetPlayerMP());

		if (anderwache)
		{
			p.Hide();
			Actor *Entry=place.GetActor(0);
			Vector pos=Entry->GetPosition();
			Game::FindFreePosition(&p,pos,100);
			p.SetCommandable(true);
			p.SetPosition (pos);
			if (imhaus)
				p.SetEnteredHouseID(rwacheid);
			p.Show();
			if (anderwerkstatt) 
			{
				p.PushActionMove(ACTION_NEWLIST,Target,TARGET_PASSENGERDOOR);
				p.PushActionTurnTo(ACTION_APPEND,Target);
				p.PushActionRepair(ACTION_APPEND,Caller);
				p.PushActionExecuteCommand(ACTION_APPEND,"sendhome",Caller,0,false);
				p.PushActionMove(ACTION_APPEND,pos);
				p.PushActionWait(ACTION_APPEND,1.0);
				p.PushActionDeleteOwner(ACTION_APPEND);
			} else if (trauma) {
				p.PushActionExecuteCommand(ACTION_NEWLIST,"InDieAnstalt",Target,0,false);						
			} else {
				p.PushActionExecuteCommand(ACTION_NEWLIST,"MoveTo",Target,112,true);			
				p.PushActionExecuteCommand(ACTION_APPEND,"entercar",Target,alarm,true);			
				switch (childID)
				{
					case 99:
						p.PushActionWait(ACTION_NEWLIST,0.1f);
						break;
					case 20:
						p.PushActionMove(ACTION_NEWLIST,Target,TARGET_PASSENGERDOOR);
						p.PushActionExecuteCommand(ACTION_APPEND,"ChangeToDiver",Target,0,false);			
						break;
					default:
						break;
				}
			}
		} else if (freiwillig)
			p.PushActionExecuteCommand(ACTION_NEWLIST,"Freiwillige",Target,fzid,false);
		else
		{
			vec.AddPassenger(&p);
			if (am_fz)
			{
				p.PushActionLeaveCar(ACTION_NEWLIST,&vec);
				p.PushActionExecuteCommand(ACTION_APPEND,"Lift",Target,0,false);
			}
		}
	}
};

//
// Abschnitt FwGeraete -> Kommandoschnittstelle zum Geraeteaufbau
//

object SetVerteiler : CommandScript
{
	SetVerteiler()
	{
		SetCursor("Verteiler");
		SetIcon("Verteiler");
		SetValidTargets(ACTOR_FLOOR | ACTOR_VIRTUAL);
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),10);
	}
	
	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool show=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),10));
		return show;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if (!Caller->IsValid() || (Caller->GetID() == Target->GetID()))
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
				break;
			default:
				return false;
		}
			
	    	VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		if (fzlocal::has_equip(&v,10))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,100,false);
	}
};

object Schnellangriff : CommandScript
{
	Schnellangriff()
	{
		SetCursor("schnella");
		SetIcon("schnella");
		SetGroupLeader(false);
		SetValidTargets (ACTOR_VEHICLE | ACTOR_PERSON);
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),15);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		bool zeig;
		if (Caller->GetType() == ACTOR_PERSON)
		{
			Person p(Caller);
			VehicleList vl(Caller->GetName());
			zeig=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),15));
		} else if (Caller->GetType() == ACTOR_VEHICLE)
				zeig=true;
			else 
				zeig=false;		
		return zeig;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;
		
		if (Caller->GetType() == ACTOR_VEHICLE)
		{
			Vehicle v(Caller);
		} else {
			Person p(Caller);
			if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
				return false;
		
			switch (p.GetPersonType())
			{
				case PT_FIREFIGHTER_NORMAL:
				case PT_FIREFIGHTER_MASK:
					break;
				default:
					return false;
			}
			
	    		VehicleList vl(Caller->GetName());
			Vehicle v=vl.GetVehicle(0);
		}
		if (fzlocal::has_equip(&v,15))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Caller->GetType() == ACTOR_VEHICLE)
		{
			Vehicle v(Caller);
			PersonList pl=v.GetPassengers();
			for (int i=0;i<pl.GetNumPersons() && pl.GetPerson(i)->HasCommand("fuehrung");i++);
			if (i<pl.GetNumPersons() && !pl.GetPerson(i)->HasCommand("fuehrung"))
			{
				Person p=pl.GetPerson(i);
				p.PushActionLeaveCar(ACTION_NEWLIST,Caller);
				p.PushActionExecuteCommand(ACTION_APPEND,"FwGeraet_raus",Target,105,false);
			}
		} else
			Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,105,false);
		Caller->PushActionExecuteCommand(ACTION_INSERT,"ma_pumpe",Caller,0,false);
	}
};

object SetMonitor : CommandScript
{
	SetMonitor()
	{
		SetCursor("Monitor");
		SetIcon("Monitor");
		SetGroupLeader(false);
		SetValidTargets(ACTOR_FLOOR | ACTOR_VIRTUAL);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),11);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),11));
		return zeig;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
				break;
			default:
				return false;
		}
			
	    	VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		if (fzlocal::has_equip(&v,11))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,101,false);
	}
};

object SetPylone : CommandScript
{
	SetPylone()
	{
		SetCursor("Pylone");
		SetIcon("Pylone");
		SetGroupLeader(false);
		SetValidTargets(ACTOR_FLOOR | ACTOR_VIRTUAL);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),13);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),13));
		return zeig;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
			case PT_POLICEMEN:
				break;
			default:
				return false;
		}
			
	    	VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		if (fzlocal::has_equip(&v,13))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,103,false);
	}
};

object AutoUmleiten : CommandScript
{
	AutoUmleiten()
	{
		SetCursor("umleiten");
		SetIcon("umleiten");
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckPossible(GameObject *Caller)
	{
		Vehicle v(Caller);
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Caller);
		if (!Caller->IsValid() || (Caller->GetID()!=Target->GetID()))
			return false;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionRedirect(ACTION_NEWLIST);
	}
};

object SetZelt : CommandScript
{
	SetZelt()
	{
		SetCursor("segzelt");
		SetIcon("segzelt");
		SetValidTargets(ACTOR_FLOOR | ACTOR_VIRTUAL);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return vl.GetVehicle(0)->IsFlagSet(OF_CARRYABLE_BY_BULLDOZER);
	}


	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		return !Caller->IsEquipped() && vl.GetVehicle(0)->IsFlagSet(OF_CARRYABLE_BY_BULLDOZER);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
	    	VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		return v.IsFlagSet(OF_CARRYABLE_BY_BULLDOZER);
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,108,false);
	}


};

object SetLima : CommandScript
{
	SetLima()
	{
		SetCursor("lima");
		SetIcon("lima");
		SetGroupLeader(false);
		SetValidTargets(ACTOR_FLOOR | ACTOR_VIRTUAL);
	}

	bool CheckPossible(GameObject *Caller)
	{
		VehicleList vl(Caller->GetName());
		return fzlocal::has_equip(vl.GetVehicle(0),14);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		VehicleList vl(Caller->GetName());
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(vl.GetVehicle(0),14));
		return zeig;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
				break;
			default:
				return false;
		}
			
	    	VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		if (fzlocal::has_equip(&v,14))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,104,false);
	}
};

object SetLuefter : CommandScript
{
	SetLuefter()
	{
		SetCursor("luefter");
		SetIcon("luefter");
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
		SetValidTargets(ACTOR_OPEN_HOUSE);
	}

	bool CheckPossible(GameObject *Caller)
	{
		return fzlocal::has_equip(Caller,22);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,22));
		return zeig;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid() || (Caller->GetID()==Target->GetID()))
			return false;

		Person p(Caller);
		if (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1)
			return false;
		
		if (fzlocal::has_equip(Caller,22))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,112,false);
		Person p(Caller);
		if (p.GetPersonType()!=PT_FIREFIGHTER_MASK)
		{
			p.PushActionExecuteCommand(ACTION_INSERT,"ChangeToMask",Caller,101,false);
		}
	}
};

object ggv_abdichten : CommandScript
{
	ggv_abdichten()
	{
		SetCursor("abdichten");
		SetIcon("abdichten");
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
		SetValidTargets(ACTOR_VEHICLE);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,19));
		return zeig;
	}

	bool CheckPossible(GameObject *Caller)
	{
		return fzlocal::has_equip(Caller,19);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
			case PT_FIREFIGHTER_ABC:
				break;
			default:
				return false;
		}
			
		bool avail=fzlocal::has_equip(Caller,19);

		if (avail && (Target->GetType()==ACTOR_VEHICLE))
		{
			Vehicle v(Target);
			bool leck=((v.GetEnergy() < v.GetMaxEnergy()) && (v.GetUserData() != 4)) && v.HasCommand("gefahrgut");
			avail=leck;
		}
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,109,false);
	}
};

object GetGZ : CommandScript
{
	GetGZ()
	{
		SetCursor("Geiger");
		SetIcon("Geiger");
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,16));
		return zeig;
	}

	bool CheckPossible(GameObject *Caller)
	{
		return fzlocal::has_equip(Caller,16);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
			case PT_FIREFIGHTER_ABC:
				break;
			default:
				return false;
		}
			
		if (fzlocal::has_equip(Caller,16))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,106,false);
	}
};

object GetMM : CommandScript
{
	GetMM()
	{
		SetCursor("Gasmultimeter");
		SetIcon("Gasmultimeter");
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,17));
		return zeig;
	}

	bool CheckPossible(GameObject *Caller)
	{
		return fzlocal::has_equip(Caller,17);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
			case PT_FIREFIGHTER_ABC:
				break;
			default:
				return false;
		}
			
		if (fzlocal::has_equip(Caller,17))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,107,false);
	}
};

object GetB : CommandScript
{
	GetB()
	{
		SetCursor("brohr");
		SetIcon("brohr");
		SetGroupID(CGROUP_GETEQUIPMENT);
		SetGroupLeader(false);
		// SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool zeig=(!Caller->IsEquipped());
		return zeig;
	}

	bool CheckPossible(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
			case PT_FIREFIGHTER_ABC:
				break;
			default:
				return false;
		}
			
		bool avail=false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (v.IsFirefighter())
				avail=fzlocal::has_equip(Target,21);
			else 
				avail=false;
		} else
			if (Caller->GetID() == Target->GetID())
				avail=fzlocal::has_equip(Caller,21);
	
		return avail;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()!=ACTOR_VEHICLE)
		{
			VehicleList vl(Caller->GetName());
			Vehicle v(vl.GetVehicle(0));
		} else
			Vehicle v(Target);
	
		Vector TargetPos = v.GetTargetPoint(Caller, TARGET_EQUIPMENTDOOR);
		if (fzlocal::take_equip(&v,21))
			Caller->PushActionGetEquipment(ACTION_INSERT, &v, EQUIP_FIREHOSE);
		Caller->PushActionTurnTo(ACTION_INSERT, &v);
		Caller->PushActionMove(ACTION_INSERT, TargetPos);
		Caller->SetUserData(111);
	}
};

object SetTS : CommandScript
{
	SetTS()
	{
		SetCursor("tragks");
		SetIcon("tragks");
		SetGroupLeader(false);
		SetValidTargets(ACTOR_FLOOR | ACTOR_VIRTUAL);
	}

	bool CheckPossible(GameObject *Caller)
	{
		return fzlocal::has_equip(Caller,12);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		Person p(Caller);
		bool zeig=(!Caller->IsEquipped() && fzlocal::has_equip(Caller,12));
		return zeig;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{

		if (!Caller->IsValid())
			return false;

		Person p(Caller);
		if (p.IsValid() && (p.IsCarryingPerson()||p.IsLinkedWithPerson()|| p.GetFirehoseID()!=0 || p.IsPulling() || p.GetEnteredCarID() != -1))
			return false;
		
		switch (p.GetPersonType())
		{
			case PT_FIREFIGHTER_NORMAL:
			case PT_FIREFIGHTER_MASK:
				break;
			default:
				return false;
		}
			
		if (fzlocal::has_equip(Caller,12))
			return true;
		else 	
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Caller,102,false);
	}
};

object geraet_entnehmen : CommandScript
{
	bool nur_entnahme=false;

	geraet_entnehmen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		nur_entnahme=true;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		GameObject obj(Target);
		Vehicle v(Caller);
		bool erg;

		switch (childID)
		{
			case 8:
				erg=v.IsFlagSet(OF_CARRYABLE_BY_BULLDOZER);
				break;
			case 13:
				erg=true;
				break;
			default:
				erg=fzlocal::take_equip(Caller,childID+10);
				break;
		}

		if (!erg)
		{
			// System::Log("Geraet NICHT DA!");
			obj.SetUserData(0);
			obj.PushActionWait(ACTION_NEWLIST,0.1);
		} else {
			if (nur_entnahme)
				Target->SetUserData(childID+200);
			else
				Target->SetUserData(childID+100);
			if (childID==8)
				v.ClearFlag(OF_CARRYABLE_BY_BULLDOZER);
		}
		nur_entnahme=false;
	}
};

object geraet_einladen : CommandScript
{
	geraet_einladen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		bool erg=true;
		Vehicle v(Target);
		if (childID==8)
				v.SetFlag(OF_CARRYABLE_BY_BULLDOZER);
		else
			erg=fzlocal::put_equip(Target,childID+10);
	}
};

/// Patrouillenfunktion

object Fahre_Patrouille : CommandScript
{
	Fahre_Patrouille()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle stw(Target);

		if (stw.HasCommand("ich_bin_nicht_frei") || stw.IsSmoking() || stw.IsDestroyed() || fzlocal::IsKripo(&stw))
		 	return;

		Vector Pos;
		ActorList al;
		Actor a;
		
		float warten=ChildID*1.0;
		
		int fzid=fzlocal::fzid(&stw)-7;
		int ptype=110;
		if (fzid>2)
		{
			ptype=1101;
			fzid=fzid-49;
		}
		
		stw.PushActionWait(ACTION_NEWLIST,warten);
		stw.PushActionExecuteCommand(ACTION_APPEND,"mannschaft_rufen",&stw,ptype,false);
		stw.PushActionExecuteCommand(ACTION_APPEND,"check_ms_vollzaehlig",&stw,0,false);
		stw.PushActionExecuteCommand(ACTION_APPEND,"fzfrei",&stw,1,false);
		if (stw.IsHidden())
			stw.PushActionExecuteCommand(ACTION_APPEND,"nachbar_holen",&stw,0,false);
		stw.PushActionExecuteCommand(ACTION_APPEND,"normale_fahrt",&stw,0,false);
		bool ende=false;
		int pfad;
		int dot;
		Vector Pos;
		for (int q=0;q<4;q++)
		{
			pfad=int(skennung[fzid][q]);
			if (pfad>32)
			{
				pfad=pfad-64;
				ende=pfad>32;
				if (ende)
					pfad=pfad-32;
				if (!deluxe)
					pfad++;	
	
				char * bhf="             ";
				char * zugname="traffic_car0%u";
				int j=snprintf(bhf,13,zugname,pfad);
				PathList pl(bhf);
				Path path(pl.GetPath(0));
				if (ende)
					Pos=path.GetPoint(path.GetNumPoints()-1);
				else
					Pos=path.GetPoint(0);
				stw.PushActionMove(ACTION_APPEND,Pos);
			}
		}
		stw.PushActionExecuteCommand(ACTION_APPEND,"gohome_winterberg",&stw,0,false);
	}
};

object Patrouille_frei : CommandScript
{
	Patrouille_frei()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle stw(Target);
		stw.PushActionExecuteCommand(ACTION_APPEND,"Fahre_Patrouille",&stw,ChildID,false);
	}
};

///
/// Nachbarfz vor Werkstattfahrt sichtbar machen
///

object Fz_ranholen : CommandScript
{

	Fz_ranholen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle stw(Caller);
		int fzid;

		if (stw.IsHidden())
		{
			GameObjectList ol;
			if (ChildID==0)
			{
				fzid=fzlocal::fzort(&stw); // Fz-Standort
				if (fzid > 50)
					fzid=fzid-50;
			} else
				fzid=Target->GetUserData()/10000;

			Game::CollectObstaclesOnVirtualObject(fzlocal::stellplatz(fzid),ol,ACTOR_VEHICLE);
			if (ol.GetNumObjects()>0)
			{
				stw.PushActionWait(ACTION_INSERT,1.0f);
				stw.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"fz_ranholen",Target,ChildID,false);
				System::Error("fz raus: ausfahrt blockiert");
			} else {
				Vector nachbarpos=stw.GetPosition();
				Game::FindFreePosition(&stw,nachbarpos,100);
				stw.SetPosition(nachbarpos);
				stw.Show();
			}
		}
	}
};


object drehen : CommandScript
{
	drehen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle vec(Caller);
		float rot[9];
		float childRot[9]=(0,0,0,0,0,0,0,0,0,0);
		int rw=childID;
		
//		vec.GetRotation(rot[0], rot[1], rot[2], rot[3], rot[4], rot[5], rot[6], rot[7], rot[8]);
		Math::EulerToMatrix(rw*90.0f, 0.f, 0.f, childRot);
		Math::MultiplyMatrices(childRot, rot);
		vec.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
	}
};

//
bool deluxe=false;

object setver : CommandScript
{
	setver()
	{
		SetGroupID(20);
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		deluxe=(Caller->GetUserData() == 11);
		sirs=Game::GetGameObjectsWithPrefix("Sir8");	
		if (sirs.GetNumObjects()==0)
			sirs=Game::GetGameObjectsWithPrefix("sir8");
		if (deluxe)

			System::Log(":MAP:1");
		
		else
			
			System::Log(":MAP:0");
	}
};

bool isdeluxe()
{
	return deluxe;
}


//
// Class FZLOCAL -> stellt Funktionen zum Zugriff auf fzspezifische Datenbank bereit
//

char fzeinsatz[MAX_FZ*25];
const char *bmask="%s0000000000000000000000000";
const char *bel="                                                                    ";


object waehle_Klinik : CommandScript
{
	waehle_Klinik()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		int platz=Math::rand()%12+1;
		ActorList fzl=Game::GetActors(pkennung[platz]); // Fz am gewuenschten Stellplatz erzeugen
		Actor fz = *fzl.GetActor(0);
		Caller->SetPosition(fz.GetPosition());
		Caller->SetUserData(Math::rand()%80+80+platz*10000);
	}
};

object verzoegern : CommandScript
{
	verzoegern()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle v(Caller);
		int p=Target->GetUserData()/10000;
		int dist=Target->GetUserData()-p*10000;
		int warte=(verzfakt * 10/v.GetSpeed()) * dist/20;
		if (ChildID==0)
		{
			Caller->PushActionExecuteCommand(ACTION_INSERT,"Fz_ranholen",Target,1,false);
			Caller->PushActionExecuteCommand(ACTION_INSERT,"check_ms_vollzaehlig",Caller,0,false);
		}
		Caller->PushActionWait(ACTION_INSERT,warte);
		Caller->SetFlag(OF_USABLE);
	}
};

class fzlocal:CommandScript
{
	public:

const char *kennung(int i)
{
	return fzkennung[i];
}

const char *fae(int i)
{
	return fzfae[i];
}

const char *dusa(int i)
{
	return fzdusa[i];
}


const char *Signal(int i)
{
	if (i<0)
		return "ERROR";
	else
		return fzsignal[i];
}

const char *stellplatz(int i)
{
	return pkennung[i];
}

int richtung(int i)
{
	int x=int(fzcode[i][3])-48;
	return x;
}

bool inplace(Actor *Caller)
{
	const char * fz[1];
	fz[0]=Caller->GetName();
	bool ok=int(fz[0][14])==73;
	return ok;
}


int fzid(Actor *Caller)
{
	const char * fz[1];
	fz[0]=Caller->GetName();
	int id=int(fz[0][11])-32;
	return id;
}

int fzort(Actor *Caller)
{
	const char * fz[1];
	fz[0]=Caller->GetName();
	int id=int(fz[0][7])-32;
	return id;
}

float verz(GameObject *Caller)
{
	int i=fzort(Caller);
	Vehicle v(Caller);
	float warte;

	if (i<51)
		warte=0;
	else 
		warte=(verzfakt * 10/v.GetSpeed()) / verz[i-50];
	return warte;
}

void fz_beladen(Actor *fz)
{
	int i=fzid(fz);
	int id=i*25;
	int x=snprintf(bel,25,bmask,fzbasisequip);
	for (int x=0;x<25;x++)
		fzeinsatz[id+x]=bel[x];
	int x=snprintf(bel,25,bmask,fzladung[i]);
	for (int x=0;x<25;x++)
		fzeinsatz[id+x]=bel[x];
}

bool has_equip(Actor *fz, int x)
{
	int id=fzid(fz);
	if (id >= MAX_FZ)
		return false;
	if (id<1)
	{
		return false;
	}
	id=id*25+x;
	if ((int(fzeinsatz[id])-48) > 0)
		return true;
	else
		return false;
}

bool take_equip(Actor *fz, int x)
{
	int id=fzid(fz);
	id=id*25+x;
	if ((int(fzeinsatz[id])-48) > 0)
	{
		int anz=int (fzeinsatz[id])-49;
		fzeinsatz[id]=char(anz+48);
		return true;
	} else 
		return false;		
}

bool put_equip(Actor *fz, int x)
{
	int id=fzid(fz);
	int i=id*25+x;
	if (int(fzeinsatz[i]) < int(fzladung[id][x]))
	{
		int anz=int (fzeinsatz[i])-47;
		fzeinsatz[i]=char(anz+48);
		return true;
	} else 
		return false;		
}

bool IsKripo(Actor *Caller)
{
	const char * fz[1];
	fz[0]=Caller->GetName();
	int id=int(fz[0][14]);
	return id==75;
}

/// Distanzbestimmung

float Distanz(Vehicle pv, Actor *Target)
{
	Vector p1=pv.GetPosition();
	Vector p2=Target->GetPosition();
	float d1=Math::dist2(p1.x,p1.y,p2.x,p2.y);
	if (d1<0)
		d1=d1*-1.0;
	return d1;
}

float fzspeed(Actor *fz)
{
	const char * fzcode[1];
	fzcode[0]=fz->GetName();
	int speed=int(fzcode[0][13])-64;
	if (speed>26)
	{
		speed=speed-32;
	}
	float fzspeed=speed*1.0;
	return fzspeed;
}

};

//
// Localizer : ab hier loke Infos -> Abschnitt kann bei Anpassungen komplett ausgetauscht werden
//
		const char * proto[MAX_FZ];
		const char * fzcode[MAX_FZ];
		const char * fzkennung[MAX_FZ];


		fzkennung[1]="8821";
		fzkennung[2]="8831";
		fzkennung[3]="8442";
		fzkennung[4]="8231";
		fzkennung[5]="8511";
		fzkennung[6]="8331";
		fzkennung[7]="stw1";
		fzkennung[8]="stw2";
		fzkennung[9]="stw3";
		fzkennung[10]="mtw";
		fzkennung[11]="asf";
		fzkennung[12]="ch25";
		fzkennung[13]="tjeep";
		fzkennung[14]="11831";
		fzkennung[15]="8921";
		fzkennung[16]="kran";
		fzkennung[17]="bsw";
		fzkennung[18]="hummel";
		fzkennung[19]="8422";
		fzkennung[20]="gtlfbb";
		fzkennung[21]="si4821";
		fzkennung[22]="si4831";
		fzkennung[23]="7831";
		fzkennung[24]="4831";
		fzkennung[25]="kb9183";
		fzkennung[26]="7821";
		fzkennung[27]="8851";
		fzkennung[28]="8481";
		fzkennung[29]="8482";
		fzkennung[30]="8211";
		fzkennung[31]="8212";
		fzkennung[32]="LNA";
		fzkennung[33]="DBNFM";
		fzkennung[34]="Bomber";
		fzkennung[35]="SEG-RD";
		fzkennung[36]="SEG-Arzt";
		fzkennung[37]="SEG-Truck";
		fzkennung[38]="8421";
		fzkennung[39]="8741";
		fzkennung[40]="8111";
		fzkennung[41]="dekonp";
		fzkennung[42]="8471";
		fzkennung[43]="8472";
		fzkennung[44]="8473";
		fzkennung[45]="8483";
		fzkennung[47]="8484";
		fzkennung[46]="7331";
		fzkennung[48]="chr7";
		fzkennung[49]="8101";
		fzkennung[50]="8291";
		fzkennung[51]="8441";
		fzkennung[52]="8102";
		fzkennung[53]="8103";
		fzkennung[54]="8475";
		fzkennung[55]="8474";
		fzkennung[56]="kripo";
		fzkennung[57]="WaWe";
		fzkennung[58]="1831";
		fzkennung[59]="zpol1";
		fzkennung[60]="zpol2";
		fzkennung[61]="flufz";
		fzkennung[62]="1121";
		fzkennung[63]="mtk8583";
		fzkennung[64]="rud8882";
		fzkennung[65]="4821";
		fzkennung[66]="5831";
		fzkennung[67]="6831";
		fzkennung[68]="WaW";
		fzkennung[69]="SEKPKW";
		fzkennung[70]="SEKMTW";
		fzkennung[71]="DEMOEL";
		fzkennung[72]="DEMOMT";
		fzkennung[73]="ITH1";
		fzkennung[74]="ITH2";
		fzkennung[75]="TRAUMA";

		const char * fzladung[MAX_FZ];
		// definiert die Anzahl der verlasteten Teile pro Einsatzmittel
		// 1. Stelle PA
		// 2. Stelle CSA
		// 3. Stelle Taucheranzuege
		// 4. Stelle Strahlrohre
		// 5. Stelle Tankinhalt in 1000 l
		// 6. Stelle Rettungsschere
		// 7. Stelle Kettensaege
		// 8. Stelle
		// 9. Stelle
		// 10. Stelle

		// 11.Stelle "verteiler_an_bord";
		// 12.Stelle "monitor_an_bord";
		// 13.Stelle "ts_an_bord";
		// 14.Stelle "pylone_an_bord";
		// 15.Stelle "lima_an_bord";
		// 16.Stelle "schnellangriff_an_bord";
		// 17.Stelle "gz_an_bord";
		// 18.Stelle "mm_an_bord";
		// 19.Stelle "zelt_an_bord";
		// 20.Stelle "dichtkissen_an_bord";
		// 21.Stelle "auto_umleiten";
		// 22.Stelle "b-rohr";
		// 23.Stelle "tempestluefter";
		// 24.Stelle "Saugleitung"

		char * fzbasisequip[]="000000000000000000001000";


		// Jede Stelle ein Zeichen, dessen ASCII-Code = 32 + Wert
		// Bei Eintreffen Wache wird die definierte Ladung als Einsatzmittel verlastet.
		// Im Verlauf des Einsatzes werden die Zaehler entsprechend modifiziert
		//            01234 6789 1234 6789 12345
		fzladung[3] ="420411189020031100011201";
		fzladung[4] ="400320089011000100001101";
		fzladung[5] ="202001189000031000001001";
		fzladung[6] ="200100089000000000001011";
		fzladung[7] ="000000089000030000001001";
		fzladung[8] ="000000089000030000001001";
		fzladung[9] ="000000089000030000001001";
		fzladung[10]="000000089000030000001001";
		fzladung[15]="N?0000089000000011011001";
		fzladung[19]="400311189010131100001101";
		fzladung[20]="200350089011000100001101";
		fzladung[28]="400310189010131100001101";
		fzladung[29]="400310089010130100001101";
		fzladung[30]="200320089010000100001101";
		fzladung[31]="200320089010000100001101";
		fzladung[38]="400310189010100100001101";
		fzladung[39]="300000289000030000031611";
		fzladung[35]="000000089000000000101001";
		fzladung[40]="400000089000041000001011";
		fzladung[41]="660000089000000011001001";
		fzladung[42]="400310089010130000001101";
		fzladung[43]="400310089010130000001101";
		fzladung[44]="400310089010130000001101";
		fzladung[46]="200100089000000000001011";
		fzladung[45]="400310089010130100001101";
		fzladung[47]="400311189010131100001101";
		fzladung[49]="400000089000041000001011";
		fzladung[50]="400310089010130100001101";
		fzladung[51]="420411189020031100011201";
		fzladung[52]="400000089000041000001011";
		fzladung[53]="400000089000041000001011";
		fzladung[54]="400310089010130000001101";
		fzladung[55]="400310089010130000001101";
		fzladung[58]="402310089010130000001101";
		fzladung[59]="000000089000030000001001";
		fzladung[60]="000000089000030000001001";
		fzladung[62]="400320089011000100001101";

		const int MAX_PLATZ=25;
		const char * pkennung[MAX_PLATZ];
		pkennung[1]="nord";		// OKZ 51 = Bad Berleburg
		pkennung[2]="ost1";		// OKZ 52 = Arnsberg
		pkennung[3]="ost";		// OKZ 53 = Langewiese
		pkennung[4]="ost1";		// OKZ 54 = Olsberg
		pkennung[5]="ost2";		// OKZ 55 = Korbach
		pkennung[6]="sued";		// OKZ 56 = Zueschen
		pkennung[7]="west";		// OKZ 57 = Langewiese
		pkennung[8]="west";		// OKZ 58 = Hildfeld
		pkennung[9]="kran";		// OKZ 59 = Siedlingshausen
		pkennung[10]="rtwm";		// OKZ 60 = Medebach
		pkennung[11]="rtwm";		// OKZ 61 = Medebach
		pkennung[12]="rtwm";		// OKZ 62 = Medebach
		pkennung[13]="west";		// OKZ 63 = Medebach
		pkennung[14]="ch25";		// OKZ 64 = Siegen
		pkennung[15]="ost";		// OKZ 64 = Siegen
		pkennung[16]="8471";		// OKZ 64 = Siegen
		pkennung[17]="kran";		// OKZ 64 = Siegen
		pkennung[18]="kran";		// OKZ 64 = Siegen
		pkennung[19]="8483";		// OKZ 64 = Siegen
		pkennung[20]="ost";		// OKZ 64 = Siegen
		pkennung[21]="nord";		// OKZ 64 = Siegen
		pkennung[22]="ost1";		// OKZ 54 = Olsberg
		pkennung[23]="ost1";		// OKZ 54 = Olsberg

		const char * skennung[MAX_PLATZ];
		skennung[0]="Ac  ";		// Streifenpfad 1 Code = 64+Pfadnr = Start; 96+PfadNr = Endpunkt
		skennung[1]="Dbd ";		// Streifenpfad 2
		skennung[2]="ea  ";		// Streifenpfad 3
		skennung[3]="B   ";		// Streifenpfad 4
		skennung[4]="E   ";		// Streifenpfad 5


const float verzfakt=30.0;
const int maxverz=25;
const float verz[maxverz];
verz[1]=1;	// Bad Berleburg entspricht 20 km
verz[2]=0.3;	// Arnsberg
verz[3]=3;	// Langewiese
verz[4]=1.0;	// Olsberg
verz[5]=0.75;	// Korbach
verz[6]=4;	// Zueschen
verz[7]=4;	// Groenebach
verz[8]=2.5;	// Hildfeld
verz[9]=2.5;	// Siedlingshausen
verz[10]=1.1;	// Medebach
verz[11]=4;	// Altastenberg
verz[12]=0;	// Enkeringhausen
verz[13]=2.1;	// Niedersfeld
verz[14]=0.4;   // Siegen
verz[15]=0.75;	// Schmallenberg
verz[16]=5;	// Elkeringhausen
verz[17]=3;	// Altenfeld
verz[18]=1.7;	// Silbach
verz[19]=0;	// Altastenberg
verz[20]=3;	// Neuastenberg
verz[21]=0.2;	// Kassel
verz[22]=0.61;	// Brilon
verz[23]=0.37;	// Marsberg

		const char * fzsignal[MAX_FZ];
		fzsignal[1]="MULTI";
		fzsignal[2]="MULTI";
		fzsignal[3]="mod:Audio/FX/Sirens/lf16.wav";
		fzsignal[4]="MULTI";
		fzsignal[5]="mod:Audio/FX/Sirens/rw.wav";
		fzsignal[6]="mod:Audio/FX/Sirens/dlk_horn_orig.wav";
		fzsignal[7]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[8]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[9]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[10]="MULTI";
		fzsignal[11]="NULL";
		fzsignal[12]="NULL";
		fzsignal[13]="NULL";
		fzsignal[14]="MULTI";
		fzsignal[15]="mod:Audio/FX/Sirens/dekon.wav";
		fzsignal[16]="mod:Audio/FX/Sirens/ehorn.wav";
		fzsignal[17]="NULL";
		fzsignal[18]="NULL";
		fzsignal[19]="mod:Audio/FX/Sirens/lfz.wav";
		fzsignal[20]="mod:Audio/FX/Sirens/gtlf.wav";
		fzsignal[21]="MULTI";
		fzsignal[22]="mod:Audio/FX/Sirens/rtwbb.wav";
		fzsignal[23]="mod:Audio/FX/Sirens/nefsiren.wav";
		fzsignal[24]="MULTI";
		fzsignal[25]="MULTI";
		fzsignal[26]="mod:Audio/FX/Sirens/nefsiren.wav";
		fzsignal[27]="mod:Audio/FX/Sirens/itw.wav";
		fzsignal[28]="mod:Audio/FX/Sirens/rw.wav";
		fzsignal[29]="mod:Audio/FX/Sirens/dlk.wav";
		fzsignal[30]="mod:Audio/FX/Sirens/tlf818.wav";
		fzsignal[31]="mod:Audio/FX/Sirens/tlf818.wav";
		fzsignal[32]="mod:Audio/FX/Sirens/martin4.wav";
		fzsignal[33]="MULTI";
		fzsignal[34]="mod:Audio/FX/Sirens/bosch.wav";
		fzsignal[35]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[36]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[37]="mod:Audio/FX/Sirens/gtlf.wav";
		fzsignal[38]="mod:Audio/FX/Sirens/lfz.wav";
		fzsignal[39]="mod:Audio/FX/Sirens/lfz.wav";
		fzsignal[40]="mod:Audio/FX/Sirens/elw.wav";
		fzsignal[41]="mod:Audio/FX/Sirens/bosch.wav";
		fzsignal[42]="mod:Audio/FX/Sirens/bosch.wav";
		fzsignal[43]="mod:Audio/FX/Sirens/bosch.wav";
		fzsignal[44]="mod:Audio/FX/Sirens/dlk.wav";
		fzsignal[45]="mod:Audio/FX/Sirens/itw.wav";
		fzsignal[47]="MULTI";
		fzsignal[46]="mod:Audio/FX/Sirens/gtlf.wav";
		fzsignal[48]="NULL";
		fzsignal[49]="MULTI";
		fzsignal[50]="mod:Audio/FX/Sirens/tlf818.wav";
		fzsignal[51]="mod:Audio/FX/Sirens/lf16.wav";
		fzsignal[52]="MULTI";
		fzsignal[53]="MULTI";
		fzsignal[54]="MULTI";
		fzsignal[55]="MULTI";
		fzsignal[56]="MULTI";
		fzsignal[57]="NULL";
		fzsignal[58]="mod:Audio/FX/Sirens/elw.wav";
		fzsignal[59]="MULTI";
		fzsignal[60]="MULTI";
		fzsignal[61]="NONE";
		fzsignal[62]="mod:Audio/FX/Sirens/martin4.wav";
		fzsignal[63]="mod:Audio/FX/Sirens/martin4.wav";
		fzsignal[64]="mod:Audio/FX/Sirens/nefsiren.wav";
		fzsignal[65]="mod:Audio/FX/Sirens/topas1.wav";
		fzsignal[66]="mod:Audio/FX/Sirens/topas2.wav";
		fzsignal[67]="mod:Audio/FX/Sirens/dlk.wav";
		fzsignal[68]="mod:Audio/FX/Sirens/bosch.wav";
		fzsignal[69]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[70]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[71]="mod:Audio/FX/Sirens/stw.wav";
		fzsignal[72]="MULTI";
		fzsignal[73]="NONE";
		fzsignal[74]="NONE";
		fzsignal[75]="NONE";

const int maxfae=70;
const char * fzfae[maxfae];

fzfae[0]="mod:Audio/FX/nef.wav"; 
fzfae[1]="mod:Audio/FX/nef7821.wav"; 
fzfae[2]="mod:Audio/FX/nefsi4821.wav";
fzfae[3]="mod:Audio/FX/rtw1.wav";
fzfae[4]="mod:Audio/FX/rtw2.wav";
fzfae[5]="mod:Audio/FX/rtw7831.wav"; 
fzfae[6]="mod:Audio/FX/rtw4831.wav"; 
fzfae[7]="mod:Audio/FX/ktw.wav"; 
fzfae[8]="mod:Audio/FX/rtw9183.wav";
fzfae[9]="mod:Audio/FX/rtwsi4831.wav"; 
fzfae[10]="mod:Audio/FX/rth.wav";
fzfae[11]="mod:Audio/FX/lgzuesch.wav"; 
fzfae[12]="mod:Audio/FX/tlfbb.wav";
fzfae[13]="mod:Audio/FX/lggroene.wav"; 
fzfae[14]="mod:Audio/FX/lglangew.wav"; 
fzfae[15]="mod:Audio/FX/dekon.wav"; 
fzfae[16]="mod:Audio/FX/siemens.wav";
fzfae[17]="mod:Audio/FX/thw_kran.wav"; 
fzfae[18]="mod:Audio/FX/lf.wav"; 
fzfae[19]="mod:Audio/FX/lgsiedl.wav"; 
fzfae[20]="mod:Audio/FX/dlk.wav";
fzfae[21]="mod:Audio/FX/wasser.wav";
fzfae[22]="mod:Audio/FX/lz_f.wav";
fzfae[23]="mod:Audio/FX/lz_vu.wav";
fzfae[24]="mod:Audio/FX/lna.wav";
fzfae[25]="mod:Audio/FX/nfm.wav";
fzfae[26]="mod:Audio/FX/bomber.wav";
fzfae[27]="mod:Audio/FX/seg.wav";
fzfae[28]="mod:Audio/FX/gsg_wtbg.wav";
fzfae[29]="mod:Audio/FX/lz_gong.wav";
fzfae[30]="mod:Audio/FX/lg_ehsn.wav";
fzfae[31]="mod:Audio/FX/lg_afeld.wav";
fzfae[32]="mod:Audio/FX/lg_sbach.wav";
fzfae[33]="mod:Audio/FX/lg_aab.wav";
fzfae[34]="mod:Audio/FX/dlkolsberg.wav";
fzfae[35]="mod:Audio/FX/lg_nab.wav";
fzfae[36]="mod:Audio/FX/chr7.wav";
fzfae[37]="mod:Audio/FX/lg_nfld.wav";
fzfae[38]="mod:Audio/FX/lg_hfld.wav";
fzfae[39]="";
fzfae[40]="mod:Audio/FX/wasserwerk.wav";
fzfae[41]="mod:Audio/FX/rtw1831.wav";
fzfae[42]="mod:Audio/FX/elw1121.wav";
fzfae[43]="mod:Audio/FX/54963.wav";
fzfae[44]="mod:Audio/FX/56383.wav";
fzfae[45]="mod:Audio/FX/nef4821.wav";
fzfae[46]="mod:Audio/FX/rtw5831.wav";
fzfae[47]="mod:Audio/FX/5831na.wav";
fzfae[48]="mod:Audio/FX/rtw6831.wav";
fzfae[49]="mod:Audio/FX/6831na.wav";
fzfae[50]="mod:Audio/FX/gong_fw_wache.wav";
fzfae[51]="mod:Audio/FX/gong_fw_wache.wav";
fzfae[52]="mod:Audio/FX/fme/fme110.wav";
fzfae[53]="";
fzfae[54]="mod:Audio/FX/4941.wav";
fzfae[55]="mod:Audio/FX/probevor.wav";
fzfae[56]="mod:Audio/FX/probenach.wav";

const char * fzdusa[maxfae];
const char * metronam="tenne";

fzdusa[0]="Einsatz Notarzt 8-82-1";
fzdusa[1]="Einsatz Notarzt 7-82-1";
fzdusa[2]="Zu Ihnen kommt der Notarzt Bad Berleburg";
fzdusa[3]="Notfalleinsatz RTW 8-83-1";
fzdusa[4]="Notfalleinsatz RTW 11-83-1";
fzdusa[5]="Notfalleinsatz RTW 7-83-1";
fzdusa[6]="Notfalleinsatz RTW 4-83-1";
fzdusa[7]="Notfalleinsatz KTW 8-85-1";
fzdusa[8]="Zu Ihnen kommt der Rot-Kreuz Korbach 91/83";
fzdusa[9]="Zu Ihnen kommt der RTW Bad Berleburg";
fzdusa[10]="Zu Ihnen kommt der Christoph 25";
fzdusa[11]="Einsatz Löschgruppe Züschen";
fzdusa[12]="Einsatz GTLF Feuerwehr Bad Berleburg";
fzdusa[13]="Einsatz Löschgruppe Grönebach";
fzdusa[14]="Einsatz Löschgruppe Langewiese";
fzdusa[15]="Einsatz für den Gerätewagen-Messtechnik";
fzdusa[16]="Einsatz für den Service-Techniker der Fa. Siemens";
fzdusa[17]="Einsatz für den Kran des THW";
fzdusa[18]="Einsatz Feuerwehr Winterberg";
fzdusa[19]="Einsatz Löschgruppe Siedlinghausen";
fzdusa[20]="Einsatz für die Drehleiter Winterberg! Menschenleben in Gefahr";
fzdusa[21]="Einsatz Wasserrettung Winterberg";
fzdusa[22]="Brandeinsatz für den Löschzug Winterberg";
fzdusa[23]="Hilfeleistungseinsatz für den Löschzug Winterberg";
fzdusa[24]="Einsatz Leitender Notarzt Hochsauerland";
fzdusa[25]="Einsatz für den DB Notfallmanager";
fzdusa[26]="Kampfmittelräumdienst an der EStelle erforderlich";
fzdusa[27]="Einsatz SEG Rettung";
fzdusa[28]="Gefahrguteinsatz Löschzug Winterberg";
fzdusa[30]="Einsatz Löschgruppe Elkeringhausen";
fzdusa[31]="Einsatz Löschgruppe Altenfeld";
fzdusa[32]="Einsatz Löschgruppe Silbach";
fzdusa[33]="Einsatz Löschgruppe Altastenberg";
fzdusa[35]="Einsatz Löschgruppe Neuastenberg";
fzdusa[29]="Einsatz Dekon-Fz Fw Schmallenberg";
fzdusa[34]="Einsatz Drehleiter Olsberg";
fzdusa[36]="Einsatz Christoph 7";
fzdusa[37]="Einsatz Löschzug Niedersfeld";
fzdusa[38]="Einsatz Löschgruppe Hildfeld";
fzdusa[39]="Kripo zur Einsatzstelle";
fzdusa[40]="Wasserwerk zur Einsatzstelle";
fzdusa[41]="Notfalleinsatz RTW Arnsberg";
fzdusa[42]="Einsatz Fernmeldedienst Arnsberg";
fzdusa[43]="Nachbarschatfliche Rettungsdienstverstaerkung wird gerufen";
fzdusa[44]="Nachbarschatfliche Notarztverstaerkung wird gerufen";
fzdusa[45]="Einsatz NEF Fredeburg";
fzdusa[46]="Einsatz RTW Brilon";
fzdusa[47]="Einsatz NAW Brilon";
fzdusa[48]="Einsatz RTW Marsberg";
fzdusa[49]="Einsatz NAW Marsberg";
fzdusa[50]="Einsatz für das SEK";
fzdusa[51]="Einsatz ITH Sekundärverlegung vom KH Winterberg";
fzdusa[52]="Ringfunk Traumteam/Kliniknotfall";
fzdusa[53]="KatS-Alarm Hochsauerland";
fzdusa[54]="DekonEinsatz Feuerwehr Schmallenberg";
fzdusa[55]="Funktionsprobe Sirenensteueranlagen";
fzdusa[56]="Ende der Überprüfung";

proto[1]="mod:Prototypes/Vehicles/Ambulance/nef8821.e4p";
fzcode[1]="M2030";
proto[2]="mod:Prototypes/Vehicles/Ambulance/rtw2.e4p";
fzcode[2]="J3130";
proto[3]="mod:Prototypes/Vehicles/Fire Department/lf1612.e4p";
fzcode[3]="I9010";
proto[4]="mod:Prototypes/Vehicles/Fire Department/WB_TLF_16_25.e4p";
fzcode[4]="I6010";
proto[5]="mod:Prototypes/Vehicles/Fire Department/unimog.e4p";
fzcode[5]="I3000";
proto[6]="mod:Prototypes/Vehicles/Fire Department/CHIDEA_DLK_WINTERBERG.e4p";
fzcode[6]="I3010";
proto[7]="mod:Prototypes/Vehicles/Police/stw1.e4p";
fzcode[7]="M4230";
proto[8]="mod:Prototypes/Vehicles/Police/stw1.e4p";
fzcode[8]="M4230";
proto[9]="mod:Prototypes/Vehicles/Police/stw1.e4p";
fzcode[9]="M4230F";
proto[10]="mod:Prototypes/Vehicles/Police/mtw1.e4p";
fzcode[10]="L6530";
proto[11]="mod:Prototypes/Vehicles/TEC/asfwtb.e4p";
fzcode[11]="I1030";
proto[12]="mod:Prototypes/Vehicles/Ambulance/rhc2.e4p";
fzcode[12]="Y3130";
proto[13]="mod:Prototypes/Vehicles/THW/siemens.e4p";
fzcode[13]="J1020";
proto[14]="mod:Prototypes/Vehicles/Ambulance/rtw2m.e4p";
fzcode[14]="J3131F";
proto[15]="mod:Prototypes/Vehicles/gwmess/8921.e4p";
fzcode[15]="J3200";
proto[16]="mod:Prototypes/Vehicles/TEC/fgr.e4p";
fzcode[16]="H2030";
proto[17]="mod:Prototypes/Vehicles/Ambulance/bsw.e4p";
fzcode[17]="J1130";
proto[18]="mod:Prototypes/Vehicles/Police/phc.e4p";
fzcode[18]="Y5330";
proto[19]="mod:Prototypes/Vehicles/Fire Department/LF_8_Zuechen.e4p";
fzcode[19]="I9000";
proto[20]="mod:Prototypes/Vehicles/Winterberg/gtlf_berleburg.e4p";
fzcode[20]="H3030";
proto[21]="mod:Prototypes/Vehicles/Ambulance/nef_si4821.e4p";
fzcode[21]="M2033";
proto[22]="mod:Prototypes/Vehicles/Ambulance/rtw_si4831.e4p";
fzcode[22]="J3134";
proto[23]="mod:Prototypes/Vehicles/Ambulance/rtw7831.e4p";
fzcode[23]="J3132";
proto[24]="mod:Prototypes/Vehicles/Ambulance/rtw4831.e4p";
fzcode[24]="J3133";
proto[25]="mod:Prototypes/Vehicles/Ambulance/rtw9183.e4p";
fzcode[25]="J3135";
proto[26]="mod:Prototypes/Vehicles/Ambulance/nef7821.e4p";
fzcode[26]="M2031";
proto[27]="mod:Prototypes/Vehicles/Ambulance/ktw8851.e4p";
fzcode[27]="J2139F";
proto[28]="mod:Prototypes/Vehicles/Winterberg/tsfw8481.e4p";
fzcode[28]="K6030";
proto[29]="mod:Prototypes/Vehicles/Winterberg/tsfw8482.e4p";
fzcode[29]="K6030";
proto[30]="mod:Prototypes/Vehicles/Fire Department/tlf8212.e4p";
fzcode[30]="I3000";
proto[31]="mod:Prototypes/Vehicles/Fire Department/tlf8211.e4p";
fzcode[31]="I3011";
proto[32]="mod:Prototypes/Vehicles/Ambulance/lna_jeep.e4p";
fzcode[32]="J2035";
proto[33]="mod:Prototypes/Vehicles/TEC/nfm.e4p";
fzcode[33]="J1030";
proto[34]="mod:Prototypes/Vehicles/vario/variobody.e4p";
fzcode[34]="M2030";
proto[35]="mod:Prototypes/Vehicles/Ambulance/vito_drk.e4p";
fzcode[35]="j7930";
proto[36]="mod:Prototypes/Vehicles/Ambulance/ktw_seg.e4p";
fzcode[36]="J6030";
proto[37]="mod:Prototypes/Vehicles/Ambulance/DRK_Truck.e4p";
fzcode[37]="K2000";
proto[38]="mod:Prototypes/Vehicles/Winterberg/lf86.e4p";
fzcode[38]="I9011";
proto[39]="mod:Prototypes/Vehicles/Winterberg/LKW.e4p";
fzcode[39]="I3010F";
proto[40]="mod:Prototypes/Vehicles/Fire Department/elw.e4p";
fzcode[40]="j6010";
proto[41]="mod:Prototypes/Vehicles/Winterberg/dekon_od.e4p";
fzcode[41]="J6800";
proto[42]="mod:Prototypes/Vehicles/Winterberg/tsf8471.e4p";
fzcode[42]="K6000";
proto[43]="mod:Prototypes/Vehicles/Winterberg/tsf8472.e4p";
fzcode[43]="K6011";
proto[44]="mod:Prototypes/Vehicles/Winterberg/tsf8473.e4p";
fzcode[44]="K6011";
proto[45]="mod:Prototypes/Vehicles/Winterberg/tsfw8483.e4p";
fzcode[45]="K6030";
proto[46]="mod:Prototypes/Vehicles/Fire Department/CHIDEA_DLK_OLSBERG.e4p";
fzcode[46]="I3020";
proto[47]="mod:Prototypes/Vehicles/Winterberg/tsfw8484.e4p";
fzcode[47]="K6030";
proto[48]="mod:Prototypes/Vehicles/Ambulance/chr7neu.e4p";
fzcode[48]="Y3131";
proto[49]="mod:Prototypes/Vehicles/niedersfeld/8101.e4p";
fzcode[49]="j6031";
proto[50]="mod:Prototypes/Vehicles/niedersfeld/wawe8291.e4p";
fzcode[50]="H6031";
proto[51]="mod:Prototypes/Vehicles/Fire Department/lf1612.e4p";
fzcode[51]="H9031";
proto[52]="mod:Prototypes/Vehicles/Winterberg/kdow8102.e4p";
fzcode[52]="j6011";
proto[53]="mod:Prototypes/Vehicles/Winterberg/kdow8103.e4p";
fzcode[53]="j6030";
proto[54]="mod:Prototypes/Vehicles/Niedersfeld/8474.e4p";
fzcode[54]="K6031";
proto[55]="mod:Prototypes/Vehicles/Niedersfeld/8474.e4p";
fzcode[55]="K6031";
proto[57]="mod:Prototypes/Vehicles/Tec/wasserwerk.e4p";
fzcode[57]="J1001";
proto[56]="mod:Prototypes/Vehicles/police/kripo.e4p";
fzcode[56]="R4201K";
proto[58]="mod:Prototypes/Vehicles/rd/rtw1.e4p";
fzcode[58]="J3138";
proto[59]="mod:Prototypes/Vehicles/police/kripo.e4p";
fzcode[59]="R4201";
proto[60]="mod:Prototypes/Vehicles/police/kripo.e4p";
fzcode[60]="R4201F";
proto[61]="mod:Prototypes/Vehicles/police/fluchtwagen.e4p";
fzcode[61]="M2201";
proto[62]="mod:Prototypes/Vehicles/Feuerwehr Arnsberg/elw2.e4p";
fzcode[62]="I3410I";
proto[63]="mod:Prototypes/Vehicles/vsama/variobody.e4p";
fzcode[63]="J3132";
proto[64]="mod:Prototypes/Vehicles/Ambulance/nef8882.e4p";
fzcode[64]="M2031";
proto[65]="mod:Prototypes/Vehicles/Audi A6 Sani/audi-sani.e4p";
fzcode[65]="M2032";
proto[66]="mod:Prototypes/Vehicles/Ambulance/rtw5831.e4p";
fzcode[66]="J3136";
proto[67]="mod:Prototypes/Vehicles/Ambulance/rtw6831.e4p";
fzcode[67]="J3137";
proto[68]="mod:Prototypes/Vehicles/polizei/wasser.e4p";
fzcode[68]="K3030";
proto[69]="mod:Prototypes/Vehicles/Polizei SEK/SEK KOMBI.e4p";
fzcode[69]="o4203";
proto[70]="mod:Prototypes/Vehicles/Polizei SEK/SEK MTW.e4p";
fzcode[70]="O9403";
proto[71]="mod:Prototypes/Vehicles/Police/stw1.e4p";
fzcode[71]="m4230";
proto[72]="mod:Prototypes/Vehicles/Police/mtw1.e4p";
fzcode[72]="L6530";
proto[73]="mod:Prototypes/Vehicles/Ambulance/ITH.e4p";
fzcode[73]="Y3130I";
proto[74]="mod:Prototypes/Vehicles/Ambulance/ith2.e4p";
fzcode[74]="Y3130I";
proto[75]="mod:Prototypes/Vehicles/TEC/nfm.e4p";
fzcode[75]="04000";
proto[76]="mod:Prototypes/Vehicles/police/kripo2.e4p";	// kein eigenes Fz in der Mod, wird per Zufall mit dem BMW abgewechselt
fzcode[76]="R4201F";

int fzstatus[MAX_FZ];
int fzobj[MAX_FZ];

// fzstatus übernimmt Statusinfos fuer die einzelnen Fz
// die 4 LSB zeigen den Fz-Status an, dergestalt dass eine &-Abfrage auf das Bit einen True-Wert ergibt, wenn
// der Status gueltig ist
// Bit 0 = Fz ist auf Funk
// Bit 1 = Fz ist disponiert auf Anfahrt
// Bit 2 = Fz ist belegt
// Bit 3 = ..
// die Bits 4 bis .. klassifzieren das Fz
// Bit 4 : Notarztbesetzt
// Bit 5 : kann Patienten transportieren
// Bit 6 : Fluggeraet
// Bit 7 : Führungsfz
// Bit 8 : LöschFz
// Bit 9 : Hubretter
// Bit 10 : Hilfeleistungssatz
// Bit 11 : Taucher
// Bit 12 : führt Wasser
// Bit 13 : GTLF
// Bit 14 : 
// Bit 15 : 
// Bit 16 : Pol
// Bit 17 : MTW
// Bit 18 : KriPo
// Bit 19 : SEK
// Bit 20 : 

const int FZ_FUNK=1;
const int FZ_DISPO=2;
const int FZ_BELEGT=4;
//
const int FZ_NA = 16;
const int FZ_RTW = 32;
const int FZ_HUBI = 64;
const int FZ_FUEHRUNG = 128;
const int FZ_LF=256;
const int FZ_DLK=512;
const int FZ_HLF=1024;
const int FZ_TAUCHER=2048;
const int FZ_TANKER=4096;
const int FZ_GTLF=8192;
const int FZ_SEG=FZ_GTLF*2;
const int FZ_POL=65536;
const int FZ_MTW=FZ_POL*2;
const int FZ_KRIPO=FZ_MTW*2;
const int FZ_SEK=FZ_KRIPO*2;
const int FZ_ITH=FZ_SEK*2;
// 
const int FZ_NACHBAR=FZ_ITH*2;
const int FZ_BEDARF=FZ_NACHBAR*2;
const int FZ_BSW=FZ_NACHBAR*2;

