// ## 
// ## WEM4 Scripting
// ## WEM4 9 Taikapalo
// ## 
// ## Script fuehrung
// ## 
// ## Release 03.05.2014
// ## 
// ## created by WitchDoctor




#pragma compile






object wf_fp : CommandScript
{

   wf_fp()
   {	
	SetIcon("fp");
	SetCursor("fp");
	SetGroupID(7);
	SetGroupLeader(true);
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return !Input::LCtrlPressed();
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return false;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
   }
};



object wf_ts : CommandScript
{

   wf_ts()
   {	
	SetIcon("fpts");
	SetCursor("fpts");
	SetGroupID(7);
	SetGroupLeader(false);
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return Input::LCtrlPressed();
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return false;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
   }
};

object einsatz_pa : CommandScript
{

   einsatz_pa()
   {	
	SetIcon("paeinsatz");
	SetCursor("paeinsatz");
	SetGroupID(6);
	SetGroupLeader(true);
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->AssignCommand("einsatz_wasser");
	Caller->RemoveCommand("einsatz_pa");
   }
};


object einsatz_csa : CommandScript
{

   einsatz_csa()
   {
      SetIcon("csaeinsatz");
      SetCursor("csaeinsatz");
	SetGroupID(6);
	SetGroupLeader(false);
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->AssignCommand("einsatz_ohne");
	Caller->RemoveCommand("einsatz_csa");
   }
};

object einsatz_wasser : CommandScript
{

   einsatz_wasser()
   {
      SetIcon("wasserrettung");
      SetCursor("wasserrettung");
	SetGroupID(6);
	SetGroupLeader(false);
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->AssignCommand("einsatz_csa");
	Caller->RemoveCommand("einsatz_wasser");
   }
};

object einsatz_ohne : CommandScript
{

   einsatz_ohne()
   {
      SetIcon("ohnesonder");
      SetCursor("ohnesonder");
	SetGroupID(6);
	SetGroupLeader(false);
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->AssignCommand("einsatz_pa");
	Caller->RemoveCommand("einsatz_ohne");
   }
};

object angriff : CommandScript
{

   angriff()
   {
	SetGroupID(20);
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
   }
};

object set_angriff : CommandScript
{

   set_angriff()
   {
	SetGroupID(20);
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->AssignCommand("angriff");
   }
};

object gf_LIGHT : CommandScript
{
	gf_LIGHT()
	{
		SetIcon("lighton");
		SetCursor("lighton");
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Caller->GetID()!=Target->GetID();
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		// System::Log("GF Light %u",childID);
		PersonList gruppe(Caller->GetName());
		Person p;
		int i=0;
		bool im_korb=false;
		if (childID==0)
		{
			VehicleList vl(Caller->GetName());
			Vehicle v=vl.GetVehicle(0);
			if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
			{
				GameObject t=bungarext::hierhin(Game::GetCommandPos());
				Target=&t;
			}
			childID=1;
			Caller->SetUserData(v.GetID());
		} 
		
		if (childID>0)
		{
			if (Caller->GetType()==ACTOR_VEHICLE)
				Vehicle v(Caller);
			else {
				Actor a=Game::GetActor(Caller->GetUserData());
				Vehicle v(&a);
			}

			if (childID==1)
			{		
				for (i=0; ((i<gruppe.GetNumPersons()) && !im_korb);i++)
				{
					p=gruppe.GetPerson(i);
					if (!p.HasCommand("fuehrung") && !p.IsLinkedWithPerson())
					{
						im_korb=true;
						p.PushActionMove(ACTION_NEWLIST, Caller, TARGET_DLK_BASKET_BASE);
						p.PushActionExecuteCommand(ACTION_APPEND,"EnterBasket",&v,1002,true);
						if (p.GetEnteredCarID()>1)
							p.PushActionLeaveCar(ACTION_INSERT,&v);
						p.PushActionExecuteCommand(ACTION_APPEND,"gf_LIGHT",Target,2,false);
						p.SetUserData(v.GetID());
					} 
				}
			} else {		
				Caller->PushActionExecuteCommand(ACTION_NEWLIST,"DLK_lichtbruecke",Target,1,false);
			}
		}
	}
};


object gf_ts : CommandScript
{
	gf_ts()
	{
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL);
		SetIcon("tragks");
		SetCursor("tragks");
		SetGroupID(1);
		SetGroupLeader(true);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return !Input::LShiftPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		PersonList gruppe(Caller->GetName());
		Person p;
		bool ts_taken=false;
		int anz_p=gruppe.GetNumPersons()-1;

		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}

		for (int i=anz_p; (i>-1) && !ts_taken;i--)
		{
			p=gruppe.GetPerson(i);
			if (p.HasCommand("ma") && !p.IsLinkedWithPerson() && !p.IsInjured() && !p.IsCarryingPerson())
			{
				if (!p.IsEquipped() && (p.GetUserData()<100))
				{
					p.PushActionExecuteCommand(ACTION_NEWLIST,"FwGeraet_raus",Target,102,false);
					ts_taken=true;
					if (p.GetEnteredCarID()>-1)
					{
						Actor v=Game::GetActor(p.GetEnteredCarID());
						p.PushActionLeaveCar(ACTION_INSERT,&v);
					}
				} else
					System::Log("Maschinist anderweitig belegt %s Task %u",Caller->GetName(),p.GetUserData());
			} 
		}
	}
};

object gf_we : CommandScript
{
	gf_we()
	{
		SetValidTargets(ACTOR_FLOOR|ACTOR_VIRTUAL|ACTOR_OBJECT|ACTOR_VEHICLE|ACTOR_LIQUID);
		SetIcon("hydrant");
		SetCursor("hydrant");
		SetGroupID(2);
		SetGroupLeader(true);
		SetPriority(110);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return !Input::LShiftPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		bool ok=false;
		switch (Target->GetType())
		{
			case ACTOR_OBJECT:
				GameObject obj(Target);
				Vehicle v(Caller);
				ok=obj.IsHydrant();
				break;
			case ACTOR_VEHICLE:
				Vehicle v(Target);
				ok=v.HasChild("pumpe") && v.GetVehicleType()!=VT_FIREFIGHTERS_DLK && v.IsFirefighter();
				break;
			case ACTOR_LIQUID:
				ok=true;
				// System::Log("WE Ueberflutung abpumpen aus %s",Target->GetName());
				break;
			default:
				ok=Game::IsWater(Game::GetCommandPos(),true);
				break;
		}			
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		PersonList gruppe(Caller->GetName());
		Person p;
		VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);

		bool we_taken=false;
		int anz_p=gruppe.GetNumPersons();
		Person wt;
		bool via_ts=(Input::LCtrlPressed() && childID==0) || !v.HasChild("pumpe");
		int pumpcode=120;
		char *code="wt";
	

		if (Target->GetType()!=ACTOR_VEHICLE && Game::IsWater(Game::GetCommandPos(),true))
		{
			pumpcode=113;
			wt=fwdv4::select_trupp(gruppe,0,false,v);
		} else
			wt=fwdv4::select_trupp(gruppe,1,false,v);

		if (via_ts)
			pumpcode++;
		if (wt.IsValid())
		{
			if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
			{
				GameObject t=bungarext::hierhin(Game::GetCommandPos());
				Target=&t;
			}
			wt.AssignCommand("ich_bin_nicht_frei");
			wt.PushActionExecuteCommand(ACTION_APPEND,"FwGeraet_raus",Target,pumpcode,false);
			wt.PushActionExecuteCommand(ACTION_APPEND,"ma_wasser",&v,1,false);
		}

		if (v.GetVehicleType()==VT_FIREFIGHTERS_DLK)
		{
			Person at=fwdv4::select_trupp(gruppe,1,true,v);
			if (at.IsValid())
				at.PushActionExecuteCommand(ACTION_APPEND,"EnterBasket",&v,0,true);
				at.PushActionExecuteCommand(ACTION_APPEND,"ma_wasser",&v,1,false);
		}
	}
};

object gf_v1 : CommandScript
{
	gf_v1()
	{
		// SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL|ACTOR_VEHICLE);
		SetIcon("1c");
		SetCursor("1c");
		SetGroupID(1);
		SetGroupLeader(false);
		SetPriority(98);
	}


	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Input::LShiftPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON)
			return false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			return v.IsFirefighter();
		} else
			return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"gf_verteiler",Target,1,Input::LCtrlPressed());
	}
};

object gf_v2 : CommandScript
{
	gf_v2()
	{
		//SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL|ACTOR_VEHICLE);
		SetIcon("2c");
		SetCursor("2c");
		SetGroupID(2);
		SetGroupLeader(false);
		SetPriority(99);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Input::LShiftPressed() && !Caller->HasCommand("tf");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			return v.IsFirefighter();
		} else
			return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"gf_verteiler",Target,2,Input::LCtrlPressed());
	}
};

object gf_v3 : CommandScript
{
	gf_v3()
	{
		// SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL|ACTOR_VEHICLE);
		SetIcon("3c");
		SetCursor("3c");
		SetGroupID(3);
		SetGroupLeader(false);
		SetPriority(100);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Input::LShiftPressed() && !Caller->HasCommand("sf") && !Caller->HasCommand("tf");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			return v.IsFirefighter();
		} else
			return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"gf_verteiler",Target,3,Input::LCtrlPressed());
	}
};

object gf_vb : CommandScript
{
	gf_vb()
	{
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL|ACTOR_VEHICLE);
		SetIcon("cbc");
		SetCursor("cbc");
		SetGroupID(4);
		SetGroupLeader(false);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Input::LShiftPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			return v.IsFirefighter();
		} else
			return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"gf_verteiler",Target,4,Input::LCtrlPressed());
	}
};

object gf_verteiler : CommandScript
{
	
	bool via_ts=false;

	gf_verteiler()
	{
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL|ACTOR_VEHICLE);
		SetIcon("verteiler");
		SetCursor("verteiler");
		SetGroupID(3);
		SetGroupLeader(true);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return !Input::LShiftPressed();
	}

	bool CheckPossible(GameObject *Caller)
	{
		return Caller->HasCommand("fuehrung");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if (Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON)
			return false;

		via_ts=childID>0 || Input::LCtrlPressed();

		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			return v.IsFirefighter();
		} else
			return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		bool zumischer=childID==20 || childID==-20;
		
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject o=bungarext::hierhin(Game::GetCommandPos());
			Target=&o;
		} else
			GameObject o(Target);

		bool bereit=Target->GetType() == ACTOR_VEHICLE && o.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER);

		if (bereit)
		{
			Vehicle v(Target);
		} else {
			VehicleList vl(Caller->GetName());
			Vehicle v=vl.GetVehicle(0);
		}

		via_ts=(via_ts || !v.HasChild("pumpe") || childID<0) && !bereit;

		PersonList gruppe(Caller->GetName());
		Person p=fwdv4::select_trupp(gruppe,6,false,v);
		Person ma=fwdv4::select_trupp(gruppe,0,false,v);
		bool autoerkunden=childID>0;

		System::Log("Verteiler vor %s %u %u %u",Caller->GetName(),int(via_ts),int(autoerkunden));

		if (p.IsValid())
		{
			p.AssignCommand("ich_bin_nicht_frei");
			int code;
			if (p.GetUserData()==100 || p.GetUserData()==200)
			{
				code=0;
				bereit=false;
			} else {
				if (via_ts)
					code=122;
				else if (bereit)
						code=200;
					else
						code=100;
			}
			p.PushActionExecuteCommand(ACTION_APPEND,"FwGeraet_raus",Target,code,false);
			if (bereit)
			{
				Caller->Deselect();
				p.Select();
			}
			p.AssignCommand("SetVerteiler");
			p.SetUserData(200);
		}

		if (childID==4)
		{
			Caller->PushActionExecuteCommand(ACTION_APPEND,"gf_rohrvor",Target,1,false);
			childID=2;
			if (Caller->HasCommand("sf"))
				childID--;
			else if (Caller->HasCommand("tf"))
				childID-=2;
		}
		
		
		for (int x=0;x<childID;x++)
			Caller->PushActionExecuteCommand(ACTION_APPEND,"gf_rohrvor",Target,10,false); // C-Rohr ohne Bungar

		if (!bereit)
			ma.PushActionExecuteCommand(ACTION_APPEND,"ma_pumpe",&v,2,false);

		via_ts=false;	
	}
};

object gf_rohrvor : CommandScript
{
	gf_rohrvor()
	{
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL|ACTOR_VEHICLE);
		SetIcon("loeschzug");
		SetCursor("loeschzug");
		SetGroupID(4);
		SetGroupLeader(true);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return !Input::LShiftPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			return v.IsFirefighter();
		} else
			return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		bool bereit=Target->GetType() == ACTOR_VEHICLE;
		int wentnahme;
		bool dobung=childID==0;
		bool getB=childID==1;
		bool schaum=childID==2;
		bool getsonder=getB || schaum;
		
		if (!Target->HasNamePrefix("bungar") && dobung)
			if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
			{
				GameObject t=bungarext::hierhin(Game::GetCommandPos());
				Target=&t;
			}

		if (bereit)
		{
			Vehicle v(Target);
		} else {
			VehicleList vl(Caller->GetName());
			Vehicle v=vl.GetVehicle(0);
		}


		PersonList gruppe(Caller->GetName());
		Person p=fwdv4::select_trupp(gruppe,7,true,v);

		// System::Log("Rohr vor %s",Caller->GetName());

		if (p.IsValid() && !p.HasCommand("ich_bin_nicht_frei"))
		{
			p.AssignCommand("ich_bin_nicht_frei");
			if (p.HasCommand("ChangeToMask"))
				p.PushActionExecuteCommand(ACTION_APPEND,"ChangeToMask",&v,1,false);
			if (!p.IsEquipped())
			{
				if (!getsonder)
					p.PushActionExecuteCommand(ACTION_APPEND,"GetFirehose",&v,0,false);
				else 
					p.PushActionExecuteCommand(ACTION_APPEND,"GetSonderRohr",&v,6+childID,false);
			}
			fwdv4::belege_trupp(gruppe,&p);
			p.PushActionExecuteCommand(ACTION_APPEND,"trupp_loeschen",Target,int(dobung),false);
		}		
	}
};

object trupp_loeschen : CommandScript
{
	trupp_loeschen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		VehicleList vl(Caller->GetName());
		Vehicle v;

		if (childID==1)
			if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
			{
				GameObject to=bungarext::hierhin(Game::GetCommandPos());
				Target=&to;
			} else
				GameObject to(Target);
		else
			GameObject to(Target);
		

		for (int i=0;i<vl.GetNumVehicles() && vl.GetVehicle(i)->GetUserData()!=100;i++);
		if (i<vl.GetNumVehicles())
			v=vl.GetVehicle(i);
		if (v.IsValid() && v.GetUserData()==100)
		{
			Person p(Caller);
			// System::Log("FWDV3 Trupp zum Loeschangriff");
			Caller->PushActionMove(ACTION_NEWLIST, &v, TARGET_FREE_CONNECTOR);
			Caller->PushActionCheckFreeConnector(ACTION_APPEND, &v);
			Caller->PushActionUseEquipment(ACTION_APPEND, &v, 0,0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"tank_anschluss",&v,childID,false);
			if (v.HasCommand("wama"))
			{
				Caller->AssignCommand("wama");
				p.EnableAutoTarget(true);	
			} else
				p.EnableAutoTarget(false);
			if (to.HasNamePrefix("bungar"))
				Caller->PushActionMove(ACTION_APPEND, Target->GetPosition());
			switch (childID)
			{
				case 1: // Monitor anschliessen
					break;
				case 2:	// Schaumrohr anschliessen
					break;
			}
			bungarext::debung (Target);
		} else {
			Caller->PushActionWait(ACTION_NEWLIST,3.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"trupp_loeschen",Target,childID,false);
		}
	}
};


object gf_rettung : CommandScript
{
	gf_rettung()
	{
		// SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL);
		SetIcon("mrettung");
		SetCursor("mrettung");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID())
			return false;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}

		bool nur_eh=Input::LCtrlPressed();
		Vector Ziel=Target->GetPosition();
		VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		int cid=0;
		bool hubrettung=((v.GetVehicleType() == VT_FIREFIGHTERS_DLK) && (Target->GetType() == ACTOR_OPEN_HOUSE));
		Vector TargetPos = Game::GetCommandPos();
		bool wasserrettung=Game::IsSubmergible(TargetPos);
		bool locked=false;
		bool feuer=false;
		bool braucht_wasser=false;
		bool trupp_vor_ort=false;
		Person gf(Caller);

		if (Target->GetType() == ACTOR_OPEN_HOUSE)
		{
			OpenHouse oh(Target);
			locked=oh.IsLocked();
			feuer=oh.IsBurning() || oh.IsBurningInside();
			braucht_wasser=feuer && oh.HasGroundEntrance();
			if (braucht_wasser && !locked)
			{
				PersonList ep=oh.GetSquadPersonsInside();
				Person *tr;
				for (int sq=0;sq<ep.GetNumPersons() && !trupp_vor_ort;sq++)
				{
					// System::Log("Rettung Squad im Hause %u von %u",sq,ep.GetNumPersons());
					tr=*ep.GetPerson(sq);
					trupp_vor_ort=tr->IsEquipped() && tr->GetEquipment()==EQUIP_FIREHOSE;
				}
				if (!trupp_vor_ort)
				{
					Game::ShowHelpTextWindow("WIB_EL_KEINERETTUNG");
					return; // unsauber aber hilfreich
				}
			}
		}

		if (wasserrettung)
			cid=3;
		else if (hubrettung)
			{
				OpenHouse oh(Target);
				hubrettung=!oh.HasGroundEntrance();
				if (hubrettung)
					cid=2;
			}
		else 
			System::Log("Rettung an Land EH %u",int (nur_eh));

		bool e_pa=Caller->HasCommand("einsatz_pa") || Input::LShiftPressed() || gf.GetPersonType()==PT_FIREFIGHTER_MASK || feuer;
		bool e_csa=Caller->HasCommand("einsatz_csa") || gf.GetPersonType()==PT_FIREFIGHTER_ABC;
		if (e_pa && !hubrettung)
			cid=1;
		if (e_csa && !hubrettung)
			cid=4;

		if (e_pa && Caller->HasCommand("ChangeToMask"))
			Caller->PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToMask",&v,0,false);
		else 
			if (e_csa && Caller->HasCommand("ChangeToABC"))
				Caller->PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToABC",&v,0,false);
			else
				Caller->PushActionWait(ACTION_NEWLIST,0.1f);

		if (!wasserrettung)
		{
			Game::FindFreePosition(Caller,Ziel,100);
			Caller->PushActionMove(ACTION_APPEND,Ziel,true);
			Caller->PushActionWait(ACTION_APPEND,5.0);
		}
		if (hubrettung)
		{
			if (v.IsInstalled())
			{
				if (v.IsUplifted() || v.IsUplifting())
					v.PushActionBasketDown(ACTION_NEWLIST, Vector(0.f, 0.f, 0.f));
			} else {
				v.PushActionWait(ACTION_NEWLIST,5.0);
				Vector TargetPos = Target->GetTargetPoint(Caller, TARGET_ENTRY_WINDOW_PARKING);
			    	v.PushActionMove(ACTION_APPEND, TargetPos);
				v.PushActionInstall(ACTION_APPEND, Target);
				v.PushActionExecuteCommand(ACTION_APPEND,"gf_hubrettung_start",Target,0,nur_eh);
			}
		} else if (!wasserrettung && (!braucht_wasser || trupp_vor_ort))
			Caller->PushActionExecuteCommand(ACTION_APPEND,"gf_rettung_start",Target,cid,nur_eh);

		PersonList gruppe(Caller->GetName());
		Person p;
		bool axt_taken=!locked;

		for (int i=0; i<gruppe.GetNumPersons();i++)
		{
			p=gruppe.GetPerson(i);
			if(!p.HasCommand("fuehrung") && !p.IsLinkedWithPerson() && !p.IsInjured() && !p.IsCarryingPerson() && !p.IsEquipped())
			{
				if (e_pa && p.HasCommand("ChangeToMask"))
					p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToMask",&v,0,false);
				else 
					if (e_csa && p.HasCommand("ChangeToABC"))
						p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToABC",&v,0,false);
					else if (wasserrettung && p.HasCommand("ChangeToDiver"))
						p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToDiver",&v,0,false);
						else p.PushActionWait(ACTION_NEWLIST,0.1f);

				if (p.GetEnteredCarID()>-1)
					p.PushActionLeaveCar(ACTION_INSERT,&v);

				if (!axt_taken)
				{
					p.PushActionExecuteCommand(ACTION_APPEND,"GetAxe",&v,1,false);
					p.PushActionExecuteCommand(ACTION_APPEND,"UseAxe",Target,-1,true);
					axt_taken=true;
				}
			}
		}
	}
};

object gf_rettung_start : CommandScript
{

	bool nur_eh=false;

	gf_rettung_start()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		nur_eh=true;	
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int cid)
	{
		PersonList gruppe(Caller->GetName());
		int zug=Caller->GetUserData();
		char * fms="            ";
		char * format[]="%uFPS";
		int j=snprintf(fms,12,format,zug);
		GameObjectList ol(fms);
		if (ol.GetNumObjects()>0)
			int ps=ol.GetObject(0)->GetID();
		else
		{
			VehicleList psl(Caller->GetName());
			int ps=psl.GetVehicle(0)->GetID();
		}

		Person p;
		int y=0;
		int i=0;
		bool e_pa=(cid==1);
		bool e_csa=(cid==4);
		bool im_haus=(Target->GetType()==ACTOR_OPEN_HOUSE);
		int n;

		if (im_haus)
		{
			OpenHouse oh(Target);
			PersonList triage=oh.GetNonSquadPersonsInside();
			n=triage.GetNumPersons();
			Person pat;
		} else {
			GameObjectList triage=Caller->GetObjectsInRange(700,ACTOR_PERSON);
			n=triage.GetNumObjects();
		}

		for (y=0; ((i<gruppe.GetNumPersons()) && (y<n));y++)
		{
			if (im_haus)
				pat=triage.GetPerson(y);
			else
				Person pat(triage.GetObject(y));
			
			p=gruppe.GetPerson(i);
			if(!p.HasCommand("fuehrung") && !p.IsLinkedWithPerson() && !p.IsInjured() && !p.IsCarryingPerson())
			{
				if ((e_pa && (p.GetPersonType() != PT_FIREFIGHTER_MASK)) || (e_csa && (p.GetPersonType() != PT_FIREFIGHTER_ABC)) || (p.IsEquipped() && p.GetEquipment()!=EQUIP_FIREAXE))
				{
					p.PushActionWait(ACTION_APPEND,1.0f);
					y--;
					i++;
				}
				else 
				{
					if (pat.GetRole() == ROLE_ANIMAL)
						pat.PushActionDeleteOwner(ACTION_NEWLIST);
					else if (pat.IsInjured() && !pat.IsCarried() && !pat.HasCommand("ich_bin_nicht_frei") && pat.GetFlags()!=8448)
					{
						if (pat.GetEnteredHouseID()<1 || im_haus)
						{
							pat.AssignCommand("ich_bin_nicht_frei");
							p.PushActionExecuteCommand(ACTION_APPEND,"gf_rettung_pat",&pat,ps,nur_eh);
						}
						i++;
					}
					
				}
			} else {
				i++;
				y--;
			}
		}

		if (y<n)
			Mission::PlayHint("WIB_MEHR_OPFER");
		nur_eh=false;
	}
};

object gf_hubrettung_start : CommandScript
{
	bool nur_eh=false;

	gf_hubrettung_start()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		nur_eh=true;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		OpenHouse oh(Target);
		PersonList gruppe(Caller->GetName());
		GameObjectList triage;
		Person p;
		int i=0;
		bool im_korb=false;
		bool e_pa=true;
		bool feuer=oh.IsBurning() || oh.IsBurningInside();

		for (i=0; ((i<gruppe.GetNumPersons()) && !im_korb);i++)
		{
			p=gruppe.GetPerson(i);
			if (!p.HasCommand("fuehrung") && !p.IsLinkedWithPerson())
			{
				if (e_pa && p.HasCommand("ChangeToMask") && feuer) 
				{
					p.PushActionWait(ACTION_APPEND,1.0f);
				}
				else 
				{
					im_korb=true;
					p.PushActionMove(ACTION_NEWLIST, Caller, TARGET_DLK_BASKET_BASE);
					p.PushActionEnterBasket(ACTION_APPEND, Caller);
				}
			} 
		}
		nur_eh=false;
	}
};

object gf_rettung_pat : CommandScript
{
	
	bool nur_eh=false;

	gf_rettung_pat()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		nur_eh=true;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Actor a=Game::GetActor(childID);
		GameObject v(&a);
		Vector Ziel;
		Person Pat(Target);
		
		if (Pat.IsFlagSet(OF_BLOCKED))
		{
			nur_eh=true;
		}

		Caller->SetCommandable(true);
		Caller->PushActionMove(ACTION_APPEND,Target,TARGET_TREATMENT);
		Caller->PushActionTurnTo(ACTION_APPEND,Target);
		if (!Pat.HasCommand("blutung") && !Pat.IsHidden() && !nur_eh)
		{
			Caller->PushActionLift(ACTION_APPEND,Target);
			if (Pat.GetEnteredHouseID()!=-1)
			{
				Actor ha=Game::GetActor(Pat.GetEnteredHouseID());
				OpenHouse oh(&ha);
				Vector tuer = oh.GetEntrancePosition(true);
				Caller->PushActionMove(ACTION_APPEND,tuer,true);
				Caller->PushActionLeaveHouse(ACTION_APPEND,&ha);
			}
			Caller->PushActionMove(ACTION_APPEND,&v,TARGET_ANY);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"UnloadPerson",Target,1,false);
		} else {
			Pat.SetFoundByDog(true);
			Pat.PushActionAppear(ACTION_NEWLIST,0.1);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"RDVersorgt",Target,1,false); // erste Hilfe vor Ort
			Pat.AssignCommand("ich_bin_nicht_frei");
		}
		nur_eh=false;
	}
};

object gf_tec_rettung : CommandScript
{
	gf_tec_rettung()
	{
		// SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_VIRTUAL);
		SetIcon("techrett");
		SetCursor("techrett");
		// SetGroupID(2);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_VEHICLE || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON)
			return false;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		if (Target->GetType()==ACTOR_FLOOR || Target->GetType()==ACTOR_STREET)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}
		Vector Ziel=Target->GetPosition();
		VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		Vector TargetPos = Target->GetPosition();
		Person gf(Caller);
		bool wasser_rettung=Game::IsSubmergible(TargetPos);
		bool e_pa=Caller->HasCommand("einsatz_pa") || Input::LShiftPressed() || gf.GetPersonType()==PT_FIREFIGHTER_MASK;
		bool e_csa=Caller->HasCommand("einsatz_csa") || gf.GetPersonType()==PT_FIREFIGHTER_ABC;
		bool e_wasser=(Caller->HasCommand("einsatz_wasser") || wasser_rettung);

		PersonList gruppe(Caller->GetName());
		int gn=gruppe.GetNumPersons();
		bool isStaffel=gn>3;
		bool TakeLiMa;
		bool TecRetter;
		Person p;
		Person sich;

		p=fwdv4::select_trupp(gruppe,7,false,v);
		if (p.IsValid())
		{
			p.AssignCommand("ich_bin_nicht_frei");
			if (e_pa && p.HasCommand("ChangeToMask"))
				p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToMask",&v,0,false);
			else 
				if (e_csa && p.HasCommand("ChangeToABC"))
					p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToABC",&v,0,false);
				else p.PushActionWait(ACTION_NEWLIST,0.1f);
			p.PushActionExecuteCommand(ACTION_APPEND,"GetShears",&v,0,true);
		}

		sich=fwdv4::select_trupp(gruppe,7,false,v);
		if (sich.IsValid())
		{
			sich.AssignCommand("ich_bin_nicht_frei");
			if (e_wasser)
				sich.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToDiver",&v,0,false);
			else if (v.HasChild("schnella"))
			{
				sich.PushActionExecuteCommand(ACTION_APPEND,"ma_pumpe",&v,0,false);
				sich.PushActionExecuteCommand(ACTION_APPEND,"FwGeraet_raus",&v,105,false);						
			} else {
				sich.PushActionExecuteCommand(ACTION_APPEND,"GetExtinguisher",&v,0,true);
			}
		}

		p=fwdv4::select_trupp(gruppe,0,false,v);
		if (p.IsValid())
		{
			p.AssignCommand("ich_bin_nicht_frei");
			if (!wasser_rettung)
			{
				if (isStaffel)
					p.PushActionWait(ACTION_NEWLIST,0.1f);
				p.PushActionExecuteCommand(ACTION_APPEND,"FwGeraet_raus",Target,104,true);
			 	p.PushActionWait(ACTION_APPEND,2.0f);
				p.PushActionExecuteCommand(ACTION_APPEND,"gf_tec_rettung_start",&sich,0,false);
			}
		}
	}
};

object gf_tec_rettung_start : CommandScript
{
	gf_tec_rettung_start()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		PersonList gruppe(Caller->GetName());
		GameObjectList triage;
		VehicleList equip(Caller->GetName());
		Person p;
		Person sich(Target);
		bool weiter=true;
		int y=0;
		int i=0;
		
		//System::Log("Tec Rettung starten");

		bool e_pa=Caller->HasCommand("einsatz_pa");
		bool e_csa=Caller->HasCommand("einsatz_csa");

		for (i=0;i<equip.GetNumVehicles();i++)	
			if (equip.GetVehicle(i)->GetUserData()==104)
				Person LiMa(equip.GetVehicle(i));

		triage=Caller->GetObjectsInRange(800,ACTOR_VEHICLE);
		i=0;
		for (y=0; ((i<gruppe.GetNumPersons()) && (y<triage.GetNumObjects()));y++)
		{
			Vehicle vu(triage.GetObject(y));
			p=gruppe.GetPerson(i);
			//System::Log("Tec rettung %s %u",p.GetName(),i);
			if (p.GetEquipment() == EQUIP_SHEARS)
			{
				if ((e_pa && p.HasCommand("ChangeToMask")) || (e_csa && p.HasCommand("ChangeToABC")))
				{
					p.PushActionWait(ACTION_APPEND,1.0f);
					y--;
					i++;
				} else {
					if (!vu.HasCommand("ich_bin_nicht_frei"))
					{
						vu.AssignCommand("ich_bin_nicht_frei");
						if (vu.HasEnclosedPerson() && !vu.IsInsideWater() && !vu.IsUplifted())
						{
							sich.PushActionMove(ACTION_NEWLIST,&vu,TARGET_ENGINE);
							p.PushActionExecuteCommand(ACTION_APPEND,"UseShears",&vu,1,false);
							Caller->PushActionTurnTo(ACTION_INSERT,&vu);
							Caller->PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"drehen",&LiMa,90,false);
							i++;
						}
					}
				}
			} else {
				y--;
				i++;
			}
		}
		Caller->PushActionWait(ACTION_APPEND,10.0);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"gf_tec_rettung_start",Caller,0,false);
	}
};

object gf_gefahr : CommandScript
{
	gf_gefahr()
	{
		SetIcon("gefahr");
		SetCursor("gefahr");
		SetRestrictions(RESTRICT_SELFEXECUTE);
		// SetGroupID(2);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Caller->GetID()==Target->GetID();	
	}

	void PushActions(GameObject *Caller, Actor *Target, int cid)
	{
		PersonList gruppe(Caller->GetName());
		VehicleList vl(Caller->GetName());
		Person p;
		Vehicle v=vl.GetVehicle(0);
		for (int i=gruppe.GetNumPersons()-1; i > -1; i--)
		{
			p=gruppe.GetPerson(i);
			if (!p.IsInjured() && !p.IsDead() && !p.IsCarried() && p.GetEnteredCarID() == -1)
			{
				p.PushActionMove(ACTION_NEWLIST,&v,TARGET_PASSENGERDOOR);
				// if ((p.GetFirehoseID()!=0) && (p.GetUserData()!=105))
				//	p.PushActionExecuteCommand(ACTION_INSERT,"RemoveFirehose",Target,112,false);
			}
		}
	}
};

int erdcount;

object gf_erdung : CommandScript
{
	gf_erdung()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		PersonList gruppe(Caller->GetName());
		VehicleList vl(Caller->GetName());
		Vehicle v=vl.GetVehicle(0);
		GameObjectList triage(Target->GetName());
		Person p;
		int i=0;
		int t=3;
		GameObject erde;
		erdcount=0;

		for (i=gruppe.GetNumPersons()-1;i>=0 && erdcount<2;i--)
		{
			if (t>triage.GetNumObjects())
				t=0;
			else if (t==triage.GetNumObjects())
				t--;
			if (t<0) 
				t=0;
			p=gruppe.GetPerson(i);
			if (!p.HasCommand("fuehrung") && !p.IsLinkedWithPerson() && !p.IsInjured())
			{
				erde=triage.GetObject(t);
				t=t-3;
				p.PlaceObjectInRightHand("mod:Models/Objects/Equipment/erdungsstange.v3o");
				p.AssignCommand("fuehrung");
				p.PushActionMove(ACTION_NEWLIST, &erde, TARGET_ANY);
				if (p.GetEnteredCarID()>-1)
					p.PushActionLeaveCar(ACTION_INSERT,&v);
				p.PushActionExecuteCommand(ACTION_APPEND,"gf_erdung_anlegen",Target,0,false);
				erdcount++;
			} 
		}
	}
};

object gf_erdung_anlegen : CommandScript
{
	gf_erdung_anlegen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		erdcount--;
		if (erdcount==0)
		{
			Vehicle v(Target);
			v.PushActionExecuteCommand(ACTION_APPEND,"ggv_check",Caller,18,false);
		}
	}
};

class gf_tec : CommandScript
{

	Vector zielpos (Actor *host, Actor *client)
	{
		Vehicle transporter(host);
		Vehicle vehicle(client);
		float dx, dy, dz;
		Vector VehiclePos = transporter.GetPosition();
		Vector TargetPos;
		vehicle.GetLookatDir(dx, dy, dz);
		TargetPos = VehiclePos + transporter.GetLookatDir()*(vehicle.GetBoundingRadiusXY() + transporter.GetBoundingRadiusXY());
		return TargetPos;
	}

	void rausziehen(GameObject *Caller,Actor *Target)
	{
		Actor a=Game::GetActor(Caller->GetUserData());
		Vehicle v(&a);
		Vehicle asf(Caller);
		Vehicle test(Target);
		//System::Log("Object Pull Post Flag %u %s",test.GetFlags(),test.GetName());
	
			Vector pos=zielpos(Caller,&a);
			v.SetSpeed(1.5);
			v.PushActionMove(ACTION_NEWLIST,pos,true);
			if (asf.GetVehicleType()==VT_FIREFIGHTERS_ASF)
				v.PushActionMove(ACTION_INSERT,pos,true);
			Vehicle reset(Target);
			reset.ClearFlag(OF_PULLABLE);
	}

	void winde_abbauen(GameObject *Caller)
	{
		PersonList pl(Caller->GetName());
		Person p;
		for (int i=0;i<pl.GetNumPersons();i++)
			if (pl.GetPerson(i)->HasCommand("Geraet_abbauen"))
				p=pl.GetPerson(i);
		if (p.IsValid()) 
		{
			p.PushActionExecuteCommand(ACTION_NEWLIST,"Geraet_abbauen",Caller,0,false);
		}			
	}

	void winde_installieren (GameObject *Caller, Actor *Target, int childID)
	{
		if (childID>-1)
		{
			Caller->PushActionTurnTo(ACTION_INSERT,Target);
			Caller->PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"gf_winde",Target,-1,false);
		} else {
			Vehicle test(Target);
			//System::Log("Object Pull Flag  Winde Aufbauen %u",test.GetFlags(), test.GetName());
			PersonList gruppe(Caller->GetName());
			Vehicle v(Target);
			Person ma=fwdv4::select_trupp(gruppe,0,false,v);
			ma.AssignCommand("ich_bin_nicht_frei");
			Person at=fwdv4::select_trupp(gruppe,7,false,v);
			at.PushActionExecuteCommand(ACTION_APPEND,"ma_pumpe",Caller,1,false);
			at.PushActionTurnTo(ACTION_APPEND,Target);
			at.PushActionExecuteCommand(ACTION_APPEND,"FwGeraet_raus",Target,115,false);
			at.PushActionTurnTo(ACTION_APPEND,&ma);
			if (ma.IsEngineer())
				ma.PushActionRotateTarget(ACTION_APPEND,Caller,0,180.0,0,0.2);
			ma.PushActionExecuteCommand(ACTION_APPEND,"ma_pumpe",Caller,1,false);
			ma.PushActionExecuteCommand(ACTION_APPEND,"ma_winde_frei",Caller,0,false);				
			ma.PushActionExecuteCommand(ACTION_APPEND,"goaside",Caller,2,false);
			ma.PushActionTurnTo(ACTION_APPEND,Caller);
		}
	}
};

const int windegroup=10;

object gf_winde : CommandScript
{
	gf_winde()
	{
		SetIcon("winde");
		SetCursor("winde");
		SetGroupID(windegroup);
		SetGroupLeader(true);
	}

   	bool CheckGroupVisibility(GameObject *Caller)
   	{
		bool ok=Caller->IsChildEnabled("winde");
		return ok;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle o(Target);
		bool ok=(o.IsFlagSet(OF_RECOVERABLE) && Caller->GetID()!=Target->GetID());
		if (Target->GetType()==ACTOR_VEHICLE)
			ok=ok && !o.HasEnclosedPerson();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		gf_tec::winde_installieren (Caller, Target, childID);
	}
};

object gf_winde_stop : CommandScript
{

	Actor a;

	gf_winde_stop()
	{
		SetIcon("winde_stop");
		SetCursor("winde_stop");
		SetGroupID(windegroup);
		SetGroupLeader(false);
		SetPriority(100);
	}

   	bool CheckGroupVisibility(GameObject *Caller)
   	{
		bool ok=!Caller->IsChildEnabled("winde");
		if (ok) {
			a=Game::GetActor(Caller->GetUserData());
			Vehicle v(&a);
			ok=v.IsMoving() && v.IsPulling();
		}
		return ok;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		bool ok=true; // Target->GetID()!=Caller->GetID();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(&a);
		v.PushActionWait (ACTION_NEWLIST,0.1);		
	}
};

object gf_winde_pull : CommandScript
{

	Actor a;

	gf_winde_pull()
	{
		SetIcon("winde_zug");
		SetCursor("winde_zug");
		SetGroupID(windegroup);
		SetGroupLeader(false);
		SetPriority(100);
	}

   	bool CheckGroupVisibility(GameObject *Caller)
   	{
		bool ok=!Caller->IsChildEnabled("winde");
		if (ok) {
			a=Game::GetActor(Caller->GetUserData());
			Vehicle v(&a);
			ok=!v.IsMoving() && v.IsPulling();
		}
		return ok;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		bool ok=Target->GetID()!=Caller->GetID();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		gf_tec::rausziehen (Caller,Target);
	}
};

object gf_winde_weg : CommandScript
{

	gf_winde_weg()
	{
		SetIcon("winde");
		SetCursor("winde");
		SetGroupID(windegroup+1);
		SetGroupLeader(false);
		SetPriority(100);
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

   	bool CheckGroupVisibility(GameObject *Caller)
   	{
		bool ok=!Caller->IsChildEnabled("winde");
		if (ok) {
			Actor a=Game::GetActor(Caller->GetUserData());
			Vehicle v(&a);
			ok=!v.IsMoving() && v.IsPulling();
		}
		return ok;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		bool ok=Caller->GetID()==Target->GetID();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{	
		gf_tec::winde_abbauen (Caller);
	}
};

object fuehrung : CommandScript
{
	fuehrung()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object gf : CommandScript
{
	gf()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object me : CommandScript
{
	me()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object sf : CommandScript
{
	sf()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object tf : CommandScript
{
	tf()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object at : CommandScript
{
	at()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object wt : CommandScript
{
	wt()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object st : CommandScript
{
	st()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object tl : CommandScript
{
	tl()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}

};

object ma : CommandScript
{
	ma()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object zugfz : CommandScript
{
	zugfz()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};

object wassermarsch : CommandScript
{
	wassermarsch()
	{
		SetGroupID(20);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false;
	}
};


object gf_pa : CommandScript
{
	gf_pa()
	{
		SetValidTargets(ACTOR_VEHICLE);
		SetIcon("gruppepa");
		SetCursor("gruppepa");
		SetGroupID(5);
		SetPriority(100);
	}

	   bool CheckGroupVisibility(GameObject *Caller)
	   {
		return !Input::LCtrlPressed() && !Caller->IsFlagSet(FLAG_TL);
	   }

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;

		Vehicle v(Target);
		return v.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER) && v.IsFirefighter();
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);

		PersonList gruppe(Caller->GetName());
		Person p;
		bool isFz=Caller->GetType()==ACTOR_VEHICLE;
		int code=0;
		if (isFz)
			code=1;
		for (int i=0; (i<gruppe.GetNumPersons());i++)
		{
			p=gruppe.GetPerson(i);
			if (p.HasCommand("ChangeToMask") && !p.HasCommand("tl"))
			{
				p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToMask",Target,code,false);
				if (isFz)
				{
					p.PushActionLeaveCar(ACTION_INSERT,Caller);
					p.PushActionExecuteCommand(ACTION_APPEND,"EnterCar",Caller,0,false);
				} else 
					if (p.GetEnteredCarID()>-1)
					{
						Actor vec=Game::GetActor(p.GetEnteredCarID());
						p.PushActionLeaveCar(ACTION_INSERT,&vec);
					}
			}
		}
	}
};

object gf_csa : CommandScript
{
	gf_csa()
	{
		SetValidTargets(ACTOR_VEHICLE);
		SetIcon("gruppecsa");
		SetCursor("gruppecsa");
		SetGroupID(5);
		SetPriority(100);
	}

	   bool CheckGroupVisibility(GameObject *Caller)
	   {
		return Input::LCtrlPressed() && !Caller->IsFlagSet(FLAG_TL);
	   }

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
			return false;

		Vehicle v(Target);
		return v.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER) && v.IsFirefighter();
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);

		PersonList gruppe(Caller->GetName());
		Person p;
		bool isFz=Caller->GetType()==ACTOR_VEHICLE;
		int code=0;
		if (isFz)
			code=1;
		for (int i=0; (i<gruppe.GetNumPersons());i++)
		{
			p=gruppe.GetPerson(i);
			if (p.HasCommand("ChangeToABC") && !p.HasCommand("tl"))
			{
				p.PushActionExecuteCommand(ACTION_NEWLIST,"ChangeToABC",Target,code,false);
				if (isFz)
				{
					p.PushActionLeaveCar(ACTION_INSERT,Caller);
					p.PushActionExecuteCommand(ACTION_APPEND,"EnterCar",Caller,0,false);
				} else
					if (p.GetEnteredCarID()>-1)
					{
						Actor vec=Game::GetActor(p.GetEnteredCarID());
						p.PushActionLeaveCar(ACTION_INSERT,&vec);
					}
			}
		}
	}
};

object gf_gofmb : CommandScript
{
	gf_gofmb()
	{
		SetValidTargets(ACTOR_VEHICLE);
		SetIcon("sendto");
		SetCursor("sendto");
		SetGroupID(24);
		SetPriority(200);
	}

	   bool CheckGroupVisibility(GameObject *Caller)
	   {
		return true;
	   }

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if( Caller->GetID() == Target->GetID())
			return false;

		Vehicle v(Target);
		return v.HasChild("FMB");
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle v(Target);
		if (!v.IsFirefighter())
			v.SetVehicleRole(VT_FIREFIGHTERS_FMB);
		PersonList gruppe(Caller->GetName());
		Person p;
		for (int i=0; (i<gruppe.GetNumPersons());i++)
		{
			p=gruppe.GetPerson(i);
			p.PushActionMove(ACTION_NEWLIST,Target,TARGET_PASSENGERDOOR);
			p.PushActionExecuteCommand(ACTION_APPEND,"EnterCar",Target,0,false);
			if (p.GetEnteredCarID()>-1)
			{
				Actor vec=Game::GetActor(p.GetEnteredCarID());
				p.PushActionLeaveCar(ACTION_INSERT,&vec);
			}
		}
	}
};


object gf_bma_quittung : CommandScript
{
	gf_bma_quittung()
	{
		SetIcon("bma");
		SetCursor("bma");
		// SetGroupID(3);
	}

	   bool CheckGroupVisibility(GameObject *Caller)
	   {
		return true;

	   }

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		if (Target->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Target);
			if (Caller->HasCommand("fuehrung") && (v.GetVehicleType()==VT_THW_FGRR_RL))
			{
				if (v.IsSpecialLightEnabled())
					return true;
				else
					return false;
			}
			else
				return false;
		}
		else
			return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Caller->PushActionMove(ACTION_NEWLIST,Target,TARGET_ANY);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"wt_bma_quittung",Target,0,false);
	}
};

// TEL-Modul
//

object zugliste_fz : CommandScript
{
	zugliste_fz()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		fwdv4::zug_fzreg(Caller, Target,childID,0);
		if (Caller->HasNamePrefix("SEG"))
			fwdv4::zug_fzreg(Caller, Caller,1,2);
		// System::Log("Fz im Zug registrieren %s %u",Caller->GetName(),Target->GetID());
	}
};

object zugliste_fz_entfernen : CommandScript
{
	zugliste_fz_entfernen()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		fwdv4::zug_fzreg(Caller,Target, childID,1);
		// System::Log("Fz vom Zug deregistrieren %s %u",Caller->GetName(),Target->GetID());
	}
};

object zugliste_zugid : CommandScript
{
	zugliste_zugid()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		fwdv4::zug_fzreg(Caller,Target,childID,2);
	}
};

// TEL-Kommandos

object tl_abmarsch : CommandScript
{
	tl_abmarsch()
	{
		SetValidTargets(ACTOR_PERSON);
		SetCursor("abmarsch");
		SetIcon("abmarsch");
		SetPriority(500);
 		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int zugort)
	{ 
		zugort=fwdv4::fzort(Caller);
		// System::Log("TL Abmarsch befohlen");
		if (!Caller->IsFlagSet(FLAG_TL))
			fwdv4::zug_manipulation(0,Caller->GetUserData(),Caller->GetID(),zugort,Input::LCtrlPressed());
		else
			fwdv4::zug_manipulation(256,Caller->GetUserData(),Caller->GetID(),-1,Input::LCtrlPressed());
	}
};

object tl_gefahr : CommandScript
{
	tl_gefahr()
	{
		SetCursor("gefahr");
		SetIcon("gefahr");
		// SetPriority(2000);
 		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Caller->GetID()==Target->GetID();	
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int zugort=fwdv4::fzort(Caller);
		if (!Caller->IsFlagSet(FLAG_TL))
			fwdv4::zug_manipulation(3,Caller->GetUserData(),Caller->GetID(),zugort,false);
		else
			fwdv4::zug_manipulation(259,Caller->GetUserData(),Caller->GetID(),-1,false);
	}
};

object tl_funkfrei : CommandScript
{
	tl_funkfrei()
	{
		SetValidTargets(ACTOR_PERSON);
		SetCursor("keineinsatz");
		SetIcon("keineinsatz");
		SetPriority(90);
 		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int zugort=fwdv4::fzort(Caller);
		if (!Caller->IsFlagSet(FLAG_TL))
			fwdv4::zug_manipulation(1,Caller->GetUserData(),Caller->GetID(),zugort,false);
		else
			fwdv4::zug_manipulation(257,Caller->GetUserData(),Caller->GetID(),-1,false);
		// System::Log("zug zurueck");
	}
};

object tl_do_tel : CommandScript
{
	tl_do_tel()
	{
		SetIcon("tel_el");
		SetRestrictions(RESTRICT_SELFEXECUTE);
		SetGroupID(1);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL) && Caller->HasCommand("sofa");
	}

	bool CheckPossible(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Actor a=Game::GetActor(Caller->GetUserData());
		GameObject o(&a);
		o.SetSelectable(true);
		o.Select();
		Caller->Deselect();
		if (Game::IsMultiplayer())
			o.SetPlayerMP(Caller->GetPlayerMP());
		//System::Log("TEL funktionen an %s fuer %s",o.GetName(),Caller->GetName());
	}
};

object tl_take_fz : CommandScript
{
	tl_take_fz()
	{
		SetIcon("tel_el");
		SetCursor("cursor_selectiongroup01");
		SetRestrictions(ACTOR_VEHICLE);
		SetGroupID(2);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL);
	}

	bool CheckPossible(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Target->GetID()!=Caller->GetID();
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int code=4;
		if (Input::LShiftPressed())
			code++;
		fwdv4::zug_fzreg(Caller, Target,childID,code);
		//System::Log("TEL Fz übernehmen an %s fuer %s",Caller->GetName(),Target->GetName());
	}
};


object tl_rufe_fza : CommandScript
{
	tl_rufe_fza()
	{
		SetIcon("faz");
		SetRestrictions(RESTRICT_SELFEXECUTE);
		SetGroupID(7);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL) && Caller->HasCommand("sofa");
	}

	bool CheckPossible(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		GameObjectList ol("fza");
		GameObject o=ol.GetObject(0);
		o.Select();
		Caller->Deselect();
		if (Game::IsMultiplayer())
			o.SetPlayerMP(Caller->GetPlayerMP());
		o.SetUserData(Caller->GetUserData());
	}
};

object tl_pat_sammelstelle : CommandScript
{
	tl_pat_sammelstelle()
	{
		SetIcon("vsammel");
		SetCursor("vsammel");
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET );
	}

	bool CheckPossible(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int zug=Caller->GetUserData();
		char * fms="               ";
		char * format[]="%uFPS";
		int j=snprintf(fms,15,format,zug);
		Vector Pos=Game::GetCommandPos();
		GameObject v = Game::CreateObject("mod:Prototypes/Objects/Equipment/vsammel.e4p", fms);
		Game::FindFreePosition(&v, Pos, 35.0f);
		v.ClearFlags();
		v.SetPosition(Pos);
	}
};

object tl_bereitstelle : CommandScript
{
	tl_bereitstelle()
	{
		SetIcon("fsammel");
		SetCursor("fsammel");
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET );
	}

	bool CheckPossible(GameObject *Caller)
	{
		return Caller->IsFlagSet(FLAG_TL);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vector Pos=Game::GetCommandPos();
		int zug=Caller->GetUserData();

		Actor a=Game::GetActor(zug);
		if (a.IsValid())
		{
			GameObject v(&a);
			Game::FindFreePosition(&v, Pos, 35.0f);
			v.SetPosition(Pos);
			// Game::ExecuteCommand("zug_umleiten",&v);
		} else
			System::Log("passende EStelle nicht gefunden");
	}
};

object tl_aufsitzen : CommandScript
{
	tl_aufsitzen()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		fwdv4::zug_fzreg(Caller,Target,childID,3);
	}
};

object tl_rufe_ith : CommandScript
{
	tl_rufe_ith()
	{
		SetIcon("ith");
		SetCursor("ith");
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET );
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vector pos=Game::GetCommandPos();
		GameObject ithlanding=Game::CreateObject("mod:Prototypes/Objects/Missionspec/tutplane01.e4p",Caller->GetName());
		ithlanding.SetPosition(pos);
		ithlanding.AssignCommand("isith");
		ithlanding.SetTerrain(TERRAIN_SQUAD);
	}
};

object tl_vk : CommandScript
{
	tl_vk()
	{
		SetIcon("aufbau_vk");
		SetCursor("aufbau_vk");
		SetValidTargets(ACTOR_VEHICLE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Target->GetUserData()==103;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vehicle hier(Target);
		hier.AssignCommand("alarm_dummy");

		PersonList pl(Caller->GetName());
		VehicleList vl(Caller->GetName());
		Person p;
		EquipmentType eq;

		int func=0;
		for (int i=0;func<5;i++)
		{
			p=pl.GetPerson(i);
			if (!p.HasCommand("tl"))
				p.SetUserData(0);
			if (!p.HasCommand("tl_vk") && p.GetUserData()!=104)
			{
				switch (func)
				{
					case 1:
					case 2:
					case 3:
						p.PushActionMove(ACTION_NEWLIST,vl.GetVehicle(0),TARGET_EQUIPMENTDOOR);
						if (func==2)
							eq=EQUIP_REDIRECTSIGN;
						else
							eq=EQUIP_RIFLE;
						p.PushActionGetEquipment(ACTION_APPEND,vl.GetVehicle(0),eq);
					case 4:
						if (func==2)
							p.PushActionMove(ACTION_APPEND,vl.GetVehicle(vl.GetNumVehicles()-1),TARGET_ANY);
						else					
							p.PushActionMove(ACTION_APPEND,&hier,TARGET_ANY);
						break;
				}
				func++;
			}
		}
		Vehicle first;
		for (i=0;i<vl.GetNumVehicles();i++)
		{
			vl.GetVehicle(i)->PushActionWait(ACTION_NEWLIST,1000.0);
			if (vl.GetVehicle(i)->GetUserData()==103)
			{
				if (first.IsValid())
					vl.GetVehicle(i)->SetRotation(&first);
				else
					first=vl.GetVehicle(i);
			}
		}
	}	
};

const char *aggregat[3];
const char *aggregat[0]="pumpe";
const char *aggregat[1]="winde";
const char *aggregat[2]="pumpe";

object ma_pumpe : CommandScript
{

	ma_pumpe()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int agg)
	{
		bool found=false;
		if (agg>0)
		{
			Person p(Caller);
			Vehicle v(Target);
			found=!v.HasCommand("flf");
		} else {
			PersonList pl(Caller->GetName());
			VehicleList vl(Caller->GetName());
			Person p;
			Vehicle v=vl.GetVehicle(0);
			found=false;
				char * cmd="ma";
				if (pl.GetNumPersons()<4)
					cmd="gf";
				for (int i=0;i<pl.GetNumPersons() && !found;i++)
				{
					p=pl.GetPerson(i);
					found=p.HasCommand(cmd) && !p.IsInjured() && !p.IsDead();
				}
		}

		if (v.HasChild(aggregat[agg]) && found)
		{
			Vector mpos=v.GetChildPosition(aggregat[agg]);
			if (agg!=1)
				p.PushActionExecuteCommand(ACTION_INSERT,"tank_takt",&v,0,false);
			if (!v.HasCommand("flf"))
			{
				p.PushActionMove(ACTION_INSERT,mpos);
				p.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"grollo",&v,9,false);
				p.PushActionTurnTo(ACTION_INSERTAFTERFIRST,&v);
				if (p.GetEnteredCarID()!=-1)
				{
					Actor a=Game::GetActor(p.GetEnteredCarID());
					p.PushActionLeaveCar(ACTION_INSERT,&a);
				}			
			}
		}
	}
};

object ma_winde_frei : CommandScript
{

	ma_winde_frei()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int agg)
	{ 
		Caller->PushActionSwitchAnim(ACTION_INSERT,"useobjmid");
		Caller->PushActionWait(ACTION_INSERTAFTERFIRST,2.0);
		Vehicle v(Target);
		v.SetChildEnabled("winde1",false);
		v.SetChildEnabled("winde",false);
		v.SetChildEnabled("winde2",false);
		Caller->RemoveCommand("ich_bin_nicht_frei");
	}
};

object ma_wasser : CommandScript
{

	ma_wasser()
	{
		SetIcon("wasser");
		SetCursor("wasser");
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckPossible(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int onoff)
	{
		return Caller->GetID()==Target->GetID();
	}
	
	void pumpe_wasser (Vehicle pumpe, bool wamarsch)
	{
		
		//System::Log("Pumpe schalten %u %s",pumpe.GetUserData(),pumpe.GetName());
		if (wamarsch)
		{
			pumpe.AssignCommand("wama");
			if (!pumpe.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER))
				pumpe.EnableAutoTarget(true);
		} else {
			pumpe.RemoveCommand("wama");
			pumpe.EnableAutoTarget(false);
			pumpe.PushActionWait(ACTION_NEWLIST,0.1);
		}

		if (pumpe.GetNumUsedConnectors()>0)
		{
			Vector abc;
			Person fw;
			GameObject hydrant;
			GameObjectList pl=Game::GetGameObjects(TYPE_PERSON);
			// System::Log("%u Leitungen an %s, %u Feuerwehrleute",pumpe.GetNumUsedConnectors(),pumpe.GetName(),pl.GetNumObjects());
			bool rohr;
			Actor a;
			int gcode;

			for (int i=0;i<pl.GetNumObjects();i++)
			{
				Person fw(pl.GetObject(i));	
				// System::Log("%u. %s %u",i,fw.GetName(),fw.GetFirehoseID());
				if (fw.GetFirehoseID()!=0 && fw.GetUserData()!=120 & fw.GetUserData()!=110)
				{
					if (pumpe.IsUsingConnector(&fw))
					{
						// System::Log("An der Pumpe %u %u %u",pumpe.GetID(),fw.GetFirehoseID(),fw.GetUserData());
						hydrant=fw.GetHydrant();
						Vehicle hyd(&hydrant);
						hyd.GetUsedConnectorPosition(&fw,abc);
						a=Game::GetActor(fw.GetUserData());
						if (a.IsValid()) {
							GameObject o(&a);
							gcode=o.GetUserData();
						} else
							gcode=fw.GetUserData();
						rohr=gcode<100 || gcode>120 || gcode==105 || gcode==111;
						if (!rohr)
							fw.PushActionExecuteCommand(ACTION_INSERT,"ma_wasser",&fw,2-int(wamarsch),false);
						else {
							fw.EnableAutoTarget(wamarsch);
							if (!wamarsch) {
								fw.RemoveCommand("wama");
								fw.EnableAutoTarget(false);
								fw.PushActionMove(ACTION_NEWLIST,abc);
							} else {
								fw.AssignCommand("wama");
								fw.EnableAutoTarget(true);
								fw.PushActionMove(ACTION_INSERT,fw.GetPosition());
							}
						}
					}
				} 
			}
		}
	}

	void DLK_wasser(Vehicle pumpe, bool wamarsch)
	{
		if (pumpe.HasCommand("wama"))
		{
			pumpe.EnableAutoTarget(wamarsch);
			PersonList pl(pumpe.GetName());
			for (int i=0;i<pl.GetNumPersons();i++)
				if (pl.GetPerson(i)->IsInDLKBasket())
					pl.GetPerson(i)->AssignCommand("wama");
		}
	}

	void pumpe_schalten(GameObject *Caller, int onoff)
	{
		Person p(Caller);
		bool wamarsch=onoff==1;
	
		int i;
		if (wamarsch)
			Mission::PlayHint("WIB_MA_WAMA");
		else
			Mission::PlayHint("WIB_MA_WAHA");

		//System::Log("Wasser marsch/halt %s %u %u",Caller->GetName(),onoff,Caller->GetUserData());
		Vehicle pumpe;
		if (Caller->GetType()==ACTOR_PERSON)
		{
			Actor a=Game::GetActor(Caller->GetUserData());
			if (a.IsValid())
				Vehicle pumpe(&a);
			else if (Caller->HasCommand("ma")) {
				VehicleList vl(Caller->GetName());
				Vehicle pumpe=vl.GetVehicle(0);
			}
		} else
			Vehicle pumpe(Caller);

		if (pumpe.IsValid())
		{
			if (pumpe.GetVehicleType()==VT_FIREFIGHTERS_DLK)
				DLK_wasser(pumpe,wamarsch);
			else
				pumpe_wasser(pumpe,wamarsch);
			VehicleList vl(pumpe.GetName());
			int code;
			if (pumpe.IsFlagSet(OF_HAS_FIRE_EXTINGUISHER))
				for (i=1;i<vl.GetNumVehicles();i++)
				{
					code=vl.GetVehicle(i)->GetUserData();	
					if (code==105 || code==150)
						pumpe_schalten(vl.GetVehicle(i),wamarsch);
				}
		}		
	}

	void show_pumpenstand(GameObject *Caller)
	{
		char *id="          ";
		snprintf(id,10,"PU%u",Caller->GetID());
		//System::Log("Pumpenstand %s %u %s %u",id,Caller->GetID(),Caller->GetName(),Caller->GetUserData());
		PersonList pl(id);
		if (pl.GetNumPersons()>0)
		{
			Caller->Deselect();
			//System::Log("Caller deselektiert");
			pl.GetPerson(0)->Select();
			pl.GetPerson(0)->SetPlayerMP(Caller->GetPlayerMP());
			//System::Log("Pumpenstand selektiert %s",pl.GetPerson(0)->GetName());
		}
	}

	void PushActions(GameObject *Caller, Actor *Target, int onoff)
	{
		bool ls=Input::LShiftPressed();
		bool lc=Input::LCtrlPressed();
		GameObject p(Caller);

		if (onoff==0)
			onoff=int(lc)*2+int(ls)*1;
		else
			if (Caller->GetType()!=ACTOR_VEHICLE)
				GameObject p(Target);

		if (onoff>0)
			pumpe_schalten(&p,onoff);
		else if (Caller->GetType()==ACTOR_VEHICLE)
			show_pumpenstand(Caller);
	}
};



object trauma_ende : CommandScript
{
	trauma_ende()
	{
		SetIcon("station");
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		PersonList pl(Caller->GetName());
		for (int x=0;x<pl.GetNumPersons();x++)
		{
			pl.GetPerson(x)->PushActionDeleteOwner(ACTION_NEWLIST);	
		}
		VehicleList vl(Caller->GetName());
		vl.GetVehicle(0)->PushActionExecuteCommand(ACTION_NEWLIST,"Statussenden",Caller,2,false);
		vl.GetVehicle(0)->PushActionDeleteOwner(ACTION_APPEND);
	}
};

int fzr [500][4];


class fwdv4 : CommandScript
{ 
	Person select_trupp(PersonList gruppe,int funk, bool e_pa, Vehicle v)
	{
		// Funktionen : 
		// 0. Maschinist suchen
		// 1. Wasserentnahme
		// 6. Verteiler setzen
		// 7. n. Angriffstrupp suchen
		// 10. Verteilersetzer finden
		
		Person p;
		Person t;
		bool found=false;
		int max=gruppe.GetNumPersons();
		int wert=9;
		int val=999;
		bool valid;
		
		// System::Log("FWDV4 : Trupp suchen Code %u",funk);

		for (int i=0;i<max;i++)
		{
			t=gruppe.GetPerson(i);
			valid=!t.IsEquipped() && !t.HasCommand("ich_bin_nicht_frei") && t.IsIdle();
			bool asf=t.IsEngineer();
			
			switch (funk)
			{
				case 0:
					found=t.HasCommand("ma") || t.HasCommand("tf") || asf;
					val=1;
					break;
				case 1:
					found=t.HasCommand("at") || t.HasCommand("st") || t.HasCommand("wt") || t.HasCommand("ma") || t.HasCommand("tf") || asf;
					if (found)
						if (t.HasCommand("wt"))
							val=4;
						else if (t.HasCommand("st"))
								val=5;
							else if (t.HasCommand("at"))
									val=6;
								else val=8;
					else val=999;
					break;
				case 2:
					found=t.HasCommand("st");
					break;
				case 3:
					found=t.HasCommand("at");
					break;
				case 6: // wer setzt verteiler ?
					if ((t.GetUserData()==100||t.GetUserData()==200) && t.IsEquipped())
					{
						// System::Log("Verteiler man gefunden mit Verteiler");
						found=true;
						valid=true;
						val=1;
					} else {
						found=t.HasCommand("at") || t.HasCommand("st") || t.HasCommand("me");
						if (found)
							if (t.HasCommand("st"))
								val=6;
							else if (t.HasCommand("me"))
									val=5;
								else if (t.HasCommand("at"))
										val=4;
									else val=8;
						else val=999;
					}
					break;
				case 7: // finde 1.2.3 Angriffstrupp
					found=t.HasCommand("at") || t.HasCommand("wt") || t.HasCommand("st") || asf;
					if (found)
					{
						if (t.HasCommand("at"))
							val=4;
						else if (t.HasCommand("wt"))
								val=5;
							else if (t.HasCommand("st"))
									val=6;
								else 	if (asf)
										val=1;
									else 
										val=10;
						if (t.IsEquipped() && t.GetEquipment()==EQUIP_FIREHOSE && t.GetFirehoseID()==0)
						{
							val=val-3;
							valid=!t.HasCommand("ich_bin_nicht_frei");
						}
					} else val=999;
					break;
				case 10:
					found=t.GetUserData()==100;
					break;
			}	

			found=found && valid && !t.IsInDLKBasket(); 

			// System::Log("FWDV4 Auswahl gueltig %u Ausruestung %u Wert %i",int(found),int(t.IsEquipped()),val);
	
			if (found && wert>val)
			{
				p=t;
				wert=val;
			}
		}
		if (p.IsValid() && p.GetEnteredCarID()>-1)
		{
			Actor a=Game::GetActor(p.GetEnteredCarID());
			p.PushActionLeaveCar(ACTION_NEWLIST,&a);
		} else
			p.PushActionWait(ACTION_NEWLIST,0.1);
		if (e_pa && p.HasCommand("ChangeToMask"))
			p.PushActionExecuteCommand(ACTION_APPEND,"ChangeToMask",&v,0,false);
		return p;	
	}

	void belege_trupp(PersonList gruppe,Person *p)
	{
		int n=gruppe.GetNumPersons();
		Person *px;
		bool found=false;

		p->AssignCommand("ich_bin_nicht_frei");
	
		for (int i=0;i<n && !found;i++)
		{
			px=gruppe.GetPerson(i);
			if (p->HasCommand("at"))
				found=px->HasCommand("at");
			else 	if (p->HasCommand("wt"))
					found=px->HasCommand("wt");
				else found=px->HasCommand("st");
			found=found && p->GetID()!=px->GetID();
		}
		if (found)
			px->AssignCommand("ich_bin_nicht_frei");
	}
	
	void fz_funkfrei(Vehicle v)
	{
		if (v.IsCurrentAction("EActionFindPath"))
		{
			v.PushActionExecuteCommand(ACTION_NEWLIST,"aufsitzen",&v,0,false);
		} else {
			int lp=1;
			if (v.GetVehicleType() == VT_AMBULANCE_RTW)
				lp=2;
			if ((v.GetFreePassengers()<lp) && (v.GetNumTransported()==0))
			{
				v.PushActionExecuteCommand(ACTION_NEWLIST,"funkfrei",&v,0,false);
			}
		}
	}

	void sturm_vorbereiten (Vehicle v)
	{
		PersonList pl(v.GetName());
		for (int i=0;i<pl.GetNumPersons();i++)
		{
			Person p=pl.GetPerson(i);
			if (p.GetPersonType()==PT_SHOOTER)
			{
				p.PushActionEquipWeapon(ACTION_NEWLIST,true);
				if (p.GetEnteredCarID()>1)
				{
					Actor car=Game::GetActor(p.GetEnteredCarID());
					p.PushActionLeaveCar(ACTION_INSERT,&car);
				}
				p.Select();
			}
		}
	}

	void pol_zugriff(Vehicle v,Actor haus)
	{
		PersonList pl(v.GetName());
		OpenHouse oh(&haus);
		PersonList al=oh.GetNonSquadPersonsInside();
		int n=al.GetNumPersons()-1;	
		bool gotone=false;
		Person susp;
		int q;
	
		for (int i=0;i<pl.GetNumPersons();i++)
		{
			Person p=pl.GetPerson(i);
			if (p.GetPersonType()==PT_SHOOTER || p.GetPersonType()==PT_POLICEMEN)
			{
				if (!p.IsEquipped() && !p.HasCommand("fuehrung"))
				{
					// System::Log("Zugriff jetzt");
					p.PushActionWait(ACTION_NEWLIST,i*0.7);
					if (p.GetEnteredCarID()>1)
					{
						Actor car=Game::GetActor(p.GetEnteredCarID());
						p.PushActionLeaveCar(ACTION_APPEND,&car);
					}
					if (n>=0)
					{
						gotone=false;
						for (q=n;q>=0 && !gotone;q--)
						{
							susp=al.GetPerson(q);
							gotone=(!p.IsArrested() && !p.IsCarried() && !p.IsInjured() && !p.IsDead() && p.GetUserData()!=40);
							if (gotone)
							{
								susp.SetUserData(40);
								// System::Log("Festnehmen %s",susp.GetName());
								p.PushActionExecuteCommand(ACTION_APPEND,"Arrest",&susp,0,false);
							}
						}
						n=q;
					}
				}
			}
		}
	}

	// Verbandmanagement via Array-Liste statt Merkerobjekten
	// -> Verband-ID = Object-ID des EStelle-Objektes (bisheriges Konzept), besser wäre Object-ID Verbandsführer > dann Baumstruktur möglich
	// -> bisher pro Einheit zwei Objekte -> Name ZugID Speichert FzID und Name FzID speichert zugeordneten Zug
	// jetzt mehrspaltiges Integer-Array :
	// Spalte 0 : FzID (0 = freie Zeile)
	// Spalte 1 : verbandID (0 = keinem Verband zugeteilt)
	// Spalte 2 : ggf ID des zuständigen Unterführers (zur Unterscheidung einzelner Züge an Grossschadenlagen)

	int fzr_get (int ziel, int s)
	{
		for (int i=499;i>-1 && fzr[i][s]!=ziel;i--);
		//System::Log("FZR GET %u Sp %u Erg %u",ziel,s,i);
		return i;
	}

	int fzr_squad (int ziel, int s)
	{
		bool go=true;
		int sq=0;
		for (int i=499;i>-1 && go;i--)
			if ((fzr[i][1]==ziel) && (fzr[i][3]==1)) { 
				// System::Log ("Squad search Idx %u CountDown %u SquadCode %u SqadMem %u",i,s,fzr[i][2],sq);
				s--;
				go=s>0;
				sq=i;

			};
		return sq;
	}

	int fzid(Actor *Caller)
	{
		const char * fz;
		fz=Caller->GetName();
		int id=int(fz[11])-32;
		if (id<0)
		{
			id+=256;
		}
		return id;
	}

	int fzort(Actor *Caller)
	{
		const char * fz;
		fz=Caller->GetName();
		int id=int(fz[7])-32;
		return id;
	}

	void zug_fzreg (GameObject *Caller,Actor *Target, int cid, int function)
	{
		switch (function) {
			case 0:	
				//System::Log("TL Fz hinzufuegen %s",Caller->GetName());
				int x;
				// 1. Schritt : EStelle Object ID ist ZugID
				GameObject o(Target);
				if (o.HasCommand("lst_estelle"))
					x=Target->GetID();
				else
					x=Target->GetUserData();

				if (x>1000) // liegt eine ObjectID vor ?
				{
					int j=fzr_get(Caller->GetID(),0); // Finde registrierung
					if (j<0)
						j=fzr_get(0,0); // Finde freie Zeile
					fzr[j][0]=Caller->GetID();
					fzr[j][1]=x;
					fzr[j][2]=cid;
					if (Caller->IsFlagSet(FLAG_TL))
						fzr[j][3]=1;
					else
						fzr[j][3]=0;
					Caller->AssignCommand("zugfz");
					Caller->AssignCommand("tl_select");
					// System::Log("ZUGID Fzreg : Fz %s : %u an %u Zeile %u Code %u TL %u",Caller->GetName(),Caller->GetID(),x,j,cid,fzr[j][3]);
				} else
					System::Log("Kein gueltiges Zug Ziel Object %u %s",x,Target->GetName());

				break;
			case 1:	
				// System::Log("TL Fz entfernen %s",Caller->GetName());
				Caller->RemoveCommand("zugfz");
				Caller->RemoveCommand("tl_select");
				// 1. Schritt : Finde Object im Zug
				int j=fzr_get(Caller->GetID(),0);
				if (j>-1) {
					fzr[j][0]=0;
					fzr[j][1]=0;
				}
				//System::Log("TL Fz entfernen Ende");
				break;
			case 2:
				// 1. Schritt : Finde Object im Zug
				VehicleList vl(Caller->GetName());
				int j=fzr_get(vl.GetVehicle(0)->GetID(),0);
				bool doit=j>-1;
				// System::Log("ZUGID Fz %s %u %u",Caller->GetName(),Caller->GetID(),j);

				if (doit) {
					if (cid==1)
					{
						Vehicle v(Target);
						PersonList pl=v.GetPassengers();
						for (int i=0;i<pl.GetNumPersons();i++)
							pl.GetPerson(i)->SetUserData(fzr[j][1]);
						// System::Log("ZUGID %s Personal %u Leute setzen %u",Caller->GetName(),pl.GetNumPersons(),fzr[j][1]);
					} else
						Target->SetUserData(fzr[j][1]);
					// System::Log("ZUGID %s %u %u %u -> %s",Caller->GetName(),Caller->GetID(),fzr[j][0],fzr[j][1],Target->GetName());
				}
				break;
			case 3:
				int x=Caller->GetUserData();
				for (int i=499;i>-1;i--)	
					if (fzr[i][0]==x)
						fzr[i][0]=0;
				Vehicle ofz(Target);
				if (ofz.IsValid() && ofz.IsFlagSet(FLAG_TL))
				{
					ofz.ClearFlag(FLAG_TL);
				} else
					System::Log("Ungueltiges FuehrungsFz");

				break;
			case 4:
			case 5:
				// 1. Schritt : Finde Object im Zug
				int zug=fzr_get(Caller->GetID(),0);
				int est=fzr[zug][1];
				zug=fzr[zug][2];
				int j=fzr_get(Target->GetID(),0);
				if (j>-1) {
					fzr[j][1]=est;
					fzr[j][2]=zug;
				} else {
					int j=fzr_get(0,0);
					fzr[j][0]=Target->GetID();
					fzr[j][1]=est;
					fzr[j][2]=zug;
					fzr[j][3]=0;
				}
				break;

			case 10:
				int j=fzr_get(Caller->GetID(),0);
				Actor a=Game::GetActor(fzr [j][1]);
				bool goon=a.IsValid();
				if (goon)
					a=Game::GetActor(a.GetUserData());
				goon=a.IsValid();
				if (!goon) {
					System::Log("Kein Gültiger EL gefunden !");
					return;
				}
				Caller->Deselect();
				if (Caller->IsFlagSet(FLAG_TL))
				{
					Person p(&a);
					if (p.GetEnteredCarID()<1)
						p.Select();
				} else {
					VehicleList vl(a.GetName());
					vl.GetVehicle(0)->Select();
				}
				break;

		}
	}

	void zug_manipulation (int befehl, int zug, int zf, int zugort, bool LCtrl)
	{
		Actor a;
		bool tel=(befehl&256)>0;
		befehl=befehl&255;
		bool gohome=befehl==0;
		bool funkfrei=befehl==1;
		bool select=befehl==2;
		bool gefahr=befehl==3;
		bool pol_sichern=befehl==100;
		bool pol_zugriff=befehl==101;
		bool localfz;
		bool allefz;
		int j;
		if (pol_zugriff)
			Actor haus=Game::GetActor(zugort);
		char *zsel="                                                                                                  ";
		char *buf="                                                                                                  ";

		// System::Log("ZugManipulation EStelle %u Ort %u Cmd %u TEL %u Switch %u",zug,zugort,befehl,int(tel),int(LCtrl));

		for (int x=499;x>-1;x--) 
		if (fzr[x][1]==zug)
		{
			j=fzr[x][0];
			if (zf!=j)
			{
				a=Game::GetActor(j);	
				Vehicle v(&a);
				localfz=!v.HasCommand("sofa") || gefahr;
				localfz=localfz && (fzr[x][2]==zugort);
							
				if (tel || localfz)
				{				
					// System::Log("ZugManipulation Fz %s",v.GetName());
					if (select) {
						v.Select();
						snprintf(buf,80,"%.*s",7,v.GetName());
						zsel=buf;
						// System::Log("ZugMani %s",buf);
					} else if (gefahr)
						{
							if (v.GetFreePassengers()>0)
								v.PushActionExecuteCommand(ACTION_NEWLIST,"gf_gefahr",&v,0,false);
						}
					else  if (funkfrei)
						fz_funkfrei(v);
					else if (gohome) {
						v.RemoveCommand("zugfz");
						if (!LCtrl || !v.IsPolice())
						{
							v.PushActionExecuteCommand(ACTION_NEWLIST,"aufsitzen",&v,0,false);
							fzr[x][1]=0;
						}
					} else if (pol_sichern) {
						if (v.HasNamePrefix("SEK"))
							sturm_vorbereiten(v);
					} else if (pol_zugriff) {
						pol_zugriff(v,haus);
					}
				}
			}
			if (tel && gohome)
			{
				fzr[x][0]=0;
				fzr[x][1]=0;
			}
		}
		// System::Log("zug zurueck");
		if (tel && gohome)
		{
			a=Game::GetActor(zug);
			if (a.IsValid())
			{
				GameObject o(&a);
				if (o.HasCommand("lst_estelle"))
					Game::RemoveGameObject(&o);
			}
		}

		if (select)
			Game::ShowHelpTextWindow(zsel);
	}
};

const int na_her=400;
const int rtw_her=600;

object gf_lage : CommandScript
{
	gf_lage()
	{
		SetIcon("lageerk");
		SetCursor("lageerk");
		SetValidTargets(ACTOR_FLOOR |  ACTOR_STREET |ACTOR_OPEN_HOUSE);
		SetPriority(2000);
	}

	bool CheckPossible(GameObject *Caller)
	{
		Person p(Caller);
		bool ok=!Caller->HasCommand("ma") && !Caller->HasCommand("me") && Input::LCtrlPressed() && !Input::LShiftPressed() && p.GetEquipment()!=EQUIP_ROADBLOCK;
		return ok;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		Person p(Caller);
		bool ok=true;
		if (Target->GetType()==ACTOR_OPEN_HOUSE)
			ok=true;
		else 
			ok=p.HasCommand("fuehrung") || p.HasCommand("DrawWeapon");
		ok=ok && !Game::IsWater(Game::GetCommandPos(),true);
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		int water=0;
		if (Input::LShiftPressed())
			water=1;
		if (Caller->GetType()==ACTOR_VEHICLE)
		{
			Vehicle v(Caller);
			PersonList pl(v.GetPassengers());
			GameObject *Caller(pl.GetPerson(0));
		}

		Vector ziel=Game::GetCommandPos();
		Game::FindFreePosition(Caller,ziel,100);

		switch (Target->GetType())
		{
			case ACTOR_VEHICLE:
				GameObjectList nb=Game::GetGameObjectsWithPrefix("FogOfDoc");
				//System::Log("Lage : Fogs of War : %u fuer %s",nb.GetNumObjects(),Caller->GetName());
				if (nb.GetNumObjects()==0)
					return; //evil aber effektiv
				else 
				{
					if (nb.GetObject(0)->IsInsideMap())
						Caller->PushActionLeaveCar(ACTION_NEWLIST,&v);
					else
						Game::RemoveGameObject(nb.GetObject(0));
				}
				break;
			case ACTOR_OPEN_HOUSE:
				Person p(Caller);
				Caller->PushActionMove(ACTION_NEWLIST,ziel);
				if (p.GetEnteredHouseID()<1) {
					if (p.GetFirehoseID()!=0)
						water=112;
					else
						water=0;
					Caller->PushActionExecuteCommand(ACTION_INSERT,"EnterHouse",Target,112,true);
				}
				water=0;
				break;
			default:
				Caller->PushActionMove(ACTION_NEWLIST,ziel);
				break;
		}
		Caller->PushActionExecuteCommand(ACTION_APPEND,"gf_lage_erkunden",Target,water,false);
	}
};

char * lage[25];

lage[0]="WIB_EL_LAGE";
lage[1]="WIB_EL_FEUER";
lage[2]="WIB_EL_FZ";
lage[3]="WIB_EL_INC";
lage[4]="WIB_EL_INJ";
lage[5]="WIB_EL_GGV";
lage[6]="WIB_EL_WASSER";
lage[7]="WIB_EL_WASFZ";
lage[8]="WIB_EL_BUILD";
lage[9]="WIB_EL_DLK";
lage[10]="WIB_EL_GGV_LECK";
lage[11]="WIB_EL_NONE";
lage[12]="WIB_EL_TAETER";
lage[13]="WIB_EL_WEAPON";
lage[14]="WIB_EL_STEINE";
lage[15]="WIB_EL_MOLOTOV";
lage[16]="WIB_EL_TRIAGE_ROT";
lage[17]="WIB_EL_TRIAGE_GELB";
lage[18]="WIB_EL_TRIAGE_GRUEN";
lage[19]="WIB_EL_TRIAGE_TOT";
lage[20]="WIB_EL_DRUNTER";

int kz[10];

kz[1]=33;
kz[2]=486;
kz[3]=20;
kz[4]=11;
kz[5]=86;
kz[6]=76;


object gf_lage_erkunden : CommandScript
{

	int msgcount=-1;
	char *msg[11];
	int q;
	bool lmsg=false;

	gf_lage_erkunden()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return ok;
	}

	void add_message(int lm, int anz, bool building,bool nonums)
	{	
		msgcount++;
		lmsg=lmsg || lm!=6;
		msg[msgcount]="                              ";
		char *build="                    ";
		char *buf="                           ";
		Game::GetGameString(lage[8],build,25);
		Game::GetGameString(lage[lm],buf,25);
		// System::Log("Add Msg %u : %s %s %u %u",lm,buf,build,anz,int(building));
		if (nonums)
			if (building)
				q=snprintf(msg[msgcount],30,buf,build);
			else
				q=snprintf(msg[msgcount],30,buf," ");
		else
			if (building)
				q=snprintf(msg[msgcount],30,buf,anz,build);
			else
				q=snprintf(msg[msgcount],30,buf,anz," ");
	}

	void meldung_abgeben(GameObject *Act)
	{
		// System::Log("Lagemeldung abgeben");
		char *fz="    ";
		snprintf(fz,4,"%s",Act->GetName());
		char *name="          ";
		char *mask="%s %s";
		if (Act->HasCommand("fuehrung"))
			if (Act->HasCommand("tl"))
				snprintf(name,7,mask,fz,"EL");
			else
				snprintf(name,7,mask,fz,"GF");
		else
			snprintf(name,7,mask,fz,"Tr");

		char * meldung="                                                                                                                                                                                                         ";
		char * mask="                         ";
		Game::GetGameString(lage[0],mask,28);
		if (!lmsg)
		{
			Game::GetGameString(lage[11],mask,28);
			snprintf(meldung,200,mask,name);
		} else
			snprintf(meldung,200,mask,name,msg[0],msg[1],msg[2],msg[3],msg[4],msg[5],msg[6],msg[7],msg[8],msg[9]);
		Game::ShowHelpTextWindow(meldung);
	}

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		bool autowater=childID==1;
		bool scout=childID==2;
		msgcount=-1;
		for (int x=0;x<10;x++)
			msg[x]=" ";
		Person lage(Caller);
		VehicleList lfl(Caller->GetName());
		Vehicle lf=lfl.GetVehicle(0);
		int verletzte=0;
		int eingeklemmte=0;
		int fz=0;
		int feuer=0;
		int aqua=0;
		int ggv=0;
		int taeter=0;
		int rot=0;
		int gelb=0;
		int gruen=0;
		int tot=0;
		int drunter=0;

		bool weapon=false;
		bool steine=false;
		bool molotov=false;
		
		bool SanD=false;
		bool Pol=false;
		bool Fw=false;


		switch (lage.GetBehaviour())
		{
			case BEHAVIOUR_SQUAD_RESCUE:
				SanD=true;
				break;
			case BEHAVIOUR_SQUAD_POLICE:
				Pol=true;
				break;
			case BEHAVIOUR_SQUAD_FIREFIGHTER:
				Fw=true;
				break;
		}

		// System::Log("Lagemeldung %s PT %u Fw %u Pol %u SanD %u Scout %u",lage.GetName(),int(lage.GetPersonType()), int(Fw),int(Pol),int(SanD),int(scout));

		bool imhaus=lage.GetEnteredHouseID()>1;
		bool gf=Caller->HasCommand("gf") || Caller->HasCommand("sf") || Caller->HasCommand("tf");
		bool tl=Caller->HasCommand("tl");
		GameObject *hydrant;
		GameObjectList ol;
		GameObject *obj;
		int hyddist=100000;
		bool leck=false;
		bool hashydrant=false;
		
		switch (Target->GetType())
		{
			case ACTOR_OPEN_HOUSE:
				ol=Caller->GetObjectsInRange(1500,ACTOR_PERSON|ACTOR_OPEN_HOUSE);
				break;
			default:
				ol=Caller->GetObjectsInRange(2100,ACTOR_OBJECT|ACTOR_VEHICLE|ACTOR_PERSON|ACTOR_HOUSE|ACTOR_OPEN_HOUSE);
				break;
		}
		
		imhaus=lage.GetEnteredHouseID()>1 || scout;
		if (imhaus && lage.GetFirehoseID()>0)
			lage.EnableAutoTarget(false);

		for (int i=0;i<ol.GetNumObjects();i++)
		{
			obj=*ol.GetObject(i);
			switch(obj->GetType())
			{
				case ACTOR_PERSON:				
					Person p(obj);
					if (p.GetFlags()!=8448 && (p.GetEnteredHouseID()==lage.GetEnteredHouseID() || (p.GetEnteredHouseID()==Target->GetID() && scout)))
					{
						if (p.IsInjured() || p.IsDead() || p.IsInsideWater())
						{
							verletzte++;
							if (p.HasCommand("na_cat")) {
								if (p.IsDead())
									tot++;
								else if (p.GetLife()<na_her)
									rot++;
								else if (p.GetLife()<rtw_her)
									gelb++;
								else gruen++;
							}
							if (SanD && p.HasCommand("na_cat"))
								p.PushActionExecuteCommand(ACTION_INSERT,"TriageKarte",&p,0,false);
						} else
							if (p.GetRole()==ROLE_GANGSTER)
							{
								taeter++;
								steine=steine || p.GetBehaviour()==BEHAVIOUR_GANGSTER_THROWSTONES;
								molotov=molotov || p.GetBehaviour()==BEHAVIOUR_GANGSTER_THROWMOLOTOV;
								weapon=weapon || p.GetEquipment()==EQUIP_PISTOL || p.GetEquipment()==EQUIP_RIFLE;
							}

						if (p.IsFlagSet(OF_BLOCKED))
							drunter++;
					}
					break;
				case ACTOR_VEHICLE:
					if (!obj->HasCommand("isbma") & !obj->HasCommand("aufsitzen")) {
						Vehicle v(obj);
						if (v.HasEnclosedPerson() || v.GetEnergy()<v.GetMaxEnergy() || v.IsSmoking() || (v.HasNamePrefix("ccar") && !v.IsHidden()))
							{ fz++;
								System::Log("Defektes FZ : %s",v.GetName()); }
						if (v.IsInsideWater())
							aqua++;
						if (v.IsSmoking())
							feuer++;
						if (v.HasEnclosedPerson() && !v.IsInsideWater())
							eingeklemmte++;
					}
				default:
					if (gf && obj->IsHydrant() && !obj->IsHydrantInUse()) 
						if (hyddist > lf.DistanceXY(obj))
						{
							hydrant=obj;
							hyddist=lf.DistanceXY(obj);
							hashydrant=true;
						}
					if (obj->IsBurning() || obj->IsBurningInside())
					{
						feuer++;
						if (obj->GetType()==ACTOR_OPEN_HOUSE)
							imhaus=true;
					}
					if (obj->HasCommand("gefahrgut"))
					{
						Vehicle v(obj);
						ggv=v.GetUserData();
						leck=(v.GetEnergy() < 0.95*v.GetMaxEnergy());
					}
					if (obj->HasNamePrefix("FogOfDoc"))
						Game::RemoveGameObject(obj);					
					break;			
			}
		}

		if (feuer>0)
			add_message(1,feuer,imhaus,true);
		if (fz>0)
			add_message(2,fz,false,false);
		if (aqua>0 && Fw)
			add_message(7,aqua,false,true);
		if (eingeklemmte>0)
			add_message(3,eingeklemmte,false,false);
		if (drunter>0)
			add_message(20,drunter,false,false);

		if (verletzte)
			add_message(4,verletzte,imhaus,false);

		if (rot>0 && SanD)
			add_message(16,rot,false,false);
		if (gelb>0 && SanD)
			add_message(17,gelb,false,false);
		if (gruen>0 && SanD)
			add_message(18,gruen,false,false);
		if (tot>0 && SanD)
			add_message(19,tot,false,false);

		if (ggv>0 && ggv<7 && Fw)
			add_message(5,kz[ggv],false,false);
		if (leck && Fw)
			add_message(10,0,false,true);
		if (hashydrant && gf && Fw)
		{
			add_message(6,0,false,false);
			// hydrant->SetHighlighted(true);
			if (autowater)
				Caller->PushActionExecuteCommand(ACTION_APPEND,"gf_we",hydrant,0,false);
		}

		if (taeter>0 && Pol)
			add_message(12,taeter,false,false);
		if (weapon>0 && Pol)
			add_message(13,0,false,true);
		if (steine>0 && Pol)
			add_message(14,0,false,true);
		if (molotov>0 && Pol)
			add_message(15,0,false,true);
		meldung_abgeben(Caller);
	}
};

object tl_zug_select : CommandScript
{
	tl_zug_select()
	{
		SetValidTargets(ACTOR_PERSON|ACTOR_VEHICLE);
		SetCursor("lz_befehl");
		SetIcon("lz_befehl");
		SetPriority(500);
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		bool ok=Caller->GetID()==Target->GetID();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int zugort)
	{
		int el=0;
		int id=Caller->GetID();
		int ESt=Caller->GetUserData();
		if (!zugort)
		{
			Vehicle v(Target);
			v.RemoveCommand("sofa");
			if (Caller->IsFlagSet(FLAG_TL))
			999{
				el=256;
				zugort=-1;
			} else {
				VehicleList vl(Caller->GetName());
				zugort=fwdv4::fzr_get(vl.GetVehicle(0)->GetID(),0);
				zugort=fzr[zugort][2];
			}
		} else {
			zugort=fwdv4::fzr_squad(id,zugort);
			if (zugort>-1)
				zugort=fzr[zugort][2];
			else 
				zugort=-1;
			ESt=id;
		}
		Caller->Deselect();
		//System::Log("Zug auswaehlen Ort %u Zug %u",zugort,Caller->GetUserData());
		fwdv4::zug_manipulation(el+2,ESt,id,zugort,false);
	}
};

object tl_select : CommandScript
{
	tl_select()
	{
		SetValidTargets(ACTOR_PERSON|ACTOR_VEHICLE);
		SetCursor("el_finden");
		SetIcon("el_finden");
		SetRestrictions(RESTRICT_SELFEXECUTE);
		SetGroupID(8);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return Caller->HasCommand("zugfz") || Caller->HasCommand("lst_estelle");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		bool ok=Caller->GetID()==Target->GetID();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int zugort)
	{
		fwdv4::zug_fzreg (Caller,Target, zugort, 10);
	}
};

object tl_rufe_tel : CommandScript
{

   tl_rufe_tel()
   {
	SetIcon("tel_alarm");
	SetCursor("tel_alarm");
	SetRestrictions(RESTRICT_SELFEXECUTE);
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return Caller->GetID()==Target->GetID();
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	VehicleList vl(Caller->GetName());
	int j=fwdv4::fzr_get(vl.GetVehicle(0)->GetID(),0);
	Actor a=Game::GetActor(fzr[j][1]);
	if (a.IsValid()) {
		GameObject p(&a);
		// System::Log("TEL rufen %s %s",Caller->GetName(),p.GetName());
		Caller->PushActionExecuteCommand(ACTION_NEWLIST,"rufe_winterberg",&p,10,false); // ZF bestellen
		Caller->PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,99303,false); // ELW2
	} // else
		// System::Log ("TEL rufen : Ungültige E-Stelle !");
   }
};

object tl_tel_uebernimmt : CommandScript
{

   tl_tel_uebernimmt()
   {
	SetIcon("el_uebern");
	SetCursor("el_uebern");
	SetRestrictions(RESTRICT_SELFEXECUTE);
	SetGroupID(5);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return !Caller->HasCommand("sofa");
   }
	
   bool CheckPossible(GameObject *Caller)
   {
	return Input::LCtrlPressed();
   }


   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return Caller->GetID()==Target->GetID();
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	//System::Log("Leitung übernehmen ? %s",Caller->GetName());
	bool goon=Caller->HasCommand("tl_tel_uebernimmt");
	if (goon) {
		goon=Caller->HasCommand("zugfz");
		if (goon)
		{
			Vehicle tel(Caller);
			int j=fwdv4::fzr_get(Caller->GetID(),0);
			Actor estelle=Game::GetActor(fzr[j][1]);
			goon=estelle.IsValid();
			if (goon) {
				Actor a=Game::GetActor(estelle.GetUserData());
				goon=a.IsValid();
			}
			if (!goon) {
				//System::Log("Ungueltige Ziele -> TEL kann nicht uebernehmen");
				return;
			}

			VehicleList vl(a.GetName());
			Vehicle elw=vl.GetVehicle(0);
			Person el;
			//System::Log("Leitung übernehmen ? %s %s %s",tel.GetName(),elw.GetName(),estelle.GetName());

			if (elw.GetID()==tel.GetID())
				return;		// evil aber wirksam

			//System::Log("Leitung übernehmen !");

			tel.AssignCommand("sofa"); //ZF bleibt auf dem FZ, SonderFunktion (hier TEL) wird abgegeben
			elw.RemoveCommand("sofa");
			PersonList pl(tel.GetName());
			for (int i=0;i<pl.GetNumPersons() && !el.IsValid();i++)
				if (pl.GetPerson(i)->HasCommand("tl_gefahr"))
					el=pl.GetPerson(i);

			Person p(&a);
			p.ClearFlag(FLAG_TL);
			p.RemoveCommand("tl");
			el.SetFlag(FLAG_TL);
			el.AssignCommand("tl");
			estelle.SetUserData(el.GetID());
			el.SetUserData(estelle.GetID());
			tel.SetUserData(estelle.GetID());

			if (tel.HasCommand("Funkmast"))
				tel.PushActionExecuteCommand(ACTION_NEWLIST,"Funkmast",&tel,0,false); 	
		}
	}
   }
};

object tl_Lage_sichern : CommandScript
{
	tl_Lage_sichern()
	{
		SetValidTargets(ACTOR_OPEN_HOUSE);
		SetCursor("scouthouse");
		SetIcon("scouthouse");
		SetPriority(500);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	bool erkunden (Person p,Actor *Target)
	{
		bool ok=true;
		if (true)
		{
			p.PushActionExecuteCommand(ACTION_NEWLIST,"ScoutHouse",Target,0,false);
			if (p.GetEnteredCarID()>1)
			{
				Actor car=Game::GetActor(p.GetEnteredCarID());
				p.PushActionLeaveCar(ACTION_INSERT,&car);
			}
		} else 
			ok=false;
		return ok;
	}
	
	int schuetze_bereit (Person p,Actor *Target)
	{
		int bereit=1;
		if (true)
		{	
			Actor car;
			int cid=1;

			if (p.GetEnteredCarID()>1)
			{				
				car=Game::GetActor(p.GetEnteredCarID());
				cid=2;
			}
			p.Select();
			p.PushActionExecuteCommand(ACTION_NEWLIST,"POL_GetGun",&car,cid,false);
			if (cid==2)
				p.PushActionLeaveCar(ACTION_INSERT,&car);
		}
			else bereit=0;
	}

	void PushActions(GameObject *Caller, Actor *Target, int zugort)
	{
		// 1. Haus erkunden, 2 Scharfschützen bereit stellen
		PersonList pl(Caller->GetName());
		bool scoutit=false;
		int shooter=2;
		for (int i=0;i<pl.GetNumPersons();i++)
		{
			Person p=pl.GetPerson(i);
			if (!p.HasCommand("tl"))
			{
				if (!scoutit)
					scoutit=erkunden(p,Target);
				else if(shooter>0)
					shooter-=schuetze_bereit(p,Target);
			}
		}
		// 2. SEK Schützen Absitzen und Waffe ziehen

		Caller->Deselect();
		fwdv4::zug_manipulation(356,Caller->GetUserData(),Caller->GetID(),-1,false);
	}
};

object tl_Zugriff : CommandScript
{
	tl_Zugriff()
	{
		SetValidTargets(ACTOR_OPEN_HOUSE);
		SetCursor("arrest");
		SetIcon("arrest");
		SetPriority(700);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		OpenHouse oh(Target);
		return oh.IsCeilingOpen();
	}

	void PushActions(GameObject *Caller, Actor *Target, int zugort)
	{

		fwdv4::zug_manipulation(357,Caller->GetUserData(),Caller->GetID(),Target->GetID(),false);
	}
};

object tl_squad_1 : CommandScript
{

   tl_squad_1()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(10);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,1,false);
   }
};

object tl_squad_2 : CommandScript
{

   tl_squad_2()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(11);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,2,false);
   }
};

object tl_squad_3 : CommandScript
{

   tl_squad_3()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(12);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,3,false);
   }
};

object tl_squad_4 : CommandScript
{

   tl_squad_4()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(13);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,4,false);
   }
};


object tl_squad_6 : CommandScript
{

   tl_squad_6()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(15);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,6,false);
   }
};

object tl_squad_7 : CommandScript
{

   tl_squad_7()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(16);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,7,false);
   }
};

object tl_squad_8 : CommandScript
{

   tl_squad_8()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(17);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,8,false);
   }
};

object tl_squad_9 : CommandScript
{

   tl_squad_9()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(18);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,9,false);
   }
};

object tl_squad_5 : CommandScript
{

   tl_squad_5()
   {
	SetIcon("redirect");
	SetCursor("redirect");
	SetRestrictions (RESTRICT_SELFEXECUTE);
	SetGroupID(14);
   }

   bool CheckGroupVisibility(GameObject *Caller)
   {
	return true;
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	Caller->PushActionExecuteCommand(ACTION_INSERT,"tl_zug_select",Target,5,false);
   }
};

object gf_doorcheck : CommandScript
{
	gf_doorcheck()
	{
		SetValidTargets(ACTOR_OPEN_HOUSE);
		SetCursor("ScoutHouse");
		SetIcon("ScoutHouse");
		SetPriority(700);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Target->GetType()==ACTOR_OPEN_HOUSE;
	}

	void PushActions(GameObject *Caller, Actor *Target, int zugort)
	{
		OpenHouse oh(Target);
		if (oh.IsLocked())
			Mission::PlayHint("House locked");
		else if (oh.IsOpen())
			Mission::PlayHin("House Open");
		if (oh.IsDoorLocked(oh.GetEntranceDoorID()))
			Mission::PlayHint("Entrance Door Locked");
		oh.ClearFlag(OF_LOCKED);
		oh.SetFlag(OF_ACCESSIBLE);
		int door=oh.GetEntranceDoorID();
		oh.OpenDoor(door);
		
	}
};



object UseRoadBlock : CommandScript
{

	bool isfw;

	UseRoadBlock()
	{
		SetValidTargets(ACTOR_FLOOR|ACTOR_OBJECT);
		SetPossibleCallers(ACTOR_PERSON);
		SetPossibleEquipment(EQUIP_ROADBLOCK);
		// SetPriority(700);
		SetSelfClickActivation(true);
	}

	bool CheckPossible(GameObject *Caller)
	{

		Person p(Caller);
		if (Input::LCtrlPressed())
			SetPriority(700);
		else
			SetPriority(0);
		isfw=p.GetPersonType()==PT_FIREFIGHTER_NORMAL || p.GetPersonType()==PT_FIREFIGHTER_MASK || p.GetPersonType()==PT_FIREFIGHTER_ABC || p.GetPersonType()==PT_POLICEMEN;
		if (isfw)
		{
			SetIcon("band");
			SetCursor("band");
		} else {
			SetIcon("useroadblock");
			SetCursor("useroadblock");
		}

		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		Person p(Caller);
		if(!Caller->IsValid() || Caller->GetEquipment()!=EQUIP_ROADBLOCK || Caller->GetID()==Target->GetID())
			return false;			
		if (Caller->GetType() != ACTOR_PERSON)
			return false;
		if (Target->IsValid() && Target->GetType() == ACTOR_OBJECT)
		{
			GameObject target(Target);
			if(!target.IsBridge())
				return false;
		}
		if(p.GetEnteredCarID() != -1)
			return false;
		isfw=p.GetPersonType()==PT_FIREFIGHTER_NORMAL || p.GetPersonType()==PT_FIREFIGHTER_MASK || p.GetPersonType()==PT_FIREFIGHTER_ABC || p.GetPersonType()==PT_POLICEMEN;
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		if (ChildID==0)
		{
			GameObject t=bungarext::hierhin(Game::GetCommandPos());
			Target=&t;
		}

		if (isfw || ChildID>0)
		{
			switch (ChildID)
			{
				case 0:
				case 2:
					if (Target->GetName()!=Caller->GetName())
					{
						Caller->PushActionTurnTo(ACTION_NEWLIST,Target);
						Caller->PushActionExecuteCommand(ACTION_APPEND,"UseRoadBlock",Target,1,false);
					} else {
						GameObject o(Target);
						Game::RemoveGameObject(&o);
					}
					break;
				case 1:
					char * obname="                    ";
					char * obmask="FB%s";
					int j=snprintf(obname,20,obmask,Caller->GetName());

					GameObject sperrung=Game::CreateObject("mod:Prototypes/Objects/Equipment/flatterband.e4p",obname);
					sperrung.SetRotation(Caller);
					sperrung.SetPosition(Caller);
					sperrung.PushActionHalt(ACTION_NEWLIST,250,HALT_PERSONS);
					if (Caller->DistanceXY(Target) > 150)
					{
						Vector l,r,pos;
						sperrung.GetOrientedBBoxPoint(1,l.x,l.y,l.z);
						sperrung.GetOrientedBBoxPoint(2,r.x,r.y,r.z);
						pos.x=(l.x+r.x)/2;
						pos.y=(l.y+r.y)/2;
						pos.z=(l.z+r.z)/2;
						Caller->PushActionMove(ACTION_NEWLIST,pos);
						Caller->PushActionExecuteCommand(ACTION_APPEND,"UseRoadBlock",Target,2,false);
					}
					break;
			}
		} else
			if (Caller->GetID() == Target->GetID())
			   	Caller->PushActionUseEquipment(ACTION_NEWLIST, Target, ChildID, 3.f); // Target, Child and Time does not matter
			else {
				Caller->PushActionTurnTo(ACTION_NEWLIST,Target);
				Caller->PushActionUseEquipment(ACTION_APPEND,Caller,ChildID, 3.f);	
			}
	}
};

class bungarext : CommandScript
{

	GameObject hierhin (Vector cp)
	{
		GameObject obj=Game::CreateObject("mod:Prototypes/Objects/Equipment/marker.e4p","bungar");
		obj.SetPosition(cp);
		obj.AssignCommand("alarmdummy");
		obj.PushActionWait(ACTION_NEWLIST,50.0);
		obj.PushActionDisappear(ACTION_APPEND,7.0,50.0,true);
		return obj;
	}
	
	void debung (Actor *bung)
	{
		if (bung->HasNamePrefix("bungar"))
		{
			GameObject db(bung);
			db.PushActionDeleteOwner(ACTION_NEWLIST);
		}
	}
};


const int FLAG_FUNK=OF_HAS_FIREAXE * 2;
const int FLAG_SOSI=OF_HAS_FIREAXE * 4;
const int FLAG_TL=OF_HAS_FIREAXE * 8;
const int FLAG_NA=OF_HAS_FIREAXE * 16;
