// ## 
// ## WEM4 Scripting
// ## WEM4 9 Taikapalo
// ## 
// ## Script witchdoc_action
// ## 
// ## Release 03.05.2014
// ## 
// ## created by WitchDoctor



#pragma compile


  



int eventid=-1;
int emmatime;
VehicleList markit;
int nmark;
GameObjectList Baumliste;
int klinik;
Actor ffparken;
Actor fftor;
Path gleis_1;
Path bahnsteig;
Path bahnbus;
Path sportboot;
Path frachter;
Actor stop_gleis1;
Actor stop_gleis2;
int traincycle=3;
ActorList verkehr;
Actor *traffic[25];
int traffic_n=0;
int traffic_group=-1;
int traffic_gsize=2;
int traffic_aktiv=-1;
int verkehrsindex;
bool campaign=true;
bool auto_na=true;


// Verkehrsunfall auf der Landstrasse
// by WitchDoctor

const int MAX_PROTOTYPES = 10;
const char * prototypes[MAX_PROTOTYPES];
const char PROTOTYPE1[] = "mod:Prototypes/Persons/Civil/civilminister01.e4p";
const char PROTOTYPE2[] = "mod:Prototypes/Persons/Civil/civilman03_green.e4p";
const char PROTOTYPE3[] = "mod:Prototypes/Persons/Civil/civilman02_silver.e4p";
const char PROTOTYPE4[] = "mod:Prototypes/Persons/Civil/firewatchguy01.e4p";
const char PROTOTYPE5[] = "mod:Prototypes/Persons/Civil/civilman02_blue.e4p";
const char PROTOTYPE6[] = "mod:Prototypes/Persons/Civil/civilwoman01_red.e4p";
const char PROTOTYPE7[] = "mod:Prototypes/Persons/Civil/civilwoman02_beige.e4p";
const char PROTOTYPE8[] = "mod:Prototypes/Persons/Civil/civilwoman03_blue.e4p";
const char PROTOTYPE9[] = "mod:Prototypes/Persons/Civil/civilwoman04.e4p";
const char PROTOTYPE10[] = "mod:Prototypes/Persons/Civil/civilwoman05.e4p";

const char * beweismittel[5];
const char beweismittel[0] = "mod:Prototypes/objects/equipment/gun.e4p";
const char beweismittel[1] = "mod:Prototypes/objects/equipment/gun_big.e4p";
const char beweismittel[2] = "mod:Prototypes/objects/equipment/rifle.e4p";
const char beweismittel[3] = "mod:Prototypes/objects/misc/movebox01.e4p";
const char beweismittel[4] = "mod:Prototypes/objects/misc/movebox02.e4p";

const int MAX_PROTOVECS = 13;
const char * protovecs[20];
const char PROTOVECS1[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck00.e4p";
const char PROTOVECS2[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck01.e4p";
const char PROTOVECS3[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck02.e4p";
const char PROTOVECS4[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck05.e4p";
const char PROTOVECS5[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck07.e4p";
const char PROTOVECS6[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck08.e4p";
const char PROTOVECS7[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck09.e4p";
const char PROTOVECS8[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck10.e4p";
const char PROTOVECS9[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck11.e4p";
const char PROTOVECS10[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck12.e4p";
const char PROTOVECS11[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck13.e4p";
const char PROTOVECS12[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck14.e4p";
const char PROTOVECS13[] = "mod:Prototypes/Vehicles/Wrecks_sliceable/carwreck15.e4p";
const char PROTOVECS14[] = "mod:Prototypes/Vehicles/Train/dieselloc01.e4p";
const char PROTOVECS15[] = "mod:Prototypes/Vehicles/Train/freightcar02.e4p";
const char PROTOVECS16[] = "mod:Prototypes/Vehicles/Train/freightcar03_1.e4p";
const char PROTOVECS17[] = "mod:Prototypes/Vehicles/Train/br640.e4p";

const int MAX_PROTONAMES= 8;
const char * pName[MAX_PROTONAMES];

		prototypes[0] = PROTOTYPE1;
		prototypes[1] = PROTOTYPE2;
		prototypes[2] = PROTOTYPE3;
		prototypes[3] = PROTOTYPE4;
            	prototypes[4] = PROTOTYPE5;
            	prototypes[5] = PROTOTYPE6;
            	prototypes[6] = PROTOTYPE7;
            	prototypes[7] = PROTOTYPE8;
            	prototypes[8] = PROTOTYPE9;
            	prototypes[9] = PROTOTYPE10;

int punkte;

object hata_vu : CommandScript
{
	hata_vu()
	{
		SetIcon("techrett");   
		SetCursor("techrett");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		GameObject watch=Game::CreateObject("mod:Prototypes/Objects/Equipment/parken.e4p","WitchDcCore");
		Vector Crash=disaster::incident_pos(0);

		if (Crash.x!=0 && Crash.y!=0)
		{
			watch.SetPosition(Crash);
			Caller->PushActionExecuteCommand(ACTION_INSERT,"random_vu_do",&watch,0,false);
		} 
	}
};

object random_vu_do : CommandScript
{
	random_vu_do()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		Actor Opfer;
		Actor CrashCar;
		Vector Pos;
		Vector Posabc;
		float rot[9];
		float childRot[9];
		int index;
		float winkel;
		bool autobrennt=false;
		bool eingeklemmt=false;
		bool bus=false;
		bool gefahrgut=false;
		bool lkw=false;
		bool bicycle=false;
		int disaster;
		int n_pat=0;
		int erg;
		Person p;

            	protovecs[0] = PROTOVECS1;
            	protovecs[1] = PROTOVECS2;
            	protovecs[2] = PROTOVECS3;
            	protovecs[3] = PROTOVECS4;
            	protovecs[4] = PROTOVECS5;
            	protovecs[5] = PROTOVECS6;
            	protovecs[6] = PROTOVECS7;
            	protovecs[7] = PROTOVECS8;
            	protovecs[8] = PROTOVECS9;
            	protovecs[9] = PROTOVECS10;
            	protovecs[10] = PROTOVECS11;
            	protovecs[11] = PROTOVECS12;
            	protovecs[12] = PROTOVECS13;

		pName[0]="Civil Man 01";
		pName[1]="Civil Man 01 Blue";
		pName[2]="Civil Man 01 White";
		pName[3]="Civil Man 02 Silver";
		pName[4]="Civil Pizza 01";
		pName[5]="Civil Woman 03 Red";
		pName[6]="Civil Woman 04";
		pName[7]="Civil Woman 01 Yellow";

		// System::Error("random_vu: Jetzt gehts los !");

		Vehicle carobj;
		char *incicode="               ";
		snprintf(incicode,15,"VU%u",Target->GetID());
		Vehicle car=Game::CreateVehicle("mod:Prototypes/Vehicles/Civil - Trucks/crash.e4p",incicode);
		Pos=Target->GetPosition();
		Game::FindFreePosition(&car,Pos,50.0);
		car.SetPosition(Pos); 
		car.GetRotation(rot[0], rot[1], rot[2], rot[3], rot[4], rot[5], rot[6], rot[7], rot[8]);
		winkel = rand()%180-90;
		Math::EulerToMatrix(winkel, 0.f, 0.f, childRot);
		Math::MultiplyMatrices(childRot, rot);
		car.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
		disaster=Math::rand()%15;

		int punkte=0;
		int maxcars=0;
		int maxinj=0;
		int maxrad=200;

		switch (disaster)
		{

			case 8:
			case 9:
			case 3:
				bus=true;
				maxrad=700;
				// System::Error("Busunglueck");
				car.SetSmoking(true);
				car.SetSmokeLevelDuration(30.0f);
				punkte=1000;
				carobj=Game::CreateVehicle("mod:Prototypes/Vehicles/Civil - Cars/wdcrash1.e4p",incicode);
				winkel = rand()%180-90;
				Math::EulerToMatrix(winkel, 0.f, 0.f, childRot);
				Math::MultiplyMatrices(childRot, rot);
				carobj.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
				carobj.ClearFlags();
				carobj.SetFlag(OF_RECOVERABLE|OF_TRANSPORTABLE|OF_COOLABLE);
				Game::FindFreePosition(&carobj,Pos,500);
				carobj.Destroy();
				carobj.SetPosition(Pos);
				carobj.SetParking(false);
				carobj=Game::CreateVehicle("mod:Prototypes/Vehicles/Civil - Cars/crashcar2.e4p",incicode);
				winkel = rand()%180-90;
				Math::EulerToMatrix(winkel, 0.f, 0.f, childRot);
				Math::MultiplyMatrices(childRot, rot);
				carobj.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
				carobj.ClearFlags();
				carobj.SetFlag(OF_RECOVERABLE|OF_TRANSPORTABLE|OF_COOLABLE);
				carobj.SetParking(false);
				Game::FindFreePosition(&carobj,Pos,500);
				carobj.Destroy();
				carobj.SetPosition(Pos);
				maxcars=rand()%6+2;
				maxinj=rand()%8+7;
				break;
			
			case 2:
			case 4:
				// System::Error("Gefahrgut");
				car.PushActionExecuteCommand(ACTION_NEWLIST,"setggv",&car,0,false);
				gefahrgut=true;
				maxcars=rand()%6+2;
				maxinj=rand()%5+3;
				maxrad=700;
				// erstmal keine gefahrguteinsaetze
				punkte=3000;
				break;
			case 1:
			case 7:
				System::Log("Bicycle crash");
				punkte=500;
				GameObject crash;
				bicycle=true;
				crash=Game::CreateObject("mod:Prototypes/Objects/Street/bicycle01.e4p",incicode);
				crash.GetRotation(rot[0], rot[1], rot[2], rot[3], rot[4], rot[5], rot[6], rot[7], rot[8]);
				winkel = rand()%180-90;
				Math::EulerToMatrix(0.0f, 90.f, 0.0f, childRot);
				Math::MultiplyMatrices(childRot, rot);
				crash.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
				crash.ClearFlags();
				crash.SetFlag(OF_RECOVERABLE|OF_TRANSPORTABLE|OF_COOLABLE);
				Pos=car.GetPosition();
				// Game::FindFreePosition(&crash,Pos, 50); // disaster::zielpos(&car,&crash);
				// Pos.z=Game::GetFloorHeight(Pos.x,Pos.y);
				// crash.ComputePlacement(Pos.x,Pos.y,Pos.z);
				Pos.x+=70;
				Pos.z-=50;
				crash.SetPosition(Pos);
				crash.SetPlacement(PLACEMENT_ALIGNED_CORNERS);
				crash.UpdatePlacement();
				System::Log("Bike %f %f %f",Pos.x,Pos.y,Pos.z);
				Pos=car.GetPosition();
				System::Log("Car %u %u %u",Pos.x,Pos.y,Pos.z);
				crash.Select();
				maxinj=0;
				maxcars=0;
				break;
			default:
				maxcars=rand()%3+1;
				maxinj=rand()%3;
				maxrad=300;
				break;
				
		}

		if (gefahrgut || bus)
			carobj.SetFlag(OF_RECOVERABLE);
		car.SetParking(false);
	
		// Zivilisten erzeugen und als Verletzte auf der Strasse verstreuen
		//Fahrzeuge + Eingeklemmten erzeugen

		int q=maxcars;
		bool memek=false;
		Vehicle memv;
		
		for(int i = 0; i < q; i++)
		{
			// System::Error("Unfallfz erzeugen");
			Posabc=Pos+Vector(((rand()%150)-75),((rand()%150)-75),0);
			index = rand()%MAX_PROTOVECS;
			winkel = rand()%180-90;
			Math::EulerToMatrix(winkel, 0.f, 0.f, childRot);
			Math::MultiplyMatrices(childRot, rot);

			Vehicle v = Game::CreateVehicle(protovecs[index], incicode);
			v.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
			punkte=punkte+500;
			int w=rand()%11;
			if (5 < w)
			{
				// System::Error("eingeklemmte Person erzeugen");
				char *pklem="                  ";
				snprintf(pklem,18,"VU%s%u",incicode,n_pat);
				int index = rand()%MAX_PROTONAMES;
				if (disaster::Person_insFz(&v,pklem,&p,true))
				{
					n_pat++;
					eingeklemmt=true;
					punkte=punkte+750;
				} 
			}
			if (memek)
			{
				v.SetPlacement(PLACEMENT_ALIGNED_CORNERS);
				v.UpdatePlacement();
				Posabc=memv.GetTargetPoint(&v,TARGET_SHEARSDOOR);		
				Game::FindFreePosition(&v,Posabc,1.0);
				
			} else 
				Game::FindFreePosition(&v,Posabc,300);
			v.SetPosition(Posabc);
			v.SetParking(false);
			if (memek)
			{
				v.PushActionTurnTo(ACTION_NEWLIST,Target);
				v.PushActionMove(ACTION_APPEND,Posabc);
			}
			memek=v.HasEnclosedPerson();
			memv=v;
			if (((Math::rand()%10)>6) && !gefahrgut)
			{
				v.SetSmoking(true);
				v.SetSmokeLevelDuration(30.0f);
				if (memek)
				{
					v.PushActionExecuteCommand(ACTION_NEWLIST,"ActionMotorSound",&p,112,false);
				}
				autobrennt=true;
			} else {
				if (memek)
					p.PushActionExecuteCommand(ACTION_NEWLIST,"ActionMotorSound",&p,1121,false);		
				v.Damage(v.GetMaxEnergy()*0.5);
			}
			v.SetFlag(OF_RECOVERABLE);
		}
		// Personen erzeugen und verletzt auf der Strasse verstreuen
	
		n_pat=disaster::Verletzte_streuen(&car,maxinj,700,incicode,bicycle,false);
		
		punkte=punkte+500*n_pat;

		int eid;
		// EventID-Code für Patch 1.3
		if (bicycle) 
			eid=Game::ShowEvent("WIB_WD_VUUN", Pos);
		else if (gefahrgut)	
			eid=Game::ShowEvent("WIB_WD_VUGGV", Pos);
		else
			eid=Game::ShowEvent("WIB_WD_VUUN", Pos);

		Game::ShowHelpText("WIB_WD_VU");
		Mission::PlayHint("WIB_WD_VU");
		if (autobrennt && ((Math::rand()%10)<5))
			Mission::PlayHint("WIB_WDVU_FEUER");
		else 	if (bus && ((Math::rand()%10)<4))
				Mission::PlayHint("WIB_WDVU_BUS");
			else 	if (eingeklemmt && ((Math::rand()%10)<3))
				Mission::PlayHint("WIB_WDVU_KLEMM");
				else 	if (n_pat > Math::rand()%10)
						Mission::PlayHint("WIB_WDVU_VIELE");
					else
						Mission::PlayHint("WIB_WDVU_SCHNELL");
		Audio::PlaySample(hatalarm);					
		if (Caller->HasNamePrefix("FogOfDoc"))
			Caller->SetPosition(Pos);
		GameObject watch(Target);
		watch.SetUserData(punkte);
		watch.PushActionExecuteCommand(ACTION_APPEND,"hata_checkvu",&watch,eid,false);	
		hatacd+=punkte/1000*5;
	}
};

GameObject Ehranger;
bool MissionMode;


object CheckWTDInit : CommandScript
{
	CheckWTDInit()
	{
		SetGroupID(20);
	}

	void PushActions(GameObject *Caller, Actor *Target, int event)
	{
		// System::Log("WTD Init");
		Ehranger=Caller;
		klinik=disaster::actor_init("klinik");
		ehrang=false;
		// warmedup=false;
		eventid=-1;
		MissionMode=event>0;
		campaign=event==666;
		char *buf="              ";
		char *val="    ";
		bool goon=true;
		ffparken=disaster::actorget("FFpark");
		fftor=disaster::actorget("wache_entry");
		goon=Game::GetGameString("WEM_AUTO_NA",val,4);
		auto_na=atoi(val)>0;

		// System::Log("WTD Init Ende");
		// if (MissionMode)
		PathList pl ("gleis1");
		if (pl.GetNumPaths()==0)
			PathList pl("Gleis3");
		if (pl.GetNumPaths()>0)
			gleis_1=pl.GetPath(0);
		PathList pl("Bahnhof");
		if (pl.GetNumPaths()>0)
			bahnsteig=pl.GetPath(0);
		PathList pl("Busbahn");
		if (pl.GetNumPaths()>0)
			bahnbus=pl.GetPath(0);
		stop_gleis1=disaster::actorget("stop_regio");
		stop_gleis2=disaster::actorget("stop_fracht");

		PathList pl("flussfisch");
		if (pl.GetNumPaths()>0)
			sportboot=pl.GetPath(0);
		else
			System::Log("Kein Sportboot Pfad");
		PathList pl("flussfisch");
		if (pl.GetNumPaths()>0)
			frachter=pl.GetPath(0);
		else
			System::Log("Kein Frachter Pfad");

		verkehr=Game::GetActors(ACTOR_SPAWNPOINT);
		for (int i=verkehr.GetNumActors()-1;i>-1;i--)
			if (verkehr.GetActor(i)->HasNamePrefix("traffic_car"))
			{
				traffic_n++;
				traffic[traffic_n]=verkehr.GetActor(i);
				// disaster::verkehr_aktiv(traffic_n,false,traffic_n,false);
			}
		if (traffic_n>0)
		{
			// traffic_aktiv=1;
			// disaster::verkehr_aktiv(traffic_aktiv,true,traffic_n,true);
		} else {
			System::Log("Ungueltige Map geladen, keine Traffic-Pfade gefunden");
		}
	}
};

object CheckWitchDoc : CommandScript
{
	CheckWitchDoc()
	{
		SetGroupID(20);
	}

	void PushActions(GameObject *Caller, Actor *Target, int event)
	{
		bool feddisch=false;
		bool missed=false;
		bool razzia=false;
		
		// System::Log("CheckWitchDoc %u",event);
		switch (event)
		{
			case 90:	
				razzia=true;
			case 70:
				PersonList pl("ueberfall");
				Vehicle v(Target);
				int i;
				feddisch=(pl.GetNumPersons() == 0);
				if (razzia && feddisch)
				{
					GameObjectList ol("beweis");
					for (i=0;i<ol.GetNumObjects() && !missed;i++)
						missed=!ol.GetObject(i)->IsCarried();
				}
				else
					missed=v.IsValid() && v.IsHidden() && v.GetNumPassengers()>0;
				feddisch=feddisch && !missed;
				if (missed)
				{
					if (razzia)
					{
						Mission::PlayHint("WIB_WD_RAZZIA_NIX");
					} else {
						Mission::PlayHint("WIB_WD_UEBERFALL_NIX");
						for (i=0;i<pl.GetNumPersons();i++)
							pl.GetPerson(i)->PushActionDeleteOwner(ACTION_NEWLIST);
						if (v.HasNamePrefix("ueberfall"))
							v.PushActionDeleteOwner(ACTION_NEWLIST);
					}
					Audio::PlaySample("mod:Audio/FX/Voices/sardlach.wav");
				}
				break;
			case 60:
				// System::Log("Schlaegerei/Demo laeuft");
				PersonList pl("randale");
				feddisch=(pl.GetNumPersons() == 0);
				break;
			case 66:
				// System::Log("Bombe gefunden");
				feddisch=(!Target->IsValid());
				if (!feddisch)	
				{
					GameObject o(Target);
					missed=int (o.GetBurningStatus())>1;
				}
				punkte=1500;
				break;
			case 20:
				GameObjectList pl=Game::GetGameObjectsWithPrefix("HerbTank");
				feddisch=(pl.GetNumObjects() == 0);
				// System::Log("Herborn laeuft");
				if (feddisch)
				{
					//System::Log("Tankzug feddisch");
					GameObjectList ol("33HerbOel");
					Game::RemoveGameObject(ol.GetObject(0));
				}
				break;
			case 25:
				GameObjectList pl=Game::GetGameObjectsWithPrefix("emma");
				feddisch=(pl.GetNumObjects() == 0);
				// System::Log("Orkan läuft");
				if (feddisch)
					System::Log("Emma fertig");
				else if (emmatime<disaster::hmin())
					Caller->PushActionExecuteCommand(ACTION_INSERT,"emma",Caller,3+rand()%5,false);		
				break;
			case 26:
				feddisch=!Game::ExistsInjuredPerson();
				if (feddisch)
				{
					ActorList al("wintersport");
					SpawnPoint sp(al.GetActor(0));
					sp.SetEnabled(true);
				}
				break;
			case 27:
				GameObjectList ol=Game::GetGameObjectsWithPrefix("captain");
				feddisch=ol.GetNumObjects()==0;
				// System::Log("Seenot laeuft");
				if (feddisch)
					System::Log("Sportboot fertig");
				else {
					VehicleList vl("captain");
					for (int i=0;i<vl.GetNumVehicles();i++)
						missed=missed || vl.GetVehicle(i)->IsDestroyed();
					if (!missed) {
						missed=true;
						PersonList pl("captain");
						for (i=0;i<pl.GetNumPersons();i++)
							missed=missed && pl.GetPerson(i)->IsDead();
					}
				}
				break;
			case 50:
				GameObjectList ol("regio");
				// System::Log("Ruesselsheim laeuft");

				if (ol.GetNumObjects() == 0)
					feddisch=true;
		
				if (feddisch)
				{
					ehrang=false;
					//System::Log("Ruesselsheim beendet");
				}
				break;	
			case 55:
				GameObjectList ol("Air_Berlin");
				// System::Log("PlaneCrash läuft");

				if (ol.GetNumObjects() == 0)
					feddisch=true;
				else
				{	
					feddisch=true;	
					for (int x=0;(x<ol.GetNumObjects()) && feddisch;x++)
						feddisch=feddisch && ol.GetObject(x)->IsHidden();
				}
		
				if (feddisch)
				{
					//System::Log("PlaneCrash beendet");
				}
				break;	
			case 15:
				feddisch=!Game::ExistsInjuredPerson() && !Target->IsValid();
				if (!feddisch) {
					Person p(Target);
					missed=p.IsDead();
					if (!p.IsDead()&&!p.HasAnyAction())
						p.PushActionExecuteCommand(ACTION_NEWLIST,"mers_do",&p,1,false);
				}
				break;
			default:
				GameObjectList ol("ehrang");
				Vehicle v;
				// System::Log("Ehrang laeuft");

				if (ol.GetNumObjects() == 0)
					feddisch=true;
		
				if (feddisch)
				{
					punkte=10000;
					ehrang=false;
					//System::Log("Ehrang beendet");
				}
				break;	
		}
		
		if (feddisch || missed)
		{	
			System::Log ("Hata Event over %u %u",event, eventid);
			Game::SetEventFinished(eventid, feddisch, punkte);  // Code für Patch 1.3
			eventid=-1;
			int oi;
			switch (event)
			{
				case 25:
					Mission::PlayHint("WIB_WD_EMMA_ENDE");
					break;
				case 27:
					if (missed)
						for (oi=0;oi<ol.GetNumObjects();oi++)
							ol.GetObject(oi)->PushActionDeleteOwner(ACTION_NEWLIST);
					break;	
				case 60:
					PersonList pl("unnschuess");
					for (int i=0;i<pl.GetNumPersons();i++)
						pl.GetPerson(i)->PushActionDeleteOwner();
					break;
				case 66:
					if (missed)
						o.PushActionDeleteOwner(ACTION_NEWLIST);
					break;
			}
		} else {
			Caller->PushActionWait(ACTION_APPEND,7.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",Target,event,false);
		}
		//System::Log("CheckWitchDoc Ende");
	}
};

// 2/2015

object wda_na_fordern : CommandScript
{
	wda_na_fordern()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int cid)
	{
		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int cid)
	{
		if (auto_na) {
			Caller->PushActionExecuteCommand(ACTION_INSERT,"rufe_nef",Target,1,false);
		} else {
			char *mask="%.7s : NA erforderlich !";
			char *Will_NA="                              ";
			snprintf(Will_NA,28,mask,Caller->GetName());
			Audio::PlaySample("mod:Audio/FX/pageboy.wav");
			int eventid=Game::ShowEvent(Will_NA, Target->GetPosition());
			Ehranger.PushActionExecuteCommand(ACTION_APPEND,"wda_na_check",Target,eventid);	
		}
	}
};

object wda_na_check : CommandScript
{
	wda_na_check()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int cid)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int event)
	{
		bool done=!Target->IsValid();
		if (!done) {
			Person p(Target);
			// System::Log("WDA Notarzt Check");
			done=p.HasCommand("na_cat");
			if (!done) {
				Caller->PushActionWait(ACTION_APPEND,2.0);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"wda_na_check",Target,event,false);
			}
		}

		if (done) {
			Game::SetEventFinished(event, true, 0);  // NA Nachforderung erfolgreich abgearbeitet
			// System::Log("WDA NA war da");
		}
	}
};

//

VehicleList bmalist;

object wt_bma : CommandScript
{
	wt_bma()
	{
		SetIcon("bma");   
		SetCursor("bma");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		// 1. Gebaeudeobjekt suchen
		Vehicle bma;
		if (bmalist.GetNumVehicles()<1)
			return;
		int x=Math::rand()%bmalist.GetNumVehicles();
		bma=bmalist.GetVehicle(x);
		punkte=500;
		bool feuer=false;
		bool forcefire=Caller->GetID()==Target->GetID() && Caller->HasCommand("isbma");
		if (forcefire)
			Vehicle bma(Target);

		System::Log("Action BMA %s %u %u",bma.GetName(),int(feuer),int(forcefire));

		// 2. Wenn ChildID=1 -> wirkliches Feuer -> Haus anzuenden
		// 3. Wenn Gebaeude OPEN_HOUSE, dann Objekt im Haus anzuenden
		if ((Math::rand()%20)> 12 || forcefire)
		{
			GameObjectList ol;
			GameObject obj;
			bool open=false;
			punkte=3000;
			Game::CollectObstaclesOnVirtualObject(bma.GetName(),ol, ACTOR_PERSON|ACTOR_OBJECT|ACTOR_OPEN_HOUSE|ACTOR_HOUSE);
			for (int bx=0;(bx<ol.GetNumObjects());bx++)
			{
				obj=ol.GetObject(bx);
				switch (obj.GetObjectType())
				{
					case TYPE_HOUSE:
					case TYPE_OPEN_HOUSE:
						if (!feuer)
							disaster::feuer_legen(&obj,&bma);
						feuer=true;
						break;
					case TYPE_PERSON:
						punkte+=500;
						break;
				}
			}
		} else 
			// 5. BMA Fehl-Alarm auslösen
			bma.PushActionExecuteCommand(ACTION_NEWLIST,"wt_bma_alarm",&bma,0,false);
		if (!bma.IsFlagSet(FLAG_TL)) 
			bma.SetFlag(OF_LOCKED);
	}
};

object wt_bma_quittung : CommandScript
{
	wt_bma_quittung()
	{
		SetGroupID(20);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		// BMA wieder scharf schalten
		// 1. Testen auf vorhandene Feuer und Verletzte im Gebaeude
		GameObjectList ol;
		GameObject obj;
		Vehicle bma(Target);
		bool e_ende=true;

		Game::CollectObstaclesOnVirtualObject(bma.GetName(),ol, ACTOR_PERSON|ACTOR_OBJECT|ACTOR_HOUSE|ACTOR_OPEN_HOUSE);
		for (int i=0;(i<ol.GetNumObjects() && e_ende);i++)
		{
			obj=ol.GetObject(i);
			if (obj.GetObjectType() == TYPE_PERSON)
			{
				Person p(&obj);
				e_ende=(e_ende && (!p.IsInjured() && !p.IsComatose() || p.IsCarried()));
			} else {
				e_ende=(e_ende && !obj.IsBurning());
			}
		}
		
		if (e_ende)
		{
			bma.EnableSpecialLights(false);
			Mission::PlayHint("WIB_WDBMA_AKTIV");
			bma.PushActionExecuteCommand(ACTION_NEWLIST,"wt_bma_scharf",&bma,0,false);
			if (bma.IsFlagSet(FLAG_TL)) {
				Game::SetEventFinished(bma.GetUserData(), true, punkte);  // Code für Patch 1.3
				bma.SetUserData(-1);
				bma.ClearFlag(FLAG_TL);
			}
			bma.PushActionExecuteCommand(ACTION_INSERT,"StatusSenden",Target,11,false);
		} else
			Mission::PlayHint("WIB_WDBMA_REST");
		e_ende=false;
	}
};

object wt_bma_alarm : CommandScript
{
	wt_bma_alarm()
	{
		SetGroupID(20);
		SetPriority(900);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int linie)
	{
		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int feuer)
	{
		Vehicle bma(Target);
		bma.SetVehicleRole(VT_THW_FGRR_RL);
		GameObjectList ohl;
		Game::CollectObstaclesOnVirtualObject(bma.GetName(),ohl, ACTOR_OPEN_HOUSE);
		if (feuer<0)
		{
			GameObjectList ol;
			GameObject obj;
			Game::CollectObstaclesOnVirtualObject(bma.GetName(),ol, ACTOR_PERSON);
			for (int i=0;(i<ol.GetNumObjects());i++)
			{
				obj=ol.GetObject(i);
				float val=rand()%300+600;
				Person p(&obj);
				if (p.GetPersonType()!=PT_FIREFIGHTER_MASK)
				{
					p.Injure(INJUREREASON_ENERGY,true);
					p.SetLife(val);
					float val=rand()%2+0.7;
					p.SetInjuredLifeDrain(val);
				} else
					punkte-=500;
			}
			int h,m,s;
			Game::GetTime(h,m,s);
			if ((h>19) || (h<9))
			{
				for (int i=0;(i<ohl.GetNumObjects());i++)
				{
					OpenHouse oh=ohl.GetObject(i);
					id=oh.GetEntranceDoorID();
					oh.CloseDoor(id);
					oh.SetDoorCollision(id,true);
				}
			}
		}
		for (int i=0;(i<ohl.GetNumObjects());i++)
			bma.PushActionEvacuate(ACTION_INSERT,ohl.GetObject(i));
		bma.PushActionExecuteCommand(ACTION_INSERT,"StatusSenden",&bma,10,false);
		bma.EnableSpecialLights(true);
		char * bmaname="                     ";
		char * bmafile[]="mod:Audio/fx/bma%u.wav";
		int j=snprintf(bmaname,21,bmafile,(Math::rand()%6+1));
		Audio::PlaySample(bmaname);
		char *buf="                                                                                                                ";
		char *NLS="                                         ";
		Game::GetGameString("WIB_WD_BMA",NLS,40);
		snprintf(buf,100,"%s : %s",NLS,bma.GetName());
		Game::ShowHelpText(buf);
		if (bma.IsFlagSet(OF_LOCKED))
		{
			Vector Posabc=bma.GetPosition();
			bma.SetUserData(Game::ShowEvent("WIB_WD_BMAALM", Posabc));
			hatacd+=180;
			bma.ClearFlag(OF_LOCKED);
			bma.SetFlag(FLAG_TL);
			GameObject Nebel=Game::CreateObject("mod:Prototypes/Objects/Equipment/marker.e4p","FogOfDoc");
			Nebel.SetPosition(&bma);
			Nebel.PushActionEmitParticles(ACTION_NEWLIST,"warfog",1000);
			Nebel.PushActionDeleteOwner(ACTION_APPEND);
		}
	}
};

object wt_bma_scharf : CommandScript
{
	wt_bma_scharf()
	{
		SetGroupID(20);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return false;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vehicle bma(Target);
		bma.SetVehicleRole(VT_NOSQUAD);
		bool feuer=Game::IsBurningObjectInVirtualObject(bma.GetName());
		if (feuer)
		{
			bma.PushActionExecuteCommand(ACTION_NEWLIST,"wt_bma_alarm",&bma,1,false);		
			bma.PushActionExecuteCommand(ACTION_APPEND,"wt_bma_rauchgas",&bma,0,false);
		}
		else
		{
			bma.PushActionWait(ACTION_NEWLIST,5.0f);
			bma.PushActionExecuteCommand(ACTION_APPEND,"wt_bma_scharf",&bma,0,false);
		}
	}
};

object wt_bma_rauchgas : CommandScript
{
	wt_bma_rauchgas()
	{
		SetGroupID(20);
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return false;
	}

	void flashover (Vehicle bma, OpenHouse oh)
	{
		// System::Log("Flashing over %s",bma.GetName());
		Vector pos;
		Vector l,r;
		GameObject flo=Game::CreateObject("mod:Prototypes/Objects/Misc/flashover.e4p","flo");
		PersonList pl=oh.GetSquadPersonsInside();
		Person p=pl.GetPerson(0);
		p.SetResistance(INJUREREASON_FIRE,0.0);
		flo.SetPosition(p.GetPosition());
		// System::Log("Flashover in %s : %u Objects",bma.GetName(),0);
	}


	int flash_it (GameObject *Caller, Vehicle bma, int code)
	{
		GameObjectList ol;
		bool can_flash=code<2;
		if (can_flash)
		{
			// System::Log("Can Flash %u %s",code,bma.GetName());
			if (Game::CollectObstaclesOnVirtualObject(bma.GetName(),ol, ACTOR_OPEN_HOUSE))
			{
				
				//System::Log("Can Flash House %u %s",ol.GetNumObjects(),bma.GetName());
				if (ol.GetNumObjects()==0)
					return;
				OpenHouse oh(ol.GetObject(0));
				//System::Log("Can Flash House code ? %u %s",code,bma.GetName());
				if (code==0)
				{
					//System::Log("Can Flash Decke zu %u %s",code,bma.GetName());
					oh.ShowCeiling(true,false,true);
					code++;
				} else 
					//System::Log("Can Flash EK im Haus ?	%u %s",code,bma.GetName());
					if (oh.IsCeilingOpen())
					{ 
						if ((rand()%10)>6)
						{
							// Mission::PlayHint("F L A S H   O V E R ! ");
							flashover (bma,oh);
						}
						code++;
					}
			} else code=2;
		} else 
			code=2;

		//System::Log("could flash" );
		return code;
	}

	void tox_it (Vehicle bma)
	{
		//System::Log("Tox em %s", bma.GetName());
		GameObjectList ol;
		Game::CollectObstaclesOnVirtualObject(bma.GetName(),ol, ACTOR_PERSON);
		for (int i=0;i<ol.GetNumObjects();i++)
		{
			Person p(ol.GetObject(i));
			if (!p.IsInjured())
				if (p.GetPersonType() != PT_FIREFIGHTER_MASK && p.GetPersonType() != PT_FIREFIGHTER_ABC)
				{
					if (p.GetEnteredHouseID()<1)
					{
						p.Hurt(INJUREREASON_FIRE,50);
						p.SetInjuredLifeDrain(1.5);
					} else {
						Actor h=Game::GetActor(p.GetEnteredHouseID());
						GameObject hou(&h);
						if (hou.IsBurningInside() || hou.IsCompletelyBurning())
						{
							p.Hurt(INJUREREASON_FIRE,350);
							p.SetUserData(p.GetUserData()|trauma_pneu|med_intub);
							p.SetInjuredLifeDrain(3.5);
						}
					}
				} 
		}
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Vehicle bma(Target);
		bma.PushActionWait(ACTION_NEWLIST,2.0);
		bool feuer=Game::IsBurningObjectInVirtualObject(bma.GetName());
		if (feuer)
		{
			code=flash_it(Caller,bma,code);
			tox_it(bma);
		}

		bma.PushActionExecuteCommand(ACTION_APPEND,"wt_bma_rauchgas",&bma,code,false);
	}
};

object wt_bma_init : CommandScript
{
	wt_bma_init()
	{
		SetGroupID(20);
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		VehicleList bl(VT_THW_FGRR_RL,VT_THW_FGRR_RL);
		bmalist=bl;
		Vehicle bma;
		for (int i=0;(i<bl.GetNumVehicles());i++)
		{
			bma=bl.GetVehicle(i);
			Vector p=bma.GetPosition();
			Game::FindAvailablePosition(&bma,p,1.0,true);
			bma.SetPosition(p); // Objekte INS haus bringen
			System::Log("INIT BMA %s",bma.GetName());
			bma.PushActionExecuteCommand(ACTION_NEWLIST,"StatusSenden",&bma,11,false);
			bma.PushActionExecuteCommand(ACTION_APPEND,"wt_bma_scharf",&bma,0,false);
			bma.AssignCommand("isbma");
		}
	}
};

bool ehrang=false;

object ehrang_brennt : CommandScript
{
	ehrang_brennt()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void place_wagon(Vehicle lok, Path *p, int verz)
	{
		lok.Hide();
		lok.SetPosition(p->GetStartPosition());
		lok.PushActionUsePath(ACTION_NEWLIST,p,true,5.0+verz*0.5,false);
		lok.PushActionShowHide(ACTION_INSERT,false);
		lok.PushActionWait(ACTION_INSERT,verz*4.0);
	}

	void create_ehrang(GameObject *Caller)
	{
		// System::Log("Create Ehrang Train");
		Vehicle lok;
		Vehicle wagon1;
		Vehicle wagon2;
		Vehicle wagon3;
		Vehicle wagon4;
		float wartezeit;
		PathList pl("Gleis4");
		if (pl.GetNumPaths()>0)
			wartezeit=10+rand()%15*5;
		else {
			wartezeit=45;
			PathList pl("gleis2");
		}
		if (pl.GetNumPaths()>0) {
			Path p=pl.GetPath(0);
			p.SetOnFinishDeleteObject(false);
			lok=Game::CreateVehicle(PROTOVECS14,"ehrang");
			wagon1=Game::CreateVehicle(PROTOVECS15,"ehrang");
			wagon2=Game::CreateVehicle(PROTOVECS15,"ehrang");
			wagon3=Game::CreateVehicle(PROTOVECS15,"ehrang");
			wagon4=Game::CreateVehicle(PROTOVECS15,"ehrang");
			place_wagon(lok,&p,0);
			place_wagon(wagon1,&p,1);
			place_wagon(wagon2,&p,2);
			place_wagon(wagon3,&p,3);
			place_wagon(wagon4,&p,4);
			stop_gleis2.SetVirtualObjectTerrain("Person only");
			Caller->PushActionWait(ACTION_APPEND,wartezeit);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"ehrang_brennt",&lok,1,false);
		}
	}

	bool do_ehrang(GameObjectList ol, GameObject *Caller)
	{
		Vehicle v;

		char * fzkz[1];
		fzkz[0]="WitchDoc";

		int n=ol.GetNumObjects()-1;
		int x=int(rand()%n)+1;
		int q=int(rand()%n)+1;
		float alpha=rand()%180;

		//System::Log("Do Ehrang .. brennt %u, Leck an %u, drehen um %u",x,q,int(alpha));

		for (int i=0;i<ol.GetNumObjects();i++)
		{
			Vehicle v(ol.GetObject(i));
			v.PushActionExecuteCommand(ACTION_NEWLIST,"setggv",&v,8,false);
			v.SetSmokeLevelDuration(rand()%15+15.0f);
			if (i==x)
			{
				v.SetSmoking(true);
			} else if (i==q) {
				GameObject oel=Game::CreateObject("mod:Prototypes/Objects/Missionspec/fluessigkeit.e4p","ehrang");
				Vector hier=v.GetPosition();
				Game::FindFreePosition(&oel,hier);
				oel.SetPosition(hier);
				oel.SetRotation(&v);
				oel.SetUserData(1);
				oel.AssignCommand("gefahrgut");
				oel.PushActionExecuteCommand(ACTION_NEWLIST,"ggv_wirken",&oel,0,false);
				v.PushActionRotateTarget(ACTION_INSERT,&oel,alpha,0,0,0);
			}
		}

		Mission::PlayHint("WIB_WD_EHRANG");
		Game::ShowHelpText("WIB_WD_EHRANG");

		Vector Posabc=ol.GetObject(1)->GetPosition();
		eventid=Game::ShowEvent("WIB_WD_BRENNTZUG", Posabc);
		ScriptInterface::ShowBriefing();
		if (Caller->HasNamePrefix("FogOfDoc"))
			Caller->SetPosition(Posabc);
		Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,0,false);
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		if (ChildID>0)
		{
			GameObjectList ol("ehrang");
			if (ol.GetNumObjects()>0)
				do_ehrang(ol,Caller);
		} else if (stop_gleis2.IsValid())
				create_ehrang(Caller);
	}
};

bool deluxe=false;

object wtd_setver : CommandScript
{
	wtd_setver()
	{
		SetGroupID(20);
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		// System::Log("WTD Init");
		deluxe=(Caller->GetUserData() == 11);		
	}
};


object herborn_do : CommandScript
{
	herborn_do()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		// 1. Init
		punkte=50000;

		// 2. Gebaeudeobjekt suchen
		GameObjectList ohl=Game::GetGameObjects(TYPE_OPEN_HOUSE);
		int i=Math::rand()%ohl.GetNumObjects();
		for (bool do=true;do;i--)
		{
			OpenHouse hou(ohl.GetObject(i));
			do=(i>-1) && !hou.HasGroundEntrance();
		}

		if (hou.HasGroundEntrance())
		{
		
			FireObject fo;
			Vector hierhin=hou.GetEntrancePosition(true,0.f);
			Vehicle v=Game::CreateVehicle("mod:Prototypes/Vehicles/Winterberg/tanktruck01.e4p","HerbTank");
			GameObject lache=Game::CreateObject("mod:Prototypes/Objects/Missionspec/fluessigkeit.e4p","33HerbOel");
			v.SetChildEnabled("33",false);
			v.SetChildEnabled("201",false);
			v.SetChildEnabled("202",false);
			v.SetChildEnabled("203",false);
			v.SetChildEnabled("861",false);
			v.SetChildEnabled("862",false);
			v.SetChildEnabled("863",false);
			Game::FindFreePosition(&v,hierhin,50.0);

			//3. Explosion
			v.SetPosition(hierhin);
			v.PushActionTurnTo(ACTION_NEWLIST,&hou);
			lache.SetPosition(hierhin);
			lache.SetRotation(&v);
			v.SetSmokeLevelDuration(0);
			v.SetSmoking(true);
			v.SetParking(false);
	
			//4. Einsatzauftrag
			Audio::PlaySample("mod:Audio/FX/destruction/carcrash02.wav");
		
			// EventID-Code für Patch 1.3
			eventid=Game::ShowEvent("WIB_WD_TANKZUG", hierhin);

			Game::ShowHelpText("WIB_WD_HERBORN");
			Mission::PlayHint("WIB_WD_HERBORN");
			ScriptInterface::ShowBriefing();
			if (Caller->HasNamePrefix("FogOfDoc"))
				Caller->SetPosition(hierhin);
			Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,20,false);
		} 
	}
};

object sniper_do : CommandScript
{
	sniper_do()
	{
		SetIcon("shoot");   
		SetCursor("shoot");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		// 1. Init
		punkte=2000;
		int eid=-1;

		// 2. Fussgaenger suchen
		Actor *a = disaster::GetFocus(1);
		if (a->IsValid()) {
			GameObject o(a);
			Person p=Game::CreatePerson("mod:Prototypes/Persons/Civil/gangster02.e4p",a->GetName());
			p.SetPosition(o.GetPosition());
			o.Hide();
		
			System::Log("Sniper selected Name %s",p.GetName());
			// 3. EquipEm
			p.SetRole(ROLE_GANGSTER);
			p.SetBehaviour(BEHAVIOUR_GANGSTER_CIVILARMED);
			// p.PushActionWait(ACTION_NEWLIST,1.0);
			p.PushActionGetEquipment(ACTION_NEWLIST,&p,EQUIP_RIFLE);
			p.SetShootPower(700.0);
			p.SetShootFrequency(10.0);
			p.SetShootRange(750.0);
			System::Log("Sniper Equipped");
			//4. Einsatzauftrag
			Audio::PlaySample(hatalarm);
			Vector hierhin=p.GetPosition();
		
			// EventID-Code für Patch 1.3
			eid=Game::ShowEvent("WEM_HATA_SNIPE", hierhin);

			Game::ShowHelpText("WIB_WD_SNIPER");
			ScriptInterface::ShowBriefing();
			if (Caller->HasNamePrefix("FogOfDoc"))
				Caller->SetPosition(hierhin);
			GameObject watch=Game::CreateObject("mod:Prototypes/Objects/Equipment/parken.e4p","WitchDcCore");
			watch.SetUserData(punkte);
			System::Log("Sniper Go");
			// watch.PushActionExecuteCommand(ACTION_NEWLIST,"CheckEOShooting",&p,eid,false);
			watch.PushActionExecuteCommand(ACTION_NEWLIST,"shootem",&p,eid,false);
		}
	}
};


object shootem: CommandScript
{
	shootem()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int eid)
	{
		if (Target->IsValid()) {
			Person p(Target);
			System::Log("Sniper Check %s ",Target->GetName());
			if (p.IsInjured() || p.IsDead() || p.IsArrested()) {
				if (p.IsInjured())
					Caller->SetUserData(Caller->GetUserData()/2);
				Caller->PushActionExecuteCommand(ACTION_NEWLIST,"hata_checkobj",Target,eid,false);
			} else {
				float actrange=600.0;
				GameObjectList tl=p.GetObjectsInRange(actrange, ACTOR_PERSON); // | ACTOR_VEHICLE);
				int tarnum=tl.GetNumObjects();
				if (tarnum>0) {
					System::Log("Sniper Target selected");
					GameObject snipetarget=tl.GetObject(rand()%tl.GetNumObjects());
					System::Log("SHOOT!  -> %s",snipetarget.GetName());
					p.PushActionExecuteCommand(ACTION_NEWLIST,"shoot",&snipetarget,0,false);
 				} else
					System::Log("I dont hate those targets enough");
				Caller->PushActionWait(ACTION_NEWLIST,2.0);			
				Caller->PushActionExecuteCommand(ACTION_APPEND,"shootem",&p,eid,false);
			}
		}
	}
};


object hata_checkobj: CommandScript
{
	hata_checkobj()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int eid)
	{
		bool success=true;
		bool fertig=!Target->IsValid();
		if (!fertig) {
			Person p(Target);
			fertig=p.IsDead();
			success=false;
		}
		if (fertig) {
			Game::SetEventFinished(eid, success, Caller->GetUserData()); 
			Caller->PushActionDeleteOwner(ACTION_NEWLIST);
		} else {
			if (!Caller->HasAnyAction())
				Caller->PushActionWait(ACTION_APPEND,2.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"hata_checkobj",Target,eid,false);
		}
	}
};


int opfer;

object messer_do : CommandScript
{
	messer_do()
	{
		SetIcon("ekgm");   
		SetCursor("ekgm");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		// 1. Init
		int punkte=1000;
		int i=-1;
		int eid=-1;

		Actor *act=disaster::GetFocus(1);
		Person killed(act);
		if (killed.IsValid())
		{
			Vector hierhin;
			hierhin=killed.GetPosition();
			int switch=rand()%18;
			if (ChildID>0) {
				switch=ChildID;
			} 

			ActorList al("aqua");
			if (al.GetNumActors()==0)
				switch+=3;

			if (switch>12)
			{
				killed.Injure (INJUREREASON_SHOT,true);
				killed.AssignCommand("crime");
				int injcode=(rand()%3+1) < 1;
				if (injcode & trauma_pneu)
					if (rand()%10>7)
						injcode=injcode|med_buelau;
				killed.SetUserData(injcode|trauma_blutung|200);		
				killed.PushActionExecuteCommand(ACTION_NEWLIST,"art_blutung",&killed,0,false);
				// EventID-Code für Patch 1.3
				eid=Game::ShowEvent("WIB_WD_PMESS", hierhin);
				Game::ShowHelpText("WIB_WD_MESSER");
				Mission::PlayHint("WIB_WD_MESSER");
				punkte+=1000;
			} else if (switch>2) {
				killed.Injure (INJUREREASON_UNKNOWN,true);
				killed.PushActionWait(ACTION_NEWLIST,0.1);
				killed.SetInjuredLifeDrain(0.2+(rand()%20/10));
				eid=Game::ShowEvent("WIB_WD_PHILO", hierhin);
				Game::ShowHelpText("WIB_WD_PHILOHINT");
				killed.SetAnimation("sitdown02");
				if (rand()%10>6)
					killed.SetEquipment(EQUIP_BOTTLE);				
				punkte=250;
			} else {
				killed.Injure (INJUREREASON_DROWN,true);
				i=Math::rand()%al.GetNumActors();
				hierhin=al.GetActor(i)->GetPosition();
				// System::Log("Person im Wasser Nr %u -> Name %s",i,al.GetActor(i)->GetName());
				killed.SetPlacement(PLACEMENT_AXISALIGNED);
				killed.UpdatePlacement();
				killed.ComputePlacement(hierhin.x,hierhin.y,hierhin.z);
				killed.SetPosition(hierhin);
				killed.SetAnimation("drown1");
				eid=Game::ShowEvent("ID_FREEPLAY_EVENT_SUICIDE", hierhin);
				Game::ShowHelpText("WIB_WD_PIW");
				Mission::PlayHint("ID_FREEPLAY_EVENT_SUICIDE");
			}

			Audio::PlaySample(hatalarm);					
			if (Caller->HasNamePrefix("FogOfDoc"))
				Caller->SetPosition(hierhin);
			GameObject watch=Game::CreateObject("mod:Prototypes/Objects/Equipment/parken.e4p","WitchDcCore");
			watch.SetUserData(punkte);
			watch.PushActionWait(ACTION_NEWLIST,3.0);
			watch.PushActionExecuteCommand(ACTION_APPEND,"hata_checkobj",&killed,eid,false);
		}
	}
};

object kann_ich_schon_raus : CommandScript
{
	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Vehicle lok(Target);
		if (lok.IsCollidingWithVirtualObject("stop_regio"))
		{
			Caller->PushActionExecuteCommand(ACTION_NEWLIST,"ruess_do",&lok,11,false);
		} else {
			Caller->PushActionWait(ACTION_NEWLIST,1.5);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"kann_ich_schon_raus",&lok,0,false);
		}	
	}
};

object ruess_do : CommandScript
{

	ruess_do()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void check_aussteigen (Vehicle *wagon) 
	{
		// System::Log("RegioExpress Checker :) ");
		PersonList pl=wagon->GetPassengers();
		pl.GetPerson(0)->PushActionExecuteCommand(ACTION_NEWLIST,"kann_ich_schon_raus",wagon,0,false);
	}

	void place_wagon(Vehicle lok, Path *p, int verz)
	{
		Person *dummy;
		lok.Hide();
		lok.SetPosition(p->GetStartPosition());
		lok.SetVehicleRole(VT_BUS);
		lok.SetMaxPassengers(12);
		int max=rand()%12+1;
		for (int i=0;i<max;i++)
			disaster::Person_insFz(&lok,"bahnreise",dummy,false);
		lok.PushActionUsePath(ACTION_NEWLIST,p,true,7.5,true);
		lok.PushActionShowHide(ACTION_INSERT,false);
		lok.PushActionWait(ACTION_INSERT,verz*3.0);
		if (verz==0)
			check_aussteigen(&lok);
	}

	void create_ruess(int code,GameObject *Caller)
	{
		// System::Log("Create RegioExpress Code %u",code);
		Vehicle lok;
		Vehicle wagon1;
		Vehicle wagon2;
		Path p=gleis_1;
		if (eventid!=-1)
			code=10;
		float wartezeit;
		p.SetOnFinishDeleteObject(false);
		lok=Game::CreateVehicle(PROTOVECS17,"regio");
		wagon1=Game::CreateVehicle(PROTOVECS17,"regio");
		wagon2=Game::CreateVehicle(PROTOVECS17,"regio");
		int verz=0;
		if (code==0)
			verz++;
		place_wagon(lok,&p,verz);
		verz++;
		place_wagon(wagon1,&p,verz);
		verz++;
		place_wagon(wagon2,&p,verz);
		if (MissionMode)
			wartezeit=25+rand()%8*5;
		else
			wartezeit=20;

		// Code = 0 -> trad. Ruesselsheim Event mit entgleistem Zug
		// Code = 10 -> RegioExpress fährt ein, Passagiere rein/raus und Zug weg

		if (!code) {
			stop_gleis1.SetVirtualObjectTerrain("Freely accessible");
			Caller->PushActionWait(ACTION_APPEND,wartezeit);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"ruess_do",&lok,1,false);
		} else {
			stop_gleis1.SetVirtualObjectTerrain("Person only");
		}
	}

	void do_regio (GameObjectList ol, int direction, GameObject *Caller)
	{
		// System::Log("Do regio Start %u Wagons",ol.GetNumObjects());
		Caller->PushActionWait(ACTION_NEWLIST,2.0);
		for (int i=ol.GetNumObjects();i>0;i--)
		{
			Vehicle v(ol.GetObject(i-1));
			// System::Log("Do Regio %u Dir %u ",i-1,direction);
			if (direction==1)
				Caller->PushActionExecuteCommand(ACTION_APPEND,"regio_aussteigen",&v,i-1,false);
			 else
				Caller->PushActionExecuteCommand(ACTION_APPEND,"bahnhof_verlassen",&v,0,false);
		}
		if (direction==1)
		{
			Caller->PushActionWait(ACTION_APPEND,7.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"ruess_do",&v,21,false);
		}
	}

	void do_ruess(GameObjectList ol,GameObject *Caller)
	{
		Vehicle v;
		// System::Log("Do Regio Go ");
		punkte=15000;

		char * fzkz[1];
		fzkz[0]="WitchDoc";

		for (int x=0;x<ol.GetNumObjects();x++)
		{
			Vehicle v(ol.GetObject(x));
			v.Show();
			v.PushActionExecuteCommand(ACTION_NEWLIST,"setggv",&v,8,false);
			int w=rand()%11;
			if (7 < w)
			{
				System::Error("eingeklemmte Person erzeugen");
				int index = rand()%MAX_PROTONAMES;
				fzkz[0][5]=char(x+32);
				Person pat = Game::CreatePerson(prototypes[index], fzkz[0]);
				if (v.SetEnclosedPerson(fzkz[0]))
				{
					float val=rand()%300+500;
					pat.Injure(INJUREREASON_ENERGY,true);
					pat.SetLife(val);
					float val=rand()%2+0.5;
					pat.SetInjuredLifeDrain(val);
					punkte=punkte+1000;
				} 
			}

		}

		int q=Math::rand()%50+20;

		int n_pat=disaster::Verletzte_streuen(ol.GetObject(x/2),q,1500,"regio",false,false);
		
		punkte=punkte+500*n_pat;

		Audio::PlaySample("mod:Audio/FX/destruction/carcrash02.wav");
		
		// EventID-Code für Patch 1.3
		Vector Posabc=ol.GetObject(1)->GetPosition();
		eventid=Game::ShowEvent("WIB_WD_VUBAHN", Posabc);

		Game::ShowHelpText("WIB_WD_SBAHN");
		Mission::PlayHint("WIB_WD_SBAHN");
		ScriptInterface::ShowBriefing();
		if (Caller->HasNamePrefix("FogOfDoc"))
			Caller->SetPosition(Posabc);

		Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,50,false);
	
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{

		System::Error("Ruesselsheim: Jetzt gehts los ! Code %u",code);
		
		GameObjectList ol("regio");
		if (ol.GetNumObjects()>0)
			switch (code)
			{
				case 1:
					do_ruess(ol,Caller);
					break;
				case 11:
					do_regio(ol,1,Caller);
					break;
				case 21:
					gleis_1.SetOnFinishDeleteObject(true);
					if (MissionMode)
						stop_gleis1.SetVirtualObjectTerrain("Freely accessible"); // Gilt so Nur auf der ChemieMap;
					else
						do_regio(ol,0,Caller);
					break;
			}
		else 	if (gleis_1.IsValid())
				create_ruess(code,Caller);
			else
				System::Log("Kein Gleis fuer Regionalexpress");

	}
};

object regio_aussteigen : CommandScript
{

	regio_aussteigen()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int gruppe)
	{
		Vehicle v(Target);
		// System::Log("Regio aussteigen Anz Passagiere %u",v.GetNumPassengers());
		GameObjectList passl;
		if (bahnsteig.IsValid())
			Game::CollectObstaclesOnPath("Bahnhof",passl);
		// System::Log("Passagiere warten auf dem Bahnsteig %u",passl.GetNumObjects());
		PersonList pl=v.GetPassengers();
		bool nobus=!bahnbus.IsValid();
		for (int i=pl.GetNumPersons();i>0;i--)
		{
			Person p=pl.GetPerson(i-1);
			if (p.GetID()!=Caller->GetID())
			{
				p.PushActionLeaveCar(ACTION_NEWLIST,&v);
				if (bahnsteig.IsValid()) {
					if (nobus || rand()%10>3)
					
						p.PushActionUsePath(ACTION_APPEND,&bahnbus,true,4.0,false);
					else 
						p.PushActionUsePath(ACTION_APPEND,&bahnsteig,(rand()%2)>0,3.0,false);
				} else 
					p.PushActionDisappear (ACTION_APPEND,15.0,5.0,true);
			}
		}
		int getem=gruppe;
		for (i=0;i<passl.GetNumObjects();i++)
		{
			//System::Log("Passagiere einsteigen Gruppe %u Nr %u von %u",gruppe,i,passl.GetNumObjects());
			if (passl.GetObject(i)->GetType()==ACTOR_PERSON)
			{
				getem--;
				if (getem<0)
				{
					Person pass(passl.GetObject(i));
					if (!pass.IsDead() && !pass.IsInjured()) {
						pass.PushActionMove(ACTION_NEWLIST,Target,TARGET_PASSENGERDOOR,false);
						pass.PushActionEnterCar(ACTION_APPEND,Target);
						getem=2;
					}
				}
			}
		}
	}
};

object bahnhof_verlassen : CommandScript
{

	bahnhof_verlassen()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		// System::Log("Bahnhof verlassen %s ",Target->GetName());
		Vehicle v(Target);
		v.PushActionUsePath(ACTION_NEWLIST,&gleis_1,MissionMode,6.0,false);
	}
};

object plane_crash : CommandScript
{
	plane_crash()
	{
		SetIcon("kats");   
		SetCursor("kats");
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		Vector Pos;
		int n_pat=0;
		int punkte=0;

		System::Error("Flugzeugabsturz: Jetzt gehts los !");
		GameObject watch=Game::CreateObject("mod:Prototypes/Objects/Equipment/parken.e4p","WitchDcCore");
		char *buf="               ";
		snprintf(buf,15,"VU%u",watch.GetID());
			
		Pos=disaster::incident_pos(0);
		GameObject plane=Game::CreateObject("mod:Prototypes/Objects/airport/airplane01.e4p",buf);
		plane.SetPlacement(PLACEMENT_NONE);
		plane.ComputePlacement(Pos.x,Pos.y,Pos.z);
		Pos.z-=40;
		plane.SetPosition(Pos);
		plane.SetFlags (OF_TRANSPORTABLE|OF_COOLABLE);

		punkte=15000;

		int q=Math::rand()%40+50;
		n_pat=disaster::Verletzte_streuen(&plane,q,rand()%500+800,buf,false,false);
		disaster::feuer_machen(&plane);

		GameObjectList ol=plane.GetObjectsInRange(rand()%500+500,ACTOR_OBJECT);
		FireObject fob;
		for (int x=0;x<ol.GetNumObjects();x++)
			if (ol.GetObject(x)->HasFireChilds())
				disaster::feuer_legen(ol.GetObject(x),&plane);		
		
		punkte=punkte+500*n_pat;

		Audio::PlaySample("mod:Audio/FX/destruction/carcrash02.wav");
		
		// EventID-Code für Patch 1.3
		int eid=Game::ShowEvent("WIB_WD_PLANE", Pos);

		Game::ShowHelpText("WIB_WD_PLANECRASH");
		Mission::PlayHint("WIB_WD_PLANECRASH");

		if (Caller->HasNamePrefix("FogOfDoc"))
			Caller->SetPosition(Pos);

		watch.SetUserData(punkte);
		watch.PushActionRotateTarget(ACTION_NEWLIST,&plane,-30.0,-50.0,0,0.0);
		watch.PushActionExecuteCommand(ACTION_APPEND,"hata_checkvu",&watch,eid,false);
	}
};

object ueberfall : CommandScript
{

	ueberfall()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		Actor Opfer;
		Vector Pos;
		Vector tuerpos;
		int index,q;
		bool razzia=ChildID>0;	
		// 1. Init
		if (razzia)
		{
			punkte=3000;
		} else {
			punkte=5000;
		}

		// 2. Gebaeudeobjekt suchen

		GameObjectList ohl=Game::GetGameObjects(TYPE_OPEN_HOUSE);
		int i=Math::rand()%ohl.GetNumObjects();
		for (bool do=true;do;i--)
		{
			OpenHouse hou(ohl.GetObject(i));
			do=(i>0) && !hou.HasGroundEntrance();
		}
		
		if (Caller->GetType()==ACTOR_OPEN_HOUSE)
			OpenHouse hou(Caller);
	
		if (hou.HasGroundEntrance() && !hou.IsLocked())
		{
			if (hou.IsLocked() && !razzia)
			{
				hou.ClearFlag(OF_LOCKED);
				hou.OpenDoor(hou.GetEntranceDoorID());				
			}
			tuerpos=hou.GetEntrancePosition(true,0.f);
			
			PersonList ol=hou.GetNonSquadPersonsInside();
			// FireObjectList fl;
			// bool jo=hou.GetInhouseFires(fl);
			int no=0;
			bool FluFz=false;
			Vehicle ffz;

			if (razzia)
			{
				q=2+rand()%4;
			} else {				
				q=3+rand()%6;
				GameObjectList vl=hou.GetObjectsInRange(700,ACTOR_VEHICLE);
				bool weiter=vl.GetNumObjects()>0;
				if (weiter)
				{
			
					int k=rand()%vl.GetNumObjects();				
					for (i=k;weiter;i--)
					{
						Vehicle v(vl.GetObject(i));
						FluFz=v.IsParking() && v.IsCivilCar();
						if (i==0)
							i=vl.GetNumObjects();
						weiter=!FluFz && i!=k+1;
					}
				}
			}

			if (FluFz)
			{
				ffz=Game::CreateVehicle(v.GetPrototypeFileName(),"ueberfall");
				ffz.Hide();
				ffz.SetVehicleRole(VT_BUS);
				ffz.SetMaxPassengers(9);
				ffz.SetMaxTransports(9);
				ffz.SetCommandable(true);
				ffz.SetAutoShoot(true);
				ffz.AddRifleToGetawayCar();
				ffz.ClearFlag(OF_TRANSPORTABLE);
				ffz.SetRotation(&v);
				ffz.SetParking(false);
				ffz.SetSpeed(18);
				int a;
				a=disaster::hmin();
				if (a>2399)
					a=a-23;
				a=a+rand()%75+100;	// Fluchtzeitpunkt festlegen
				ffz.PushActionExecuteCommand(ACTION_NEWLIST,"waehle_klinik",&ffz,0,false);
				ffz.PushActionExecuteCommand(ACTION_APPEND,"ueb_flufz_pos",&v,0,false);
				ffz.PushActionExecuteCommand(ACTION_APPEND,"ueb_flufz_flucht",&ffz,a,false);
			} 
	
			for(i = q; i > 0; i--)
			{
				System::Error("Taeter erzeugen");
				int index = rand()%MAX_PROTOTYPES;
				Person p = Game::CreatePerson(prototypes[index], "ueberfall");
				Pos=tuerpos;
				// p.SetEnteredHouseID(hou.GetID());
				Game::FindAvailablePosition(&p,Pos,400,false);
				p.SetPosition(Pos);
				punkte=punkte+500;
				p.SetRole(ROLE_GANGSTER);
				p.SetFleeing(true);
				if (razzia)
					p.SetBehaviour(BEHAVIOUR_GANGSTER_CIVILARMED);
				else
					p.SetBehaviour(BEHAVIOUR_GANGSTER_CIVILARMED);
				p.SetDisableGangsterSymbol(true);
				p.SetCivilsFleeing(false);
				if (!razzia || Math::rand()%10>7)
					p.PushActionEquipWeapon(ACTION_NEWLIST, true);
				if (!razzia)
					p.SetShootFrequency(rand()%5+2);
				if (rand()%10>5)
					p.SetShootAtPsychologist(true);
				p.PushActionMove(ACTION_NEWLIST,tuerpos,true);
				p.PushActionEnterHouse(ACTION_APPEND,&hou);

				if (no==0)
					no=ol.GetNumPersons();
				if (no>0)
				{
					no--;
					p.SetPrimaryTarget(ol.GetPerson(no));
					p.PushActionMove(ACTION_APPEND,ol.GetPerson(no),TARGET_TOUCHPERSON);
				}

				if (!razzia) switch (i)
				{
					case 1:
					case 2:
						p.PushActionExecuteCommand(ACTION_APPEND,"ueb_setbev",&p,BEHAVIOUR_GANGSTER_GUARDPASSAGE,false);
						break;
					default:
						p.PushActionExecuteCommand(ACTION_APPEND,"ueb_setbev",&p,BEHAVIOUR_GANGSTER_ATTACKSQUAD_SMART,false);
						break;
				}
			}

			if (razzia)
			{
				int x=Math::rand()%5;
				GameObject beweis = Game::CreateObject(beweismittel[x], "beweis");
				// System::Log(beweismittel [x]);
				Pos=tuerpos;
				beweis.ClearFlags();
				beweis.SetPlacement(PLACEMENT_ALIGNED_CORNERS);
				beweis.UpdatePlacement();
				beweis.SetFlag(OF_RECOVERABLE|OF_PULLABLE|OF_TRANSPORTABLE);
				Game::FindAvailablePosition(&beweis,Pos,450,false);
				beweis.ComputePlacement(Pos.x,Pos.y,Pos.z);
				Pos.z=Game::GetFloorHeight(Pos.x,Pos.y);
				beweis.SetPosition(Pos);
			
				p.PushActionExecuteCommand(ACTION_NEWLIST,"razzia_entdeckt",&hou,0,false);
				eventid=Game::ShowEvent("WIB_WD_POLR", tuerpos);
				Game::ShowHelpText("WIB_WD_RAZZIA");
			} else {
				eventid=Game::ShowEvent("WIB_WD_POLU", tuerpos);
				Game::ShowHelpText("WIB_WD_UEBERFALL");
			}

			Audio::PlaySample(hatalarm);					
			if (razzia)
				int code=90;
			else
				int code=70;
			if (Caller->HasNamePrefix("FogOfDoc"))
				Caller->SetPosition(tuerpos);
			Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&ffz,code,false);
		} 
	}
};

object razzia_entdeckt : CommandScript
{

	razzia_entdeckt()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		switch (ChildID)
		{
			case 0:
				Caller->PushActionWait(ACTION_NEWLIST,5.0);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"razzia_entdeckt",Target,1,false);
				break;
			case 1:
				OpenHouse hou(Target);
				if (hou.IsCeilingOpen())
				{
					Caller->PushActionWait(ACTION_NEWLIST,35.0);
					Caller->PushActionExecuteCommand(ACTION_APPEND,"razzia_entdeckt",Target,2,false);
				} else {
					Caller->PushActionWait(ACTION_NEWLIST,5.0);
					Caller->PushActionExecuteCommand(ACTION_APPEND,"razzia_entdeckt",Target,1,false);
				}
				break;
			case 2:
				Mission::PlayHint("WIB_WD_RAZZIA_FOUND");
				PersonList pl(Caller->GetName());
				for (int i=0;i<pl.GetNumPersons();i++)
				{
					pl.GetPerson(i)->SetBehaviour(BEHAVIOUR_GANGSTER_ATTACKSQUAD_SMART);
					pl.GetPerson(i)->SetShootFrequency(rand());
				}
				break;
		}
	}
};

object ueb_flufz_pos : CommandScript
{

	ueb_flufz_pos()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vector start=Target->GetPosition();
		Vector ziel=Caller->GetPosition();
		GameObject o(Target);
		Game::RemoveGameObject(&o);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"WT_SoSi",Caller,100,false);
		Caller->PushActionMove(ACTION_APPEND,ziel);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"WT_SoSi",Caller,1,false);
		Caller->PushActionShowHide(ACTION_APPEND,true);
		Caller->SetPosition(start);
		Caller->PushActionShowHide(ACTION_INSERT,false);
	}
};

object ueb_flufz_flucht : CommandScript
{

	ueb_flufz_flucht()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		if (disaster::hmin()<ChildID)
		{
			Caller->PushActionExecuteCommand(ACTION_INSERT,"ueb_flufz_flucht",Caller,ChildID,false);
			Caller->PushActionWait(ACTION_INSERT,7.0);
		} else {
			Caller->PushActionWait(ACTION_INSERT,50.0f);
			Caller->PushActionExecuteCommand(ACTION_INSERT,"aufsitzen",Caller,666,false);
		}
	}
};

object ueb_setbev : CommandScript
{

	ueb_setbev()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Person p(Caller);
		p.SetBehaviour(ChildID);
	}
};

const char * baume[10];
baume[0]="mod:Prototypes/Objects/Trees/brokentree01a.e4p";
baume[1]="mod:Prototypes/Objects/Trees/brokentree01b.e4p";
baume[2]="mod:Prototypes/Objects/Trees/brokentree01c.e4p";
baume[3]="mod:Prototypes/Objects/Trees/brokentree01d.e4p";
baume[4]="mod:Prototypes/Objects/Trees/brokentree02a.e4p";
baume[5]="mod:Prototypes/Objects/Trees/brokentree02b.e4p";

object emma : CommandScript
{

	emma()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Vector start;
		Vector TargetPos;
		bool nachhut=ChildID>0;

		VehicleList markit(VT_THW_FGRR_TRL,VT_THW_FGRR_TRL);
		int nmark=markit.GetNumVehicles();

		Weather::SetFlashVisible(false);
		Weather::SetSnowVisible(true);
		Weather::SetRainVisible(true);
		Weather::SetRainIntensity(0.7);
		Weather::SetStormVisible(true);
		Weather::SetStormIntensity(0.5);
		Weather::SetStormSpeed(0.4);
		Weather::SetFogVisible(true);
		Weather::SetFogIntensity(0.4);

		if (nachhut)
			Game::ShowHelpText("WIB_WD_EMMA_NOCHMAL");
		else
			Game::ShowHelpText("WIB_WD_EMMA");

		Baumliste=Game::GetGameObjectsWithPrefix("wib_baum");

		if (!nachhut)
			punkte=2000;
		int k=rand()%10+7;
		if (nachhut)
			k=ChildID;

		for (int n=k;n>0;n--)
		{
			Ehranger.PushActionWait(ACTION_INSERT,3+rand()%10);
			Ehranger.PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"emma_throw",Caller,n,false);
		}
		emmatime=disaster::hmin()+360+rand()%120;
		if (!nachhut)
		{
			eventid=Game::ShowEvent("WIB_WD_ORK1",Caller->GetPosition());
			Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,25,false);
			emmatime=disaster::hmin()+360+rand()%200;
			Audio::PlaySample(hatalarm);					
		} else 
			emmatime=disaster::hmin()+480+rand()%240;
	}
};

object emma_throw : CommandScript
{
	emma_throw()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int n)
	{
		int x=disaster::wirf_baum(n);
	}
};

object emma_clear_mark : CommandScript
{
	emma_clear_mark()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		if (Target->IsValid())
		{
			Caller->PushActionWait(ACTION_NEWLIST,10.0f);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"emma_clear_mark",Target,0,false);
		} else
			Caller->Hide();			
	}
};

class disaster : CommandScript
{

	const int gsize=2;

	bool infolevel (int breakeven)
	{
		return rand()%100 < breakeven;
	}

	void verkehr_aktiv (int x,bool aktiv,int max, bool gruppe)
	{
		// System::Log("Verkehr schalten %u",x);
		int add;
		if (gruppe)
			add=3;
		else
			add=max;
		for (int i=x;i<=max;i=i+add)
		{
			SpawnPoint sp(traffic[i]);
			sp.SetEnabled(aktiv);
			// System::Log("Pfad %s geschaltet auf %u",sp.GetName(),int(aktiv));
		}
	}

	bool Person_insFz(Vehicle *fz, char *opfer,Person *pers,bool einklemmen)
	{
		Person p;

		//System::Log("Person einklemmen %s Fz %s",opfer,fz->GetName());
		int index = rand()%MAX_PROTONAMES;
		bool ok=true;
		p = Game::CreatePerson(prototypes[index], opfer);
		if (!p.IsValid())
		{
			// System::Log("Disaster Invalid Person %s",prototypes[index]);
			return false;
		} 
		if (einklemmen)
			ok=fz->SetEnclosedPerson(opfer);
		else {
			p.SetUserData(fz->GetID());
			fz->AddPassenger(&p);
		}
		if (ok && einklemmen)
		{
			p.Injure(INJUREREASON_ENERGY,true);
			medisim::injure(p,800,200,0.5);
		}
		//System::Log("Person ins Fz verbracht");
		pers=&p;
		return ok;	
	}
	
	int hmin()
	{
		int a,b,c;
		Game::GetTime(a,b,c);
		return a*100+b;
	}

	Vector incident_pos(int code)
	{
		Path path;
		int i;
		
		if (code==0) {
			i=Math::rand()%3+1;	
			char * bhf="             ";
			char * zugname="traffic_car0%u";
			snprintf(bhf,13,zugname,i);
			PathList pl(bhf);
			path=pl.GetPath(0);
		} else if (code==2) {
			ActorList al=Game::GetActors(ACTOR_PATH);
			Path path(al.GetActor(Math::rand()%al.GetNumActors()));
			System::Log("MERS-Pfad %s mit %u Punkten",path.GetName(),path.GetNumPoints());
		} else if (code==1)
				path=sportboot;
			else
				path=frachter;

		i=path.GetNumPoints()-4;

		if (i>0)
		{
			Vector Crash=path.GetPoint(Math::rand()%i+2);
			Crash.z=Game::GetFloorHeight(Crash.x,Crash.y);
		} else
			Vector Crash=Vector (0,0,0);

		// System::Log("Incident Post Code %u i=%u, X : %u Y : %u",code,i,Crash.x,Crash.y);

		return Crash;
	}

	Vector zielpos (Actor *host, Actor *client)
	{
		Vehicle transporter(host);
		Vehicle vehicle(client);
		float dx, dy, dz;
		Vector VehiclePos = transporter.GetPosition();
		Vector TargetPos;
		vehicle.GetLookatDir(dx, dy, dz);
		TargetPos = VehiclePos + transporter.GetLookatDir()*(vehicle.GetBoundingRadiusXY() + transporter.GetBoundingRadiusXY());
		return TargetPos;
	}

	int  wirf_baum(int mx)
	{
		char * fzkz[2];
		fzkz[0]="emma%u";
		fzkz[1]="          ";
		int erg;
		Person p;
		
		// eeeevil
		if (Baumliste.GetNumObjects()==0) 
			return;

		Vector start=Baumliste.GetObject(rand()%Baumliste.GetNumObjects())->GetPosition();
		int bx=rand()%6;
		GameObject baum=Game::CreateObject(baume[bx],"emma");
		baum.SetFlags(OF_CUTABLE|OF_RECOVERABLE);
		baum.ClearFlag(OF_PULLABLE);
		Vector TargetPos=disaster::incident_pos(0);
		Game::FindFreePosition(&baum,TargetPos,50.0);
		baum.SetPosition(start);
		punkte+=250;
		GameObject ziel=baum.GetClosestObjectInRange(2000,800,ACTOR_PERSON|ACTOR_VEHICLE);

		for (mx;mx<nmark && !markit.GetVehicle(mx)->IsHidden();mx++);
		if (mx>=nmark)
			Vehicle marker=Game::CreateVehicle("mod:prototypes/vehicles/TEC/emma.e4p","marker");
		else 
			Vehicle marker=markit.GetVehicle(mx);
		marker.Hide();

		//System::Log("Baum werfen");

		if (ziel.IsValid() && ziel.IsInsideMap() && rand()%10>4 &&!ziel.IsFlagSet(OF_BLOCKED))
		{
			if (ziel.GetType()==ACTOR_PERSON)
			{
				Person zp(&ziel);
				if (zp.GetEnteredHouseID()<1)
				{
					float val=rand()%400+300;
					zp.Injure(INJUREREASON_ENERGY,true);
					zp.SetLife(val);
					float val=rand()%2+0.5;
					zp.SetInjuredLifeDrain(val);
					punkte+=1000;
				} else {
					//System::Log("Person im Haus");
					Actor h=Game::GetActor(zp.GetEnteredHouseID());
					GameObject ziel(&h);
					OpenHouse oh(&h);
					if (oh.HasGroundEntrance())
					{
						TargetPos=oh.GetEntrancePosition(true);
						float val=rand()%400+300;
						zp.Injure(INJUREREASON_ENERGY,true);
						zp.SetLife(val);
						float val=rand()%2+0.5;
						zp.SetInjuredLifeDrain(val);
						punkte+=1000;
					} else 
						oh.GetOrientedBBoxPoint(6,TargetPos.x,TargetPos.y,TargetPos.z);
					oh.ShowCeiling(true,false,true);
					oh.SetCeilingCollision(true);
					punkte+=500;
				}			
			} else {
				erg=snprintf(fzkz[1],10,fzkz[0],mx);
				Vehicle v(&ziel);
				bool isHubi=v.GetVehicleType()==VT_AMBULANCE_RHC || v.GetVehicleType()==VT_POLICE_PHC || v.GetVehicleType()==VT_TV_HELI;
				if (isHubi && !v.IsOnGround())
					v.Explode();
				v.SetSmokeLevelDuration(30.0f);	
				v.SetSmoking(true);
				v.ClearActions();
				if (!v.IsParking() && (rand()%10>6 || v.IsCivilCar() ))
					if (disaster::Person_insFz(&v,fzkz[1],&p,true))
						punkte+=1500;
					else punkte+=500;
				else punkte+=500;
				v.SetSmoking(false);
			}
			if (rand()%10>7)
			{
				baum.ClearFlag(OF_CUTABLE);
				punkte+=500;
			}
			baum.SetRotation(&ziel);
			ziel.SetFlag(OF_BLOCKED);
			baum.SetUserData(ziel.GetID());
			if (ziel.GetType()!=ACTOR_OPEN_HOUSE)
				TargetPos=ziel.GetPosition();
		} 
		marker.SetPlacement(PLACEMENT_NONE);
		marker.SetPosition(TargetPos);
		baum.SetPlacement(PLACEMENT_NONE);
		baum.PushActionMoveToPoint(ACTION_NEWLIST,&marker,500.0,0.0);
		baum.PushActionExecuteCommand(ACTION_APPEND,"PosIt",&ziel,0,false);
		baum.PushActionExecuteCommand(ACTION_APPEND,"ShowIt",&marker,0,false);
		marker.ClearFlags();
		marker.PushActionWait(ACTION_NEWLIST,10.0f);
		marker.PushActionExecuteCommand(ACTION_APPEND,"emma_clear_mark",&baum,0,false);
		mx++;
		return mx;
	}

	int Verletzte_streuen (GameObject *unfall,int anz,int radius,char *name,bool bicycle,bool water)
	{
		Vector Pos=unfall->GetPosition();
		int diam=2*radius;
		int n_pat=0;
		Person p;
		float rot[9];
		float childRot[9];
		int winkel;
		Vector Posabc;
		bool im_wasser;

		unfall->GetRotation(rot[0], rot[1], rot[2], rot[3], rot[4], rot[5], rot[6], rot[7], rot[8]);

		for(int i = 0; i < anz; i++)
		{
			// System::Error("Verletzte verstreuen");
			Posabc=Pos+Vector(((rand()%diam)-radius),((rand()%diam)-radius),0);
			winkel = rand()%360;
			Math::EulerToMatrix(winkel, 0.f, 0.f, childRot);
			Math::MultiplyMatrices(childRot, rot);
			int index = rand()%MAX_PROTOTYPES;
			Person p = Game::CreatePerson(prototypes[index], name);
			p.SetRotation(childRot[0], childRot[1], childRot[2], childRot[3], childRot[4], childRot[5], childRot[6], childRot[7], childRot[8]);
			float val=300+rand()%500;
			if (bicycle)
				Posabc=zielpos(unfall,&p);
			else
				Game::FindAvailablePosition(&p,Posabc,300,false);
			p.SetPosition(Posabc);
			p.Injure(INJUREREASON_ENERGY,true);
			medisim::injure(p,800,200,0.2+rand()%4/10);
			n_pat++;
		}
		return n_pat;
	}

	void feuer_machen(Actor *obj)
	{
		System::Log("Jetz zerbeiss ichs");
		GameObject ofen(obj);
		if (ofen.GetNumFireChilds() > 0)
		{
			System::Log("%u FireChilds gefunden",ofen.GetNumFireChilds());
			int fx=rand()%ofen.GetNumFireChilds();
			System::Log("FC %u gwählt",fx);
			FireObject fob=ofen.GetFireChild(fx);
			System::Log("also AB ! %s",fob.GetName());
			ofen.SetFireObjectBurning(fob.GetName());
			// fob.SetActive(true);
			System::Log("jetz brennts ..");
		}
	}

	void feuer_legen(Actor  *obj, Actor *bma)
	{
		System::Log("Feuer legen %s %s",obj->GetName(),bma->GetName());

		GameObjectList ol;
		bool coll=bma->IsValid() && bma->GetType()==ACTOR_VEHICLE;

		if (coll)
			coll=Game::CollectObstaclesOnVirtualObject(bma->GetName(),ol,ACTOR_OBJECT);

		if (coll && rand()%10<7)
		{
			bool nochmal=ol.GetNumObjects()>0;
			GameObject feuer;
			for (int nix=0;nochmal;nix++)
			{
				// System::Log("Kleinfeuer suchen %s",bma->GetName());
				int go=rand()%ol.GetNumObjects();
				feuer=ol.GetObject(go);
				FireObject fob=feuer.GetFireChild(0);
				nochmal=StrCompare(fob.GetName(),"Kleinfeuer") && nix<10;
			}
			if (feuer.IsValid())
				feuer.SetFireObjectBurning("Kleinfeuer");
		} else {
			feuer_machen(obj);
			System::Log(" Streichholz aus");
		}
	}

	void aibalarm (Person p, int code)
	{
		//System::Log("AIB Alarm");
		int pc=p.GetID();
		GameObjectList ol=Game::GetGameObjectsWithPrefix("bett15");
		int weiter=-1;
		for (int i=0;weiter<0 && i<ol.GetNumObjects();i++)
		{
			if (ol.GetObject(i)->GetUserData()==pc)
				weiter=i;
		}
		if (weiter>-1)
		{
			char * action="         ";
			int j=snprintf(action,9,"ev%s",ol.GetObject(weiter)->GetName());
			GameObjectList ol(action);
			GameObject o=ol.GetObject(0);
			switch (code)
			{
				case 1:
					o.EnableTrafficLight(TLT_RED);
					o.PushActionExecuteCommand(ACTION_NEWLIST,"evitawatch",&p,0,false);
					Audio::PlaySample("mod:Audio/FX/ippvalarm.wav");
					break;
				case 0:
					o.EnableTrafficLight(TLT_NONE);
					break;
			}
		}
	}


	int actor_init (char * name)
	{
		int erg;
		ActorList al(name);
		// System::Log("Actor Init %s %u",name,al.GetNumActors());
		if (al.GetNumActors()>0)
			erg=al.GetActor(0)->GetID();
		else 
			erg=-1;
		return erg;
	}

	Actor actorget (char * name)
	{
		Actor erg;
		ActorList al(name);
		// System::Log("Actor Get %s %u",name,al.GetNumActors());
		if (al.GetNumActors()>0)
			erg=al.GetActor(0);
		return erg;
	}

	Actor *GetFocus (int code) 
	//
	//	1 -> Person wählen, 2 -> Fz wählen 
	{
		Actor a;
		
		switch (code)
		{
			case 1:
				Person p;
				PersonList pl(ROLE_CIVILIAN);
				int i=Math::rand()%pl.GetNumPersons();
				Person p=pl.GetPerson(i);
				bool move=rand()%6>1; // Person in Bewegung erzwingen ?
				for (i-=1;(!p.IsValid() || p.IsInjured() || !p.IsInsideMap() || p.IsDead() || p.IsLinkedWithPerson()||p.GetEnteredHouseID()>0 || p.IsMoving()!=move) && i>0;i--)
					p=pl.GetPerson(i);
				if (i>0)
					a=Actor(p);
				break;
		}

		return &a;
	}

	

};


object evitawatch : CommandScript
{
	evitawatch()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Person p(Target);
		if (p.IsCarried())
			disaster::aibalarm(p,0);
		else
		{
			Caller->PushActionWait(ACTION_APPEND,1.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"evitawatch",Target,0,false);
		}
	}
};

object deblock : CommandScript
{
	deblock()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		Actor a=Game::GetActor(ChildID);
		GameObject t(Target);
		t.SetFlags(OF_TRANSPORTABLE | OF_CUTABLE);
		GameObject o(&a);
		o.ClearFlag(OF_BLOCKED);
	}
};

object PosIt : CommandScript
{
	PosIt()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		GameObject ziel(Target);
		Vector l,r, Posabc;
		ziel.GetOrientedBBoxPoint(0,l.x,l.y,l.z);
		ziel.GetOrientedBBoxPoint(6,r.x,r.y,r.z);
		Posabc.x=(l.x+r.x)/2;
		Posabc.y=(l.y+r.y)/2;
		if (ziel.GetObjectType()==TYPE_HOUSE || ziel.GetObjectType()==TYPE_OPEN_HOUSE)
			Posabc.z=r.z;
		else
			Posabc.z=l.z;
		Caller->SetPosition(Posabc);
	}
};


object ShowIt : CommandScript
{
	ShowIt()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		GameObject o(Target);
		o.Show();
		Caller->SetPlacement(PLACEMENT_ALIGNED_CORNERS);
		Caller->UpdatePlacement();
		Caller->SetPosition(o.GetPosition());
	}
};

object randale_raeumen : CommandScript
{

	randale_raeumen()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		// System::Log("Randale aufloesen");
		PersonList pl(Caller->GetName());
		Person p,pn;
		for (int i=0;i<pl.GetNumPersons();i++)
		{
			p=pl.GetPerson(i);
			if (p.GetBehaviour()==BEHAVIOUR_GANGSTER_CIVILUNARMED))
			{
				// System::Log("Geeignete Person gefunden");
				if (rand()%10>7)
				{
					// System::Log("Person flieht");
					pn=Game::CreatePerson(p.GetPrototypeFileName(),"unnschuess");
					pn.Hide();
					pn.SetRotation(&p);
					pn.SetBehaviour(BEHAVIOUR_CIVILIAN_GAZER);
					pn.SetRole(ROLE_SQUAD);
					pn.SetPosition(&p);
					pn.Show();
					pn.PushActionMove(ACTION_NEWLIST,disaster::incident_pos(0));
					p.Hide();
					p.PushActionDeleteOwner(ACTION_NEWLIST);
				}
			}
		}
	}
};

object randale : CommandScript
{
	randale()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		Vector Pos;
		Vector Posabc;
		int i,q;
		char * brief;
		char * alarm;
		
		// 1. Init
		if (Math::rand()%100>90)
			int size=1;
		else
			int size=0;

		switch (size)
		{
			case 0 :	// nur Schlägerei
				punkte = 3000;  // Basispunkte
				int maxpers = 20;
				int basepers = 7;
				int maxweap = 22;
				int maxstone = 19;
				brief="WIB_WD_HITB";
				alarm="WIB_WD_HIT";
				break;
			case 1: 	// Studentenunruhe
				punkte = 7000;  // Basispunkte
				int maxpers = 50;
				int basepers = 25;
				int maxweap = 20;
				int maxstone = 15;
				brief="WIB_WD_HITD";
				alarm="WIB_WD_DEMO";
				break;
		}

		
								
		System::Log(brief);
		Pos=disaster::incident_pos(0);

		int q=Math::rand()%maxpers+basepers;
		int n_pat=q/10;
		int n_shoot=25;
		bool victim=false;
		Person Gegner;
		

		for(i = 0; i < q; i++)
		{
			System::Error("Schläger erzeugen");
			Posabc=Pos+Vector(((rand()%600)-300),((rand()%600)-300),0);
			int index = rand()%MAX_PROTOTYPES;
			Person p = Game::CreatePerson(prototypes[index], "randale");
			float val=rand()%300+600;
			Game::FindAvailablePosition(&p,Posabc,400,false);
			p.SetPosition(Posabc);
			punkte=punkte+500;
			if (n_pat>0)
			{
				p.Injure(INJUREREASON_ENERGY,true);
				p.SetLife(val);
				float val=rand()%2+0.7;
				p.SetInjuredLifeDrain(val);
				if (Math::rand()%10 > 7)
			 		p.PushActionExecuteCommand(ACTION_NEWLIST,"art_blutung",&p,0,false);
				n_pat--;	
			} else {
				p.SetRole(ROLE_GANGSTER);
				p.SetBehaviour(BEHAVIOUR_GANGSTER_FISTFIGHT);
				int j=Math::rand()%n_shoot;
				if (j>maxweap)
				{
					p.PushActionEquipWeapon(ACTION_NEWLIST, true);
					p.SetBehaviour(BEHAVIOUR_GANGSTER_ATTACKSQUAD);
					if (rand()%10>5)
						p.SetShootAtPsychologist(true);
					// p.SetShootFrequency(0.03);	
					punkte=punkte+250;
					n_shoot--;
				} else 
					if (j>maxstone)
						p.SetBehaviour(BEHAVIOUR_GANGSTER_THROWSTONES);
					else 	if (size>0)
						{
							p.SetBehaviour(BEHAVIOUR_GANGSTER_CIVILUNARMED);
							//p.PlaceObjectInRightHand("mod:Models/Objects/Equipment/demosign01.v3o");
							p.PushActionSwitchAnim(ACTION_NEWLIST,"demonstrate");
						} else {
							if (victim)
							{
								Gegner.PushActionMove(ACTION_NEWLIST,&p,TARGET_TOUCHPERSON);
								if (rand()%10>6)
									Gegner.PushActionFistFight(ACTION_APPEND,&p,false);
								// p.SetResistance(INJUREREASON_ENERGY,5000.0);
							}
							else
								Gegner=p;
							victim=!victim;
						}
					
			}
				
		}

		eventid=Game::ShowEvent(brief, Pos);
		Game::ShowHelpText(alarm);
		Audio::PlaySample(hatalarm);					

		if (Caller->HasNamePrefix("FogOfDoc"))
			Caller->SetPosition(Pos);
		Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,60,false);
	}
};


float ffw=4.0;

object Freiwillige : CommandScript
{
	Freiwillige()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int wache)
	{
		//System::Log("Freiwillige go");
		Caller->ChangePrototype(prototypes[rand()%5+2]);
		Caller->SetCommandable(false);
		Vector start;
		int max,min;
		char *spind="        ";
		snprintf(spind,8,"Spind%u",100+wache);
		char *pfad="       ";
		snprintf(pfad,7,"FFW%u",100+wache);
		char *gh="     ";
		snprintf(gh,5,"fw%u",100+wache);

		GameObjectList ol(spind);
		OpenHouseList oh(gh);
		PathList pl(pfad);

		Path p(pl.GetPath(0));
		min=0;max=p.GetNumPoints();
		start=p.GetPoint(rand()%(max-min)+min);
		Game::FindFreePosition(Caller,start,50);
		Caller->SetPosition(start);
		Person fw(Caller);
		fw.SetRole(ROLE_SQUAD);
		Caller->PushActionWait(ACTION_NEWLIST,1.0f+ffw);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"EnterHouse",oh.GetOpenHouse(0),112,true);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"DummyChange",ol.GetObject(0),41,false);
		ffw=ffw-.5f;
		if (ffw<0)
			ffw=4.0f;
	}
};

const int lifelim[4];
	lifelim[1]=340;
	lifelim[2]=250;
	lifelim[3]=250;


object wt_sekundaer : CommandScript
{

	wt_sekundaer()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		Person p(Target);
		bool ok=(p.GetLife()<500);
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		// System::Log("wt_sekundaer %u",ChildID);
		bool verlegen=false;
		bool notop=false;
		Person p(Target);
		int r=int(p.GetInjuryReason())+ChildID;
		switch (r)
		{
			case 2:
			case 3:
				notop=rand()%10>7;
			case 1:
				verlegen=p.GetLife()<lifelim[r] && !p.IsDead();
				if (notop)
				{
					Game::ShowHelpText("WIB_ICU_OP");
					int auftrag=Game::ShowEvent("WIB_WD_NOTOP",p.GetPosition());
					p.PushActionExecuteCommand(ACTION_NEWLIST,"art_blutung",&p,0,false);
					p.SetUserData(auftrag);
					p.SetFlag(FLAG_SOSI);		
					disaster::aibalarm(p,1);
				} else if (verlegen) {
					disaster::aibalarm(p,1);
					p.PushActionExecuteCommand(ACTION_NEWLIST,"wt_callsek",&p,r,false);		
				} else
					p.PushActionDeleteOwner(ACTION_NEWLIST);
				break;
			default:
				if (r>9)
				{
					Person pat = Game::CreatePerson(p.GetPrototypeFileName(), "WTSekVer");
					pat.Hide();
					pat.SetUserData(p.GetLife());
					pat.PushActionExecuteCommand(ACTION_NEWLIST,"wt_callsek",&pat,r,false);		
				} else {
					System::Log("Ungültiger Sekundärcode %s %u",p.GetName(),r);		
					p.PushActionDeleteOwner(ACTION_NEWLIST);
				}
				break;
		}
	}
};

	const char * grund[7];
		grund[1]="Verlegung ins Verbrennungsbett";
		grund[2]="Verlegung HTG";
		grund[3]="Verlegung Polytrauma";

	const InjuryReason ir[8];
		ir[0]=INJUREREASON_UNKNOWN;
		ir[1]=INJUREREASON_FIRE;
		ir[2]=INJUREREASON_SHOT;
		ir[3]=INJUREREASON_ENERGY;
		ir[4]=INJUREREASON_DROWN;
		ir[5]=INJUREREASON_CONTAM_ATOM;
		ir[6]=INJUREREASON_CONTAM_CHEM;
		ir[7]=INJUREREASON_CONTAM_BIO;

object wt_callsek : CommandScript
{

	wt_callsek()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PatInsBett(GameObject bett, Person p, int reason, int auftrag)
	{
				// System::Log("Ins Bett %s %u %u",bett.GetName(),bett.GetUserData(),p.GetID());
				Vector l,r, Posabc;
				bett.GetOrientedBBoxPoint(0,l.x,l.y,l.z);
				bett.GetOrientedBBoxPoint(6,r.x,r.y,r.z);
				Posabc.x=(l.x+r.x)/2;
				Posabc.y=(l.y+r.y)/2;
				Posabc.z=l.z+(r.z-l.z)*0.63;
				p.SetInjuredAnimation();
				if (auftrag>-1)
				{
					float val=rand()%200+200;
					if (p.GetRole()==ROLE_SQUAD)
						p.SetRole(ROLE_CIVILIAN);
					p.Injure(ir[reason],true);
					p.SetLife(p.GetUserData());
					p.SetMaxLife(p.GetUserData()*1.3);
					p.SetInjuredLifeDrain(0.3);
					p.SetClassified(true);
					p.SetEnteredHouseID(klinik);
				}
				p.SetPlacement(PLACEMENT_NONE);
				p.UpdatePlacement();
				p.FreezePhysics();
				p.SetPosition(Posabc);
				p.SetRotation(&bett);
				p.Show();
				bett.SetUserData(p.GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int reason)
	{

		// System::Log("WT_CALLSek %2.2f ",reason);
		Vector Posabc;
		Person p(Caller);
		GameObject o(Target);

		if (reason<0)
		{
			GameObject bett(Target);
			PatInsBett(bett,p,p.GetInjuryReason(),reason);
			if (reason==-1)
			{
				p.PushActionWait(ACTION_NEWLIST,15.0);
				p.PushActionDeleteOwner(ACTION_APPEND);
			} 
				
		} else if (reason<10) {
				Posabc=p.GetPosition();
				char * action="           ";
				char * zugname="WIB_SEKRD_%u";
				int j=snprintf(action,11,zugname,reason);
				int auftrag=Game::ShowEvent(grund[reason], Posabc);
				p.SetUserData(auftrag);
				p.SetFlag(FLAG_SOSI);
				p.SetHighlighted(true);
				p.SetInjuredLifeDrain(0.5);
				Game::ShowHelpText(action);
		} else {
			reason-=10;
			GameObjectList al=Game::GetGameObjectsWithPrefix("bett15");
			bool weiter=true;
			for (int i=al.GetNumObjects()-1;weiter;i--)
			{
				GameObject bett=al.GetObject(i);
				Actor a=Game::GetActor(bett.GetUserData());
				weiter=a.IsValid() && i>0 && a.GetID()!=p.GetID();
			}
			if (!a.IsValid() || a.GetID()==p.GetID())
			{	
				PatInsBett(bett,p,reason,reason);
				p.PushActionWait(ACTION_NEWLIST,10.0*(Math::rand()%10+3));
				p.PushActionExecuteCommand(ACTION_APPEND,"wt_sekundaer",&p,0,false);					
				Mission::PlayHint("WIB_WD_TOICU");
			} else
				Mission::PlayHint("WIB_WD_NOICU");
		}
	}
};

object wt_sekundaertransport : CommandScript
{

	wt_sekundaertransport()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		PersonList pl(Caller->GetName());
		PersonList tl("WTSekVer");
		Person opfer=tl.GetPerson(0);
		if (opfer.GetLife()<100)
		{
			Game::SetEventFinished(opfer.GetUserData(), false, 0);			
			Game::ShowHelpText("WIB_SEKRD_OVER");
			opfer.PushActionDeleteOwner(ACTION_NEWLIST);
		} 

		for (int i=0;i<pl.GetNumPersons();i++)
		{
			Person rd=pl.GetPerson(i);
			if (rd.IsParamedicTeam())
			{
				rd.PushActionMove(ACTION_APPEND,&opfer,TARGET_ANY);
				rd.PushActionLift(ACTION_APPEND,&opfer);
			}
			rd.SetFlag(FLAG_SOSI);
			rd.PushActionExecuteCommand(ACTION_APPEND,"EnterCar",Target,33,true);
		};

	}
};

object WDMsg : CommandScript
{

	WDMsg()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		if (Target->GetType()==ACTOR_PERSON)
		{
			Person t(Target);
			t.ClearFlag(FLAG_SOSI);
		}

		if (code>100)
		{
			char *fz="       ";
			snprintf(fz,7,"%s",Caller->GetName());
			char *mask="%s : %s";
			char * meldung="                                                         ";
			char * txt="                                                                                                                                                                                                         ";
			switch (code)
			{
				case 101: 
					Game::GetGameString("WIB_MSG_REA",meldung,50);
					break;
				case 102: 
					Game::GetGameString("WIB_NA_HER",meldung,50);
					break;
				case 103: 
					Game::GetGameString("WIB_RTW_HER",meldung,50);
					break;
			}
			snprintf(txt,125,mask,fz,meldung);
			Mission::PlayHint(txt);
		} else

		switch (code)
		{
			case 1:
				Game::ShowHelpTextWindow("WIB_WD_OBD"); 
				break;
			case 0:
				Game::ShowHelpTextWindow("WIB_WD_NOOBD"); 
				break;
			case 10:
				Game::ShowHelpTextWindow("WIB_WD_FKOK"); 
				break;
			case 11:
				Game::ShowHelpTextWindow("WIB_WD_FKBASS"); 
				break;
			case 12:
				Game::ShowHelpTextWindow("WIB_WD_FKDRAENG"); 
				break;
			case 13:
				Game::ShowHelpTextWindow("WIB_WD_FKTUEV"); 
				break;
			case 14:
				Game::ShowHelpTextWindow("WIB_WD_FKALK"); 
				break;
			case 15:
				Game::ShowHelpTextWindow("WIB_WD_FKWHAT"); 
				break;
			case 16:
				Game::ShowHelpTextWindow("WIB_WD_FKKLAU"); 
				break;
			case 17:
				Game::ShowHelpTextWindow("WIB_WD_FKSUSPECT"); 
				break;
			case 18:
				Game::ShowHelpTextWindow("WIB_WD_FKSPEED"); 
				break;
		}
	}
};


object TaeterInsFz : CommandScript
{

	TaeterInsFz()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		// System::Log("Taeter erzeugen %i",code);
		Person p;
		Vehicle v(Caller);
		v.SetMaxPassengers(2);
		disaster::Person_insFz(&v,"Fahrer",&p,false);
		PersonList pl(v.GetPassengers());
	
		switch (code)
		{
			case -10:
				p=pl.GetPerson(0);
				p.PushActionExecuteCommand(ACTION_NEWLIST,"Alkoholfahrt",&v,0,false);
				p.PushActionWait(ACTION_INSERT,2.0);
				break;
			case -5:
				for (int i=0;i<pl.GetNumPersons();i++)
				{
					p=pl.GetPerson(i);
					p.SetRole(ROLE_GANGSTER);
					if (rand()%10>7)
						p.SetBehaviour(BEHAVIOUR_GANGSTER_GUARDPASSAGE);
					else
						p.SetBehaviour(BEHAVIOUR_GANGSTER_CIVILARMED);
					if (rand()%4>1)
						p.PushActionEquipWeapon(ACTION_NEWLIST,true);
				}
				break;
		}
	}
};


object Alkoholfahrt : CommandScript
{

	Alkoholfahrt()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Vehicle v(Target);
		Person p(Caller);

		GameObject obj=v.GetClosestObjectInRange(200.0,10.0,ACTOR_PERSON);
		if (obj.IsValid() && v.IsMoving())
		{
			v.PushActionExecuteCommand(ACTION_INSERT,"CrashEm",&obj,0,false);
			v.PushActionMove(ACTION_INSERT,&obj,TARGET_FOLLOW);
			p.PushActionWait(ACTION_NEWLIST,5.0);
		} else {
			p.PushActionWait(ACTION_NEWLIST,1.0);
		}
		if (v.IsValid())
			p.PushActionExecuteCommand(ACTION_APPEND,"Alkoholfahrt",&v,0,false);
	}
};

object CrashEm : CommandScript
{

	CrashEm()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Person p(Target);
		p.Hurt(INJUREREASON_ENERGY,2000);
		p.SetLife(rand()%400+300);
		p.ClearActions();
		p.RemoveObjectPath();
	}
};

object MegaBass : CommandScript
{

	MegaBass()
	{
		SetIcon("fluchtwagen");   
		SetCursor("fluchtwagen");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{

		// System::Log("MegaBass Start");
		int i=Math::rand()%3+1;	
		
		char * bhf="             ";
		char * zugname="traffic_car0%u";
		int j=snprintf(bhf,13,zugname,i);
		GameObjectList ol;	

		if (Game::CollectObstaclesOnPath(bhf,ol))
		if (ol.GetNumObjects()>0)
		{
			Person p;
			int vnum=ol.GetNumObjects()-1;
			Vehicle v(ol.GetObject(vnum));
			if (!v.IsParking() && v.IsCivilCar() && !v.HasCommand("isbma") && !v.HasCommand("isbw"))
			{
				if (v.GetNumPassengers()<10)
				{
					v.SetMaxPassengers(4);
					disaster::Person_insFz(&v,"bassproll",&p,false);
				}
				v.AssignCommand("crime");
				v.SetVehicleRole(VT_GANGSTER_GETAWAY);
				v.SetAutoShoot(false);
				switch (rand()%10)
				{
					case 3:
					case 8:
					case 0:
						v.EnableBlinker(BLT_BOTH);
						v.EnableHeadLights(true);
						v.SetSpeed(12.0);
						v.PushActionExecuteCommand(ACTION_INSERT,"WT_SoSi",&v,-2,false); //Einsatzfahrt
						break;
					default:			
						v.PushActionExecuteCommand(ACTION_INSERT,"WT_SoSi",&v,-1,false); //Einsatzfahrt
						break;
				}
			}
		} else
			System::Log("MegaBass : Kein geeignetes Fz gefunden");
	}
};


object Ersthelfer : CommandScript
{

	Ersthelfer()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		Person p(Caller);
		bool ok=rand()%10>3;
		ok=ok && !p.IsBeingHealed();
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		GameObjectList pl=Caller->GetObjectsInRange(750.0,ACTOR_PERSON);
		for (int i=0;i<pl.GetNumObjects();i++)
		{
			Person eh(pl.GetObject(i));
			if (eh.GetPersonType()==PT_NOSQUAD && !eh.IsDead() && !eh.IsInjured() && !eh.IsCarried() && eh.GetRole()!=ROLE_GANGSTER && eh.GetRole()!=ROLE_ANIMAL)
			{
				eh.SetRole(ROLE_SQUAD);
				eh.SetBehaviour(BEHAVIOUR_SQUAD_RESCUE);
				eh.PushActionMove(ACTION_NEWLIST,Caller,TARGET_TREATMENT);
				eh.PushActionExecuteCommand(ACTION_APPEND,"eh",Caller,10,false);
				i=pl.GetNumObjects();
			}
		}
	}
};

object Bauunfall : CommandScript
{

	Bauunfall()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		GameObjectList kraene("baukran");
		if (kraene.GetNumObjects()>0)
		{
			GameObject kran=kraene.GetObject(rand()%kraene.GetNumObjects());
			kran.SetPlacement(PLACEMENT_BOXALIGNED);
			kran.UpdatePlacement();
			kran.PushActionRotateTarget(ACTION_NEWLIST,&kran,-90.0,0.0,0.0,3.0);
			kran.StopAnimation();
		}
	}
};

object Lawine : CommandScript
{

	Lawine()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		PathList failcheck("wintersport");
		return failcheck.GetNumPaths()>0;
	}

	void lawine_do (GameObject *Caller, Actor *Target, ActorList al)
	{
		// Camera::SetShakingEnabled(true);
		// Camera::StartTransition("wintersport",4.0f);
		GameObjectList ol;
		bool ok=Game::CollectObstaclesOnPath("wintersport",ol);
		for (int i=0;i<al.GetNumActors();i++)
			if (al.GetActor(i)->GetType()==ACTOR_SPAWNPOINT)			
				SpawnPoint sp(al.GetActor(i));
		if (sp.IsValid())
			sp.SetEnabled(false);
		punkte=0;
		Vector shaker;

		for (int i=0;i<ol.GetNumObjects();i++)
		{
			if (ol.GetObject(i)->GetType()==ACTOR_PERSON)
			{
				Person p(ol.GetObject(i));
				if (p.GetRole()!=ROLE_ANIMAL)
				{
					punkte+=500;
					p.SetBloodPuddle(false);
					p.Injure(INJUREREASON_ENERGY,true);
					p.SetLife(400+rand()%400);
					p.SetInjuredLifeDrain(rand()%2+0.8);
					p.SetInjuredAnimation();
					if (rand()%10>2)
					{
						punkte+=250;
						p.SetFoundByDog(false);
						p.SetFlags(8448);
						p.SetBloodPuddle(false);
					} else
						p.SetFoundByDog(true);
					shaker=p.GetPosition();
					shaker.x+=rand()%700;
					shaker.y+=rand()%800-400;
					p.SetPosition(shaker);
				} else 
					p.Kill();
			}
		}

		Vector Posabc;
		if (sp.IsValid())
			Posabc=sp.GetPosition();
		eventid=Game::ShowEvent("WIB_WD_SNOW", Posabc);

		Game::ShowHelpText("WIB_WD_LAWINE");
		Mission::PlayHint("WIB_WD_LAWINE");
		ScriptInterface::ShowBriefing();
		Caller->PushActionWait(ACTION_INSERT,15.0);
		Caller->PushActionExecuteCommand(ACTION_INSERTAFTERFIRST,"Lawine",Caller,1,false);

		Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,26,false);
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		if (code==1)
		{
			// Camera::SetShakingEnabled(false);
			return;
		}
		
		ActorList al("wintersport");
		if (al.GetNumActors()>0) 
			lawine_do(Caller,Target,al);
	}
};


object Schleuderfahrt : CommandScript
{

	Schleuderfahrt()
	{
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Vehicle v(Target);
		float winkel=140.0*code;
		
		if (code==0)
		{
			code=-1;
			PersonList pl=v.GetPassengers();
			if (pl.GetNumPersons()==0)
				return;
			Person p=pl.GetPerson(0);
			Mission::PlayHint("Schleuderfahrt !");
			winkel=-70;
			v.EnablePhysics();
			v.SetPhysicsFriction(0.0);
			v.ActivateOBBCollision();
			v.SetCollisionMode(PHYSICS_COLLISION_ALL);
			// v.EnablePhysicsSimulation(true,false,false);
			// v.UnfreezePhysics();
			v.SetTerrain(TERRAIN_AIRPLANE);
			v.SetPlacement(PLACEMENT_NONE);
			p.PushActionWait(ACTION_NEWLIST,0.1);
		} else
			Person p(Caller);

		if (v.IsMoving())
		{	
			p.PushActionRotateTarget(ACTION_APPEND,Target,0,winkel,0,0.2);
			p.PushActionWait(ACTION_APPEND,0.5);
			p.PushActionExecuteCommand(ACTION_APPEND,"Schleuderfahrt",Target,-code,false);
			v.ClearFlag(OF_TRANSPORTABLE);
			v.EnableBrakeLights(true);
		}
	}
};

object Bombenfund : CommandScript
{

	Bombenfund()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		//System::Log("Bombenfund");
		ActorList fund=Game::GetActors("wt_bomb");
		int max=fund.GetNumActors();
		if (max>0)
		{
			//System::Log("Bombe verstecken %u",max);
			char *buf="mod:Prototypes/Objects/bomben/kmrd_bomb01.e4p";
			snprintf(buf,46,"mod:Prototypes/Objects/bomben/kmrd_bomb0%u.e4p",rand()%6+1);
			max=rand()%max;
			//System::Log("Bombe %s an Platz %u",buf,max);
			Actor fundort;
			fundort=fund.GetActor(max);
			GameObject bombe=Game::CreateObject(buf,"witchbomb");
			Vector pos=fundort.GetPosition();
			Game::FindFreePosition(&bombe,pos);
			bombe.SetPosition(pos);
			// bombe.SetRotation(&fundort);
			// bombe.SetEnergy(bombe.GetMaxEnergy()/2);
			bombe.SetUserData(4);
			bombe.AssignCommand("gefahrgut");
			bombe.SetFlags(OF_USABLE|OF_TRANSPORTABLE|OF_PULLABLE|OF_RECOVERABLE);
			bombe.AssignCommand("kmrd_target");
			eventid=Game::ShowEvent("WIB_WD_MYBOMB", pos);

			Game::ShowHelpText("WIB_WD_MYBOMB_HT");
			Audio::PlaySample(hatalarm);					
			if (Caller->HasNamePrefix("FogOfDoc"))
				Caller->SetPosition(pos);
			Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&bombe,66,false);
		}
	}
};

object Wasser_im_Keller : CommandScript
{

	Wasser_im_Keller()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		ActorList wasser=Game::GetActors(ACTOR_LIQUID);
		int max=wasser.GetNumActors();
		if (false)
		{
			Actor w;
			int i=rand()%max;
			w=wasser.GetActor(i);
			while (!w.HasNamePrefix("hydrant") && !w.HasNamePrefix("flut"))
			{
				i--;
				if (i<0)
					i=max-1;
				w=wasser.GetActor(i);
			}
			Vector pos=w.GetPosition();
			Game::ActivateLiquid(w.GetName());
		
			eventid=Game::ShowEvent("WIB_WD_FLUT_KELLERVOLL", pos);
			w.SetUserData(eventid);		
			eventid=-1;
			Game::ShowHelpText("WIB_WD_FLUT_MACHLEER");
			ScriptInterface::ShowBriefing();

			if (Caller->HasNamePrefix("FogOfDoc"))
				Caller->SetPosition(pos);
		}
	}
};

object ff_pkw : CommandScript
{

	ff_pkw()
	{
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		VehicleList vl(VT_DRIVERCAR,VT_DRIVERCAR);
		float speed=17.0;
		Person p;
		if (vl.GetNumVehicles()>0)
			for (int i=0;i<code;i++)
			{
				Vehicle v=vl.GetVehicle(rand()%vl.GetNumVehicles());
				if (v.GetNumPassengers()<10 && !v.IsDestroyed() && !v.IsSmoking())
				{
					v.SetMaxPassengers(4);
					disaster::Person_insFz(&v,"ffw",&p,false);
				}
				v.PushActionWait(ACTION_NEWLIST,0.5);
				// v.SetVehicleRole(VT_FIREFIGHTERS_RW);
				// v.SetCommandable(true);
				v.SetSpeed(speed);
				// v.AssignCommand("bedarfsfz");
				Path test=v.GetObjectPath();
				if (test.IsValid())
					v.RemoveObjectPath();
				v.EnableHeadLights(true);
				v.PushActionMove(ACTION_APPEND,&ffparken,TARGET_RANDOM);
				v.PushActionExecuteCommand(ACTION_APPEND,"ff_leave_car",&fftor,0,false);
			}
	}
};

object ff_leave_car : CommandScript
{

	ff_leave_car()
	{
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Vehicle v(Caller);
		PersonList pl=v.GetPassengers();
		for (int i=0;i<pl.GetNumPersons();i++)
		{
			Person ffm=pl.GetPerson(i);
			ffm.SetRole(ROLE_SQUAD);
			ffm.PushActionLeaveCar(ACTION_NEWLIST,Caller);
			ffm.PushActionMove(ACTION_APPEND,&fftor,TARGET_RANDOM);
			ffm.PushActionWait(ACTION_APPEND,2.0);
			ffm.PushActionDeleteOwner(ACTION_APPEND);
		}
		Caller->PushActionDisappear(ACTION_APPEND,5.0,5.0,true);
	}
};

object send_ffw : CommandScript
{

	send_ffw()
	{
		SetIcon("start");
	}
	
	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		Caller->PushActionExecuteCommand(ACTION_INSERT,"ff_pkw",Caller,code,false);
	}
};

int did_joke=2;

object Doc_Joke: CommandScript
{

	Doc_Joke()
	{
	}
	
	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		if (did_joke>0)
		{
			Vehicle v(Target);
			if (v.IsAmbulance())
				Game::ShowHelpTextWindow("DOC_JOKE_ZIVI");
			else  if (v.IsFirefighter())
				Game::ShowHelpTextWindow("DOC_JOKE_MANNE");
			did_joke--;
		}
	}
};

object Doc_Lock: CommandScript
{

	Doc_Lock()
	{
		SetIcon("start");
		SetCursor("start");
		SetValidTargets(ACTOR_OPEN_HOUSE);
	}
	
	bool CheckTarget(GameObject *Caller, Actor *Target, int ChildID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		OpenHouse hou(Target);
		if (hou.IsFlagSet(OF_LOCKED))
			Mission::PlayHint("Flag : Abgeschlossen!");
		else
			Mission::PlayHint("Flag :Offen!");
		hou.ToggleFlag(OF_LOCKED);
		if (hou.IsLocked())
			Mission::PlayHint("Haus Abgeschlossen!");
		else
			Mission::PlayHint("Haus Offen!");
	}
};


object freizeitcaptain : CommandScript
{

	freizeitcaptain()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		bool isfrachter=rand()%20>16;
		// System::Log("Schiff in Not .. jetz versenken :D");

		Vector Crash=disaster::incident_pos(1);
		if (Crash.x!=0 && Crash.y!=0)
		{
			if (isfrachter)
				Vehicle car=Game::CreateVehicle("mod:Prototypes/Vehicles/Water Craft/wib_fracht.e4p","captain");
			else
				Vehicle car=Game::CreateVehicle("mod:Prototypes/Vehicles/Water Craft/yacht01.e4p","captain");
			Game::FindFreePosition(&car,Crash,50.0);
			car.SetPosition(Crash);
			Caller->PushActionExecuteCommand(ACTION_INSERT,"captain_do",&car,int(isfrachter),false);
		} else {
			System::Log("Schiff keine gültige Pos");
		}
	}
};

object captain_do : CommandScript
{

	captain_do()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{

		Vector Pos;
		int disaster;
		int n_pat=0;
		int q;
		bool isfrachter=ChildID>0;

		Vehicle car(Target);
		Pos=car.GetPosition();
		disaster=Math::rand()%20;

		punkte=0;

		if (disaster>20 && isfrachter) {			
			// System::Error("Gefahrgut");
			car.PushActionExecuteCommand(ACTION_NEWLIST,"setggv",&car,0,false);
			gefahrgut=true;
			car.SetSmokeLevelDuration(20.0f);
			// erstmal keine gefahrguteinsaetze
			punkte=5000;
		} else if (disaster > 14) {
			car.SetSmokeLevelDuration(15.0+rand()%15);
			disaster::feuer_machen(&car);
			punkte=3000;
		} else {
			if (!isfrachter) {
				car.SetPlacement(PLACEMENT_NONE);
				car.UpdatePlacement();
				car.PushActionRotateTarget(ACTION_NEWLIST,Target,0.0,0.0,110.0,0.1);
				car.SetPosition(Pos);
			}
			punkte=2000;
		}

		car.SetFlags(OF_RECOVERABLE | OF_PULLABLE);
		car.SetParking(false);
		
	
		// Zivilisten erzeugen und als Verletzte auf der Strasse verstreuen
		//Fahrzeuge + Eingeklemmten erzeugen
		if (isfrachter)
			q=(rand()%5)+5;
		else
			q = (rand()%4)+2;	
	
		n_pat=disaster::Verletzte_streuen(&car,q,700,"captain",false,true);
		
		punkte=punkte+700*n_pat;

		
		// EventID-Code für Patch 1.3
		eventid=Game::ShowEvent("WIB_WD_SHIP_EM", Pos);

		if (isfrachter)
			Game::ShowHelpText("WIB_WD_FREIGHT_EM");
		else
			Game::ShowHelpText("WIB_WD_YACHT_EM");
		Audio::PlaySample(hatalarm);					
		if (Caller->HasNamePrefix("FogOfDoc"))
			Caller->SetPosition(Pos);
		Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Ehranger,27,false);	
	}
};

object Pandemie : CommandScript
{

	Pandemie()
	{
		SetIcon("kats");   
		SetCursor("kats");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	void PushActions(GameObject *Caller, Actor *Target, int ChildID)
	{
		System::Log("Pandemie Init");

		Person Abdul=Game::CreatePerson("mod:Prototypes/Persons/Civil/arabman01.e4p","MERS");
		Vector Crash=disaster::incident_pos(2);		
		Abdul.SetPosition(Crash);
		// Abdul.Contaminate(CONTAMINATION_BIOLOGICAL);
		Abdul.PushActionExecuteCommand(ACTION_NEWLIST,"mers_do",&Abdul,1,false);

		Crash=Caller->GetPosition();
		eventid=Game::ShowEvent("WIB_WD_MERS", Crash);
		Game::ShowHelpText("WIB_WD_MERS_BRIEF");

		Audio::PlaySample(hatalarm);					
		punkte=5000;
		Ehranger.PushActionExecuteCommand(ACTION_APPEND,"CheckWitchDoc",&Abdul,15,false);	
	}
};

object mers_do : CommandScript
{

	mers_do()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int code)
	{
		System::Log("Pandemie MERS Code %u",code);

		Person p(Caller);
		switch (code) {
			case 0:
				GameObject Jack;
				Jack=Caller->GetClosestObjectInRange(750.0,150.0,ACTOR_PERSON);		
				if (!p.IsArrested())
					Caller->PushActionMove(ACTION_NEWLIST,&Jack,50.0,30.0);
				else
					Caller->PushActionWait(ACTION_NEWLIST,rand()%10+5);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"mers_do",&Jack,1,false);
				break;
			case 1:
				Caller->SetAnimation("cough");
				GameObjectList pl=Caller->GetObjectsInRange(125.0,ACTOR_PERSON);
				for (int i=pl.GetNumObjects()-1;i>-1;i--) {
					Person op(pl.GetObject(i));
					if (op.GetID()!=Caller->GetID()) {
						op.PushActionWait(ACTION_NEWLIST,3.0);
						op.PushActionExecuteCommand(ACTION_APPEND,"mers_do",&op,2,false);
					}
				}
				Vector away=disaster::incident_pos(2);
				if (!p.IsArrested())
					Caller->PushActionMove(ACTION_NEWLIST,away);
				else
					Caller->PushActionWait(ACTION_NEWLIST,rand()%20+15);
				Caller->PushActionExecuteCommand(ACTION_APPEND,"mers_do",Caller,0,false);
				break;
			case 2:
				Person p(Target);
				p.ExposeContamination(CONTAMINATION_BIOLOGICAL);
				punkte-=250;
				break;
		}
	}
};

const int FLAG_FUNK=OF_HAS_FIREAXE * 2;
const int FLAG_SOSI=OF_HAS_FIREAXE * 4;
const int FLAG_TL=OF_HAS_FIREAXE * 8;
const int FLAG_NA=OF_HAS_FIREAXE * 16;

// XX10 Incident generator

const int lev_naw=400;
const int lev_rtw=600;
const int lev_ktw=900;

int hatacd=0;
int hataload=45;
int hataspread=60;
bool hatalock=false;

int hatacnt=-1;
int hatafreq[30];
int hatalim[30];
int hatasum=0;

object wem_hata_init: CommandScript
{
	wem_hata_init()
	{
	}

	// KYMMENXX Incident Generator

	void PushActions(GameObject *Caller, Actor *Target, int cd)
	{
		System::Log("WEM HATA Init");
		Vehicle tisch=Game::CreateVehicle("mod:Prototypes/Vehicles/Winterberg/funktisch1.e4p","SmallGod");
		tisch.SetCommandable(true);
		tisch.SetUserData(0);
		Game::AddToGroup(&tisch,5);
		char * val="    ";
		bool goon=Game::GetGameString("WEM_HATALOAD",val,4);
		System::Log("HATA Load %s",val);
		if (goon) hataload=atoi(val);
		char * val="    ";
		goon=Game::GetGameString("WEM_HATASPREAD",val,4);
		System::Log("HATA Spread %s",val);
		if (goon) hataspread=atoi(val);
		hatacd=10;
		goon=true;
		for (int i=0;goon;i++)
		{
			char * buf="           ";
			snprintf(buf,11,"WEM_HATA%u",100+i);
			char * val="    ";
			goon=Game::GetGameString(buf,val,4);
			if (goon) {
				char *cmd="                     ";
				hatacnt++;
				hatafreq[i]=atoi(val);
				hatasum=hatafreq[i]+hatasum;	
				snprintf(buf,11,"WEM_HCMD%u",100+i);
				goon=Game::GetGameString(buf,cmd,20);
				tisch.AssignCommand(cmd);
				snprintf(buf,11,"WEM_HLIM%u",100+i);
				val="    ";
				if (Game::GetGameString(buf,val,4))
					hatalim[i]=atoi(val);
				else 
					hatalim[i]=0;
				System::Log("WEM Incident %u p %u %s nach %u Incidents",i,hatafreq[i],cmd,hatalim[i]);
			}
		}
	}
};

char *hatalarm="mod:Audio/fx/fme/fme119.wav";

object wem_hata: CommandScript
{
	wem_hata()
	{
	}

	// KYMMENXX Incident Generator

	void PushActions(GameObject *Caller, Actor *Target, int cd)
	{
		if (hatalock)
			hatacd=hataload;
		hatacd-=cd;
		System::Log("Hata go %d ? %d %d",hatacd,hataload,hataspread);
		if (hatacd<1) {
			// Action
			int act=rand()%hatasum;
			bool doit=false;
			System::Log("Hata act %u !",act);
			int sq=0; int c=0;
			do {
				sq=sq+abs(hatafreq[c]);
				doit=hatafreq[c]>0 && !hatalim[c];
				c++;
			} while (act>=sq && c<hatacnt);	
			
			if (act<sq && doit) {
				char * buf="           ";
				bool goon=true;
				snprintf(buf,11,"WEM_HCMD%u",99+c);
				char * val="                                                ";
				goon=Game::GetGameString(buf,val,20);
				System::Log ("Hata Do %s",val);
				if (goon) {
					Caller->PushActionExecuteCommand(ACTION_APPEND,val,Target,0,false);
					hatacd=hataload-hataspread/2+rand()%hataspread;	
					snprintf(buf,11,"WEM_HLVL%u",99+c);
					char * val="    ";
					goon=Game::GetGameString(buf,val,4);
					if (goon) 
						hatacd+=atoi(val);

					for (c=0;c<hatacnt;c++)
						if (hatalim[c])
							hatalim[c]--;
				}
			}
			// wieder scharfmachen
		}
		System::Log("Hata bye !");		
		Caller->PushActionWait(ACTION_APPEND,cd*1.0);
		Caller->PushActionExecuteCommand(ACTION_APPEND,"wem_hata",Target,cd,false);
	}
};

object hata_checkobj: CommandScript
{
	hata_checkobj()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int eid)
	{
		bool success=true;
		bool fertig=!Target->IsValid();
		if (!fertig) {
			Person p(Target);
			fertig=p.IsDead();
			success=false;
		}
		if (fertig) {
			Game::SetEventFinished(eid, success, Caller->GetUserData()); 
			Caller->PushActionDeleteOwner(ACTION_NEWLIST);
		} else {
			if (!Caller->HasAnyAction())
				Caller->PushActionWait(ACTION_APPEND,2.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"hata_checkobj",Target,eid,false);
		}
	}
};

object hata_checkfire: CommandScript
{
	hata_checkfire()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int eid)
	{
		if (Game::GetGameObjects().GetNumBurningObjects() < 1) {
			Game::SetEventFinished(eid, true, Caller->GetUserData()); 
		} else {
			if (!Caller->HasAnyAction())
				Caller->PushActionWait(ACTION_APPEND,3.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"hata_checkfire",Target,eid,false);
		}
	}
};

object hata_checkvu: CommandScript
{
	hata_checkvu()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int eid)
	{
		char *buf="               ";
		snprintf(buf,15,"VU%u",Caller->GetID());
		GameObjectList pl=Game::GetGameObjects(buf);
		bool fertig=(pl.GetNumObjects() == 0);
		if (fertig) {
			Game::SetEventFinished(eid, true, Caller->GetUserData()); 
			Caller->PushActionDeleteOwner(ACTION_NEWLIST);
		} else {
			System::Log("HATA Check VU %u Obj, Erstes Object %s %s",pl.GetNumObjects(),pl.GetObject(0)->GetName(),pl.GetObject(0)->GetPrototypeFileName());
			Caller->PushActionWait(ACTION_APPEND,3.0);
			Caller->PushActionExecuteCommand(ACTION_APPEND,"hata_checkvu",Target,eid,false);
		}
	}
};

ActorType at[4];
at[0]=ACTOR_HOUSE;
at[1]=ACTOR_OPEN_HOUSE;
at[2]=ACTOR_VEHICLE;
at[3]=ACTOR_OBJECT;

object hata_stopit: CommandScript
{
	hata_stopit()
	{
		SetIcon("notaus");   
		SetCursor("notaus");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	// erzeugt Braende

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		hatalock=!hatalock;
		if (hatalock)
			Mission::PlayHint("Keine weiteren Einsätze ab sofort");		
		else
			Mission::PlayHint("Einsatzerzeugung aktiv");
		hatacd=hataload;
	}
};

object hata_feuer: CommandScript
{
	hata_feuer()
	{
		SetIcon("sir");   
		SetCursor("sir");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	// erzeugt Braende

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{
		Vector hierhin;
		System::Log("Let's have FEUER!");
		int x=rand()%3;
		ActorList fl=Game::GetActors(at[x]);
		int punkte=-1;
		
		if (fl.GetNumActors()>0) {
			bool valid=false;
			x=rand()%fl.GetNumActors();
			do {
				Actor *feuer=fl.GetActor(x);
				GameObject o(feuer);
				valid = o.IsInsideMap() && !o.HasCommand("isbma") && !o.HasCommand("aufsitzen");
				x--;
			} while (!valid && x>-1);
			if (valid) {
				char *msg="WEM_HATA_FEUER100";
				hierhin=feuer->GetPosition();
				System::Log("Feuer machen bei %s",feuer->GetName());
				switch (feuer->GetType()) {
					case ACTOR_VEHICLE:
						Vehicle car(feuer);
						car.SetSmoking(true);
						car.SetSmokeLevelDuration(rand()%30+20.0);
						if (disaster::infolevel(75))
							char *msg="WEM_HATA_FEUER099";
						punkte=1000;
						break;
					default:
						disaster::feuer_legen(feuer,feuer);
						punkte=1500;
						switch (feuer->GetType()) {
							case ACTOR_HOUSE:
								punkte+=500;
								if (disaster::infolevel(60))
									msg[16]++;
								break;
							case ACTOR_OPEN_HOUSE:
								punkte+=1500;
								if (disaster::infolevel(60))
									msg[16]++;
								if (disaster::infolevel(50))
									msg[16]++;
								break;
							break;
								
						}
						break;
				}
				System::Log("Feuer gemacht");
				int eid=Game::ShowEvent(msg, hierhin);
				// Game::ShowHelpText("WIB_WD_MESSER");
				Mission::PlayHint(msg);
				Audio::PlaySample(hatalarm);					
				GameObject watch=Game::CreateObject("mod:Prototypes/Objects/Equipment/parken.e4p","WitchDcCore");
				watch.SetUserData(punkte);
				watch.PushActionWait(ACTION_NEWLIST,3.0);
				watch.PushActionExecuteCommand(ACTION_APPEND,"hata_checkfire",Target,eid,false);
			} else
				System::Log("Nicht in der Map");
		} else 
			System::Log("Kein Feuer :( ");
	}

};

object hata_mednot: CommandScript
{
	hata_mednot()
	{
		SetIcon("umdisponieren");   
		SetCursor("umdisponieren");
		//SetPriority(2000);
	}
	
	bool CheckPossible(GameObject *Caller)
   	{
		return Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return (Caller->GetID()==Target->GetID());
	}

	// erzeugt Einstätze mit Personenschaden div. Schwere

	void PushActions(GameObject *Caller, Actor *Target, int childID)
	{

		System::Log("Hata med Not Start!");

		Actor *act=disaster::GetFocus(1);
		Person killed(act);
		int punkte=-1;
		if (killed.IsValid())
		{
			if (true)
			{
				int injure=rand()%8; 	// Verletzungstyp finden
				killed.Injure (ir[0],true);
				Vector hierhin=killed.GetPosition();
				killed.PushActionWait(ACTION_NEWLIST,0.1);
				char *msg="WEM_HATA_MED100";
				
				int switch=rand()%12;

				switch (switch) {
					case 0 :
					case 11:
							medisim::injure (killed,850,lev_ktw,0.2);
							// Level blau
							punkte=100;
							break;
					case 1 :
					case 2 :
					case 3 :
							medisim::injure (killed,lev_ktw,lev_rtw,0.2);
							// Level grün
							punkte=250;
							break;
					case 4 :
					case 5 :
					case 6 :
					case 7 :
							medisim::injure (killed,lev_rtw,lev_naw,0.35);
							// Level gelb
							punkte=500;
							break;
					case 8 :
					case 9 :
					case 10 :
							medisim::injure (killed,lev_naw,200,0.5);
							// Level rot
							punkte=1000;
							break; 
				}				
					
				GameObject watch=Game::CreateObject("mod:Prototypes/Objects/Equipment/parken.e4p","WitchDcCore");
				watch.SetUserData(punkte);
				int eid=Game::ShowEvent(msg, hierhin);
				Mission::PlayHint(msg);
				Audio::PlaySample(hatalarm);					
				watch.PushActionWait(ACTION_NEWLIST,3.0);
				watch.PushActionExecuteCommand(ACTION_APPEND,"hata_checkobj",&killed,eid,false);
			}
		}
	}
};


// ---- Extended Medical Simulation

// ## 
// ## WEM4 Scripting
// ## WEM4 9 Taikapalo
// ## 
// ## Script emv
// ## 
// ## Release 03.05.2014
// ## 
// ## created by WitchDoctor




object Superdoc : CommandScript
{
	Superdoc()
	{
		SetValidTargets(ACTOR_PERSON | ACTOR_VEHICLE);
		SetGroupID(20);
		SetPriority(1000);
		SetGroupLeader(false);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return false; // Caller->HasCommand("emv");
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		if(Target->GetType()==ACTOR_PERSON)
		{
			Person p(Target);
			if (p.HasCommand("manv_schwarz") && p.IsDead())
				ok = false;
			else
				ok=(!p.IsFlagSet(FLAG_P_NEU) && !p.IsDrowning() && p.GetRole() != ROLE_ANIMAL && !p.IsRescueDog() && (p.IsInjured() || p.IsWoundedSquad()) && p.GetEnteredCarID() == -1 && !p.IsCarried());
		} 

		if(Target->GetType()==ACTOR_VEHICLE)
		{
			GameObject obj(Target);
			Person p(Caller);
			ok=obj.IsFlagSet(OF_PERSON_ENCLOSED) && p.IsDoctor();
		}
		return ok;
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		PersonList pl(Caller->GetName());
		Caller->RemoveEquipment();
		bool got_case=false;
		Person p;
		for (int i=0;i<pl.GetNumPersons();i++)
		{
			p=pl.GetPerson(i);
			if (p.IsDoctor())
			{
				medfunc::zum_pat(&p,Target,-1);
				p.SetAutoHealDistance(0.0);
			} else {
				medfunc::zum_pat(&p,Target,-2);
				if (!got_case)
				{
					got_case=true;
					p.PushActionExecuteCommand(ACTION_INSERT,"Hole_NEF_Equip",&p,0,false);
				}
			}
		}
	}
};

object DocBasis : CommandScript
{
	DocBasis()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("untersuch");
		SetCursor("untersuch");
		SetPriority(100);
		SetGroupID(2);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		if (p.HasCommand("manv_schwarz") && p.IsDead())
			ok = false;
		else
			ok=  (!p.IsDrowning()  && p.GetRole() != ROLE_ANIMAL && !p.IsRescueDog() && (p.IsInjured() || p.IsWoundedSquad())  && !p.IsCarried());
		return ok; // && Caller->IsAnimationFinished();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		Caller->SetUserData(Target->GetID());
		medfunc::zum_pat(Caller,Target,2);
	}
};

object stetho : CommandScript
{
	stetho()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("abhoer");
		SetCursor("abhoer");
		SetRestrictions(RESTRICT_SELFEXECUTE);
		SetGroupID(3);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Caller->GetID()==Target->GetID();	
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,3);
	}
};

object Vitalparm : CommandScript
{
	Vitalparm()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("blutdr");
		SetCursor("blutdr");
		SetGroupID(4);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Caller->GetID()==Target->GetID();	
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,4);
	}
};


object DocEKG : CommandScript
{
	DocEKG()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("ekgm");
		SetCursor("ekgm");
		SetGroupID(7);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		ok=  p.HasCommand("raheal") && !p.HasAnyAction() && !p.IsWoundedSquad() && !p.IsDead();
		return ok && Caller->IsAnimationFinished();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,7);
	}
};

object FAST : CommandScript
{
	FAST()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("sonog");
		SetCursor("sonog");
		SetGroupID(8);
		SetRestrictions(RESTRICT_SELFEXECUTE);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return true;
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		if (play)
			Audio::PlayVideo("mod:emv/milz.mpg");
		else
			medfunc::zum_pat(Caller,Target,8);
	}
};

object DocNuele : CommandScript
{
	DocNuele()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("vzugang");
		SetCursor("vzugang");
		SetGroupID(6);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		ok=  !p.HasAnyAction() && !p.IsWoundedSquad() && !p.IsDead() && !p.IsInjured();
		return ok ; // && Caller->IsAnimationFinished();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,6);
	}
};

object DocMed : CommandScript
{
	DocMed()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("medik");
		SetCursor("medik");
		SetGroupID(9);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		if (!p.IsFlagSet (FLAG_P_NEU) || (p.HasCommand("manv_schwarz") && p.IsDead()))
			ok = false;
		else
			ok=  (!p.IsDrowning() && !p.IsHealing() && p.GetRole() != ROLE_ANIMAL && !p.IsRescueDog() && (p.IsInjured() || p.IsWoundedSquad()) && p.GetEnteredCarID() == -1 && !p.IsCarried());
		return ok;// && Caller->IsAnimationFinished();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,99);
	}
};

object Doctub : CommandScript
{
	Doctub()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("intub");
		SetCursor("intub");
		SetGroupID(11);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		ok=p.HasCommand("raheal") && !p.HasAnyAction() && !p.IsWoundedSquad() && !p.IsDead();
		return ok; //&& medfunc::DocCanDo(Caller);
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,20);
	}
};

object DocDrain : CommandScript
{
	DocDrain()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("pleuradr");
		SetCursor("pleuradr");
		SetGroupID(12);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		ok=p.HasCommand("raheal") && !p.HasAnyAction() && !p.IsWoundedSquad() && !p.IsDead();
		return ok ; // && Caller->IsAnimationFinished();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,21);
	}
};

object DocInj : CommandScript
{
	DocInj()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("injekt");
		SetCursor("injekt");
		SetGroupID(10);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		return Caller->GetID()==Target->GetID();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,22);
	}
};

object DocHLW : CommandScript
{
	DocHLW()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("ekgm");
		SetCursor("ekgm");
		SetGroupID(13);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true;
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		if (p.IsInjured() || p.IsDead())
			ok = false;
		else
			ok=  (!p.IsDrowning()  && p.GetRole() != ROLE_ANIMAL && !p.IsRescueDog() && !p.IsWoundedSquad() && p.GetEnteredCarID() == -1 && !p.IsCarried());
		return ok; //&& Caller->IsAnimationFinished();
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		medfunc::zum_pat(Caller,Target,13);
	}
};

object DocTransport : CommandScript
{
	DocTransport()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("pat_rtw");
		SetCursor("pat_rtw");
		SetGroupID(14);
		SetPriority(500);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true  && Input::LShiftPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		ok=  p.HasCommand("ratransport") && !p.IsWoundedSquad() && !p.IsDead();
		return ok;
	}


	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		int func=14;
		medfunc::zum_pat(Caller,Target,func);
	}
};

object DocTransNA : CommandScript
{
	DocTransNA()
	{
		SetValidTargets(ACTOR_PERSON);
		SetIcon("pat_naw");
		SetCursor("pat_naw");
		SetPriority(500);
		SetGroupID(14);
	}

	bool CheckGroupVisibility(GameObject *Caller)
	{
		return true && Input::LCtrlPressed();
	}

	bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
	{
		if(!Caller->IsValid() || !Target->IsValid() || Target->GetID() == Caller->GetID())
			return false;
		
		bool ok;

		Person p(Target);
		ok=  p.HasCommand("ratransport") && !p.IsWoundedSquad() && !p.IsDead();
		return ok;
	}


	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		int func=15;
		Mission::PlayHint("WIB_EMV_NAGEHTMIT");
		medfunc::zum_pat(Caller,Target,func);
	}
};

object DocDoIt : CommandScript
{
	DocDoIt()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int play)
	{
		int func=play;
		Person obj(Target);

		if (func<0)
			medfunc::zum_pat(&obj,Caller,-func);
		else
			medfunc::zum_pat(Caller,Target,func);
	}
};

object emv_medisim : CommandScript
{
	emv_medisim()
	{
	}

	void PushActions(GameObject *Caller, Actor *Target, int simcode)
	{
		if (Target->IsValid())
		{
			switch (simcode) {
				case -1:
					// medisim (Caller,Target,simcode);
					break;
				case 2 :
					medisim::medi_status(Caller,Target);				
					break;
				case 3 :
					medisim::medi_stetho(Caller,Target);
					break;
				case 4 :
					medisim::medi_vital(Caller,Target);
					break;
			}
			// Caller->PushActionWait(ACTION_APPEND,1.0);
			// Caller->PushActionExecuteCommand(ACTION_APPEND,"emv_medisim",Target,-1);
		} // else {
		//	System:.Log("MediSim beendet fuer Patient %s",Caller->GetName());		
		//	Caller->PushActionDeleteOwner(ACTION_NEWLIST);
		// }
	}
};

object emv : CommandScript
{
	emv()
	{
		SetGroupID(35);
	}

};

	// traumafolgen
	const int trauma_icb = 0x100;
	const int trauma_pneu = 0x200;
	const int trauma_abd = 0x400;
	const int trauma_ws = 0x800;
	const int trauma_arm = 0x1000;
	const int trauma_bein = 0x2000;
	const int trauma_becken = 0x4000;
	const int trauma_blutung = 0x8000;

	// Innere



	// Massnahmen
	const int med_basis = 0x10000;
	const int med_rr = 0x20000; 
	const int med_stetho = 0x40000;
	const int med_nuele = 0x80000;
	const int med_fast = 0x100000;
	const int med_ekg = 0x200000;
	const int med_medi = 0x400000;
	const int med_intub = 0x800000;
	const int med_buelau = 0x1000000;
	const int med_hlw = 0x2000000;
	const int med_inj = 0x4000000;
	const int med_immob = 0x8000000;

class medisim : CommandScript
{
		// generiert ICD und Massnahmenmaske für Patienten
		// und legt diese in den Userdata ab
		// Codierung
		//	Bits 0-7 =  xFF -> Belegt, werden für TriageStatus etc von den HealScripts genutzt
		//	Bits 8-15 = xFFnn -> codieren 255 div Krankheitszustände
		//	Bit 16-31 = xFFFFnnnn -> Bitmaske erforderlicher Einzelmassnahmen -> Durchführung gibt Zusatzpunkte bei Behandlung des Pat.
		//									   Unterlassug kann zum Scheitern der Behandlung führen
		//  DIES wird KEIN RescueTrainer !! Massnahmen bleiben allgemein gehalten und verständlich
		//
		//
		//

	char *dname(GameObject *p) 
	{
		const char *buf="        ";
		snprintf(buf,7,"%s",p->GetName());
		return buf;
	}

	int iss (float life)
	{
		int val;
		if (life <0)
			val=4;
		else if (life<400)
			val=3;
		else if (life<600)
			val=2;
		else if (life<800)
			val=1;
		else val=0;
		return val;
	}
			
	bool istrauma(Person pat)
	{
		return pat.GetInjuryReason()==INJUREREASON_ENERGY || pat.GetInjuryReason()==INJUREREASON_SHOT || pat.GetUserData()&med_immob;
	}	

	bool isburn(Person pat)
	{
		return pat.GetInjuryReason()==INJUREREASON_FIRE;
	}	

	int gcs (Person pat) 
	{
		int gcs=15;
		int score=iss(pat.GetLife());
		switch (score) {
			case 4:
				gcs=3;
				break;
			case 3:
				gcs=rand()%3+rand()%3+rand()%1+5;
				break;
			case 2:
				gcs=rand()%3+rand()%3+rand()%2+10;
				break;
			case 1:
				gcs=rand()%3+13;
				break;
		}
		if (istrauma(pat) && (pat.GetUserData() & trauma_icb) && gcs>6)
			gcs-=rand()%(gcs/2);
		if (gcs<9)
			pat.SetUserData(pat.GetUserData() | med_intub);
		return gcs;
	}

	void injure (Person pat, int l1, int l2, float dr)
	{
	
		bool trauma=false;
		int injcode=0;
		int bw=l1-l2;
		if (bw>0) {
			int val=l2+rand()%bw;
			float drain=dr+rand()%2;
		} else {
			int val=pat.GetLife();
			float drain=pat.GetInjuredLifeDrain();
		}

		switch (pat.GetInjuryReason()) {
			case INJUREREASON_FIRE:
				injcode=med_inj;
				if (val>799)
					val=799;
				break;
			case INJUREREASON_UNKNOWN:
				if (bw>0)
					break;
				else
					pat.Hurt(INJUREREASON_ENERGY,10.0);
			case INJUREREASON_ENERGY:
				if (val<lev_naw) { 
					if (rand()%15 > 12) {
						injcode=(rand()%256 & 7) | (rand()%256 & 248); // Polytrauma
						drain*=1.8;
					} else {
						injcode=(rand()%256 & 240); 
						drain*=1.4;
					}
				} else if (val<lev_rtw) {
					injcode=(128 >> (rand()%4+1)) | (injcode=128 >> (rand()%6+1)) | (injcode=128 >> (rand()%5));
					drain*=1.3;
				} else if (val<lev_ktw)
					injcode=128 >> (rand()%4+1);
				injcode=(injcode*256)|med_immob|med_inj;
				trauma=true;
				break;
			case INJUREREASON_SHOT:
				trauma=true;
				if (val>799)
					val=799;
				injcode=(rand()%2>>15) | (rand()%4 >> 9)|med_inj;
				break;
			case INJUREREASON_DROWN:
				break;
			case INJUREREASON_CONTAM_ATOM:
				break;
			case INJUREREASON_CONTAM_CHEM:
				break;
			case INJUREREASON_CONTAM_BIO:
				break;
		}

		injcode=med_basis|med_rr|med_nuele|injcode|200;
		if (bw>0)
			pat.SetLife(val);
		int score=iss(val);
		if (trauma) {
			if ((injcode & trauma_pneu) && score>1) {
				switch (rand()%(14-score-score)) {
					case 2:
					case 3:
					case 4:
						drain*=1.3;					
						injcode=injcode|med_buelau;
						break;
					case 7:
					case 6:
						injcode=injcode|med_intub|med_buelau;
						drain*=1.3;					
						break;
				}
			}
			if (injcode & trauma_blutung) 
				pat.PushActionExecuteCommand(ACTION_NEWLIST,"art_blutung",&pat,0,false);
		}
		pat.SetInjuredLifeDrain(drain);
		System::Log("MediGen %s Code %8X Life %u  Drain %u",pat.GetName(),injcode,val,int(drain));
		pat.SetUserData(injcode); // 136|64 -> Injured by Code
	}


	void medisim (GameObject *Caller, Actor *Target, int simcode)
	{
		Person pat(Target);
		Caller->PushActionWait(ACTION_NEWLIST,1.0);
		System::Log ("MediSim : %s Status aktualisieren  %s %u",Caller->GetName(),pat.GetName(),pat.GetID());
	}

	void medi_status (GameObject *Caller, Actor *Target)
	{
		char *les[20];
			les[0]="";
			les[1]="Anisocorie";
			les[2]="Thoraxkompressionsschmerz";
			les[3]="Abdomendruckschmerz";
			les[4]="WirbelsäulenKlopfschmerz";
			les[5]="Fehlstellung Arm";
			les[6]="Fehlstellung Bein";
			les[7]="Beckenkompressionsschmerz";
			les[8]="stark blutende Wunde";
			les[11]="Verbrennungen Grad 3";
			les[12]="Russ in Nase/Mund";		
		int ix[10];
		for (int x=0;x<10;x++)
			ix[x]=0;
		char *meldung="                                                                                                                                                                                                            ";
		Person pat(Target);
		// float val=pat.GetLife();
		int coma=gcs(pat);
		char *buf="                                                                                                                                                                    ";
		if (istrauma(pat)) {
			int code=(pat.GetUserData() &  0xff00) >> 7;
			System::Log("Status InjCode %4X",code);
			for (x=1;x<9;x++) {
				code=code >> 1;
				if (code & 1)
					ix[x]=x;
			}		
		} else if (isburn(pat)) {
			ix[1]=11;
			if (pat.GetUserData()&trauma_pneu) 
				ix[2]=12;
		}
		snprintf(meldung,200,"%s : GCS %u/15 %s %s %s %s %s %s %s %s",dname(Caller),coma,les[ix[1]],les[ix[2]],les[ix[3]],les[ix[4]],les[ix[5]],les[ix[6]],les[ix[7]],les[ix[8]]);
		Game::ShowHelpTextWindow(meldung);
	}

	void medi_stetho (GameObject *Caller, Actor *Target)
	{
		char *les[20];
			les[0]="";
			les[1]="Tachypnoe, verkürzte Inspiration, seitengleich belüftet";
			les[2]="Einseitig aufgehobene AG";
			les[3]="Tachypnoe, abgeschwächte AG, einseitig paradoxe Atembewegungen";
			les[18]="Keine Atemgeräusche, keine Thoraxwandbewegungen";
			les[5]="Inspiratorischer Stridor + Giemen";
			les[6]="Feines Rasseln";
			les [19]="Seitengleich belüftet, keine RG, keine Obstruktion";
		int ix[10];
		for (int x=0;x<10;x++)
			ix[x]=0;
		char *meldung="                                                                                                                                                                                                            ";
		Person pat(Target);
		int inj=pat.GetUserData();
		if (inj & trauma_pneu) {
			if (istrauma(pat)) {
				if (inj & med_buelau)
					ix[1]=2;
				else if (inj & med_intub)
					ix[1]=3;
				else 
					ix[1]=1;
			} else if (isburn(pat) && (inj & med_intub))
				ix[1]=5;
		} else ix[1]=19;
		if (pat.GetLife()<1)
			ix[1]=18;
		snprintf(meldung,200,"%s : %s %s %s",dname(Caller),les[ix[1]],les[ix[2]],les[ix[3]]);
		Game::ShowHelpTextWindow(meldung);
	}

	void medi_vital (GameObject *Caller, Actor *Target)
	{
		char *meldung="                                                                                                                                                                                                            ";
		Person pat(Target);
		float val=pat.GetLife();
		bool PAIN=pat.GetUserData() & med_inj;
		int sys=0;
		int dia=0;
		int hf=0;
		float stress=1.0;
		if (istrauma(pat) & PAIN)
			stress=1.2;
		if (isburn(pat) & PAIN)
			stress=1.4;
		
		if (val > 0 && val <100) {
			hf+=0.4*val;
			
		}
		if (val < 400) {
			sys+=60+10*val/100;
			hf=100+30*200/val;
		}
		if (val < 600) {
			sys=val*110/500;
			dia=60*val/500;
			hf=120*450/val;
		}
		if (val < 800) {
			sys=120*val/700;
			dia=70*val/700;
			hf=100*600/val;
		}
		if (val > 800) {
			sys=140*val/900;
			dia=90*val/1000;
			hf=60*900/val;
		}
		if (val>400) {
			sys=sys*stress;
			hf=hf*stress;
		}	
		if (sys<0) 
			sys=0;
		if (dia<0)
			dia=0;
		if (hf<0)
			hf=0;
		else if (hf>190)
			hf=190;
		snprintf(meldung,200,"%s : RR %u / %u - %u/min",dname(Caller),sys,dia,hf);
		Game::ShowHelpTextWindow(meldung);
	}

	void medi_ekg (GameObject *Caller, Actor *Target)
	{
		char *meldung="                                                                                                                                                                                                            ";
		Person pat(Target);
		snprintf(meldung,200,"Patientenstatus von %7s : Dummy %s",dname(Caller),pat.GetName());
		Game::ShowHelpTextWindow(meldung);
	}
};

class medfunc : CommandScript
{

	bool DocCanDo(GameObject *o) 
	{
		Person p(o);
		return (o->IsAnimationFinished() || p.IsHealing());
	}
	
	void med_bonus (int val,Actor *pat)
	{
		GameObject p(pat);
		p.PushActionExecuteCommand(ACTION_INSERT,"Fine",pat,val,false);
	}

	void med_mist (int val,Actor *pat)
	{
		GameObject p(pat);
		p.PushActionExecuteCommand(ACTION_INSERT,"Fine",pat,val,false);
	}

	void an_den_kopf (GameObject *doc, Person p)
	{
			Vector l,r,pos;
			p.GetOrientedBBoxPoint(1,l.x,l.y,l.z);
			p.GetOrientedBBoxPoint(2,r.x,r.y,r.z);
			pos.x=(l.x+r.x)/2;
			pos.y=(l.y+r.y)/2;
			pos.z=(l.z+r.z)/2;
			doc->PushActionMove(ACTION_NEWLIST,pos);
	}
	
	void pat_lagern (Person pat)
	{
		pat.PushActionSwitchAnim(ACTION_INSERT,"layingwounded03");
	}

	void GetInHouse (Person a, Person b)
	{
		Actor oh=Game::GetActor(b.GetEnteredHouseID());
		a.PushActionExecuteCommand(ACTION_INSERT,"EnterHouse",&oh,112,true);
	}

	void kristalloide (Actor *pat) 
	{
		Person p(pat);
		float life=p.GetLife(); float wirk=75 *(1000-life)/1000;
		System::Log("Infusion Pat %s Life vor %u",p.GetName(),int(life));
		if (life<p.GetMaxLife()*1.3) {
			p.Heal(wirk);
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*0.8);
			med_bonus(50,pat);
			System::Log("Infusion Pat %s Life nach %u wirk %u",p.GetName(),int(p.GetLife()),int(wirk));
		} else {
			p.Hurt(p.GetInjuryReason(),wirk/5);
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*1.8);
		}
	}

	void intubation (Actor *pat)
	{
		Person p(pat);
		int code=p.GetUserData();
		Game::ShowHelpTextWindow ("Intubation");
		if (code & med_buelau) {
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*1.2);
			med_mist(-500,pat);
		} else if (code & med_intub) {
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*0.1);
			med_bonus(300,pat);
		} else {
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*0.5);
			med_mist(-100,pat);
		}
		p.Hurt(p.GetInjuryReason(),100);
		code=code & ~med_intub;		
		p.SetUserData(code);
	}

	void thxdrain (Actor *pat)
	{
		Person p(pat);
		int code=p.GetUserData();
		Game::ShowHelpTextWindow ("ThoraxDrainage");
		if (code & med_buelau) {
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*0.1);
			med_bonus(300,pat);
		} else {
			p.Hurt(p.GetInjuryReason(),150);
			med_mist(-500,pat);
		}
		code=code & ~med_buelau;
		p.SetUserData(code);
	}

	void injektion (Actor *pat)		# Soll zunächst v.a. Analgesie simulieren
	{
		Person p(pat);
		int code=p.GetUserData();
		Game::ShowHelpTextWindow ("I.v. Analgesie/Sedierung");
		if (code & med_inj) {
			p.SetInjuredLifeDrain(p.GetInjuredLifeDrain()*0.7);
			med_bonus(100,pat);
		} else {
			p.Hurt(p.GetInjuryReason(),150);
			med_mist(-100,pat);
		}
		code=code & ~med_inj;
		p.SetUserData(code);
	}

	Person der_Patient(GameObject *doc, Actor *pat, int com)
	{
		Actor ziel=Game::GetActor(doc->GetUserData());
		bool goon=true;
		Person p;
		switch (com)
		{
			case 13:
			case 8:
			case 11:	
			case 14:
			case 15:
			case 2:
			case 3:
			case 6:
			case 4:
			case 7:
			case 20:
			case 21:
			case 22:
				goon=ziel.IsValid();
				if (goon)
					Person p(&ziel);
				else
					Mission::PlayHint("wib_emv_nopat");
				break;
			default:
				Person p(pat);
				break;
		};
		return p;
	}

	void zum_pat (GameObject *doc,Actor *pat, int com)
	{
		Person p=der_Patient(doc,pat,com);
		bool goon=p.IsValid();
		if (goon)
		{
			Person d(doc);
			int icode=p.GetUserData();
			if (!p.IsFlagSet(FLAG_SOSI)) {
				System::Log("InjCodeCheck %s %8X",p.GetName(),p.GetUserData());
				if ((icode&200)!=200)
					medisim::injure (p,0,0,1.0);
				p.SetUserData(p.GetUserData()|255);
			}
			if (!d.IsHealing()) {
				if (d.IsDoctor())
					an_den_kopf(doc,p);
				else
					doc->PushActionMove(ACTION_NEWLIST,&p,TARGET_TREATMENT);
				doc->PushActionTurnTo(ACTION_APPEND,&p);
				if (com!=0)
					if (doc->IsEquipped()) {
						doc->PushActionSwitchAnim(ACTION_APPEND,"kneeldown");
						doc->PushActionSwitchAnim(ACTION_APPEND,"treatment1");
					} else
						doc->PushActionSwitchAnim(ACTION_APPEND,"disarm_mine");
				if (d.GetEnteredHouseID()!=p.GetEnteredHouseID())
					GetInHouse(d,p);
			}
			switch (com)
			{
				case 0:	// No Op
					break;
				case -1:	// Generate Medical Emergency -> Obsolet im Thor-Code
					p.SetFlag(FLAG_P_NEU);
					doc->PushActionExecuteCommand(ACTION_APPEND,"emv_medisim",&p,0,false);
					doc->PushActionExecuteCommand(ACTION_APPEND,"DocBasis",&p,0,false);
					break;
				case 2:
					if (d.IsDoctor())
						doc->PushActionExecuteCommand(ACTION_APPEND,"lna_categorize",&p,1,false);
					else if (d.IsEquipped())
						doc->PushActionExecuteCommand(ACTION_APPEND,"lna_categorize",&p,112,false);
					doc->PushActionExecuteCommand(ACTION_APPEND,"FirstCheck",&p,0,false);
				case 3:
				case 4:
					if (!d.IsHealing()) {
						doc->PushActionExecuteCommand(ACTION_APPEND,"emv_medisim",&p,com,false);
						doc->PushActionExecuteCommand(ACTION_APPEND,"Heal",&p,0,false);
					} else 	
						if (com==2)
							medisim::medi_status(doc,pat);
						else if (com==4)
							medisim::medi_vital(doc,pat);
						else
							medisim::medi_stetho(doc,pat);
						
					// PatStatus beschreiben
					break;
				case 8:
					break;
				case -2:
					d.PushActionSwitchAnim(ACTION_APPEND,"treatinjured1");
					break;
				case 11:
					pat_lagern(p);
					break;
				case 6: // Nuele
					Person d(pat);
					zum_pat(&d,&p,0);
					d.RemoveEquipment();
					d.PushActionSwitchAnim(ACTION_APPEND,"arrestidle");
					d.PlaceObjectInRightHand("mod:Models/Objects/Equipment/stero.v3o");
					kristalloide (&p);
					break;
				case 13:
					Person d(pat);
					zum_pat(&d,&p,0);
					d.RemoveEquipment();
					d.PushActionHeal(ACTION_APPEND,&p);
					break;
				case 14:
				case 15:
					Person d(pat);
					if (com==15)
						p.SetFlag(OF_RECOVERABLE);
					if (d.HasCommand("ratransport")) 
						d.PushActionExecuteCommand(ACTION_NEWLIST,"ratransport",&p,0,true);
					else {
						d.PushActionMove(ACTION_NEWLIST,&p,TARGET_TOUCHPERSON);
						d.PushActionTurnTo(ACTION_APPEND,&p);
						d.PushActionLift(ACTION_APPEND,&p);
						d.PushActionExecuteCommand(ACTION_APPEND,"DocDoIt",doc,-101,false);
					}
					doc->PushActionHeal(ACTION_APPEND,&p);
					if (d.IsEquipped())
						d.RemoveEquipment();
					break;
				case 20 : // Intubation
					Person d(pat);
					zum_pat(&d,&p,0);
					doc->PushActionHeal(ACTION_APPEND,&p);
					intubation(&p);
					break;
				case 21 : // Thoraxdrainage
					Person d(pat);
					zum_pat(&d,&p,0);
					doc->PushActionHeal(ACTION_APPEND,&p);
					thxdrain(&p);
					break;
				case 22 : // AnalgoSed
					Person d(pat);
					zum_pat(&d,&p,0);
					doc->PushActionHeal(ACTION_APPEND,&p);
					injektion(&p);
					break;
				case 101:
					doc->PushActionMove(ACTION_NEWLIST,pat,TARGET_TOUCHPERSON);
					doc->PushActionTurnTo(ACTION_APPEND,pat);
					doc->PushActionArrest(ACTION_APPEND,pat);
					break;
				default:
					dummy_treat(doc,pat);
					break;
			}
		}	
	}

	void dummy_treat (GameObject *doc, Actor *pat)
	{
	}
};


object eplus : CommandScript
{

   eplus()
   {
     	SetIcon("bma");
   }

   bool CheckPossible(GameObject *Caller)
   {
	return Input::LShiftPressed();
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	if (hataload>2)
	{
		hataload=hataload/2;
		hataspread=hataspread/2;
	}
   }
};

object eminus : CommandScript
{

   eminus()
   {
     	SetIcon("bma");
   }

   bool CheckPossible(GameObject *Caller)
   {
	return Input::LCtrlPressed();
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
	return true;
   }

   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {
	if (hataload<30)
	{
		hataload=hataload*2;
		hataspread=hataspread*2;
	}
   }
};


const int FLAG_P_NEU=OF_HAS_FIREAXE * 32;
