// ## 
// ## Winterberger für EM4 Scripting
// ## Version 4.0  
// ## 
// ## Script rufe_chemiezug
// ## 
// ## Stand : 12.08.2007
// ## 
// ## created by WitchDoctor
// ## 



// basiert auf rufe_loeschzug.script für Em3 by manuelt
//
// Revision
// 17.6.2006 : Fz-Auswahl über VehicleList (schneller)
//		Zug wird  anhand Fahrzeugtypen zusammengestellt, von jedem Typ ein Fz
// 
// Basis: Garagenausfahrt by BigBob

// Die Verwendung in anderen Mods ist gestattet, solange dieser
// Kommentar erhalten bleibt

const char DUMMY_HASWARNINGLIGHTS[] = "DUMMYHasWarningLights";
const char DUMMY_DISABLE[] = "DUMMYDisableSiren";

object rufe_chemiezug : CommandScript
{
   rufe_chemiezug()
   {
      SetValidTargets(ACTOR_FLOOR);
      SetIcon("abczug");
      SetCursor("abczug");
   }

   bool CheckTarget(GameObject *Caller, Actor *Target, int childID)
   {
      if( Caller->GetID() == Target->GetID() || Target->GetType() == ACTOR_VEHICLE || Target->GetType() == ACTOR_HOUSE || Target->GetType() == ACTOR_OPEN_HOUSE || Target->GetType() == ACTOR_PERSON || Target->GetType() == ACTOR_OBJECT)
         return false;
      return true;
   }


   void PushActions(GameObject *Caller, Actor *Target, int childID)
   {

	Vector TargetPos=Game::GetCommandPos();
	int alarmtype=101;
 	bool dum=false;
	Person p;

	alarmtype=101;
	p = Game::CreatePerson("mod:Prototypes/Persons/Civil/firewatchguy01.e4p", "anrufer");
	p.SetNeverResort(true);
	p.PushIgnoreEnergy();
	p.Hide();
	Game::FindFreePosition(&p,TargetPos);
	p.SetPosition(TargetPos);
	p.SetAnimation("wavehelp3");
	p.SetCommandable(true);
	p.SetUserData(0);
	if (Target->GetType() == ACTOR_PERSON)
	{
		Person TL(Target);
		if (TL.HasCommand("tl"))
		{
			alarmtype=111;
			p.AssignCommand("TL");
			p.SetUserData(TL.GetUserData());
		}
		else
			alarmtype=101;
	} 

	int cid=childID*1000;
	p.PushActionExecuteCommand(ACTION_NEWLIST,"alarmgeber",&p,120,false);	// KatSAlarm
	p.PushActionExecuteCommand(ACTION_APPEND,"alarmgeber",&p,alarmtype,false);	// Zugsequenz einschalten

	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,111,false); // Streife, kein MTW
	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,cid+555,false); // EL
	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,500,false); // GW-Mess
	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,cid+533,false); // RW
	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,cid+599,false); // örtlich
	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,cid+506,false); // GTLF
	p.PushActionExecuteCommand(ACTION_APPEND,"rufe_winterberg",&p,cid+507,false); // LKW
	p.PushActionExecuteCommand(ACTION_APPEND,"alarmgeber",&p,103,false);	// Zugsequenz abschalten

	p.PushActionExecuteCommand(ACTION_APPEND,"alarmgeber",&p,102,false);	// Zugsequenz ausschalten

   }
};
